### ISSUE TITLE
你可真牛逼

### ISSUE THREAD

**Issue by shirok1** [syhyz1990/baiduyun#1]
第一版直接就是4.2.0
![image](https://user-images.githubusercontent.com/12044683/91652329-cd7b7380-eac8-11ea-9421-8122bfe8888e.png)
盗用appid
![image](https://user-images.githubusercontent.com/12044683/91652340-e8e67e80-eac8-11ea-9265-f8c6cd33515e.png)
![image](https://user-images.githubusercontent.com/12044683/91652410-b721e780-eac9-11ea-85eb-a94d6fb93a60.png)
一万三Star
![image](https://user-images.githubusercontent.com/12044683/91652355-0582b680-eac9-11ea-89e9-e94e8f4c785f.png)
![image](https://user-images.githubusercontent.com/12044683/91652362-1d5a3a80-eac9-11ea-8c44-cb5a8366e7e6.png)
学会了，这就去fork个分支版本恰钱

**Comment by KingCoCos** [comment]
哈哈哈哈哈，暴躁老哥在线怼人，顶个

**Comment by RichardBaker3020** [comment]
第一次还需要关注微信号，恶心人，开发工具断点调试了一下，找到验证码是80149

**Comment by imThree** [comment]
很奇怪作者为什么不附上自己的名字呢？PanDownload出事儿跟这个插件没什么关系吧。
