### ISSUE TITLE
天翼云盘报未知错误

### ISSUE THREAD

**Issue by helleon** [syhyz1990/baiduyun#101]
无论哪种下载方式都是这样
![x1](https://user-images.githubusercontent.com/3538768/159156322-a292429c-ff43-41df-8bf4-0d1a08f0a325.png)

**Comment by mysq1isworst** [comment]
同样的问题，求作者尽快解决

**Comment by mysq1isworst** [comment]
天翼云都是这种报错，不管哪个下载方式都这样

**Comment by IThinkIGottaGo** [comment]
同~希望大佬有空可以修复~~
发现好像是 https://cloud.189.cn/api/open/file/getFileDownloadUrl.action?fileId=xxxxxxxxx&shareId=xxxxxxx (xxxx都是文件id)
现在这里返回的 xml 结果是如下，所以就弹未知错误了
```
<error>
<code>PermissionDenied</code>
<message>PermissionDenied</message>
</error>
```

可能是这个 api 接口现在不能再没有特定权限的条件下调用了？（或者是cookie之类的问题？）

**Comment by syhyz1990** [comment]
天翼的接口目前无法使用

**Comment by leafleave** [comment]
1G以下的文件还是可以获取的，1G以上不可以，不知道哪里的限制。
File smaller than 1GB can still be downloaded, bigger than 1GB cannot, don't know why.

**Comment by syhyz1990** [comment]
官方接口限制1G以上的文件了，目前尚未找到其他可用接口，知道的可以留言
