### ISSUE TITLE
FireFox 66.0.3 无法批量获取链接

### ISSUE THREAD

**Issue by yechs** [syhyz1990/baiduyun#101]
**期望获得的结果**：  
勾选多个文件(.rar)后，点击`显示链接`，获取多个链接

**实际获得的结果**：
勾选多个文件(.rar)后，点击`显示链接`，提示`暂时不支持文件夹下载，请勾选文件后使用【批量链接】或【显示链接】按钮`
![image](https://user-images.githubusercontent.com/49149993/56425761-316f1480-62a5-11e9-862f-b9ad8214acbf.png)

**附上浏览器console日志**：
![image](https://user-images.githubusercontent.com/49149993/56425436-d4269380-62a3-11e9-99a3-2bd020b988d1.png)

为方便复现bug，我**运行的环境**：
- Win 10 1809
- Firefox Stable 66.0.3
- Tampermonkey v4.9.5921
- 百度网盘直链下载助手 v2.2.4

值得注意的是，如果选择单个文件，那么是可以正常获得链接的

**Comment by yechs** [comment]
与 #99 可能是同一bug；  
因为那个issue没有提供太多信息，故重开此issue

**Comment by syhyz1990** [comment]
已在2.2.5中修复
