### ISSUE TITLE
好像今天百度升级了，下载地址会变，抓取不了文件

### ISSUE THREAD

**Issue by sonygod** [syhyz1990/baiduyun#102]
好像今天 2019-4-25 百度升级了，下载地址会变，中午升级的。早上还可以下载。

**Comment by sonygod** [comment]
好像大于2G文件的已经抓取不了，小文件可以

**Comment by Niefee** [comment]
Mac用户用不了

**Comment by JacoobH** [comment]
迅雷分析文件链接是0B

**Comment by coderlee** [comment]
我刚刚装好，小文件都下载不了，获取到链接后下载直接403了。

**Comment by coderlee** [comment]
重新试了一下，50M以下的可以，大的不行。
点击下载链接有如下信息：
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":2683395900248750707}
或者：
{ "error_code":31326, "error_msg":"anti hotlinking" }

**Comment by itheabyss** [comment]
> 好像今天 2019-4-25 百度升级了，下载地址会变，中午升级的。早上还可以下载。

是的，现在点下载助手时还经常要输入验证码

**Comment by zzqxztc** [comment]
百度好像会检测，封号。IDM刚开始可以，下着下着，就弹出授权框，服务器返回未授权。

**Comment by dirkhe1051931999** [comment]
现在市面上所有的百度云下载，都存在下载时间如果太长就容易被封ip，这个没办法的。好的方法就是在tb上买1天的真百度云账号。2块钱一天。
