### ISSUE TITLE
请问能支持 文件蜈蚣 这个下载器吗？

### ISSUE THREAD

**Issue by theblack6688** [syhyz1990/baiduyun#102]
http://www.filecxx.com/zh_CN/index.html

**Comment by theblack6688** [comment]
能收到。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Binbin ***@***.***>
发送时间: 2022年3月23日 22:54
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [syhyz1990/baiduyun] 请问能支持 文件蜈蚣 这个下载器吗？ (Issue #102)


借楼测试

疑似服务器故障发不了 issue

―

**Comment by qianbinbin** [comment]
昨天晚上GitHub故障，不能发新issue，回复是正常的，现在恢复了

**Comment by Dynamith** [comment]
同求支持

**Comment by syhyz1990** [comment]
@theblack6688 我的建议是文件蜈蚣 支持 aria 的链接格式

```shell
aria2c "https://下载链接.zip" --header "User-Agent: xxxx" --header "Cookie: xxxx"
```

这样比较自由，可以传递 UA 和 Cookie
