### ISSUE TITLE
右键点击选择IDM下载 ，迟迟无反应，无法弹出idm新建任务对话框 

### ISSUE THREAD

**Issue by IcarusXZ** [syhyz1990/baiduyun#103]
调用外链下载，右键点击之后 也没有反应，弹不出  idm新建任务对话框 
![无标题](https://user-images.githubusercontent.com/50135044/57003718-2b5d2a00-6bfb-11e9-8b32-e99cc7eddda8.png)

**Comment by syhyz1990** [comment]
重新安装IDM试下
