### ISSUE TITLE
Win & Mac 平台下载器推荐

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#106]
**Window平台:** 

IDM （收费）下载：http://www.internetdownloadmanager.com/download.html
NeatDownloadManager（免费）https://www.neatdownloadmanager.com/index.php/en/

**Mac平台:**

NeatDownloadManager（免费）https://www.neatdownloadmanager.com/index.php/en/

**Comment by mumeblossom** [comment]
可以用Aria2GUI + YAAW for Chrome

**Comment by shugen002** [comment]
> 可以用Aria2GUI + YAAW for Chrome

+1，希望可以加入Aria2下载支持

**Comment by lib-xdown** [comment]
https://xdown.org/baiduyun/index.htm

使用xdown.org 免费下载百度云,youtube

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)

**Comment by syhyz1990** [comment]
@shugen002 2.9.9已支持Aria2下载支持
