### ISSUE TITLE
2019.5.29日测试，脚本好像已经失效

### ISSUE THREAD

**Issue by wssy921** [syhyz1990/baiduyun#107]
连接到百度的链接好像是403的错误。是百度升级了吗。前2天还可以用，今天就不行了

**Comment by xueshukai** [comment]
嗯？穿越了

**Comment by lnsane** [comment]
> 连接到百度的链接好像是403的错误。是百度升级了吗。前2天还可以用，今天就不行了

麻烦告诉我下5月11号彩票中奖号码~😂

**Comment by lick2016** [comment]
这里也显示403  点击继续下载的话会要求输入用户名和密码（不明）——  使用作者说的先在百度云客户端内免费试用会员加速60秒内再到浏览器分享页面点击获取连接的方法可以加速，但是下载一定时间后会显示403 停止下载 然后GG

**Comment by syhyz1990** [comment]
仔细阅读文档，文档上写的都有
