### ISSUE TITLE
阿里云盘API下载显示链接后右键菜单无NDM，但是度盘却有此选项

### ISSUE THREAD

**Issue by Yamazaki-wu** [syhyz1990/baiduyun#109]
浏览器：firefox
版本：99.0.1
tempermonkey：4.16.6160
本脚本：5.6.10
NDM设置UserAgent：pan.baidu.com （发现不写这个度盘也下载不了）
度盘选择任意文件，点下载助手——API下载——显示链接——右键菜单选择“Download by NeatDownloadManager”，正常调用NDM开始下载。
阿里云盘UserAgent应该设置成啥，才能正常下载？最好度盘和阿里同时都存在。

**Comment by syhyz1990** [comment]
阿里云盘对UA没有要求，对referrer有要求

**Comment by Yamazaki-wu** [comment]
> 阿里云盘对UA没有要求，对referrer有要求

那请问有什么办法可以解决么？

**Comment by syhyz1990** [comment]
NDM不支持设置referrer
