### ISSUE TITLE
下载文件打不开

### ISSUE THREAD

**Issue by FME0** [syhyz1990/baiduyun#109]
为什么有时候外链迅雷下载的文件大小不变，但文件类型显示的是文件，而且打不开

[图片]

**Comment by syhyz1990** [comment]
可以试试置顶的下载器Net

**Comment by FME0** [comment]
什么下载器Net，我搜不到啊

在 2019-05-15 10:41:23，"iPc" <notifications@github.com> 写道：


可以试试置顶的下载器Net

**Comment by syhyz1990** [comment]
NeatDownloadManager（免费）https://www.neatdownloadmanager.com/index.php/en/

**Comment by FME0** [comment]
可以用，谢谢了

在 2019-05-17 12:23:46，"iPc" <notifications@github.com> 写道：


NeatDownloadManager（免费）https://www.neatdownloadmanager.com/index.php/en/
