### ISSUE TITLE
用Shift键批量选择后，提示“未选中文件，请刷新后重试”

### ISSUE THREAD

**Issue by kakusx** [syhyz1990/baiduyun#110]
在列表页，点一下第一个文件，然后按住shift再点一下最后一个文件，列表里的所有文件都被选中
然后点击下载助手 > 显示链接，提示 “未选中文件，请刷新后重试！”

**Comment by kakusx** [comment]
列表的全选按钮可以正常使用

**Comment by zippowang** [comment]
请问您的问题解决了吗？我现在无论选择单个文件还是多个文件，都提示未选中文件，刷新后重试
