### ISSUE TITLE
firefox 容器中的账户无法获取链接。 提示：获取下载链接失败！请刷新网页后重试！

### ISSUE THREAD

**Issue by howdareyo** [syhyz1990/baiduyun#111]
也就是Firefox Multi-Account Containers插件中的用户无法使用
主用户正常
迅雷在容器中也没问题，但百度有，其他未知

**Comment by syhyz1990** [comment]
Firefox 容器是啥？

**Comment by howdareyo** [comment]
> Firefox 容器是啥？

就是multi-account containers，类比来说应该是chrome的多用户，但是可以在一个窗口打开很多各不相同的用户的页面
![图片](https://user-images.githubusercontent.com/91058390/168425011-d66673dc-8578-42b4-8590-b6caa11d7a22.png)
就像这有三个颜色的标签页分别代表着三个身份，也就是说能一个窗口能开三个账号的百度网盘。

**Comment by syhyz1990** [comment]
其他脚本是否支持呢？如果都不支持说明 Tampermonkey 本身也不支持

**Comment by howdareyo** [comment]
> 其他脚本是否支持呢？如果都不支持说明 Tampermonkey 本身也不支持

都支持的，甚至这个直链脚本中的迅雷网盘也是支持的，只是该脚本中的百度网盘没支持，非常神秘

**Comment by syhyz1990** [comment]
multi-account containers 开启后 Tapermonkey 会把Cookie删除，导致失败，可能是这俩扩展其中一个有BUG
