### ISSUE TITLE
Mac safari 没有下载的按钮，有知道怎么搞的吗

### ISSUE THREAD

**Issue by Hydane** [syhyz1990/baiduyun#112]
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/65459449/169632537-02a93a2d-f59e-4555-976d-25132ae8add4.png">

**Comment by Hydane** [comment]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/65459449/169631664-995e9e22-729b-4fcf-81c9-e762b56594d7.png">

**Comment by syhyz1990** [comment]
暂不支持 Safari。
