### ISSUE TITLE
更新到5.7.0版本后，阿里云盘和百度云盘均不出现下载选项

### ISSUE THREAD

**Issue by Ssiswent** [syhyz1990/baiduyun#114]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/37449310/170161129-a5a0bc85-731f-418e-b565-b13c5c796ce0.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/37449310/170161158-83793e0c-c624-4ee6-bf0e-8d863fa79b0f.png">

**Comment by sanbei101** [comment]
`哈哈哈哈哈哈`
- [ ] tffg

![Screenshot_20220528_202005_cn.wps.moffice_eng.jpg](https://user-images.githubusercontent.com/95988545/170827785-58820fa2-1980-4a0a-8028-e9bb11c6f272.jpg)

**Comment by GoldSunMonkey** [comment]
相同的问题，我觉得可能是百度网盘升级了，我降级到下面好几个版本无法使用。

**Comment by 1265578519** [comment]
试一下安装5.6.10版本在升级 https://greasyfork.org/zh-CN/scripts/436446-%E7%BD%91%E7%9B%98%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B?version=1044603

**Comment by GoldSunMonkey** [comment]
可以用了，多谢啦。

**Comment by 1265578519** [comment]
> 可以用了，多谢啦。

我也不知道为什么，，，反正我降级到这个版本在升级上去就好了

**Comment by sanbei101** [comment]
嗯嗯嗯
