### ISSUE TITLE
网盘直链下载助手API下载问题

### ISSUE THREAD

**Issue by deja1vu** [syhyz1990/baiduyun#116]
![1](https://user-images.githubusercontent.com/106504793/170915215-78b07a14-6883-4018-a0ad-99552e814083.PNG)
你好，我用的IDM下载，API解析完速度一直上不去，上不了1M速度很慢，是不是还要在IDM里面手动设置UA，还是需要设置什么东西，望版主解答

**Comment by syhyz1990** [comment]
百度没有其他办法，开会员下载
