### ISSUE TITLE
5.8.1版本百度网盘点击BC下载解析只显示[object Object]

### ISSUE THREAD

**Issue by 1265578519** [syhyz1990/baiduyun#117]
![image](https://user-images.githubusercontent.com/6442439/171187940-79e4e6a7-c032-407f-9616-f676740a620e.png)

**Comment by zsygood** [comment]
我也发现了，[object Object]

**Comment by 1265578519** [comment]
> 我也发现了，[object Object]


知道问题了，要安装红色beta版本的
https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

如果是黑色版本的，则需要同时安装"网盘万能助手"增强插件
https://www.baiduyun.wiki/crx/assistant.zip
