### ISSUE TITLE
百度网盘 下载助手和其它按钮都不显示了

### ISSUE THREAD

**Issue by a1156883061** [syhyz1990/baiduyun#118]
![image](https://user-images.githubusercontent.com/36263893/172131854-d6639861-4111-416a-a8df-6f41403a52bc.png)

如图，应该是百度改了tool-bar的css类名？

**Comment by a1156883061** [comment]
下载助手版本为5.8.1，浏览器为新版Edge
百度网盘的新版样式

**Comment by yuantuo666** [comment]
百度网盘新界面存在反复init的操作，会将已经加载的按钮“删除”
测试5.8.2版本仍存在此问题

![image](https://user-images.githubusercontent.com/44130602/173760155-12ca89bc-0204-4e75-9342-150d8ee5849c.png)
![image](https://user-images.githubusercontent.com/44130602/173760107-6b5b29db-4864-475c-9d05-5b29fa1d934e.png)
上图为多次刷新后出现的按钮

解决方法可以是添加一个`setTimeout()`反复检查按钮存在情况并添加新按钮

**Comment by xiezilzp** [comment]
下載助手按鈕需要反复刷新多次才会出现
