### ISSUE TITLE
[feature request]直接从Tampermonkey获取Cookie

### ISSUE THREAD

**Issue by AutumnSun1996** [syhyz1990/baiduyun#12]
从代码中来看，【网盘万能助手】是只用于获取Cookie中的BDUSS吧？

Tampermonkey Beta版本可以通过GM_cookie获取所有cookie信息，避免引入额外的【网盘万能助手】

希望添加对GM_cookie的支持，无法获取Cookie时，提醒用户安装Tampermonkey Beta版本或者【网盘万能助手】

**Comment by syhyz1990** [comment]
Tampermonkey的作者已经说过了，正式版不会支持GM_cookie的

**Comment by AutumnSun1996** [comment]
我的意思是用Tampermonkey Beta代替【网盘万能助手】的作用。
GM_cookie在Tampermonkey Beta里是支持的。
我认为对使用者来说，安装google商店里的Tampermonkey Beta要从本地安装【网盘万能助手】更简单。
并且，当使用者没有安装Tampermonkey Beta时，也可以回退到【网盘万能助手】的方案。

**Comment by syhyz1990** [comment]
@AutumnSun1996 新版已集成，感谢提供代码
