### ISSUE TITLE
无法下载文件夹

### ISSUE THREAD

**Issue by EnTIv** [syhyz1990/baiduyun#12]
点直接下载没有反应
点显示链接然后对着链接右键使用idm下载提示400 Bad Request

**Comment by wlmnzf** [comment]
错误信息是这样的，大概是百度云升级了吧
 ```{"error_code":31090,"error_msg":"package is too large","request_id":423211433969608684}```

**Comment by Henry-yuan** [comment]
没错就是这个问题，我也是，可以下压缩包，但是文件夹不行
