### ISSUE TITLE
最新版忽然下载失败，百度更新了吧

### ISSUE THREAD

**Issue by selfboot** [syhyz1990/baiduyun#120]
![image](https://user-images.githubusercontent.com/2769831/58170823-1e49cd00-7cc7-11e9-8bc1-8eeedc40e910.png)

**Comment by huige555551** [comment]
the same

**Comment by zizxzy** [comment]
the same +1

**Comment by shanzm** [comment]
me too

**Comment by jojoy1** [comment]
all links from pcs.baidu.com are failed

**Comment by Isaac-yang** [comment]
Me too

**Comment by sjfirefox** [comment]
提示：
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":3302830387287484970}
还以为系统出问题了...

**Comment by syhyz1990** [comment]
已经修复 , 更新到2.2.8即可

**Comment by chenjgui** [comment]
大家更新了之后有成功的吗😭

**Comment by Isaac-yang** [comment]
> 已经修复 , 更新到2.2.8即可

大佬威武。实测可行

**Comment by dby60202** [comment]
更新2.2.8 原本顯示鏈結的pcs.baidu.com加到IDM後自己跳成qdall01.baidupcs.com 但一樣無法下載

**Comment by AnthonyMSen** [comment]
更新后依然无法下载

**Comment by selfboot** [comment]
更新后，提示 403 了。

```
INFO   2019-05-23 14:42:45 ( 1558593765 )   All Reply For Socket ( 1 ) :
INFO   2019-05-23 14:42:45 ( 1558593765 )   
<<HTTP/1.1 403 Forbidden
Date: Thu, 23 May 2019 06:42:45 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
x-bs-client-ip: MTgzLjYwLjg4LjQ=
x-bs-request-id: cWRiaC15dW4tYXJpZXMtcjEzNC00Mi01NC5xZGJoLmJhaWR1LmNvbToxMC4xMzQuNDIuNTQ6MjA2MDozMzA3NTk3NzI2OTY2NTY3NzU5OjIwMTktMDUtMjMgMTQ6NDI6NDU=
Access-Control-Allow-Methods: HEAD, GET, OPTIONS, PUT, POST, DELETE
Access-Control-Allow-Headers: Range, Origin, Content-Type, Accept, Content-Length
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Accept-Ranges, Content-Range, Content-Length, ETag, x-bs-request-id
Access-Control-Allow-Origin: https://pan.baidu.com
Content-Length: 119
Remote-Ip: flowserver.pcs.bae.baidu.com
Server: POMS/CloudUI 1.0>>
```

**Comment by jmotallebi** [comment]
Try not to download by right clicking on link, instead click on link( as when you are doing a normal download in Browser) and see if anything changed.

**Comment by Isaac-yang** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3310740835296495034}

**Comment by Mozzi97** [comment]
Mine giving back the error message like this(already updated to 2.2.8): 

`{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3310731315466148324}`

thanks!

**Comment by syhyz1990** [comment]
返回403的同学 , 可以试着先分享文件, 再分享页面下载
