### ISSUE TITLE
5.8.2版本不显示下载按钮

### ISSUE THREAD

**Issue by zszczh** [syhyz1990/baiduyun#121]
先谢谢作者的脚本。刚更新之后发现不显示按钮，我尝试重装了几次还是不行。上个版本还挺正常的。

**Comment by 9dark9** [comment]
我也是这样5.8.1挺正常，升级就完蛋了

**Comment by zszczh** [comment]
> 我也是这样5.8.1挺正常，升级就完蛋了

我今天发现又正常了
