### ISSUE TITLE
2.2.8失效了

### ISSUE THREAD

**Issue by haooow** [syhyz1990/baiduyun#123]
显示403

**Comment by syhyz1990** [comment]
等文件名出来后再点击开始下载

**Comment by dby60202** [comment]
目前更新2.28 顯示鏈結加入IDM後 一直無法顯示檔名跟檔案容量

**Comment by duolachun** [comment]
还是403报错

**Comment by syhyz1990** [comment]
试下右键下载 , 不要直接点击链接

**Comment by feiwofeifeixiaowo** [comment]
**update to 2.2.8  403 forbidden**

![image](https://user-images.githubusercontent.com/4606937/58318301-0fd7ee80-7e4a-11e9-9540-04283d0171f1.png)
