### ISSUE TITLE
无法下载百度文件

### ISSUE THREAD

**Issue by MisakiMeiss** [syhyz1990/baiduyun#124]
一直return to javascrip(0),已更新2.2.8
![baidu unable to download](https://user-images.githubusercontent.com/50947802/58242034-b2c43600-7d80-11e9-8a55-e9d5c0394ddd.png)

**Comment by Isaac-yang** [comment]
me too

{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3310596191427738735}

**Comment by MisakiMeiss** [comment]
wait 版主 update then let's see ok or not

**Comment by mytheshow** [comment]
等了好久都不显示文件大小

**Comment by DreamAndDead** [comment]
我也遇到同样的问题
```
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3325917537624357509}
```

**Comment by Isaac-yang** [comment]
这是帐号被限制下载了。

更换一个帐号即可

**Comment by MisakiMeiss** [comment]
可是全部人的户口都被限制吗😅

**Comment by HongYuO** [comment]
Mac端使用NeatDownLoadManager也是下载速度很慢，而且一次只能下载一个文件，否则报错

**Comment by Isaac-yang** [comment]
唉，又被封了。。。。

**Comment by Isaac-yang** [comment]
> Mac端使用NeatDownLoadManager也是下载速度很慢，而且一次只能下载一个文件，否则报错

firfox 获取的链接几十K/s

**Comment by Isaac-yang** [comment]
![image](https://user-images.githubusercontent.com/13374517/58305883-2d965b00-7e2c-11e9-9800-412037f6846d.png)
