### ISSUE TITLE
[置顶] 2.2.9脚本反馈 , 仅在本贴中回复 , 有问题请附带说明和图片

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#125]
无法获取链接 , 反馈问题模板如下:

问题描述: IDM返回403错误
问题截图: xxxx  (可以去 https://sm.ms  上传截图)
所在地区: 中国台湾
获取方式: API下载 还是 外链下载

**Comment by jojoy1** [comment]
见附件， 我觉得是百度这几天做了手脚。 即便能够连上， 多线程也没了所以速度只有10K
![Capture](https://user-images.githubusercontent.com/50931501/58319840-f8e6cb80-7e4c-11e9-8a8d-d1b953d978bf.PNG)

**Comment by koulamo** [comment]
請您看看下載檔案都卡在這裡
![2019-05-24 17_47_07-下載檔案資訊](https://user-images.githubusercontent.com/50986704/58320398-1c5e4600-7e4e-11e9-82c5-cba33c50074e.png)

**Comment by MisakiMeiss** [comment]
同上，.zip ,.rar 文件也是

**Comment by Liubasara** [comment]
5/25 脚本用不了
![image](https://user-images.githubusercontent.com/24971070/58365042-05bcfb00-7ef1-11e9-8926-0d110245cf4d.png)

**Comment by dby60202** [comment]
![2019-05-25 19_41_05-百度网盘-全部文件](https://user-images.githubusercontent.com/50938381/58368847-16876400-7f25-11e9-9a99-9f37c5aeff13.png)
顯示鏈結加入IDM 後 遲遲無法顯示檔名及檔案大小

**Comment by beez19** [comment]
![idm](https://user-images.githubusercontent.com/51035515/58375430-7ada1000-7f85-11e9-864b-da53644b872d.png)
请问是什么问题呢？

**Comment by beez19** [comment]
![idm](https://user-images.githubusercontent.com/51035515/58375430-7ada1000-7f85-11e9-864b-da53644b872d.png)
请问是什么问题呢？

**Comment by syhyz1990** [comment]
@beez19 下载链接是按住你设置的快捷键 , 强制调用IDM 优先下载
![](https://i.loli.net/2019/05/26/5ce9dc43128cd21115.png)

**Comment by syhyz1990** [comment]
@koulamo @dby60202 @Liubasara 

试下外链下载 , 获取的链接里选择可以获取到文件大小的链接 **这里一定要左键点击调用IDM , 右键调用IDM是无效的**

![剪贴板图片 (1).png](https://i.loli.net/2019/05/26/5ce9dce50936f31006.png)

**Comment by dby60202** [comment]
![2019-05-26 09_05_02-百度网盘-全部文件](https://user-images.githubusercontent.com/50938381/58376126-7584c180-7f95-11e9-9541-e1de72020f29.png)
已嘗試使用外链下载 獲取到連結只有qdall01.baidupcs.com開頭 一樣無法顯示檔名及大小
使用左键点击调用IDM(按住鍵盤快速鍵同時點左鍵) 以及 右键调用IDM結果都如上圖

若是直接左鍵點選外链下载 則是出現下面的錯誤訊息
![2019-05-26 09_05_36-郵件](https://user-images.githubusercontent.com/50938381/58376150-eaf09200-7f95-11e9-9a8d-43727cd0c2a5.png)

**Comment by koulamo** [comment]
不好意思我也是出現相同的情況
使用外链下载 獲取到連結只有qdall01.baidupcs.com開頭 一樣無法顯示檔名及大小
使用左键点击调用IDM(按住鍵盤快速鍵同時點左鍵) 如下圖
![2019-05-26 09_37_26-下載檔案資訊](https://user-images.githubusercontent.com/50986704/58376291-f2b23580-7f99-11e9-9d3b-e4812e3748d7.png)
若是直接左鍵點選外链下载 則是出現下面的錯誤訊息
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":3372153307995835522}
請問一下跟檔案大小是否有影響

**Comment by drrobincroft** [comment]
今天使用仅有一例成功，其余均返回403，文件名也不对
IDM拦截的URL如下
https://qdall01.baidupcs.com/file/aa9fc60e17b90e63bdc559436d97df57?bkt=p3-0000311fb9e80eed87143f092166a67b0d2e&fid=2667689410-250528-1106624011553694&time=1558842780&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-S%2BPx5arCN7j2dhcX8i1tGJsGFL0%3D&to=92&size=179223029&sta_dx=179223029&sta_cs=30034&sta_ft=rar&sta_ct=7&sta_mt=0&fm2=MH%2CNanjing02%2CAnywhere%2C%2Chunan%2Ccnc&ctime=1393544766&mtime=1558760083&resv0=cdnback&resv1=0&vuk=2667689410&iv=-2&htype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000311fb9e80eed87143f092166a67b0d2e&sl=80740430&expires=8h&rt=pr&r=845987010&mlogid=3374443162047765491&vbdid=1471386571&fin=3DMGAME-Resident.Evil.4.Ultimate.HD.Cracked-3DM.part12.rar&fn=3DMGAME-Resident.Evil.4.Ultimate.HD.Cracked-3DM.part12.rar&rtype=1&dp-logid=3374443162047765491&dp-callid=0.1.1&hps=1&tsl=15&csl=78&csign=N8C2dtb2Qx%2FyiZ4XQPM4k4yUzmU%3D&so=0&ut=8&uter=4&serv=0&uc=2678471761&ti=5902310e0d478cb67b6c6e6f4ce08843120e41a1b3a582a0&by=themis
诡异的是成功的那一个URL也是这个形式的，而且参数一样不少，内容也差不多
https://qdall01.baidupcs.com/file/10095789ea932c7bf84231ed28ce1d50?bkt=p3-140093cd3c8a85e4bd77a40e4deacc2848ca32595dc200003e800000&fid=2667689410-250528-534277940081956&time=1558837739&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-xmYSTUXWa7KMSOoQunB1PLSOPnw%3D&to=92&size=1048576000&sta_dx=1048576000&sta_cs=17704&sta_ft=rar&sta_ct=7&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Chunan%2Ccnc&ctime=1393544875&mtime=1558760083&resv0=cdnback&resv1=0&vuk=2667689410&iv=-2&htype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=140093cd3c8a85e4bd77a40e4deacc2848ca32595dc200003e800000&sl=80740430&expires=8h&rt=sh&r=554603798&mlogid=3373089714189448490&vbdid=1471386571&fin=3DMGAME-Resident.Evil.4.Ultimate.HD.Cracked-3DM.part11.rar&fn=3DMGAME-Resident.Evil.4.Ultimate.HD.Cracked-3DM.part11.rar&rtype=1&dp-logid=3373089714189448490&dp-callid=0.1.1&hps=1&tsl=15&csl=78&csign=N8C2dtb2Qx%2FyiZ4XQPM4k4yUzmU%3D&so=0&ut=8&uter=4&serv=0&uc=2678471761&ti=ac918a9d760b19a854b6ff319248cdf3f894cbe98ed6b6e2&by=themis
![image](https://user-images.githubusercontent.com/49083808/58377231-3ca51680-7fae-11e9-9930-9c8027eb41b6.png)

![image](https://user-images.githubusercontent.com/49083808/58377240-7544f000-7fae-11e9-8c55-3e1659b1623d.png)

**Comment by drrobincroft** [comment]
刚才核实了一下，好像跟文件大小有关系

**Comment by beez19** [comment]
> @beez19 下载链接是按住你设置的快捷键 , 强制调用IDM 优先下载
> ![](https://camo.githubusercontent.com/c851686c3d4272039051c8b3821ff667bd34053b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30352f32362f3563653964633433313238636432313131352e706e67)

![idm2](https://user-images.githubusercontent.com/51035515/58377346-bf2ed580-7fb0-11e9-8239-a4752d9325c6.png)
使用强制或不使用也一样

**Comment by drrobincroft** [comment]
将文件分享之后，使用直接下载好像是可以的
好像是不能多个一起下
![image](https://user-images.githubusercontent.com/49083808/58377585-9ad5f780-7fb6-11e9-8583-67821c14e57a.png)
![image](https://user-images.githubusercontent.com/49083808/58377594-b17c4e80-7fb6-11e9-92eb-675f28759815.png)

**Comment by zmctinas** [comment]
下到一半停止了  重新开始提示连接修改或无效 请重新获取 重新api显示连接 就提示403禁止
![0682C451-E013-4D23-A4ED-57EFF48F6596](https://i.loli.net/2019/05/26/5cea518cab25c31607.png)

**Comment by drrobincroft** [comment]
这个应该是百度做了限制

**Comment by 1608637229** [comment]
百度又修改啥把。用的百度输入法的appid这周失效了。只有几十k,估计是股价最近跌的太难看了吧。

**Comment by 9Nancy6** [comment]
问题描述: API单击无效 外链显示错误无法下载
问题截图: 
<img width="1168" alt="屏幕快照 2019-05-27 上午12 24 33" src="https://user-images.githubusercontent.com/51056335/58384767-83c7f180-8018-11e9-9824-e098b027ef99.png">
<img width="472" alt="屏幕快照 2019-05-27 上午12 28 49" src="https://user-images.githubusercontent.com/51056335/58384771-8de9f000-8018-11e9-8a7b-f32d1fb72138.png">


所在地区: 中国大陆
获取方式: API下载 / 外链下载

**Comment by pythonispython** [comment]
问题描述：点击“显示链接”里的链接后未跳转IDM下载页面
具体显示：
跳转到空白页面，仅有文本内容为：
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3387601194338214703}
请问如何解决？
我已将百度资源保存到自己的账号下，为何显示未被授权？

**Comment by syhyz1990** [comment]
> 问题描述：点击“显示链接”里的链接后未跳转IDM下载页面
> 具体显示：
> 跳转到空白页面，仅有文本内容为：
> {"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3387601194338214703}
> 请问如何解决？
> 我已将百度资源保存到自己的账号下，为何显示未被授权？

确保已经安装下载插件 , 如果不行, 先分享在下载

**Comment by TeaJea** [comment]
下载36m的视频可以下，300m的点击直接下载就没有反应。。

**Comment by zwying0814** [comment]
问题同上面一样，没有解决，点击“显示链接”里的链接后未跳转IDM下载页面，保存到自己网盘也不行

**Comment by myqv** [comment]
本人经过多次尝试，发现同一个账号，对某些资源的下载就会出现403，同样的资料，换一个账号下载是完全没问题的。估计是百度对账号的封杀。

**Comment by jungleooo** [comment]
> 
> 
> 本人经过多次尝试，发现同一个账号，对某些资源的下载就会出现403，同样的资源，换一个账号下载是完全没问题的。估计是对账号的封杀。
> 对于速度这个问题，我被封了403的这个账号，刚下载的时候速度达到1M，现在只剩下100KB。新账号目前下载还是1M。所以总结了一下，应该还是对账号的封杀

我也是这种情况，换了一个账号速度就上去了

**Comment by qia0zx** [comment]
> > 本人经过多次尝试，发现同一个账号，对某些资源的下载就会出现403，同样的资源，换一个账号下载是完全没问题的。估计是对账号的封杀。
> > 对于速度这个问题，我被封了403的这个账号，刚下载的时候速度达到1M，现在只剩下100KB。新账号目前下载还是1M。所以总结了一下，应该还是对账号的封杀
> 
> 我也是这种情况，换了一个账号速度就上去了

我换了好久没使用过的新帐号，仍然遇到了一样的问题（只有分享才能下载，但也是低速且限制线程的qdall***）。

**Comment by TestSrc** [comment]
> 請您看看下載檔案都卡在這裡
> ![2019-05-24 17_47_07-下載檔案資訊](https://user-images.githubusercontent.com/50986704/58320398-1c5e4600-7e4e-11e9-82c5-cba33c50074e.png)

我也是这个问题，那估计不是个例。我测试了一下，文件大小如果是70+M是可以的。80+以上就获取不到文件。

**Comment by wangqd** [comment]
发现用官方客户端的速度比用IDM+脚本的速度快了不少。虽然比不上用SVIP，但是也比以前70K快了不少，所以，各位还是散了吧。

**Comment by TestSrc** [comment]
[
![1](https://user-images.githubusercontent.com/18453232/58457369-11aaf600-8159-11e9-80b2-7539a46e0d42.PNG)
![2](https://user-images.githubusercontent.com/18453232/58457371-12438c80-8159-11e9-99dc-3581db6606ac.PNG)

](url)
来看了一下，大家的问题都差不多，除了下载器的截图外，我截取了一下控制台的日志，400或者403.

**Comment by TeaJea** [comment]
我换了个账号后之前的600+M文件可以下载了

**Comment by pythonispython** [comment]
> 
> 
> > 问题描述：点击“显示链接”里的链接后未跳转IDM下载页面
> > 具体显示：
> > 跳转到空白页面，仅有文本内容为：
> > {"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3387601194338214703}
> > 请问如何解决？
> > 我已将百度资源保存到自己的账号下，为何显示未被授权？
> 
> 确保已经安装下载插件 , 如果不行, 先分享在下载

感谢帮助，我采用了楼下方法，换了账号，现已解决。下载的都是1G以上的文件，没有问题。所以可能不是文件大小问题，而是账号问题。

**Comment by pythonispython** [comment]
也尝试了分享再下载的方法，但下载速度均小于100k/s，不如直接换一个账号。

**Comment by TeaJea** [comment]
> 也尝试了分享再下载的方法，但下载速度均小于100k/s，不如直接换一个账号。

换个账号才下载一次就下载不了了

**Comment by TestSrc** [comment]
嗯，分享下载是可以的。

**Comment by WeiXinHuayuan** [comment]
分享下载可以下，但是限制了5个连接数，速度还没网盘客户端快

**Comment by pythonispython** [comment]
问题描述: 暂停下载后是否就无法恢复下载？
全速下载2.85G文件到81%，突然中止下载，等了很久下载速度还是0，于是按了暂停，然后就悲催发现无法恢复下载了，2G都熬过来了就差最后一点了。

问题截图: 
![图片](https://user-images.githubusercontent.com/49957991/58493447-899f0d80-81a5-11e9-8d05-a34de03807f2.png)

所在地区: 中国大陆
获取方式: API下载

**Comment by stormkerui** [comment]
链接报错
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3445282608899097920}

**Comment by beckjiang218** [comment]
确实如上面所说，同一个资源链接，换了个账号后，下载功能和下载速度都正常。暂时先换个账号下着:)

**Comment by 95513580** [comment]
我同样使用外链下载，連結就只有qdall01開頭一个，點左鍵的话就出：服务器响应显示您没有权限下载此文件备注: HTTP/1.1 403 Forbidden

**Comment by syhyz1990** [comment]
你们试试新号呢，也是只有一个链接么

**Comment by 95513580** [comment]
换了个号就没问题，但不知道能用多久，这肯定是这个百度在拉黑

**Comment by syhyz1990** [comment]
请各位更新到2.2.9 使用API下载看看能否下载

**Comment by WeiXinHuayuan** [comment]
能下载，但下载大文件账号很容易被封限速，看来得不断换账号了

**Comment by dby60202** [comment]
更新到2.2.9 目前在自己網盤獲取連結後 加入IDM一樣會跳成 qdall01.baidupcs.com
現在是能夠顯示檔名及大小並下載 但最高執行緒只能到4個
並且一次只能下載一個檔案 再點下個檔案加入IDM就無法顯示檔名及大小了

**Comment by OnceGoBlack** [comment]
2.2.9可以下载但是速度只有100k左右

**Comment by TwoNiu** [comment]
你好，目前发现该插件有两个问题。
1、点击下载链接后容易出现报错如下：
`{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3592905883272111925}`
2、使用IDM下载后，速度稳定在100kb以下，比以前的速度慢了很多（带宽是100M的）。

**Comment by skyemin** [comment]
问题描述:
直接下载或者是显示链接点左键军均无反应,但是我用其他的百度账号可以调用成功,这个是百度又做了什么限制吗?
![image](https://user-images.githubusercontent.com/38172444/58934393-ee0d2e80-879c-11e9-956a-1200ad27ca1b.png)
