### ISSUE TITLE
百度网盘好友消息分享内容能否支持提取

### ISSUE THREAD

**Issue by 15600268858** [syhyz1990/baiduyun#129]
尊敬的开发者您好，网盘助手插件是一个非常好用的工具，目前个人在使用的过程中想有更丰富的功能，比如好友消息分享页（如下图）是否可以支持提取下载链接的能力。感谢！！！
![image](https://user-images.githubusercontent.com/27670340/179181138-1975a2a8-9398-4943-8682-869b7c96ee00.png)
![image](https://user-images.githubusercontent.com/27670340/179181344-e848abfd-da21-4c32-8bd4-e4fcae43a8bf.png)

**Comment by syhyz1990** [comment]
无法支持哦
