### ISSUE TITLE
刚更新的2.2.8，结果失效了，百度封了？

### ISSUE THREAD

**Issue by zhsx616** [syhyz1990/baiduyun#129]
![Snipaste_2019-05-25_08-24-07](https://user-images.githubusercontent.com/31874799/58362370-d1354900-7ec8-11e9-8c9d-d74b939e7cf5.jpg)

**Comment by syhyz1990** [comment]
IDM 安装的问题 , 重装下IDM , 与脚本无关

**Comment by zhsx616** [comment]
重装也没用啊，也试了试旧版本，都不行了 ，突然就成这样了

**Comment by zhsx616** [comment]
> IDM 安装的问题 , 重装下IDM , 与脚本无关
重装也没用啊，也试了试旧版本，都不行了 ，突然就成这样了

**Comment by zhsx616** [comment]
又试了一下，如果把某个文件分享出来，然后在分享页面上下载没问题，但是直接在百度网盘的页面上下载就不行，可是以前都是直接在页面上下载的，几天前突然这样，Google也找不到解决办法
