### ISSUE TITLE
RPC下载方式不能自定义下载路径

### ISSUE THREAD

**Issue by l-Teng** [syhyz1990/baiduyun#132]
用默认的D:\就能成功创建下载任务，我自己改了参数里的路径的话，Motrix就会报错误16
这是他们官网的说明：
16
If aria2 could not create new file or truncate existing file.

**Comment by syhyz1990** [comment]
确认路径文件夹存在，不存在会报错

**Comment by l-Teng** [comment]
> 确认路径文件夹存在，不存在会报错

试了几次，自定义的中文名文件夹会报错，英文的不会，问题不大

**Comment by syhyz1990** [comment]
看来 aria 对中文支持太差
