### ISSUE TITLE
点击显示链接下载后，链接会变，然后返回403

### ISSUE THREAD

**Issue by Tobu-R** [syhyz1990/baiduyun#137]
现在一直提示403
![image](https://user-images.githubusercontent.com/40848133/58478135-dbd13600-8187-11e9-8bf5-20ece6f7ca50.png)
![image](https://user-images.githubusercontent.com/40848133/58478139-e1c71700-8187-11e9-9560-ddabf0ec0092.png)

**Comment by xiongmaoshouzha** [comment]
我今天也403了

**Comment by Andy1984** [comment]
第一次使用， 确实403

**Comment by FarAwaytarget** [comment]
我也这样～作者大大解决下呗
