### ISSUE TITLE
关于部分用户IDM无法获取文件名的解决方法

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#138]
收集了大家的反馈 , 部分用户使用API下载 , 获取到的链接以 qdall01.baidupcs.com 开头的均无法获取文件名和文件大小 . 

解决方法: 
选择要下载文件或文件夹分享链接 , 到分享页面使用助手下载 , 限速问题 参考说明里的常见问题

**Comment by luzhengli** [comment]
你好，我尝试过以分享读取链接，但是也没法读取出文件名（小概率可以读取），显示的错误一种是超时，另一种是没有授权。

**Comment by MisakiMeiss** [comment]
分享下载也不行了，也开了新账号，还有什么方法下载吗？

![分享下载也不行了，也开了新账号](https://user-images.githubusercontent.com/50947802/58534725-9c095d80-821e-11e9-8541-50bd214f3690.jpg)

**Comment by Mao0509** [comment]
大佬你好，分享下载使用一次过后就没有用了，点击链接后显示的是一个超时错误
{"error_code":31360,"error_msg":"expire time out error","request_id":3446644196186832693}
脚本版本:2.2.8
IDM:6.33
Chrome浏览器

**Comment by chriszhang0815** [comment]
大佬您好，我更新了最新版的百度网盘直链下载助手脚本，说是修复了下载返回403的问题；但是现在还是大概率返回403啊，不知道怎么回事。。。

**Comment by 405722907** [comment]
I tried it this morning. It can be used normally. Thank you!

**Comment by hmmmhmmhmm** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3466014460885392355}

when I click download link this code keep showing up.
I use mac. How to fix it? thanks.

**Comment by 405722907** [comment]
> {"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3466014460885392355}
> 
> when I click download link this code keep showing up.
> I use mac. How to fix it? thanks.
> ![1559184071566](https://user-images.githubusercontent.com/51069638/58604670-69fc0800-82bf-11e9-8c79-0d7499fe66fc.jpg)

Click on other links instead of those that start with qdall01

**Comment by lairenqing** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3471443428632088733}

**Comment by syhyz1990** [comment]
更新到2.2.9

**Comment by lairenqing** [comment]
> 更新到2.29
好的，谢谢！

**Comment by Mao0509** [comment]
版本2.29
Chrome浏览器
API下载
无法获取有效链接
https://qdall01.baidupcs.com/file/b38723f3bb2de7c841ab8881ac7c56eb?
分享下载返回错误链接
{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3472163385688515081}

**Comment by MisakiMeiss** [comment]
谢谢大佬，可是我还是return 403,但是分享可以下载了，但还是限制速度

Mao0509 <notifications@github.com> 于 2019年5月30日周四 下午5:00写道：

**Comment by lairenqing** [comment]
版本2.29 
Chrome浏览器
API下载
更新最新版本后还是报错。
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3472234072530054742}

显示连接下载也一样
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":3472258756954031870}

但在分享，或使用分享 可以正常下载。

**Comment by koulamo** [comment]
版本2.29
Chrome浏览器
API下载
更新最新版本后还是报错。

{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3472879966390886639}

但在分享，或使用分享 可以正常下载。
但是只能下載兩個文件，第三個就不行下載

**Comment by Asleep-Loneliness** [comment]
> 版本2.29
> Chrome浏览器
> API下载
> 更新最新版本后还是报错。
> 
> {"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3472879966390886639}
> 
> 但在分享，或使用分享 可以正常下载
> 但是速度不超過100KB，無法跟之前下載速度比較

**Comment by FrostyBonny** [comment]
+1
```
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":3487725618809393860}
```

**Comment by Jack-ban** [comment]
也是一样的问题。
```
{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3489438961794592929}
```
昨天还可以通过重新登陆，解决这个问题，今天也不行了。

**Comment by SolitaryFG** [comment]
![微信截图_20190605153340](https://user-images.githubusercontent.com/34020867/58938500-86101580-87a7-11e9-8b9b-1f7e749cefef.png)

**Comment by Odakumiko** [comment]
分享页面已经不能使用了，idm依然无法过去文件名。
