### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by zx1425819914** [syhyz1990/baiduyun#139]
希望当点击直接复制无效按钮时，可以为每条链接增加换行符

**Comment by syhyz1990** [comment]
为什么呢

**Comment by zx1425819914** [comment]
因为我要用idm批量下载，点击那个按钮后，链接之间没有换行符


 
---原始邮件---
发件人: "iPc"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 下午2:33
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "zx1425819914"<1425819914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 有问题 (#139)



为什么呢

**Comment by potatokin** [comment]
![image](https://user-images.githubusercontent.com/51268485/58750449-3be81500-84c5-11e9-8701-49738a0374f5.png)
無法下載

**Comment by potatokin** [comment]
![image](https://user-images.githubusercontent.com/51268485/58750455-54582f80-84c5-11e9-9773-89dcd715a89f.png)

**Comment by zx1425819914** [comment]
因为我是找人定制的工具，所以需要你为链接之间提供换行符号，你无法的原因我知道是什么，都是因为cookie问题，提供错误的cookie或者没有cookie，百度都会拒绝


 
---原始邮件---
发件人: "potatokin"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 晚上11:30
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "zx1425819914"<1425819914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 有问题 (#139)




 無法下載

**Comment by zx1425819914** [comment]
还有就是你那个叫蚂蚁下载器不是idm，

Internet Download Manager是idm
这个



 
---原始邮件---
发件人: "potatokin"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 晚上11:30
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "zx1425819914"<1425819914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 有问题 (#139)




 無法下載

**Comment by syhyz1990** [comment]
可以拷贝代码 , 自己修改呢

**Comment by zx1425819914** [comment]
我倒是想，我完全看不懂


 
---原始邮件---
发件人: "iPc"<notifications@github.com>
发送时间: 2019年6月5日(星期三) 中午12:08
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "zx1425819914"<1425819914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 有问题 (#139)



可以拷贝代码 , 自己修改呢

**Comment by syhyz1990** [comment]
> 我倒是想，我完全看不懂
> […](#)
> ---原始邮件--- 发件人: "iPc"<notifications@github.com> 发送时间: 2019年6月5日(星期三) 中午12:08 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>; 抄送: "zx1425819914"<1425819914@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [syhyz1990/baiduyun] 有问题 (#139) 可以拷贝代码 , 自己修改呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

我试了下,复制到记事本中是换行了的
