### ISSUE TITLE
Safari 14 不能显示下载按钮

### ISSUE THREAD

**Issue by Ca1ze** [syhyz1990/baiduyun#14]
**更新Big SUr之后在Safari 14上不显示下载按钮**

![Xnip2020-11-16_15-27-54](https://user-images.githubusercontent.com/48375862/99223931-6005f600-2820-11eb-9cf2-c4ac6d49d5e9.jpg)

**Comment by syhyz1990** [comment]
控制台打开看下信息

**Comment by Graskize** [comment]
![Xnip2020-12-01_13-54-52](https://user-images.githubusercontent.com/48375862/100702611-f4558880-33dc-11eb-8d14-9c824ed02a69.jpg)

**Comment by Ca1ze** [comment]
> 控制台打开看下信息
![Xnip2020-12-01_14-00-56](https://user-images.githubusercontent.com/48375862/100703013-ae4cf480-33dd-11eb-99ad-2a6203a86e8a.jpg)
