### ISSUE TITLE
关于使用Aria2下载的问题

### ISSUE THREAD

**Issue by Snylonue** [syhyz1990/baiduyun#141]
```
显示获取的链接，可以使用右键迅雷或IDM下载，复制无用，需要传递cookie
```
请问能否手动复制连接和cookie到aria2中进行下载，如果可以，需要复制哪个（些）cookie   
目前试过`baidu.com/cookie/bduss`和F12->Network中的cookie都不行

使用最新版的脚本

**Comment by ReeceNee** [comment]
same issues

**Comment by syhyz1990** [comment]
可以的, cookie里都复制
