### ISSUE TITLE
v2.2.9 403

### ISSUE THREAD

**Issue by FengtianJiao** [syhyz1990/baiduyun#142]
INFO   2019-06-03 00:23:10 ( 1559492590 )   All Reply For Socket ( 1 ) :
INFO   2019-06-03 00:23:10 ( 1559492590 )   
<<HTTP/1.1 403 Forbidden
Date: Sun, 02 Jun 2019 16:23:11 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
x-bs-client-ip: MTA2LjEyMi4xNzUuNQ==
x-bs-request-id: eXEwMS15dW4tYXJpZXMtcjEwMi0zMi0xNS55cTAxLmJhaWR1LmNvbToxMC4xMDIuMzIuMTU6MjA5MDozNTQ4ODc1NDIzMTMxODIyMzI2OjIwMTktMDYtMDMgMDA6MjM6MTE=
Content-Length: 83
Remote-Ip: flowserver.pcs.bae.baidu.com
Server: POMS/CloudUI 1.0>>

DEBUG  2019-06-03 00:23:10 ( 1559492590 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_GET_SENT  ->  HTTP_STATE_PARSING_HTTP_HEADER 
DEBUG  2019-06-03 00:23:10 ( 1559492590 )   Status Code For Socket (1 ) = 403
ERROR  2019-06-03 00:23:10 ( 1559492590 )   Handling Error - Socket ( 1 ) - SocketState =  HTTP_STATE_PARSING_HTTP_HEADER  ErrorText = HTTP/1.1 403 Forbidden
ERROR  2019-06-03 00:23:10 ( 1559492590 )   HTTP/1.1 403 Forbidden
INFO   2019-06-03 00:23:10 ( 1559492590 )   DownloadEngine State Changed : Starting... ( 4 ) -> Error
DEBUG  2019-06-03 00:23:10 ( 1559492590 )   Socket ( 1 ) All Headers have been Parsed. Now HttpStatus =  HTTP_STATE_PARSING_HTTP_HEADER  And StatusCode = 403
ERROR  2019-06-03 00:23:10 ( 1559492590 )   Error Occured. HTTP/1.1 403 Forbidden
DEBUG  2019-06-03 00:23:10 ( 1559492590 )   DownloadEngine's Thread Is Terminating. EngineState = Error.
DEBUG  2019-06-03 00:23:10 ( 1559492590 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_PARSING_HTTP_HEADER  ->  HTTP_STATE_VOID 
INFO   2019-06-03 00:23:10 ( 1559492590 )   Closing LogFile.

**Comment by FengtianJiao** [comment]
![捕获](https://user-images.githubusercontent.com/29243257/58764322-54752f80-8598-11e9-9163-7e3a91e92569.PNG)

**Comment by AlexLL55** [comment]
It seems that you have directly Copied the link to downloader application( no Page URL on property page), according to baiduyun documents this way will not work.
You should send link to downloader from inside browser and not directly copying it.
Hope that help.

**Comment by syhyz1990** [comment]
参见置顶问题 #148
