### ISSUE TITLE
Asking For Password?

### ISSUE THREAD

**Issue by Gazawi02** [syhyz1990/baiduyun#143]
Whenever I press the 下载助手 button, it says 请输入初始化暗号, which looks like it's asking for some type of password. I looked under older issues, but the code given in #48 is not currently working anymore.

**Comment by syhyz1990** [comment]
type 96325

**Comment by Alvarithifi** [comment]
@syhyz1990 
I'm on the same issue.
I accessed WeChat through QR code, but I couldn't find the password.
What's the password? How can I get it?
