### ISSUE TITLE
无法下载"error_code":31362,"error_msg":"sign error"

### ISSUE THREAD

**Issue by AndyS007** [syhyz1990/baiduyun#143]
左键进入后显示{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":3556718909068853098}

**Comment by TwoNiu** [comment]
你好，目前发现该插件有两个问题。
1、点击下载链接后容易出现报错如下：
`{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":3592905883272111925}`
2、使用IDM下载后，速度稳定在100kb以下，比以前的速度慢了很多（带宽是100M的）。

**Comment by syhyz1990** [comment]
参见置顶问题 #148
