### ISSUE TITLE
建议加上公开分享的代码，并将选项里的“永久有效”设成默认

### ISSUE THREAD

**Issue by redstoneleo** [syhyz1990/baiduyun#145]
建议加上公开分享的代码，并将选项里的“永久有效”设成默认
代码 https://www.52fzg.com/qtjs/2728.html

**Comment by syhyz1990** [comment]
已加入分享功能, 需要自己选择 , 设成默认有风险 , 可自行修改

**Comment by redstoneleo** [comment]
没效果啊

**Comment by syhyz1990** [comment]
![1.gif](https://i.loli.net/2019/06/06/5cf88ab6b22b237634.gif)

**Comment by redstoneleo** [comment]
我从这里下载安装的https://greasyfork.org/zh-CN/scripts/39504-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B
还是老问题，难道不对？  
百分浏览器、
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by gMan1990** [comment]
@syhyz1990 已失效，求更新
