### ISSUE TITLE
百度网盘下载助手调不出IDM

### ISSUE THREAD

**Issue by skyemin** [syhyz1990/baiduyun#147]
直接下载或者是显示链接点左键军均无反应,但是我用其他的百度账号可以调用成功,这个是百度又做了什么限制吗?

- 
![image](https://user-images.githubusercontent.com/38172444/58934258-7fc86c00-879c-11e9-8c27-bb70f570eaa0.png)

**Comment by syhyz1990** [comment]
用右键菜单里的IDM下载
