### ISSUE TITLE
显示未发现IDM

### ISSUE THREAD

**Issue by zk-lh** [syhyz1990/baiduyun#148]
IDM已安装,浏览器已集成,文件类型已配置,点击下载助手按钮使用API下载,显示找不到IDM

**Comment by syhyz1990** [comment]
用百分浏览器可以在这里设置

![image](https://user-images.githubusercontent.com/5344173/185455352-b748c2fa-3d65-4469-b3da-32df8e96e6f1.png)

**Comment by zk-lh** [comment]
用的是谷歌浏览器

**Comment by syhyz1990** [comment]
google 无法强制使用IDM，百分和qq可以
