### ISSUE TITLE
关于分享页面链接403无法下载的解决方案

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#148]
最近更新后 , 分享页面返回403问题 , 经过检查 , 百度已经封了此下载接口 .

解决方案 : 将分享的文件保存到自己的网盘中 , 使用API下载

**Comment by wkler** [comment]
请问如何使用api下载呢？

**Comment by 405722907** [comment]
> 请问如何使用api下载呢？

I also want to know

**Comment by syhyz1990** [comment]
把分享页面的文件保存到自己网盘中 , 去我的网盘中勾选文件

![1559791722(1).png](https://i.loli.net/2019/06/06/5cf8888a53a5a58967.png)

**Comment by JYeung111** [comment]
百度没有关闭连接端口。 它只是同步不同的下载方法请求检查的要求，已经有了解决方案。

Screen capture for script version 2.2.9
![BD-Share-Demo](https://user-images.githubusercontent.com/41117798/59081230-99de8780-891f-11e9-80a7-b17b64c3976a.PNG)

**Comment by LittleAlicorn** [comment]
> 百度没有关闭连接端口。 它只是同步不同的下载方法请求检查的要求，已经有了解决方案。
> 
> Screen capture for script version 2.2.9
> ![BD-Share-Demo](https://user-images.githubusercontent.com/41117798/59081230-99de8780-891f-11e9-80a7-b17b64c3976a.PNG)
什么方案啊

**Comment by CET-4** [comment]
调用IDM显示如此：
ERR_SSL_PROTOCOL_ERROR

**Comment by yggwz** [comment]
同样感谢大佬的分享@syhyz1990 ，我在使用顶置中的方法，将其显示链接后，复制链接进入IDM准备下载，还是出现了403错误，提示木有权限，是我操作有误还是怎么的呢
![image](https://user-images.githubusercontent.com/49422575/59204575-80fdfc80-8bd3-11e9-97e4-4eb11990dfcb.png)

**Comment by dumumu** [comment]
api直接下载浏览器没有反应，显示连接也错误，没有用idm，怎么办
