### ISSUE TITLE
下拉栏收不起来

### ISSUE THREAD

**Issue by zuishengmeng** [syhyz1990/baiduyun#149]
![QQ截图20220821095231](https://user-images.githubusercontent.com/64256517/185771998-c6991d47-f80d-486f-92f1-aca1456b2783.png)

**Comment by syhyz1990** [comment]
你这用的是其他人集成的版本吧，原始版本并无此问题 https://www.youxiaohou/install.html

**Comment by zuishengmeng** [comment]
不是吧，我在油小猴页面更新的啊

**Comment by zuishengmeng** [comment]
原来是和一个脚本有冲突，好了
