### ISSUE TITLE
什么是神秘代码?

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#149]
就是百度开发者的Appid , 遇到下载慢或无法下载的情况可以尝更换appid

**Comment by dby60202** [comment]
神秘代碼試過了幾組 主要影響好像是有些會無法抓到檔名及檔案大小 透過更改神秘代碼可解決
但獲取連結後在IDM還是會被強制轉到qdall01.baidupcs.com的限速下載 試過幾組代碼都一樣

**Comment by koulamo** [comment]
測試幾個代碼都一樣會傳送到qdall01.baidupcs.com的限速下載
下載速度不會超過100KB

**Comment by z7one** [comment]
还是没法加速啊！！

**Comment by Kethers** [comment]
大佬能教一下怎么换吗？不会呀……

**Comment by shadowdragon1123** [comment]
> 神秘代碼試過了幾組 主要影響好像是有些會無法抓到檔名及檔案大小 透過更改神秘代碼可解決
> 但獲取連結後在IDM還是會被強制轉到qdall01.baidupcs.com的限速下載 試過幾組代碼都一樣
appid是什么？是开发者工具里的那串吗

**Comment by Mao0509** [comment]
如何获取有效的APPID呀？

**Comment by Cishanduwang** [comment]
嗯，现在有时不能获取文件信息，有时下载速度很慢，同楼上所说的被转到qdall01.baidupcs.com限速下载，很难受！

**Comment by ttxhxz** [comment]
小文件慢就慢一点吧，大文件还是组个百度云会员配合第三方工具满速下载吧

**Comment by z78520w** [comment]
这和第三方软件的原理差不多 单账号下载达到上限 更换小号 最稳的就是开个会员配合才能满速无限制

**Comment by Isaac-yang** [comment]
同问
