### ISSUE TITLE
无法利用idm同时下载多个文件

### ISSUE THREAD

**Issue by littlesb1990** [syhyz1990/baiduyun#150]
当有下载任务时，idm无法利用下载助手下载新的文件
![QQ截图20190605200248](https://user-images.githubusercontent.com/51401365/58954875-f5e4c700-87cc-11e9-9c6d-c2f0bf84b3c1.png)
![QQ截图20190605200226](https://user-images.githubusercontent.com/51401365/58954882-f8472100-87cc-11e9-9f3d-e3022b48f0d6.png)

**Comment by syhyz1990** [comment]
多文件下载参考![4.gif](https://i.loli.net/2019/06/06/5cf887f353cb698528.gif)
