### ISSUE TITLE
[置顶] 2.4.0脚本反馈 , 仅在本贴中回复 , 有问题请附带说明和图片

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#151]
反馈问题模板如下:

问题描述: IDM返回403错误
问题截图: xxxx (可以去 https://sm.ms 上传截图)
所在地区: 中国台湾
宽带运营商: 中国电信
步骤重现: 在我的网盘中勾选文件后, 使用API下载 , 获取的链接无法下载

**Comment by jorshxp** [comment]
貌似还是一样下载速度很慢
换了APPID也是一样
下载地址还是qdall01.baidupcs.com

**Comment by garykuok** [comment]
问题描述: 插件提示獲取選中文件失敗
问题截图: 
![image](https://user-images.githubusercontent.com/13715478/59019089-ebccd200-8879-11e9-8224-3379ca1c2630.png)
所在地区: 中国澳門
宽带运营商: CTM
步骤重现: 在我的网盘中勾选文件后, 使用API下载 , 提示無法獲取連接，與其他文件一起勾選點顯示連接時也無法獲取該文件的鏈接，其他文件正常

**Comment by feixia5712** [comment]
今天好像不能下载了，获取的地址是https://qdall01.baidupcs.com/file/b841f6348d0e6b761aba17a4c77ce082?bkt=en-660aa  直接访问不到了，希望作者修复

**Comment by TomKOG** [comment]
问题描述: IDM返回403错误
问题截图: 
![2019-06-07 (1)](https://user-images.githubusercontent.com/51483193/59107061-6bd26500-896a-11e9-993c-185c8637b333.png)
![2019-06-07 (3)](https://user-images.githubusercontent.com/51483193/59107099-7987ea80-896a-11e9-88f3-bd516608c9cd.png)
![2019-06-07 (2)](https://user-images.githubusercontent.com/51483193/59107120-7f7dcb80-896a-11e9-82d7-2fcc190581fb.png)

所在地区: 中国四川
宽带运营商: 中国移动
步骤重现: 勾选文件   api显示链接   使用idm下载链接    域名psc在idm里面还是被强制更改成qball01   并且加载不了文件

**Comment by syhyz1990** [comment]
配置里神秘代码设为624966 试试

**Comment by Phil2048** [comment]
我用的是类似idm的 freedownloadmanager

**Comment by ivankevin** [comment]
问题描述: 网盘同一时间只能下载一个文件，下载第2个的话按键无反应。而且限速严重，平时几M现在只剩几十K。
问题截图: https://i.loli.net/2019/06/08/5cfb8ca4c62bd54330.jpg
https://i.loli.net/2019/06/08/5cfb8ca4cf09d71653.jpg
所在地区: 中国广东
宽带运营商: 中国电信
步骤重现: 在我的网盘中勾选文件后, 使用API下载-直接下载, 无反应

**Comment by chengjiansunboy** [comment]
请问账号限速有什么比较好的解决办法吗?更换appId是否有用。谢谢

**Comment by qia0zx** [comment]
强制转到qdall的问题。我在用pandownload这个软件里每间隔一段时间发现下载速度都会提升到正常，多下载就会限速，而不像现在这里根本无法加速。是不是可以参考下原理呢？

**Comment by mcfx0** [comment]
问题描述: 403错误
问题截图:
![](https://i.loli.net/2019/06/08/5cfba7528b47026107.png)
所在地区: 中国四川
宽带运营商: 中国电信
步骤重现: 在我的网盘中勾选文件后, 使用外链下载 , 获取的链接无法下载

**Comment by roger125** [comment]
> 配置里神秘代码设为624966 试试

问题是配置里面看来看去, 没有看到有地方可以输入这个代码...请指点下? Editor里面? Settings里面? 具体是哪里???

谢谢.

**Comment by TomKOG** [comment]
> 配置里神秘代码设为624966 试试

谢谢回复。但是还是一样，不能解决......

**Comment by chengjiansunboy** [comment]
> > 配置里神秘代码设为624966 试试
> 
> 问题是配置里面看来看去, 没有看到有地方可以输入这个代码...请指点下? Editor里面? Settings里面? 具体是哪里???
> 
> 谢谢.
选中文件->下载助手->API下载->脚本配置 里面可以设置。

**Comment by MisakiMeiss** [comment]
能给我几个神秘代码吗？我要尝试

**Comment by lunamariayu** [comment]
问题描述: 插件提示获取选中文件失败
问题截图:
<img width="748" alt="屏幕快照 2019-06-11 下午5 24 20" src="https://user-images.githubusercontent.com/51700870/59261571-4e561180-8c70-11e9-89a8-34ac80bf2dc2.png">
所在地区: 山东
宽带运营商: 中国联通
步骤重现: 在我的网盘中勾选文件后, 使用API下载 , 提示“未选中文件，请刷新后重试！”大小体积文件都出现过类似问题，但并不是每个文件都有该问题。

**Comment by roger125** [comment]
> > > 配置里神秘代码设为624966 试试
> > 
> > 
> > 问题是配置里面看来看去, 没有看到有地方可以输入这个代码...请指点下? Editor里面? Settings里面? 具体是哪里???
> > 谢谢.
> > 选中文件->下载助手->API下载->脚本配置 里面可以设置。

![QQ截图20190611195111](https://user-images.githubusercontent.com/14965189/59269722-4f903a00-8c82-11e9-8f36-03e6ffb12360.png)
你好!

如截图, "选中文件->下载助手"之后, 并没有"API下载->脚本配置"...是哪里搞错了吗?

**Comment by syhyz1990** [comment]
更新到最新版本2.4.0试试

**Comment by imyangdy** [comment]
> 更新到最新版本2.4.0试试

@syhyz1990  2.4.0也不行了
Request URL: https://qdall01.baidupcs.com/file/c8b209d13d279d11f007d82559b9ff39?bkt=en-d3a65691252603d3cf7911c557349bc03826535896245137e2101c471c50c0d4f6421f2629d317e7&fid=67176317-498065-274855408953983&time=1560256313&sign=FDTAXGERLQBHSKfW-DCb740ccc5511e5e8fedcff06b081203-WNRmxwqu1E4LMFlluOBH22Kbv9o%3D&to=92&size=24626248&sta_dx=24626248&sta_cs=2&sta_ft=flac&sta_ct=0&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Cguangdong%2Cct&ctime=1560234622&mtime=1560255036&resv0=cdnback&resv1=0&vuk=67176317&iv=-2&htype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-69c46e28104ba05a702822728a5226b3d9b92da08bed876af56fcc5e81cd2455c2708aa04cc0aac7&sl=81068110&expires=8h&rt=pr&r=759710325&mlogid=3753885648603269754&vbdid=2346920848&fin=Alan+Walker-TikTok%28Faded%29%EF%BC%88Roberto+Kan+remix%EF%BC%89+-+Roberto+Kan.flac&fn=Alan+Walker-TikTok%28Faded%29%EF%BC%88Roberto+Kan+remix%EF%BC%89+-+Roberto+Kan.flac&rtype=1&dp-logid=3753885648603269754&dp-callid=0.1.1&hps=1&tsl=10&csl=10&csign=Qi2ymjj0bsrB1hh9tAGxB0IHQl8%3D&so=0&ut=8&uter=4&serv=0&uc=3787276406&ti=37cfb58296b21ea953efbc499ef4b918b4150493886530dc&by=themis

**Comment by carson1103** [comment]
改了神秘代码為624966之後只有不到100KB
![slow](https://user-images.githubusercontent.com/51711065/59280773-b3256200-8c98-11e9-85ea-169268edca9d.PNG)

**Comment by LinsPoi** [comment]
問題描述：使用idm,點擊開始下載後報錯
問題截圖：
![11](https://user-images.githubusercontent.com/40729643/59326341-e14a8680-8d18-11e9-9209-26f2b7e56693.png)
所在地區：台灣
寬帶運營商：中華電信
步驟重現：在我的網盤中勾選文件後，使用API​​下載，直接下載 , 點擊開始下載後出現報錯

**Comment by roger125** [comment]
> 更新到最新版本2.4.0试试

这是回复我的吗? 我的本来就是2.4.0版本...没有输入神秘代码的地方...

**Comment by exi3t** [comment]
> 問題描述：使用idm,點擊開始下載後報錯
> 問題截圖：
> ![11](https://user-images.githubusercontent.com/40729643/59326341-e14a8680-8d18-11e9-9209-26f2b7e56693.png)
> 所在地區：台灣
> 寬帶運營商：中華電信
> 步驟重現：在我的網盤中勾選文件後，使用API​​下載，直接下載 , 點擊開始下載後出現報錯

mark,我也出了这个问题

**Comment by syhyz1990** [comment]
失效的问题会尽快处理的

**Comment by chilbi** [comment]
#### 百度接口限制怎么办？

![批注 2019-06-14 235758](https://user-images.githubusercontent.com/24976117/59522058-5deb8980-8f00-11e9-83ac-986bad928250.png)

**Comment by Quantum666** [comment]
无法读取文件大小

**Comment by Mickeyzhu2019** [comment]
我也遇到这个问题了。也试过输入神秘代码，但是没有作用。

**Comment by Mickeyzhu2019** [comment]
https://i.loli.net/2019/06/17/5d06fca16801a43363.png

**Comment by syhyz1990** [comment]
把下载链接中的https换成http

**Comment by 17602588136** [comment]
![image](https://user-images.githubusercontent.com/52028829/59984944-cc4aed00-9660-11e9-970e-7c46c6224ac3.png)

**Comment by hongleng** [comment]
![image](https://user-images.githubusercontent.com/43168359/60066077-a1cc6300-9738-11e9-83e0-b88faa444d13.png)
api下载显示文件被暂时移除了
所在地区：北京
宽带运营商：不知道

**Comment by morichikasora** [comment]
问题描述:无法提供安全链接/建立安全连接失败
问题截图: https://i.loli.net/2019/06/25/5d1199d17447360065.png
https://i.loli.net/2019/06/25/5d1199d17fffe60158.png
所在地区: 中国广东
宽带运营商: 中国电信
步骤重现: 在我的网盘中勾选文件后, 使用API下载 , 获取的链接无法下载，firefox/chrome均显示安全协议出现问题。

**Comment by morichikasora** [comment]
> 问题描述:无法提供安全链接/建立安全连接失败
> 问题截图: https://i.loli.net/2019/06/25/5d1199d17447360065.png
> https://i.loli.net/2019/06/25/5d1199d17fffe60158.png
> 所在地区: 中国广东
> 宽带运营商: 中国电信
> 步骤重现: 在我的网盘中勾选文件后, 使用API下载 , 获取的链接无法下载，firefox/chrome均显示安全协议出现问题。

macos

**Comment by ming3666** [comment]
问题描述:无法下载此文件，无效的HTTP服务器响应。
问题截图: 
![20190626153745](https://user-images.githubusercontent.com/52235325/60162012-39aa7980-982b-11e9-97c1-cac62d5ab6b2.png)

所在地区: 中国广东
宽带运营商: 中国电信
步骤重现: 暂停后，点击继续出现该问题

**Comment by zerotas** [comment]
问题描述：今天起下载速度从50kB/s降至10kB/s后不动，使用的下载器是FDM（IDM的免费版）
问题截图：
![image](https://user-images.githubusercontent.com/40569883/60378687-9c348d00-9a58-11e9-8494-5bdf557fb745.png)
所在地区：中国江苏
宽带运营商：中国电信
步骤重现：下载助手 -> API下载 -> 显示链接，右键使用FDM下载

**Comment by dallas145** [comment]
问题描述:单一压缩包无法下载
问题截图: 
<img src="https://i.loli.net/2019/07/07/5d21994db607341354.png" alt="問題.png" title="問題.png" />
<img src="https://i.loli.net/2019/07/07/5d21994e0653350179.png" alt="問題2.png" title="問題2.png" />
所在地区: 中国台湾
宽带运营商: 台湾大哥大
步骤重现: 在我的网盘中勾选文件后 , 使用API下载>直接下载 , 提示获取选中文件失败 . 使用API下载>显示连结 , 提示未选中文件

**Comment by carlton981010** [comment]
问题描述: 获取选中文件失败，请刷新重试！
问题截图: https://i.loli.net/2019/07/11/5d26bd37970ed12228.png
所在地区: 澳大利亚 悉尼
宽带运营商: Optus
步骤重现: 在我的网盘中勾选文件后, 使用API下载则“获取选中文件失败”，显示链接则“未选中文件，请刷新后重试！”
