### ISSUE TITLE
下载报错了，没有没大佬遇到过？

### ISSUE THREAD

**Issue by Jason8Zhang** [syhyz1990/baiduyun#153]
![image](https://user-images.githubusercontent.com/10389173/59192571-7c2a5000-8bb5-11e9-900f-525d4315b01b.png)

下面是报错信息

INFO   2019-06-10 19:27:33 ( 1560166053 )   Opening LogFile...
INFO   2019-06-10 19:27:33 ( 1560166053 )   DownloadEngine State Changed : Unkown -> Starting...
DEBUG  2019-06-10 19:27:33 ( 1560166053 )   DownloadEngine's Thread is Starting...
INFO   2019-06-10 19:27:33 ( 1560166053 )   Trying to Start Download for -> https://qdall01.baidupcs.com/file/f8c4f062ebb84aaacb57ceb934e40eda?bkt=en-29a7ad5d1913bc6ff68315fd7d6a3fc0c74a77e074750a31124e8bbedaae45c0e9194bf09ce663f2&fid=1628753341-624966-294979854739104&time=1560166037&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-LWEWhxWo%2F124bjS%2FsxhxGbsiiKU%3D&to=92&size=272777582&sta_dx=272777582&sta_cs=1&sta_ft=wmv&sta_ct=5&sta_mt=5&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshanghai%2Cother&ctime=1547562883&mtime=1547704029&resv0=cdnback&resv1=0&vuk=1628753341&iv=-2&htype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-a1245e672170579c0cf8318bd53d26e731cc444b7ba70c3164fc00030f97814782b246bfab76f239&sl=81068110&expires=8h&rt=pr&r=419835620&vbdid=468052078&fin=CC%E8%80%81%E5%B8%88-%E6%A0%B8%E5%BF%83%E5%8A%A8%E7%94%BB.wmv&bflag=92,34-92&rtype=1&dp-logid=3729652157848506401&dp-callid=0.1&hps=1&tsl=10&csl=10&csign=2GQLbUBx0USqUrRyY%2Fxdhaah7To%3D&so=0&ut=8&uter=-1&serv=1&uc=2274833460&ti=1ddbe04d331970eb2ff79db7b9a938c93ca58a90dcb371db&by=themis
INFO   2019-06-10 19:27:33 ( 1560166053 )   DownloadID = 31 , Protocol = HTTPS
INFO   2019-06-10 19:27:33 ( 1560166053 )   New Socket(s) Created. MaxAllowedConnection = 8 And ActiveSockets = 1
DEBUG  2019-06-10 19:27:33 ( 1560166053 )   Socket ( 1 )  Connecting to  140.249.34.38:443 ...
INFO   2019-06-10 19:27:33 ( 1560166053 )   Initializing SslHandShake for Socket (1 )
INFO   2019-06-10 19:27:34 ( 1560166054 )   SslHandShake OK for Socket ( 1 )
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   SegmentManager has Created a New Segment and now has 1 Segments.
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   Socket ( 1 ) HttpStatus =  HTTP_STATE_VOID  RoundNumberServer = 0 and RoundNumberProxy = 0
INFO   2019-06-10 19:27:34 ( 1560166054 )   Sending Http-GET  for Socket ( 1 )  Range = 0-
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_VOID  ->  HTTP_STATE_GET_SENT 
INFO   2019-06-10 19:27:34 ( 1560166054 )   GET Sent : 
<< GET /file/f8c4f062ebb84aaacb57ceb934e40eda?bkt=en-29a7ad5d1913bc6ff68315fd7d6a3fc0c74a77e074750a31124e8bbedaae45c0e9194bf09ce663f2&fid=1628753341-624966-294979854739104&time=1560166037&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-LWEWhxWo%2F124bjS%2FsxhxGbsiiKU%3D&to=92&size=272777582&sta_dx=272777582&sta_cs=1&sta_ft=wmv&sta_ct=5&sta_mt=5&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshanghai%2Cother&ctime=1547562883&mtime=1547704029&resv0=cdnback&resv1=0&vuk=1628753341&iv=-2&htype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-a1245e672170579c0cf8318bd53d26e731cc444b7ba70c3164fc00030f97814782b246bfab76f239&sl=81068110&expires=8h&rt=pr&r=419835620&vbdid=468052078&fin=CC%E8%80%81%E5%B8%88-%E6%A0%B8%E5%BF%83%E5%8A%A8%E7%94%BB.wmv&bflag=92,34-92&rtype=1&dp-logid=3729652157848506401&dp-callid=0.1&hps=1&tsl=10&csl=10&csign=2GQLbUBx0USqUrRyY%2Fxdhaah7To%3D&so=0&ut=8&uter=-1&serv=1&uc=2274833460&ti=1ddbe04d331970eb2ff79db7b9a938c93ca58a90dcb371db&by=themis HTTP/1.1
Host: qdall01.baidupcs.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Accept: */*
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Accept-Charset: *
Origin: https://pan.baidu.com
Referer: https://pan.baidu.com/disk/home?#/all?vmode=list&path=%2F%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99%2F2019%2F2019%E5%B9%B41%E6%9C%8815%E6%97%A5%E6%A0%B8%E5%BF%83%E5%8A%A8%E7%94%BB-CC%E8%80%81%E5%B8%88
Range: bytes=0-

>>
INFO   2019-06-10 19:27:34 ( 1560166054 )   All Reply For Socket ( 1 ) :
INFO   2019-06-10 19:27:34 ( 1560166054 )   
<<HTTP/1.1 403 Forbidden
Date: Mon, 10 Jun 2019 11:27:34 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
x-bs-client-ip: MTE2LjIyOC44OC4xOA==
x-bs-request-id: cWRiaC15dW4tYXJpZXMtcjEzNC00My0yMi5xZGJoLmJhaWR1LmNvbToxMC4xMzQuNDMuMjI6MjA1MDozNzI5NjUyMTU3ODQ4NTA2NDAxOjIwMTktMDYtMTAgMTk6Mjc6MzQ=
Access-Control-Allow-Methods: HEAD, GET, OPTIONS, PUT, POST, DELETE
Access-Control-Allow-Headers: Range, Origin, Content-Type, Accept, Content-Length
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Accept-Ranges, Content-Range, Content-Length, ETag, x-bs-request-id
Access-Control-Allow-Origin: https://pan.baidu.com
Content-Length: 94
Remote-Ip: flowserver.pcs.bae.baidu.com
Server: POMS/CloudUI 1.0>>

DEBUG  2019-06-10 19:27:34 ( 1560166054 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_GET_SENT  ->  HTTP_STATE_PARSING_HTTP_HEADER 
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   Status Code For Socket (1 ) = 403
ERROR  2019-06-10 19:27:34 ( 1560166054 )   Handling Error - Socket ( 1 ) - SocketState =  HTTP_STATE_PARSING_HTTP_HEADER  ErrorText = HTTP/1.1 403 Forbidden
ERROR  2019-06-10 19:27:34 ( 1560166054 )   HTTP/1.1 403 Forbidden
INFO   2019-06-10 19:27:34 ( 1560166054 )   DownloadEngine State Changed : Starting... ( 4 ) -> Error
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   Socket ( 1 ) All Headers have been Parsed. Now HttpStatus =  HTTP_STATE_PARSING_HTTP_HEADER  And StatusCode = 403
ERROR  2019-06-10 19:27:34 ( 1560166054 )   Error Occured. HTTP/1.1 403 Forbidden
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   DownloadEngine's Thread Is Terminating. EngineState = Error.
DEBUG  2019-06-10 19:27:34 ( 1560166054 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_PARSING_HTTP_HEADER  ->  HTTP_STATE_VOID 
INFO   2019-06-10 19:27:34 ( 1560166054 )   Closing LogFile.

**Comment by syhyz1990** [comment]
重试下看看

**Comment by AlexLL55** [comment]
after some investigation my guess is that : there are X- headers on http response (x-bs-client-ip , x-bs-request-id) but there is no X- header on the http request ,  that is the only difference between browser request and downloader request , and Baidu servers look at it as a clue that request is not  being sent  from browser but from another tool. Solution is to deceive Baidu servers by making an exact clone of Http-Request  and for doing that the download must be started from  browser and then if Downloader could  catch request then it will repeat it with all X-headers and lie to servers.
I am not sure about that (just my guess)

**Comment by Thinkgamer** [comment]
> 重试下看看

重新试了很多次都不行，还是403
