### ISSUE TITLE
还是被屏蔽了，下午还可以的，晚上就不行了

### ISSUE THREAD

**Issue by koingql** [syhyz1990/baiduyun#154]
还是被屏蔽了，下午还可以的，晚上就不行了
<img width="448" alt="QQ20190610-214616@2x" src="https://user-images.githubusercontent.com/25839354/59199820-75a5d380-8bc9-11e9-9d92-29878c3642bf.png">

**Comment by codingSy** [comment]
我这儿可以下载，就是网速只能达到500k

**Comment by koingql** [comment]
晚点再试试




| |
朗
|
|
邮箱：koing007@126.com
|

签名由 网易邮箱大师 定制

在2019年06月11日 10:43，sy 写道：

我这儿可以下载，就是网速只能达到500k

**Comment by koingql** [comment]
好像可以了


| |
朗
|
|
邮箱：koing007@126.com
|

签名由 网易邮箱大师 定制

在2019年06月11日 10:44，koingql 写道：
晚点再试试




| |
朗
|
|
邮箱：koing007@126.com
|

签名由 网易邮箱大师 定制

在2019年06月11日 10:43，sy 写道：

我这儿可以下载，就是网速只能达到500k

**Comment by sOngmml** [comment]
速度超不过80k/s。。

**Comment by laohanme** [comment]
@sOngmml 我和你一样 网线稳定快速 但是下载百度云的档案都速度都很慢

**Comment by ChesleyCN** [comment]
我这只有不到100k的速度了，用了百度干净云下也是100k，哎

**Comment by bigzturn** [comment]
前几天还没问题，今天上午就不好使了，换了appid终于变成100K了……心碎

**Comment by syhyz1990** [comment]
限速问题两个方案 :  开会员 或者注册新账号
