### ISSUE TITLE
脚本今天下午失效了。

### ISSUE THREAD

**Issue by wuhao747003943** [syhyz1990/baiduyun#157]
https://i.loli.net/2019/06/12/5d01105f4af0f68759.png

**Comment by Saafo** [comment]
> https://i.loli.net/2019/06/12/5d01105f4af0f68759.png

老哥，请问你这个图床网站有插件之类的吗

**Comment by wuhao747003943** [comment]
> > https://i.loli.net/2019/06/12/5d01105f4af0f68759.png
> 
> 老哥，请问你这个图床网站有插件之类的吗

我用的就是谷歌商店搜新浪图床。

**Comment by Saafo** [comment]
> > > https://i.loli.net/2019/06/12/5d01105f4af0f68759.png
> > 
> > 
> > 老哥，请问你这个图床网站有插件之类的吗
> 
> 我用的就是谷歌商店搜新浪图床。

新浪图床的链接不是ws1.sinaimg.cn开头的吗，主要是好奇你的loli域名是怎么来的哈哈

**Comment by wuhao747003943** [comment]
> > > > https://i.loli.net/2019/06/12/5d01105f4af0f68759.png
> > > 
> > > 
> > > 老哥，请问你这个图床网站有插件之类的吗
> > 
> > 
> > 我用的就是谷歌商店搜新浪图床。
> 
> 新浪图床的链接不是ws1.sinaimg.cn开头的吗，主要是好奇你的loli域名是怎么来的哈哈

哦！你说这个啊，这个不就是博主在提问里给的图床反馈链接吗。
