### ISSUE TITLE
获取失败

### ISSUE THREAD

**Issue by NighyRe** [syhyz1990/baiduyun#158]
用什么都是失败的，IDM无权限，xdown显示错误，Motrix也是下载发生错误
![X2}9WG@SZSOMF}2DY(5 J$3](https://user-images.githubusercontent.com/113569938/190300863-5db2d132-1c06-4a4e-bb79-2df41a8121f7.png)

![8ZHD ~89ZLZ$YHBECI}TOMR](https://user-images.githubusercontent.com/113569938/190300713-af315cc5-28d9-4799-8527-f07e44c520fa.png)

![X$1L7(YWC@`WX`%DJ1_DNS2](https://user-images.githubusercontent.com/113569938/190300615-6ce96677-bf2e-42de-9f93-158a3655f266.jpg)

**Comment by syhyz1990** [comment]
什么网盘？

**Comment by xiweiLee** [comment]
一样有这个问题，百度网盘
