### ISSUE TITLE
Error:SSl HandShake Error

### ISSUE THREAD

**Issue by muzi86754781** [syhyz1990/baiduyun#161]
一点击下载就报这个错误，Error:SSl HandShake Error

**Comment by wolfshadowkd** [comment]
me too

**Comment by syhyz1990** [comment]
是否是会员呢，使用的什么下载方式

**Comment by mraing** [comment]
同问，非会员，下载方式采用的是 Neat下载管理工具进行下载

**Comment by mraing** [comment]
百度云的下载速度，让我回到了上个世纪的 2G网络。平时用的真不多，就偶尔用用，开会员又划不来，100M 的东西能给我下一个小时。试用会员 13M,过了会员就是 50KB、30KB、20KB 徘徊。期待大佬更新~

**Comment by liqigit** [comment]
同问，就安装后成功下载过一次，之后就一直提示这个错误。
MacOS 10.14.4 + Chrome74.0.3729.157（正式版本）

**Comment by illaclv** [comment]
没有大佬解决这个问题吗？

**Comment by AlexLL55** [comment]
Problem on making secure connection ?
Try the solution of issue #163 that uses http connection (not https).

**Comment by syhyz1990** [comment]
把下载链接中https 换成http
