### ISSUE TITLE
夸克网盘 无法使用 无限转圈

### ISSUE THREAD

**Issue by warglaive6046** [syhyz1990/baiduyun#161]
版本：firefox(Mozilla)104.0.2（64位）
控制台报错信息

Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    n moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    get moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    onload moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/ 网盘直链下载助手.user.js#14:228
    HttpRequested moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    HttpRequested moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    onHandle moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    c moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
[详情了解]
[list:1:11774](https://pan.quark.cn/list#/list/all)
    HttpRequested moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    HttpRequested moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    onHandle moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    c moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/sandbox/injected-web.js:1
    s moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/injected.js:1
    post moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/injected.js:1
    HttpRequested moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/injected.js:1
    <anonymous> moz-extension://8b95e1ba-c62b-4690-9312-c7a0feb945da/injected.js:1
    apply self-hosted:2245
    raw resource://gre/modules/ExtensionCommon.jsm:2516
    wrapResponse resource://gre/modules/ExtensionChild.jsm:225
    responses resource://gre/modules/ExtensionChild.jsm:194
    map self-hosted:180
    emit resource://gre/modules/ExtensionChild.jsm:194
    recvRuntimeMessage resource://gre/modules/ExtensionChild.jsm:376
    recvRuntimeMessage self-hosted:1151
    _recv resource://gre/modules/ConduitsChild.jsm:82
    receiveMessage resource://gre/modules/ConduitsChild.jsm:188

​

**Comment by syhyz1990** [comment]
换个浏览器试试，我这里没有问题
