### ISSUE TITLE
这样也可以下载？？

### ISSUE THREAD

**Issue by tongluosao** [syhyz1990/baiduyun#163]
今天在用脚本下载的时候不能用，打开api下载里面的链接说：此网站无法提供安全连接 qdall01.baidupcs.com 发送的响应无效。
因为他说是安全连接无效，所以我就把前面的https改成了http，然后。。idm就蹦出来了， 满速。。

**Comment by Daniels5** [comment]
点赞，改http后的确可以下载了

**Comment by pc85888** [comment]
測試了一下 真的可以下載 但沒有滿速...

**Comment by tongluosao** [comment]
现在好像又限速了，之前我的100Mbps宽带可以跑到11MB/s的速度
