### ISSUE TITLE
脚本失效，包括百度云和夸克

### ISSUE THREAD

**Issue by ayoaak** [syhyz1990/baiduyun#164]
Chrome 版本 105.0.5195.125（正式版本） (arm64)
Tampermonkey BETA 版本 V4.18.6168
脚本 版本 5.9.4

描述：
无法出现直链下载的Button

**Comment by 630975** [comment]
重新安装5.9.4或降级到5.9.3可用

**Comment by ayoaak** [comment]
> 重新安装5.9.4或降级到5.9.3可用

我这边不太行，重装和降级都试过了。

**Comment by ayoaak** [comment]
> 重新安装5.9.4或降级到5.9.3可用

我通过这个方法解决了https://github.com/syhyz1990/baiduyun/issues/114#issuecomment-1140450394
