### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by ZvZvZ** [syhyz1990/baiduyun#165]
如题，最近并不知道chrome抽了什么风，关闭浏览器再打开直链下载助手就无法调用IDM，必须重新登陆百度云才行，但是edge打开就能用，两者都是5.9.4版本。想问问这是为什么，是不是禁用了什么东西导致的。谢谢

**Comment by ZvZvZ** [comment]
再次重试之后发现360禁用或者错删的可能性有但是不大了，原因依然不清晰，cookie也没有什么大问题，倒是chrome显示cookie有10G，不知道是不是什么自动清理导致的。

**Comment by syhyz1990** [comment]
检查一下 IDM 扩展的版本和IDM 是否对应

**Comment by ZvZvZ** [comment]
IDM版本为6.41 B2而IDM的插件是6.40，应该是这个问题

**Comment by OwnerCM** [comment]
> IDM版本为6.41 B2而IDM的插件是6.40，应该是这个问题

请问确定了是这个问题吗？我也遇到同样的情况，无法解决

**Comment by ZvZvZ** [comment]
> > IDM版本为6.41 B2而IDM的插件是6.40，应该是这个问题
> 
> 请问确定了是这个问题吗？我也遇到同样的情况，无法解决

最终我选择回滚到6.41 B1的版本，问题解决
