### ISSUE TITLE
视频提取不到

### ISSUE THREAD

**Issue by lbb1991** [syhyz1990/baiduyun#165]
视频提取不到，一直，昨天还好好的；
![TIM截图20190624172428](https://user-images.githubusercontent.com/11895800/60007490-f58d6c80-96a4-11e9-9e46-993f1ab6f973.png)

**Comment by syhyz1990** [comment]
把https换成http

**Comment by zyfzyfzyf0519** [comment]
![QQ图片20190624185650](https://user-images.githubusercontent.com/52160317/60014272-296f8e80-96b3-11e9-971e-ebd996f11a70.png)

换成http还是不行...麻烦楼主了

**Comment by yudiya** [comment]
+1

**Comment by yudiya** [comment]
我这边是昨晚出现的这种情况

**Comment by LIDIChuan** [comment]
我现在下载也是这样的问题，我还以为只有我一个

**Comment by pingji00** [comment]
同样问题出现，大约6个小时以前。所有文件下载速度停止，退出后重新连接，已无法获取下载链接
