### ISSUE TITLE
更新6.0版本后 夸克网盘下载助手按钮不显示

### ISSUE THREAD

**Issue by damonkm** [syhyz1990/baiduyun#166]
RT

**Comment by syhyz1990** [comment]
切换到 全部文件标签

![image](https://user-images.githubusercontent.com/5344173/195966235-8ee935d3-cea3-4ca1-9e7c-d00a30ad15dc.png)

**Comment by damonkm** [comment]
已经切换到 全部文件标签 还是没有下载助手的按钮

**Comment by syhyz1990** [comment]
退出重新登录下试试

**Comment by damonkm** [comment]
我已尝试过退出重新登录、关闭助手刷新网页再打开、重装助手、清除cookie，我的夸克网页版还是没有显示下载助手按钮，请问还有其它方法吗？

**Comment by syhyz1990** [comment]
用懒人版试试有没有问题。https://www.lanzouw.com/b00tj19nc

**Comment by damonkm** [comment]
我用的是百分浏览器，电脑重启后用360浏览器，夸克网页版可以正常显示下载助手按钮，但百分浏览器依旧没有显示

**Comment by syhyz1990** [comment]
排查下是否与其他脚本或扩展冲突，我试了下百分是正常的。

**Comment by inumimimaid** [comment]
谷歌浏览器，前不久还能用助手的，一个月左右没用，最近更新后打开百度云就不再显示且油猴那边也没启动插件

**Comment by syhyz1990** [comment]
@inumimimaid 删除重装试下

**Comment by inumimimaid** [comment]
卸载之后重装油猴就解决了
