### ISSUE TITLE
大佬们这个是什么问题

### ISSUE THREAD

**Issue by herolovecd** [syhyz1990/baiduyun#168]
![QQ截图20190625165017](https://user-images.githubusercontent.com/49236200/60084076-72821a00-9769-11e9-8f76-b2c1b5e444d6.png)

**Comment by OniityanH** [comment]
同

**Comment by kusnao0215** [comment]
使用IDM下載時，檔案名稱不會自動轉換為jpg、txt、rar等等等，導致IDM點擊開始下載時，會說失敗。
