### ISSUE TITLE
阿里云盘下载图片不正确

### ISSUE THREAD

**Issue by Tarocch1** [syhyz1990/baiduyun#169]
阿里云盘使用 curl 或者 aria 下载图片的时候，url 会添加上 x-oss-process 参数，导致下载的是经过处理后的文件，而不是源文件。使用 api 下载时 url 没有这个参数，可以正常下载。

**Comment by syhyz1990** [comment]
确实是有这个问题，但去掉参数后报错，阿里云盘图片建议使用 api 下载
