### ISSUE TITLE
百度网盘直接下载助手 直链加速版v1.3已失效多日

### ISSUE THREAD

**Issue by y162287761** [syhyz1990/baiduyun#17]
百度网盘直接下载助手 直链加速版v1.3已失效多日
  | {"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":6842083567010549795}
-- | --

**Comment by tzwjkl** [comment]
有时候是报文件过大，有时候是user is not authorized，都是自己网盘里的东西，而且有的文件没有失效有的失效了。。

**Comment by lifei6671** [comment]
我这边直接是443连接失败。

**Comment by syhyz1990** [comment]
请设置代理传递cookie下载
