### ISSUE TITLE
百度网盘只有0-20Kb速度

### ISSUE THREAD

**Issue by Perry1668** [syhyz1990/baiduyun#171]
使用IDM, 下载只有0 - 20kb, 有些时候会升上100以上, 但几秒后又回到0 - 20kb

**Comment by Kaiyuan-Guo** [comment]
我也是，不知道是什么问题，我下的另一个脚本，作者叫软件小妹，下载速度还可以

**Comment by SaHuyang77** [comment]
> 我也是，不知道是什么问题，我下的另一个脚本，作者叫软件小妹，下载速度还可以


https://greasyfork.org/zh-CN/scripts/418182-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%AE%80%E6%98%93%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B-%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%A4%8D%E6%B4%BB%E7%89%88
脚本下载一段时间速度就归零，这个脚本可以参考，速度可以拉到非常高。
