### ISSUE TITLE
提示未选中文件

### ISSUE THREAD

**Issue by ilikethisguy** [syhyz1990/baiduyun#173]
[https://i.loli.net/2019/06/27/5d14d363dc36f77594.png](url)

版本是2.4.1
更新了神秘代码为624966，但是一直出现这种情况 ，提示未选中文件

**Comment by akanecode** [comment]
我也是提示未选中文件

**Comment by keynesxu19** [comment]
可能需要改一下文件名，有特殊符号就会出现这个问题。
![Screen Shot 2019-07-01 at 8 11 37 AM](https://user-images.githubusercontent.com/46702076/60447350-1f302180-9bd8-11e9-958c-ae061021b1b9.png)
![Screen Shot 2019-07-01 at 8 13 00 AM](https://user-images.githubusercontent.com/46702076/60447353-21927b80-9bd8-11e9-9843-28a0553226ad.png)

**Comment by keynesxu19** [comment]
可能需要改文件名，去掉特殊符号

**Comment by syhyz1990** [comment]
刷新下重试 , 有时候数据还没加载完成

**Comment by Fotia5230** [comment]
> 刷新下重试 , 有时候数据还没加载完成

尝试很多遍，发现问题在于文件名
如`《Java Web开发实战经典》.(李兴华).[PDF]&ckook.pdf`无法识别，而更改为`java.pdf`后刷新即正常
