### ISSUE TITLE
推送的链接不能全部顺利下载，有数量遗失或出错

### ISSUE THREAD

**Issue by fungispore** [syhyz1990/baiduyun#173]
应用场景：   天翼网盘，下载文档全为图片，5000-6000张左右分别归属14个文件夹，图片大小皆为kb

评估判断：   数量虽多，但总体文件不大，理论上应该不是大工程

现实状况： 1. 不能实现文件夹打包下载。 
                   2. 只能打开特定文件夹，全选图片推送链接，如果一个文件夹图片170张，首次推送后实际只下载70，需要一一比对出少了哪些，再次选中推送链接，重复操作才能完成，效率极低，本想省时间，没想到倒是费了不少时间。

**Comment by syhyz1990** [comment]
一次下载太多建议分批获取链接

**Comment by fungispore** [comment]
感谢解答！
