### ISSUE TITLE
这段代码在做什么？

### ISSUE THREAD

**Issue by C0olKid** [syhyz1990/baiduyun#175]
(function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://js.users.51.la/19988117.js";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();

为什么往http://ia.51.la/这个服务器发送敏感信息？

**Comment by s635157034** [comment]
发送了一个网盘的url和跳转来的url，ds、kw好像就网盘里的文字没啥，数字还在研究。希望作者出来解释下。

**Comment by C0olKid** [comment]
> 发送了一个网盘的url和跳转来的url，ds、kw好像就网盘里的文字没啥，数字还在研究。希望作者出来解释下。

![深度截图_选择区域_20190628223436](https://user-images.githubusercontent.com/39585314/60349875-fdc31000-99f4-11e9-824e-40bb1aea51ac.png)

原来这个是www.51.la的流量统计代码，搜嘎
