### ISSUE TITLE
点什么都是获取下载链接失败

### ISSUE THREAD

**Issue by huaji1hao** [syhyz1990/baiduyun#176]
![11](https://user-images.githubusercontent.com/101538759/204126755-912c7f06-6570-479f-9937-0bbb6f9f9aa5.png)
无论下什么文件，点什么下载，都是获取下载链接失败，刷新网页，重启脚本都没用，求助qwq

**Comment by could4339** [comment]
我遇到的问题和你一样,没个人来解答

**Comment by ycyin** [comment]
我用edge不行，用Chrome就可以了。浏览器内核版本不同

**Comment by STEVENTAN100** [comment]
我重置一下浏览器就可以了，你也可以试试
