### ISSUE TITLE
连接被远程主机强行关闭

### ISSUE THREAD

**Issue by damonkm** [syhyz1990/baiduyun#176]
![QQ截图20190630043024](https://user-images.githubusercontent.com/52360177/60389252-1c0e3600-9af1-11e9-8209-4cb737c235a1.png)

连接被远程主机强行关闭，无法下载文件。求解答

**Comment by sdfgdnhcdgty** [comment]
老哥 我这边也是这种情况

**Comment by sdfgdnhcdgty** [comment]
老哥 我这边也是这种情况
