### ISSUE TITLE
显示链接之后，使用IDM无法获取到文件

### ISSUE THREAD

**Issue by phoenixor** [syhyz1990/baiduyun#179]
我使用的是qq浏览器，安装全部按照要求做的，插件正常，但是IDM无法获取到文件，如图：
![image](https://user-images.githubusercontent.com/6568115/60391761-a7ef8480-9b28-11e9-987c-4be66b3355da.png)

**Comment by lib-xdown** [comment]
https://xdown.xyz/

 可以使用xdown配合油猴脚本下载百度云文件.
