### ISSUE TITLE
百度网盘超级会员无法解析 共享给用户的文件

### ISSUE THREAD

**Issue by xyfy** [syhyz1990/baiduyun#179]
Mac   Edge  使用普通会员可以解析链接，但是当切换 用户为超级 会员后，无法识别

后面发现是位于共享文件夹的问题，这个文件是其他用户共享给这个会员用户，无法识别

![11111](https://user-images.githubusercontent.com/7838147/205476341-45442010-2296-487b-9eca-9c554cf1b6ea.png)

**Comment by xyfy** [comment]
@syhyz1990 这个在哪个版本解决了？

**Comment by syhyz1990** [comment]
移动到其他目录吧，我网盘里没这个文件夹
