### ISSUE TITLE
求助「下载助手」按钮消失了

### ISSUE THREAD

**Issue by cang171** [syhyz1990/baiduyun#180]
不论是百度还是阿里，亦或更换浏览器edge和firefox，「下载助手」都不见了，前两天还好好的。在greaky fork也有人于今日（12.16）反馈同问题，望能够尽快得到解决。

**Comment by wuhenge** [comment]
hosts文件里添加这两行内容就可以了
43.154.140.105 www.youxiaohou.com
43.154.140.105 api.youxiaohou.com

**Comment by cang171** [comment]
> hosts文件里添加这两行内容就可以了 43.154.140.105 [www.youxiaohou.com](http://www.youxiaohou.com) 43.154.140.105 api.youxiaohou.com

如果是指C:\Windows\System32\drivers\etc里的hosts文件，我已经写进去了，重启并检查过，确定保存成功，还是不行。www.youxiaohou.com也打不开

**Comment by syhyz1990** [comment]
网络问题
