### ISSUE TITLE
脚本用不了了，赶紧更新吧

### ISSUE THREAD

**Issue by Regules** [syhyz1990/baiduyun#182]
脚本用不了了，赶紧更新吧

**Comment by samtone** [comment]
你妈教过你怎么做人吗？ 上过学吗？ 老师教过你什么叫礼貌不？ 找别人帮忙要说请。 用不了专家建议你给你baidu充值会员下载。

**Comment by JMWrpi** [comment]
> 你妈教过你怎么做人吗？ 上过学吗？ 老师教过你什么叫礼貌不？ 找别人帮忙要说请。 用不了专家建议你给你baidu充值会员下载。

请问给百度充值之后能用idm下载吗？mac客户端太狗屎了
