### ISSUE TITLE
无法下载，请看看什么原因？

### ISSUE THREAD

**Issue by zhtodd** [syhyz1990/baiduyun#183]
![image](https://user-images.githubusercontent.com/121271527/209257924-0809af83-567e-483a-8c6a-6b03e46c5b96.png)
提示获取下载链接失败，请刷新重试。但刷新后还是如此。

**Comment by lpym** [comment]
同遇到这个问题，重新登录和重装插件都无法解决。上周其实还是正常的

**Comment by moran9780** [comment]
百度账号被封了，你进客户端下载会提示下载失败1252019，找客服问是说用了第三方下载器的问题，等解决了再用吧申诉了好几天才解除，现在不敢随便用了
