### ISSUE TITLE
最新版本2.4.1，提示需要输入用户名和密码以授权给www.baidupcs.com。

### ISSUE THREAD

**Issue by llh1187** [syhyz1990/baiduyun#184]
# 问题描述 
最新版的脚本2.4.1，利用“增加一个高速下载的接口”所说的接口下载的文件，出现需要授权才能解决问题。
# 展示图片
![被盯上了](https://user-images.githubusercontent.com/40154001/60602424-4d834c00-9de6-11e9-9bd6-aaa6c808983e.PNG)
![捕获](https://user-images.githubusercontent.com/40154001/60602443-570cb400-9de6-11e9-9df5-d083d0bee945.PNG)
# 尝试过的办法
自己有输入自己的百度云用户名和密码进去，可惜没有用，一直在重复请求输入用户名和密码的界面。

**Comment by syhyz1990** [comment]
请按照文档说明使用 , 不要直接复制链接
