### ISSUE TITLE
可否支持下载阿里云盘分享链接的整个文件夹

### ISSUE THREAD

**Issue by Huansheng1** [syhyz1990/baiduyun#184]
目前下载文件夹会提示 请打开文件夹后勾选文件！在太多子目录的情况帐号空间还不够的情况下很难搞。

不知道大佬能不能实现支持自动遍历该文件夹下的每个目录

* 如果文件直接下载
* 如果是文件夹继续递归遍历，直到是文件，下载的文件名可以是：文件目录 - 文件目录2 - 文件名
* 递归的方式如果考虑到api加密问题，可以考虑 操作当前界面元素自动点击展开文件夹直到得到单个文件的下载链接

过程完毕后，自动批量推送到各种支持批量下载的下载方式上

**Comment by syhyz1990** [comment]
不建议这么下载，如果一个文件夹里有1000个文件，会请求1000次接口，服务器会炸
