### ISSUE TITLE
直接链接没反应

### ISSUE THREAD

**Issue by meow-meowo** [syhyz1990/baiduyun#186]
现在API直接下载无法使用，显示链接可以但是速度很慢只有120kb/s 不知道是百度察觉出来并且限速我的账号还是脚本失效（ps.我并没有过度下载百度云，最近发现的这个脚本，只下载过一次6.2G左右的电影）。使用IDM下载youtube可以跑到4m/s  
希望大佬还旧安全，感谢您的脚本

**Comment by syhyz1990** [comment]
限速问题 充值会员解决吧 10块的就可以
