### ISSUE TITLE
[置顶]关于"连接被远程主机强行关闭"的问题

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#187]
看到大家反馈这个问题较多 , 基本上排除脚本问题

**原因如下**
凡是跳转到 qdall01.baidupcs.com 开头的链接 ,此账户被百度拉入小黑屋 , 导致无法下载

**解决方法** 
1. 更换账号 (适合临时下载的同学)
2. 分享要下载的文件 , 到分享界面调用网盘助手 -> 使用"高速下载beta" (适合<4G的文件)
3. 开通百度网盘会员 , 10元的即可**配合脚本可达到超级会员的速度** (适合文件较多的同学)

**Comment by kylin17** [comment]
方法2也已经不能用了，下一小段时间就会提示资源没有权限。

**Comment by ericjwg** [comment]
真的使用频率高，量也很大，10块会员效果还是蛮显著的，开了有大半个月了

**Comment by ericjwg** [comment]
想问一下作者大大能否加入aria2远程下载？类似这个脚本的效果，https://greasyfork.org/zh-CN/scripts/40261-cx-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98

**Comment by cqcw123123** [comment]
www.baiduwp.com    解决你的问题。

**Comment by ericjwg** [comment]
> [www.baiduwp.com](http://www.baiduwp.com) 解决你的问题。

pd直接客户端不得了。用什么网页版，网页版是轻度使用的。

**Comment by BZHBDS** [comment]
账号限速是永久的吗？一般多久会解除？
