### ISSUE TITLE
使用xdown下载超过10G大小文件

### ISSUE THREAD

**Issue by lib-xdown** [syhyz1990/baiduyun#189]
首先去
https://labs.nazo.moe/netdisk.html
解析链接地址.复制,

然后去
https://xdown.xyz
下载.
新建任务,复制进去

即可下载
![}_11OSVE{}55(UCSRBQLF`S](https://user-images.githubusercontent.com/52403944/60767659-80cb2100-a0ed-11e9-853a-6c51394f19d8.jpg)
![M3{@5}$F F1SLC(N~PYF~}A](https://user-images.githubusercontent.com/52403944/60767661-845ea800-a0ed-11e9-8e28-3661d6e48b98.png)

**Comment by woaini7755888** [comment]
不能下百度盘的文件夹吗

**Comment by cqcw123** [comment]
这个插件安装了下载是相当的慢，https://www.baiduwp.com/ 直接解析下载地址，比这个快多了。

**Comment by BZHBDS** [comment]
为什么没有速度啊？是我的账号被限速导致的吗？
