### ISSUE TITLE
mac上下载一短时间就链接失效

### ISSUE THREAD

**Issue by karterlizard** [syhyz1990/baiduyun#191]
mac上面下载一段时间后，提示下载链接失效，去下载页面再点确实失效了，又要从网盘页面重新点高速下载重新提取文件，试了几次，都没有坚持到下载完成，就会链接失效。是什么问题？

**Comment by sylvialinyz** [comment]
我也遇到类似的情况，是调取idm下载直接提示403错误，无法下载，不知道是不是百度屏蔽了

**Comment by cqcw123** [comment]
这个插件安装了下载是相当的慢，https://www.baiduwp.com/ 直接解析下载地址，比这个快多了。

**Comment by cqcw123** [comment]
> 我也遇到类似的情况，是调取idm下载直接提示403错误，无法下载，不知道是不是百度屏蔽了

这个插件安装了下载是相当的慢，https://www.baiduwp.com/ 直接解析下载地址，比这个快多了。

**Comment by sylvialinyz** [comment]
好的，谢谢！

**Comment by syhyz1990** [comment]
把https的链接替换成http 试下
