### ISSUE TITLE
脚本提示[获取选中文件失败，请刷新重试！]

### ISSUE THREAD

**Issue by wolgy** [syhyz1990/baiduyun#195]
实际上刷新无效。浏览器版本：Chrome版本 74.0.3729.131（正式版本） （32 位）。
怀疑是网盘方升级导致脚本失效，无法获取到选中内容。

**Comment by cxycxh** [comment]
今天也出现这个问题，刚刚又恢复正常了

**Comment by ivoidcat** [comment]
我也遇到了

**Comment by syhyz1990** [comment]
多刷新几次就行了 , 有时候网速问题脚本没加载完

**Comment by letterbear** [comment]
@syhyz1990 我刷新了多次, 問題 [获取选中文件失败，请刷新重试！] 仍然存在

**Comment by JYeung111** [comment]
如果刷新後，這個問題仍在，應該是以下原因：
一是你使用批量選取文件操作(ctrl+shift 那種)，腳本是不完整支持這種操作，
二或是有其他腳本同時運作，而它又奪取或干擾此腳本監控選取文件的操作！

此腳本是使用原始監控模式去即時獲取用家的選取文件資料，易受干擾又需經常維護參數，已極極少人使用！

**Comment by cqcw123123** [comment]
试试这个 www.baiduwp.com
