### ISSUE TITLE
直接下载失效分析

### ISSUE THREAD

**Issue by jeffreyhu3** [syhyz1990/baiduyun#196]
当点击直接下载时没有出现下载保存提示框。然后使用直接复制连接到Chrome里面还是无法下载。经分析http://pcs.baidu.com/********会跳转为https://qdall01.baidupcs.com/file/***************，如果把跳转后的最终连接改为http就可以正常下载了。请问这个插件能解决吗？还是百度网盘做的技术手段来阻止使用插件？

**Comment by Croc-ye** [comment]
我也遇到了这个问题

**Comment by cqcw123123** [comment]
www.baiduwp.com  比这个好用的多。

**Comment by PolyCola** [comment]
昨天可以用，今天失效了。是账号被封了吗？

**Comment by syhyz1990** [comment]
这个属于跳转后的链接 , 可以手动修改 , 脚本无法监测

**Comment by JYeung111** [comment]
脚本 是有方法可以提取跳转后的链接！
但無法升已被限速的用家下載速度，包括擁用超級會員身份的用家！
上面情況連 https://qdall01.baidupcs.com/file/****** 都出現 SSL error，即代表該用家已二次超標下載，無得救，只有停止再下載動作然後等待禁下期過！
就算是超級會員都一樣要遵守某一時段内下載限量指標，超標就是要暫禁下載，只是量標比不付會费高很多.，一般個人用是足有餘，如果是分享加上當中有人不守規，瘋狂下載，就會出現這情況！
這些人下載的文件大部份都件以上1xG，超級會員都會被玩死！

**Comment by lib-xdown** [comment]
https://xdown.org/baiduyun/index.htm

使用xdown.org 免费下载百度云,youtube
