### ISSUE TITLE
直连下载失效，显示链接下载也失效

### ISSUE THREAD

**Issue by moxiaotian7** [syhyz1990/baiduyun#198]
无法访问此网站 目前无法访问 qdall01.baidupcs.com。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_SSL_VERSION_INTERFERENCE

**Comment by Tfrain** [comment]
目前好像只能一个一个下载了，速度好像还不如百度网盘，有办法解决吗

**Comment by moxiaotian7** [comment]
我现在用的Pandown，不过下多了也会限速，可以把Pandown的链接复制到IDM下载就可以了

**Comment by Tfrain** [comment]
好吧，多谢

**Comment by lib-xdown** [comment]
https://xdown.org/baiduyun/index.htm

使用xdown.org 免费下载百度云,youtube
