### ISSUE TITLE
Mac motrix 无法正常下载

### ISSUE THREAD

**Issue by gwd0715** [syhyz1990/baiduyun#2]
按教程配置好后，点击发送至Aira下载器，显示#22号错误，瞬间停止了。
网盘上没有一个链接可以用。
![Screen Shot 2020-08-31 at 6 12 01 PM](https://user-images.githubusercontent.com/17922721/91709671-a5b60980-ebb5-11ea-8c00-882f22e1b0e3.png)

**Comment by idseventeen** [comment]
同样的问题。

**Comment by plshelpmi** [comment]
same problem here but using windows

**Comment by Icedroid** [comment]
same problem here with mac
Aria2Gui also can't download.

**Comment by PaulGreen** [comment]
> 按教程配置好后，点击发送至Aira下载器，显示#22号错误，瞬间停止了。
> 网盘上没有一个链接可以用。
> ![Screen Shot 2020-08-31 at 6 12 01 PM](https://user-images.githubusercontent.com/17922721/91709671-a5b60980-ebb5-11ea-8c00-882f22e1b0e3.png)

# #22 错误说明无法在对应的路径保存下载文件。

## 解决方法：

将 RPC 配置中的下载路径修改为绝对地址(modify the relative path to an absolute path)
<img width="476" alt="1" src="https://user-images.githubusercontent.com/4340280/92943243-1fd37180-f485-11ea-8d26-8c60e5851ae2.png">

**Comment by zaneven** [comment]
> > 按教程配置好后，点击发送至Aira下载器，显示#22号错误，瞬间停止了。
> > 网盘上没有一个链接可以用。
> > ![Screen Shot 2020-08-31 at 6 12 01 PM](https://user-images.githubusercontent.com/17922721/91709671-a5b60980-ebb5-11ea-8c00-882f22e1b0e3.png)
> 
> # #22 错误说明无法在对应的路径保存下载文件。
> ## 解决方法：
> 将 RPC 配置中的下载路径修改为绝对地址(modify the relative path to an absolute path)
> <img alt="1" width="476" src="https://user-images.githubusercontent.com/4340280/92943243-1fd37180-f485-11ea-8d26-8c60e5851ae2.png">

改了地址还是不行  Mac绝对路径使用 /Users/apple/Downloads

**Comment by Yue-Charlotte** [comment]
> 绝对地址

改成了本地绝对地址，还是没法用

**Comment by Easylife-z** [comment]
博主有试过嘛，这个 脚本是不是不可以用了，不然还会浪费很多人的时间
