### ISSUE TITLE
确定更新后频繁显示有新版本

### ISSUE THREAD

**Issue by Solomon5812** [syhyz1990/baiduyun#20]
在我更新后依旧在打开一些网站时候会显示有更新，但是我已经更新过了：(

**Comment by Solomon5812** [comment]
I still show updates when I open some websites after I update them, but I’ve already updated them: (

**Comment by syhyz1990** [comment]
把所有的脚本删除重新安装试试

**Comment by Solomon5812** [comment]
已经试过了，每次打开腾讯视频都会跳出来提示更新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "iPc"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 中午11:32
收件人: "syhyz1990/baiduyun";
抄送: "Author";
主题: Re: [syhyz1990/baiduyun] 确定更新后频繁显示有新版本 (#20)





 
把所有的脚本删除重新安装试试
 
&mdash;

**Comment by Solomon5812** [comment]
已经试过了，每次打开腾讯视频都会跳出来提示更新




------------------ 原始邮件 ------------------
发件人: "iPc"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 中午11:32
收件人: "syhyz1990/baiduyun";
抄送: "Author";
主题: Re: [syhyz1990/baiduyun] 确定更新后频繁显示有新版本 (#20)





 
把所有的脚本删除重新安装试试

**Comment by syhyz1990** [comment]
那是别的脚本，应该是 
![image](https://user-images.githubusercontent.com/5344173/102864852-d1fcdb00-446f-11eb-8e2b-9ed19be749f6.png)

**Comment by Solomon5812** [comment]
噢噢，检查了下，还真的有其他脚本把你这个旧版的功能给集成进去了额。。打扰啦很抱歉！！

**Comment by Solomon5812** [comment]
啊，当时发现就是这个插件
 
---原始邮件---
发件人: "iPc"<notifications@github.com&gt;
发送时间: 2020年12月22日 16:08:05
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Solomon5812"<1974491780@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [syhyz1990/baiduyun] 确定更新后频繁显示有新版本 (#20)




 
那是别的脚本，应该是
