### ISSUE TITLE
阿里云API浏览器下载失败

### ISSUE THREAD

**Issue by LogiChai** [syhyz1990/baiduyun#200]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<RequestId>63F87AD933F97F3332DEE901</RequestId>
<HostId>cn-beijing-data.aliyundrive.net</HostId>
<OSSAccessKeyId>STS.NSyXyhzwcysnjBYDubatS7f5L</OSSAccessKeyId>
<SignatureProvided>vLU3+utyoMjMWJI/Vn0CD/W8Fbd45hNjIG6TIruq+20=</SignatureProvided>
<StringToSign>GET 1677229359 referer:https://cn-beijing-data.aliyundrive.net/ referer %2Fccp-bj29-bj-1592982087%2F5fbe6f5182f351d6962f47b2a1d1ef9f107277ae%2F5fbe6f51823152d8082f4ac79663f951b8382d16?di=bj29&dr=9662&f=60dbe1b5116efc0762e24cc5b8c399d160f2d8e9&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%2709%2520%25E6%259D%2580%25E6%25AD%25BB%25E9%2582%25A3%25E4%25B8%25AA%25E7%259F%25B3%25E5%25AE%25B6%25E5%25BA%2584%25E4%25BA%25BA.flac&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DME8Pcl6hCzrGFaGTooHU3bft%2F2KOerjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNRaOBC7XqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABoLIycPaoX%2FFqnd2y0LHz5PZLez2hh5y4%2F3wzGL6q1YITBh%2FrGO1epcUifuyXkMqSdU8OJPG2wsv%2BIRwRFLq28fmUbkeqYxlEuFXo0HQ0tl73WATJkBn7NoATCItqsvLitr2bGYvRIcxJEhngaT8p4staSbnfuKuijaclBv6PDQI%3D&sl=xuLCHkV97ML&u=8420d88cd4d443abbcf739390d66543f&x-oss-access-key-id=STS.NSyXyhzwcysnjBYDubatS7f5L&x-oss-additional-headers=referer&x-oss-expires=1677229359&x-oss-signature-version=OSS2</StringToSign>
<StringToSignBytes>47 45 54 0A 0A 0A 31 36 37 37 32 32 39 33 35 39 0A 72 65 66 65 72 65 72 3A 68 74 74 70 73 3A 2F 2F 63 6E 2D 62 65 69 6A 69 6E 67 2D 64 61 74 61 2E 61 6C 69 79 75 6E 64 72 69 76 65 2E 6E 65 74 2F 0A 72 65 66 65 72 65 72 0A 25 32 46 63 63 70 2D 62 6A 32 39 2D 62 6A 2D 31 35 39 32 39 38 32 30 38 37 25 32 46 35 66 62 65 36 66 35 31 38 32 66 33 35 31 64 36 39 36 32 66 34 37 62 32 61 31 64 31 65 66 39 66 31 30 37 32 37 37 61 65 25 32 46 35 66 62 65 36 66 35 31 38 32 33 31 35 32 64 38 30 38 32 66 34 61 63 37 39 36 36 33 66 39 35 31 62 38 33 38 32 64 31 36 3F 64 69 3D 62 6A 32 39 26 64 72 3D 39 36 36 32 26 66 3D 36 30 64 62 65 31 62 35 31 31 36 65 66 63 30 37 36 32 65 32 34 63 63 35 62 38 63 33 39 39 64 31 36 30 66 32 64 38 65 39 26 72 65 73 70 6F 6E 73 65 2D 63 6F 6E 74 65 6E 74 2D 64 69 73 70 6F 73 69 74 69 6F 6E 3D 61 74 74 61 63 68 6D 65 6E 74 25 33 42 25 32 30 66 69 6C 65 6E 61 6D 65 25 32 41 25 33 44 55 54 46 2D 38 25 32 37 25 32 37 30 39 25 32 35 32 30 25 32 35 45 36 25 32 35 39 44 25 32 35 38 30 25 32 35 45 36 25 32 35 41 44 25 32 35 42 42 25 32 35 45 39 25 32 35 38 32 25 32 35 41 33 25 32 35 45 34 25 32 35 42 38 25 32 35 41 41 25 32 35 45 37 25 32 35 39 46 25 32 35 42 33 25 32 35 45 35 25 32 35 41 45 25 32 35 42 36 25 32 35 45 35 25 32 35 42 41 25 32 35 38 34 25 32 35 45 34 25 32 35 42 41 25 32 35 42 41 2E 66 6C 61 63 26 73 65 63 75 72 69 74 79 2D 74 6F 6B 65 6E 3D 43 41 49 53 25 32 42 67 46 31 71 36 46 74 35 42 32 79 66 53 6A 49 72 35 44 4D 45 38 50 63 6C 36 68 43 7A 72 47 46 61 47 54 6F 6F 48 55 33 62 66 74 25 32 46 32 4B 4F 65 72 6A 7A 32 49 48 46 50 65 48 4A 72 42 65 41 59 74 25 32 46 6F 78 6D 57 31 58 35 76 77 53 6C 71 35 72 52 34 51 41 58 6C 44 66 4E 52 61 4F 42 43 37 58 71 56 48 50 57 5A 48 49 6E 75 44 6F 78 35 35 6D 34 63 54 58 4E 41 72 25 32 42 49 68 72 25 32 46 32 39 43 6F 45 49 65 64 5A 64 6A 42 65 25 32 46 43 72 52 6B 6E 5A 6E 79 74 6F 75 39 58 54 66 69 6D 6A 57 46 72 58 57 76 25 32 46 67 79 25 32 42 51 51 44 4C 49 74 55 78 4B 25 32 46 63 43 42 4E 43 66 70 50 4F 77 4A 6D 73 37 56 36 44 33 62 4B 4D 75 75 33 4F 52 4F 59 36 51 69 35 54 6D 67 51 34 31 55 68 31 6A 67 6A 74 50 7A 6B 6B 70 66 46 74 6B 47 46 31 47 65 58 6B 4C 46 46 25 32 42 39 37 44 52 62 47 25 32 46 64 4E 52 70 4D 5A 74 46 56 4E 4F 34 34 66 64 37 62 4B 4B 70 30 6C 51 4C 75 6B 4D 57 72 25 32 46 77 71 33 50 49 64 70 32 6D 61 34 34 37 4E 57 51 6C 4C 6E 7A 79 43 4D 76 76 4A 39 4F 56 44 46 79 4E 30 61 4B 45 6E 48 37 4A 25 32 42 71 25 32 46 7A 78 68 54 50 72 4D 6E 70 6B 53 6C 61 63 47 6F 41 42 6F 4C 49 79 63 50 61 6F 58 25 32 46 46 71 6E 64 32 79 30 4C 48 7A 35 50 5A 4C 65 7A 32 68 68 35 79 34 25 32 46 33 77 7A 47 4C 36 71 31 59 49 54 42 68 25 32 46 72 47 4F 31 65 70 63 55 69 66 75 79 58 6B 4D 71 53 64 55 38 4F 4A 50 47 32 77 73 76 25 32 42 49 52 77 52 46 4C 71 32 38 66 6D 55 62 6B 65 71 59 78 6C 45 75 46 58 6F 30 48 51 30 74 6C 37 33 57 41 54 4A 6B 42 6E 37 4E 6F 41 54 43 49 74 71 73 76 4C 69 74 72 32 62 47 59 76 52 49 63 78 4A 45 68 6E 67 61 54 38 70 34 73 74 61 53 62 6E 66 75 4B 75 69 6A 61 63 6C 42 76 36 50 44 51 49 25 33 44 26 73 6C 3D 78 75 4C 43 48 6B 56 39 37 4D 4C 26 75 3D 38 34 32 30 64 38 38 63 64 34 64 34 34 33 61 62 62 63 66 37 33 39 33 39 30 64 36 36 35 34 33 66 26 78 2D 6F 73 73 2D 61 63 63 65 73 73 2D 6B 65 79 2D 69 64 3D 53 54 53 2E 4E 53 79 58 79 68 7A 77 63 79 73 6E 6A 42 59 44 75 62 61 74 53 37 66 35 4C 26 78 2D 6F 73 73 2D 61 64 64 69 74 69 6F 6E 61 6C 2D 68 65 61 64 65 72 73 3D 72 65 66 65 72 65 72 26 78 2D 6F 73 73 2D 65 78 70 69 72 65 73 3D 31 36 37 37 32 32 39 33 35 39 26 78 2D 6F 73 73 2D 73 69 67 6E 61 74 75 72 65 2D 76 65 72 73 69 6F 6E 3D 4F 53 53 32 </StringToSignBytes>
<EC>0002-00000101</EC>
</Error>

**Comment by quan-z00** [comment]
我也一样
