### ISSUE TITLE
直接下载点了没反应

### ISSUE THREAD

**Issue by hpeiyan** [syhyz1990/baiduyun#201]
## 第一次下载安装配置好，可以直接下载文件。之后退出过下载器，再点击直接下载文件就没反应了，只能通过‘现实链接’的方式，但是速度又奇慢无比。感谢开发者的奉献，已`捐赠`！

**Comment by syhyz1990** [comment]
可能是浏览器插件的问题 , 去扩展里重新启用试试

**Comment by hpeiyan** [comment]
> 可能是浏览器插件的问题 , 去扩展里重新启用试试


我的是Mac系统，重新启用安装还是一样。通过‘显示链接’，开32线程，客户端又好多是Disconnect的。
![image](https://user-images.githubusercontent.com/12880598/62533991-8ea1cc80-b87a-11e9-8dfe-26d1499e3725.png)

谢谢你的回复！

**Comment by SuperSparta117** [comment]
我也是同样的问题，win7 64位 360浏览器，点了没有反应，

**Comment by qbsencom** [comment]
同样问题。

**Comment by lib-xdown** [comment]
https://xdown.org/baiduyun/index.htm

使用xdown.org 免费下载百度云,youtube

**Comment by syhyz1990** [comment]
发下解析的链接
