### ISSUE TITLE
[更新]2.5.0版本已支持aria2c 链接格式 , 支持分享页面直接下载 , 欢迎反馈

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#202]
下个版本会支持aria2c 链接格式 , 支持分享页面直接下载, 请大家耐心等待

**Comment by InoryLwc** [comment]
终于要支持Aria2了，好棒

**Comment by hr567** [comment]
百度网盘 Cookie 插件能够在 Firefox 中使用吗？

**Comment by Sever-IO** [comment]
百度Cookies获取助手    此扩展程序可能已损坏。

**Comment by syhyz1990** [comment]
> 百度Cookies获取助手 此扩展程序可能已损坏。

把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试

**Comment by Sever-IO** [comment]
> > 百度Cookies获取助手 此扩展程序可能已损坏。
> 
> 把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试

解压后可用了！

**Comment by Sever-IO** [comment]
> > 百度Cookies获取助手 此扩展程序可能已损坏。
> 
> 把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试

解决了

**Comment by JYeung111** [comment]
To  syhyz1990
閣下新版有點出乎本人的預計，get BDUSS cookie 有點創意，但只適用 Chrome core Browser，火狐和其他就不能用！
而我因自建有apache，會結合 host  setting，用一個PHP script 就有相同的效果。
我己不用這方式，直接使用终鏈.！

閣下是否知道終極下載鏈是不需 cookies，只需配合用户代理，外鏈就是终鏈的好例子，

分享鏈下載仍是用舊方法，能使用是百度停用新參數要求，如恢復即會失效！

再者不知閣下使用何種 Debugger，以我所知每句完整 JS statement 指令是以分号作結尾，
例如 alert ("abc");
而不是 alert ("abc")
雖然無影響運作，但除蟲就會增添麻煩！
以此版為油猴(Tampermonkey)提示有過千錯誤
還有現在文件選擇方法，有很多問題，需要更新、、、

如有不喜，希望勿怪，當作吹水！

**Comment by syhyz1990** [comment]
> To syhyz1990
> 閣下新版有點出乎本人的預計，get BDUSS cookie 有點創意，但只適用 Chrome core Browser，火狐和其他就不能用！
> 而我因自建有apache，會結合 host setting，用一個PHP script 就有相同的效果。
> 我己不用這方式，直接使用终鏈.！
> 
> 閣下是否知道終極下載鏈是不需 cookies，只需配合用户代理，外鏈就是终鏈的好例子，
> 
> 分享鏈下載仍是用舊方法，能使用是百度停用新參數要求，如恢復即會失效！
> 
> 再者不知閣下使用何種 Debugger，以我所知每句完整 JS statement 指令是以分号作結尾，
> 例如 alert ("abc");
> 而不是 alert ("abc")
> 雖然無影響運作，但除蟲就會增添麻煩！
> 以此版為油猴(Tampermonkey)提示有過千錯誤
> 還有現在文件選擇方法，有很多問題，需要更新、、、
> 
> 如有不喜，希望勿怪，當作吹水！

火狐的插件已提交, 还在审核中 . 分号的问题应该是编辑器的问题, 不需要cookie的终链的参数能否提供下

**Comment by syhyz1990** [comment]
> To syhyz1990
> 閣下新版有點出乎本人的預計，get BDUSS cookie 有點創意，但只適用 Chrome core Browser，火狐和其他就不能用！
> 而我因自建有apache，會結合 host setting，用一個PHP script 就有相同的效果。
> 我己不用這方式，直接使用终鏈.！
> 
> 閣下是否知道終極下載鏈是不需 cookies，只需配合用户代理，外鏈就是终鏈的好例子，
> 
> 分享鏈下載仍是用舊方法，能使用是百度停用新參數要求，如恢復即會失效！
> 
> 再者不知閣下使用何種 Debugger，以我所知每句完整 JS statement 指令是以分号作結尾，
> 例如 alert ("abc");
> 而不是 alert ("abc")
> 雖然無影響運作，但除蟲就會增添麻煩！
> 以此版為油猴(Tampermonkey)提示有過千錯誤
> 還有現在文件選擇方法，有很多問題，需要更新、、、
> 
> 如有不喜，希望勿怪，當作吹水！

下个版本会修复分号的问题 , 終極下載鏈的参数能否提供下

**Comment by othpark** [comment]
我也是此扩展程序可能已损坏
crx改成zip么？这也解压不了啊。。。

**Comment by gzb39174114** [comment]
> > > 百度Cookies获取助手 此扩展程序可能已损坏。
> > 
> > 
> > 把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试
> 
> 解决了

怎么解决的？改后缀成zip无法解压，直接拖进去是损坏的扩展程序。

**Comment by fireicewater** [comment]
> > > > 百度Cookies获取助手 此扩展程序可能已损坏。
> > > 
> > > 
> > > 把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试
> > 
> > 
> > 解决了
> 
> 怎么解决的？改后缀成zip无法解压，直接拖进去是损坏的扩展程序。

我改成rar能解压安装了

**Comment by walnutist** [comment]
> > > > > 百度Cookies获取助手 此扩展程序可能已损坏。
> > > > 
> > > > 
> > > > 把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试
> > > 
> > > 
> > > 解决了
> > 
> > 
> > 怎么解决的？改后缀成zip无法解压，直接拖进去是损坏的扩展程序。
> 
> 我改成rar能解压安装了

rar在MacOS下无法解压缩，用的是Unarchiver

**Comment by fireicewater** [comment]
这个是链接支持aria2Ng吗,我复制链接过去还是报错

**Comment by dis-xcl** [comment]
> > > > > 百度Cookies获取助手 此扩展程序可能已损坏。
> > > > 
> > > > 
> > > > 把后缀改成zip解压 , 在扩展中心-> 加载已解压的扩展程序 试试
> > > 
> > > 
> > > 解决了
> > 
> > 
> > 怎么解决的？改后缀成zip无法解压，直接拖进去是损坏的扩展程序。
> 
> 我改成rar能解压安装了

安装成功了，但是刷新网盘页面，点显示链接(aric)，没有任何反应啊！

**Comment by GUccipradahaha** [comment]
MAC OS 拖进去链接显示 程序包无效‘CRX_REQUIRED_PROOF_MISSING,请问怎么解决呢’

**Comment by walnutist** [comment]
> MAC OS 拖进去链接显示 程序包无效‘CRX_REQUIRED_PROOF_MISSING,请问怎么解决呢’

后缀改RAR，解压缩，然后在扩展管理里面安装解压缩后的扩展。
但是Unarchiver在MacOS下居然不支持改名后的RAR，不知道为什么

**Comment by Pso2** [comment]
![image](https://user-images.githubusercontent.com/16096638/63075363-03a09080-bf64-11e9-89af-d3e3164dfa20.png)
等待修复

**Comment by superiver0** [comment]
分享页面必须登录账户呀，这样会被拉黑的，我下载一个大文件，下到80%就没速度了。还是在分享页面上下载的。https://labs.nazo.moe/netdisk.html什么时候恢复使用呀？

**Comment by syhyz1990** [comment]
更新到2.6.0

**Comment by superiver0** [comment]
非常感谢，这个简直太好用了，就害怕拉入黑名单限速10KB/S，现在免登录就解决了。谢谢。




------------------ 原始邮件 ------------------
发件人: "iPc"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 晚上10:35
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "superiver"<910347041@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] [更新]2.5.0版本已支持aria2c 链接格式 , 支持分享页面直接下载 , 欢迎反馈 (#202)




Closed #202.
