### ISSUE TITLE
给个关于IDM UA的建议

### ISSUE THREAD

**Issue by AllowDash** [syhyz1990/baiduyun#202]
不知作者有没有想过给个UA来让用户复制链接直接下载，而不是点击唤起IDM下载，直接使用链接下载可以规避一些用户不会配置IDM+IDM可能有时会出错的情况，还可以在手机IDM上使用链接下载（手机网盘时不时会自己掉线，这时用手机IDM下载就会比较稳。）。

**Comment by zggcdnb** [comment]
good idea
