### ISSUE TITLE
http/1.1 500 错误

### ISSUE THREAD

**Issue by zslasa** [syhyz1990/baiduyun#203]
在用 neat download manager 下载的时候总是出现这个错误，mac和win下都是

**Comment by syhyz1990** [comment]
用的什么链接

**Comment by zslasa** [comment]
你好，用的API下载中的显示链接，当然不是复制粘贴，是用右键调用下载工具，pandownload解析后也会出现500错误

在 2019年8月14日，16:08，iPc <notifications@github.com<mailto:notifications@github.com>> 写道：


用的什么链接
