### ISSUE TITLE
使用直链下载配合IDM时被限速，并且无法下载一个以上的文件

### ISSUE THREAD

**Issue by huan0808** [syhyz1990/baiduyun#204]
``[图片]

**Comment by huan0808** [comment]
正在下载一个文件时，再下载另一个文件会弹出IDM的提示：baidupcs.com规定只允许请求一次

**Comment by GitHub-fort** [comment]
用IDM下载只有 50KB/s

而且，正在下载一个文件时，再下载另一个文件会弹出IDM的提示：baidupcs.com规定只允许请求一次

**Comment by syhyz1990** [comment]
试试新的下载方式吧 , Aria
