### ISSUE TITLE
请教一下遇到的几个问题

### ISSUE THREAD

**Issue by mizuyu1** [syhyz1990/baiduyun#206]
感谢插件，希望大佬健康。下面是我遇到的几个问题，不知道是不是我的问题。
1.直接下载没有反应
2.点显示链接后会转到qdall01的那个页面，像大家说的那样讲s去掉虽然能够用idm下载，但是速度很慢。
3.如果选择冲会员的话，是不是随便一个会员就好？
再一次谢谢大佬的插件，希望能够得到解答

**Comment by syhyz1990** [comment]
冲普通会员就可以了, 直接下载有时候IDM监听不到, 使用网盘API下载或者Aria下载都可以达到满速
