### ISSUE TITLE
大佬，Win10 Edge 无法安装Cookies插件

### ISSUE THREAD

**Issue by Hervey-Hu** [syhyz1990/baiduyun#207]
下载的cookies插件没法导入到 Edge浏览器，谢谢！

**Comment by Pso2** [comment]
chrome 下载百度Cookies获取助手后出现Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'

**Comment by moneeWong** [comment]
楼上+1

**Comment by GitHub-fort** [comment]
chrome下载百度Cookies获取助手后出现包装无效：'CRX_REQUIRED_PROOF_MISSING'

Chrome浏览器扩展程序页面  百度Cookies获取助手 显示已损坏

**Comment by szhielelp** [comment]
> chrome下载百度Cookies获取助手后出现包装无效：'CRX_REQUIRED_PROOF_MISSING'
> 
> Chrome浏览器扩展程序页面 显示 百度Cookies获取助手 已损坏

扩展名改成 .zip 解压, 然后 extension - load unpack 试试看

**Comment by jasone0411** [comment]
> > chrome下载百度Cookies获取助手后出现包装无效：'CRX_REQUIRED_PROOF_MISSING'
> > Chrome浏览器扩展程序页面 显示 百度Cookies获取助手 已损坏
> 
> 扩展名改成 .zip 解压, 然后 extension - load unpack 试试看

mac上改成.zip后解压显示压缩包错误，无法解压（解压软件winzip）。

**Comment by syhyz1990** [comment]
你可以下载最新基于chrome内核的edge试下
