### ISSUE TITLE
请教作者，分享页面无法获得Aria链接

### ISSUE THREAD

**Issue by dis-xcl** [syhyz1990/baiduyun#208]
2.5.0版本，已成功安装百度Cookies助手。在网盘分享页面选中文件，点击显示链接(Aria)，无任何反应。保存到我的网盘，点击就可以获得Aria链接。是不是现在脚本还是无法分享页面使用，只能把文件保存我的网盘才能用？……

**Comment by syhyz1990** [comment]
2.5.2版本已修复这个问题 , 稍后更新下
