### ISSUE TITLE
chrome显示插件已损坏

### ISSUE THREAD

**Issue by Sunlei012** [syhyz1990/baiduyun#209]

**Comment by CCint3** [comment]
me too.

**Comment by syhyz1990** [comment]
把插件后缀crx改成zip , 解压到文件夹 , 去Chrome扩展页面 -> 勾选开发者模式 - > 加载已解压的扩展程序 , 选择刚才解压的扩展程序

**Comment by jasone0411** [comment]
> 把插件后缀crx改成zip , 解压到文件夹 , 去Chrome扩展页面 -> 勾选开发者模式 - > 加载已解压的扩展程序 , 选择刚才解压的扩展程序

解压后通过加载解压程序找不到扩展呢？格式不识别

**Comment by koulamo** [comment]
把插件后缀crx改成zip , 解压到文件夹 , 去Chrome扩展页面 -> 勾选开发者模式 - > 加载已解压的扩展程序 , 选择刚才解压的扩展程序
結果無法執行，如下圖
![2019-08-17 11_06_26-擴充功能](https://user-images.githubusercontent.com/50986704/63205983-52266a00-c0df-11e9-9800-c4bae1a69f44.png)
