### ISSUE TITLE
提示：获取下载链接失败！请刷新网页后重试！

### ISSUE THREAD

**Issue by xilinjiong** [syhyz1990/baiduyun#210]
提示：获取下载链接失败！请刷新网页后重试！

**Comment by kwl01skz** [comment]
尝试使用较新版本的浏览器，
举例来说，我使用win10自带的edge遇到此提示，
使用最新dev版edge就好了。

**Comment by zlhdd108** [comment]
出现此问题，之前相同环境正常

edge版本：
Microsoft Edge	113.0.1774.57 (正式版本) (64 位) 
修订	b3b212deff59d422d4ce9487f276cb0e0d352835
Chromium 版本	113.0.5672.127
操作系统	Windows 11 Version 22H2 (Build 22631.1825)
----
opera：
版本：98.0.4759.6
浏览器识别
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 OPR/98.0.0.0
