### ISSUE TITLE
直链无法下载

### ISSUE THREAD

**Issue by Keouy** [syhyz1990/baiduyun#210]
![Snipaste_2019-08-16_09-57-06](https://user-images.githubusercontent.com/40164931/63138230-60578600-c00c-11e9-891a-43b235f4f81a.png)

**Comment by syhyz1990** [comment]
升级到2.5.1

**Comment by Keouy** [comment]
点击直接下载没有反应




------------------ 原始邮件 ------------------
发件人: "iPc"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 中午11:32
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "Keu"<534386251@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 直链无法下载 (#210)




升级到2.5.1

**Comment by syhyz1990** [comment]
2.5.2 已经修复

**Comment by Keouy** [comment]
还是没反应，视频里左边的是您的插件


------------------ 原始邮件 ------------------
发件人: "iPc"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 下午2:35
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "Keu"<534386251@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 直链无法下载 (#210)




2.5.2 已经修复
