### ISSUE TITLE
百度cookie助手没法用？

### ISSUE THREAD

**Issue by ssguaishou** [syhyz1990/baiduyun#213]
下载好提示错误，修改后缀.zip但是显示压缩包出现问题无法打开，直接拉.crx则是显示需要修复

**Comment by jasone0411** [comment]
我的也是这个问题，mac系统，解压缩用的winzip和系统自带试了都不行

**Comment by YGingko** [comment]
现在又不能下载了？
![图片](https://user-images.githubusercontent.com/19166816/63209800-46a36500-c118-11e9-85b1-3b7b690d46d0.png)

**Comment by JYeung111** [comment]
看圖可知你巳超標下載，己被限速，加上連SSL都被拒絕，即是你係嚴重一類，暫時不能下載，要等監期完後才能再下載，好似話在監期中途再試行下載的動作會被加監期!!!

安裝 cookies 助手是覆雜困難的動作，因有太變數如多種不同Browser需要各自Addon，用家技術高低，是很難全面支援！
