### ISSUE TITLE
最近直链下载速度忽然很慢？发现一个表面情况

### ISSUE THREAD

**Issue by ma707430336** [syhyz1990/baiduyun#215]
因为我不懂脚本这些东西，所以我说一些表面上的情况。我是最近开始使用，我使用直链一直下载的一直很顺利，但是我一个朋友的下载速度确是很慢。之前一直搞不懂，突然今天我的下载速度也一下子变得很慢而且很多线程都无法连接，症状与我朋友的很类似，我忽然想起我之前好像是有一个百度云盘的小会员（百度云盘小会员10元/月 不提供加速服务   只有25元/月的才提供加速服务），而今天那个小会员到期了，我就在考虑是否今天网速变慢根这个有关，接着我就尝试又办了一个月那个不提供加速服务的小会员，发现我的下载速度又恢复到了正常情况，并且我将我的账号在朋友（就是那个下载速度一直很慢）的电脑上，发现下载速度也提上来了。我不是很懂，所以只能看到表象，那么更深层的情况是什么原因？
Ps：还有一点，在今天下载速度正常之后（也就是我办了一个小会员情况下），我更换了一个没有任何会员服务的账号进行下载，发现下载速度也恢复正常了。

**Comment by syhyz1990** [comment]
百度普通会员配合脚本就可以达到超级会员的效果 , 自己知道就好
