### ISSUE TITLE
百度网盘万能助手 下载地址 支持Chrome & FireFox

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#216]
修复了火狐浏览器无法使用的问题 , 请尽快更新

## 💽 下载地址

- [下载地址](https://baiduwp.ctfile.com/dir/3994041-35240665-e1ea37/)

- [Chrome商店地址](https://chrome.google.com/webstore/detail/baidu-cookies-get-assista/jfgjhkncgeglkbflafenjfnddlahcfop)

- [FireFox插件地址](https://addons.mozilla.org/zh-CN/firefox/addon/baidu-cookies-get-assistant/)

**Comment by Hervey-Hu** [comment]
大佬，什么时候支持Edge啊，谢谢！

**Comment by syhyz1990** [comment]
可以参考https://www.jianshu.com/p/836156ff1851?utm_source=oschina-app

**Comment by TTTPOB** [comment]
Google商店链接404，是不是被下架了

**Comment by sd123588** [comment]
404 FQ的，还是404

**Comment by ndc168** [comment]
Can you put "百度网盘万能助手 v2.0.0.crx" on Github or free for download? the cloud drive require registration to download, thanks.

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)
