### ISSUE TITLE
夸克网盘无法获取直链

### ISSUE THREAD

**Issue by icheto** [syhyz1990/baiduyun#216]
![image](https://user-images.githubusercontent.com/72912780/231737951-888c21b8-422e-4abe-aa0e-eb633fa6e845.png)
如图所示

**Comment by Joackk** [comment]
同样遇到这个问题

**Comment by superorange** [comment]
我修复了，提交了pull request等待作者合并下。https://github.com/superorange/baiduyun

**Comment by Aviciwick** [comment]
![屏幕截图 2024-05-15 202812](https://github.com/syhyz1990/baiduyun/assets/88172511/64b0a215-51ba-4881-80bb-a08c99865549)
夸克网盘无法获取直链
