### ISSUE TITLE
使用xdown没有网啊,还限制300m以下,还需要cookie,那我还不如使用pandownload呢

### ISSUE THREAD

**Issue by luoawai123** [syhyz1990/baiduyun#217]
![image](https://user-images.githubusercontent.com/33819035/63222044-96476680-c1d4-11e9-99e2-ed4e85714686.png)
使用xdown没有网啊,还限制300m以下,还需要cookie,那我还不如使用pandownload呢

**Comment by syhyz1990** [comment]
此软件主要解决第三方软件会盗用Cookie的可能, 脚本不会上传你的cookie到第三方 , 仅此而已
