### ISSUE TITLE
大佬，为什么API直接获取连接到IDM总是错误

### ISSUE THREAD

**Issue by 3q34** [syhyz1990/baiduyun#219]
API直接获取连接到IDM总是错误，复制链接到IDM也是异常，其他人也是这样还是我自己的问题？

**Comment by lomemeng** [comment]
下载是能下载，但度娘给大文件加权了，想要满速必须识别cookie，认定为会员用户或非限速用户才同意get

**Comment by syhyz1990** [comment]
楼上正解
