### ISSUE TITLE
使用Tampermonkey BETA加载脚本后获取下载链接，依然提示需要安装网盘万能助手

### ISSUE THREAD

**Issue by sde31c** [syhyz1990/baiduyun#220]
脚本版本6.0.4
Tampermonkey BETA v4.19.6180
浏览器： MS Edge v112.0.1722.48

使用Tampermonkey BETA加载脚本后获取下载链接，依然提示需要安装网盘万能助手。

**Comment by xiaoyi-feng** [comment]
我也是遇到这样的问题，edge浏览器
