### ISSUE TITLE
直接下载无法使用

### ISSUE THREAD

**Issue by moneeWong** [syhyz1990/baiduyun#220]
![批注 2019-08-19 101041](https://user-images.githubusercontent.com/17845920/63234957-39968b00-c26a-11e9-9db9-ac1d7d3081a2.jpg)

**Comment by MicroappsTeam** [comment]
Use Hyper speed download instead.
(btw, i can't type in chinese rn bc i bused my windows 10)

**Comment by syhyz1990** [comment]
你主要更新脚本了
