### ISSUE TITLE
请问下XDown下载Aria2c链接时 状态显示异常

### ISSUE THREAD

**Issue by tokaka22** [syhyz1990/baiduyun#221]
![Snipaste_2019-08-19_21-52-17](https://user-images.githubusercontent.com/50353614/63270925-a42be300-c2cb-11e9-8264-d00301c3f6d7.png)

**Comment by Edwardvi** [comment]
我这边也是异常

**Comment by 9760711243** [comment]
而且速度一直在100K一下，估计是被百度和谐了

**Comment by lomemeng** [comment]
在意料之中，从度娘推出单文件下载付费套餐开始就明白了

**Comment by dis-xcl** [comment]
我也是这样，无论是直链还是Aria链接在Xdown里都是异常，无法下载。有时反复试了好多次，突然能下载了，速度也只有几十k，我以为是账号被百度限速了。结果登陆Pandownload下载速度快得飞起，那应该没被限速。所以不知道问题出在哪里了？！

**Comment by syhyz1990** [comment]
用的是aira2c的链接么

**Comment by tokaka22** [comment]
> 
> 
> 用的是aira2c的链接么
是的，是aira2c

**Comment by HI6cirep** [comment]
一样问题，之前aira2c还能用，现在都是异常。

**Comment by superiver0** [comment]
> 我也是这样，无论是直链还是Aria链接在Xdown里都是异常，无法下载。有时反复试了好多次，突然能下载了，速度也只有几十k，我以为是账号被百度限速了。结果登陆Pandownload下载速度快得飞起，那应该没被限速。所以不知道问题出在哪里了？！

我验证了，用Xdown下载3,4G就会出现异常或者被限速40kb/s，但是再换回到pandownload下载时并未显示账号受限。问一下没有速度和异常怎么解决。

**Comment by JYeung111** [comment]
應該是下載同一文件開啟線程太多出事，估計大家是用３２線程！
如果係不被限速户，單線己過M/s，反之就算開更多線，只會死得更快。
如果换回到pandownload會有更佳效果，就應繼續用，各程式或腳本各有不同之處，只是供大家適合者選之用之。
被限速户所獲取的終極下載鏈是有固定特徵！

**Comment by syhyz1990** [comment]
更新到最新版本试下

**Comment by cbr252522489** [comment]
同样异常。估计被封了

**Comment by changewen** [comment]
我也遇到这个问题，有时暂停继续几次可以恢复，但有些就一直都异常，希望尽快更新啊~

**Comment by xdown-org** [comment]
@syhyz1990   
如果是不限次数下载,请在下载链接里面添加` --forbidCookie "1"`
然后把xdown 更新到1.0.0.4
这样就避免了自动提交cookie导致封账号.
