### ISSUE TITLE
[置顶]2.7.0 讨论专用贴

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#224]
大家有什么好的建议和意见都可以留言

**Comment by 9760711243** [comment]
2.6.0版的XDown被和谐，之前的速度是1M，现在只有160K，只试了一个14G的文件，没下完就被限速了，方法都是按图片教程来的，设置的是32线程

**Comment by Hervey-Hu** [comment]
今天更新2.60后，脚本没有启动，页面的脚本图标入口也没有了，谢谢

**Comment by wh1zper** [comment]
当使用批量下载时
下载助手 -> API下载 -> 显示链接 -> 复制全部链接
从IDM选择 任务 -> 从剪贴板中添加批量下载
文件名与文件类型都无法识别, 但下载地址是正确的, 这种是IDM的问题吗

**Comment by superiver0** [comment]
2019.8.23测试免登录IDM为8线程，速度为满速12M/S，XDOWN也是12M/S，2019.8.23测试免登录IDM32县城的时候速度为890KB/S，XDOWN96线程的时候速度为1.6MB/S，只用了一天就被和谐了。再加把劲儿呀。

**Comment by edison99x** [comment]
你好，我也是被拉黑了，现在只有80kb/s

**Comment by syhyz1990** [comment]
开隐私模式获取免登录链接下载试试

**Comment by edison99x** [comment]
你指的是分享链接吗？还是？怎么开启隐私模式？



Cheng-wei Chen,postgraduate student




在2019年8月24日 17:55，iPc<notifications@github.com> 写道：

开隐私模式获取免登录链接下载试试

**Comment by edison99x** [comment]
貌似还是不行

**Comment by superiver0** [comment]
> 开隐私模式获取免登录链接下载试试

我不知道隐私模式是什么，但是的无痕模式网页不会显示百度网盘直链下载助手的插件。我打开扩展发现插件还是开着的。他只在正常界面有显示。

**Comment by syhyz1990** [comment]
那就退出登录获取

**Comment by NeoZZZZ** [comment]
今天格式化重新安装系统后就从1m的速度下降到60k...
不知道发生了什么

**Comment by ahgan** [comment]
> > 开隐私模式获取免登录链接下载试试
> 
> 我不知道隐私模式是什么，但是的无痕模式网页不会显示百度网盘直链下载助手的插件。我打开扩展发现插件还是开着的。他只在正常界面有显示。

需要允许油猴在隐私模式启用

**Comment by Hervey-Hu** [comment]
脚本在Greasy Fork中下架了，看不到了

**Comment by Canaria21** [comment]
脚本在Greasy Fork被删除了

**Comment by JYeung111** [comment]
Greasy Fork删除了此腳本，有甚麼問題嗎？
只要此處仍然運作，繼續更新就OK！

**Comment by Hervey-Hu** [comment]
2.64版本在Edge中有启动，但是菜单栏没有出现，脚本无法使用，谢谢！

**Comment by JYeung111** [comment]
你先去查看該頁 的console.log 才有資料去查究問題所在！
火狐按 F12 再選 主控台 項
edge 就不清楚

**Comment by Hervey-Hu** [comment]
Edge无法解码，助手没法使用
![擷取](https://user-images.githubusercontent.com/52092137/64020652-baa42b00-cb64-11e9-98fb-3438a60ae750.PNG)

**Comment by JYeung111** [comment]
基本上打開百度頁面，你要在 console 見到以下訊息才可確定腳本起動成功！
![helper](https://user-images.githubusercontent.com/41117798/64024574-4de15e80-cb6d-11e9-83f7-3cedc6828a44.PNG)
失敗的原因有很多，但別人都OK，就會多是係TM設定出問顥，
其中一樣多人中招就是JQuery  library 的裝載出事即是這句指令碼

// @require           https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js

下列是 swal (代替alert) 專用，我就不能使用
// @require           https://cdn.bootcss.com/sweetalert/2.1.2/sweetalert.min.js

大部份都會無問題，但有極少少人會出事要改別的載入點！

**Comment by Hervey-Hu** [comment]
很奇怪的是，我正常進頁面，脚本不啓動，但是進入主控台后，刷新一下就能正常啓動了。
![擷取](https://user-images.githubusercontent.com/52092137/64029044-63a75180-cb76-11e9-9e55-65605d706214.PNG)

**Comment by JYeung111** [comment]
又更新2.7.0，而且加了雜項功能，又要重新再看一次，真傷神！

**Comment by jjshuaiye** [comment]
登录下载异常，免登陆下载满速，最新版2.7.0

**Comment by jjshuaiye** [comment]
有没有可能免登陆下载多个文件

**Comment by JYeung111** [comment]
登录下载异常，免登陆下载满速
==> 多是你巳被限速，而且是嚴重那種
有没有可能免登陆下载多个文件
==>是可以一次下載多個文件包括文件夾，以打包式下載，上限是3003M （不確定）

**Comment by jjshuaiye** [comment]
登录下载还是会检测账号，换了新账号下了一会又异常了

**Comment by JYeung111** [comment]
每個賬号在每一個時段有個限量下載指，不論是付費和非付費户，超量就限速，再超是限下(SSL error)， 就算係超級賬号也都是一樣，只不過限量比較高，有人說非付費是10Ｇ

**Comment by edison99x** [comment]
弱弱问下：如何进行免登陆下载？





Cheng-wei Chen,postgraduate student

Academic Editor | Neurosurgery Division | DXY.cn

Department of Neurosurgery,Key Laboratory on Brain Function Repair and Regeneration of Guangdong Province,Zhujiang Hospital of Southern Medical University,253# industry road, 510282, Guangzhou, China.

在2019年08月31日 14:58，JYeung111 写道：

每個賬号在每一個時段有個限量下載指，不論是付費和非付費户，超量就限速，再超是限下(SSL error)， 就算係超級賬号也都是一樣，只不過限量比較高，有人說非付費是10Ｇ

**Comment by JYeung111** [comment]
現在已改名為  "不限速链接"

**Comment by dis-xcl** [comment]
已升级到2.7.1版，点击"不限速链接"，无法获得链接，总是跳出 "请尝试更换IP或重新分享"

**Comment by JYeung111** [comment]
@ dis-xct
不限速链接，
在某一時間内，每個IP只能在某一分享鏈有三次免驗証下載！

**Comment by syhyz1990** [comment]
> 很奇怪的是，我正常進頁面，脚本不啓動，但是進入主控台后，刷新一下就能正常啓動了。
> ![擷取](https://user-images.githubusercontent.com/52092137/64029044-63a75180-cb76-11e9-9e55-65605d706214.PNG)
> ![2](https://user-images.githubusercontent.com/52092137/64029264-d87a8b80-cb76-11e9-8654-17605559f176.PNG)

你需要把其他的百度网盘脚本禁用掉 , 否则会冲突

**Comment by Porcelana** [comment]
> 大家有什么好的建议和意见都可以留言

高速下载(beta)选项被删除了，期待重新加回，另外2.7.1版，点击"不限速链接"，无法获得链接，总是跳出 "请尝试更换IP或重新分享"，期待支持Aria2GUI等各类mac osx的第三方下载方式

**Comment by Porcelana** [comment]
希望新版中继续支持PanDownload的web及各种第三方下载方式，2.7.1版本好像没有之前的旧版本来得方便

**Comment by xdown-org** [comment]
@syhyz1990 

xdown 更新了1.0.0.4版本,
新增了两个参数功能.
https://xdown.org/header/index.htm

自定义有三个选项,分别为[--header] [--forbidCookie "1"] [--cookieHost "pan.baidu.com"]

[--forbidCookie "1"] 为禁用cookie,程序下载会默认载入cookie进行填充,此参数为某种需求,不想提交cookie使用.

--forbidCookie "1" 
[--cookieHost "pan.baidu.com"] 此参数的意思是使用跨域cookie, 例子就是使用pan.baidu.com的cookie请求. 还可以是

--cookieHost "http://pan.baidu.com"
--cookieHost "https://pan.baidu.com"
当请求某个域名,并不想使用本地cookie,例子如下:

"https://d.pcs.baidu.com/file/52f9b60bff29cb2fc300c228629f8d83?fid=1187826186-250528-196948380033096&dstime=1562498630&rt=sh&sign=FDtAERyK-DCb740ccc5511e5e8fedcff06b081203-AaxLelIrc436z9mCGjGx%2Baewgng%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8967488906706405743&dp-callid=0&r=230531620&clienttype=25&vuk=1187826186&sh=1" --out "[SUBPIG][艺人史上最糟糕的一天].mp41" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --forbidCookie "1" 
当请求某个域名,想使用其他域名cookie,例子如下:

"https://d.pcs.baidu.com/file/52f9b60bff29cb2fc300c228629f8d83?fid=1187826186-250528-196948380033096&dstime=1562498630&rt=sh&sign=FDtAERyK-DCb740ccc5511e5e8fedcff06b081203-AaxLelIrc436z9mCGjGx%2Baewgng%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8967488906706405743&dp-callid=0&r=230531620&clienttype=25&vuk=1187826186&sh=1" --out "[SUBPIG][艺人史上最糟糕的一天].mp41" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --cookieHost "pan.baidu.com"
注意
[--forbidCookie "1"] [--cookieHost "pan.baidu.com"] 这个两个参数是1.0.0.4版本才具备的,若想使用,需要升级到1.0.0.4版本.


免登录链接里面可以新增xdown下载,里面添加一个--forbidCookie "1"  ,禁用cookie,不然会默认连带cookie一起请求,导致被限速.

[--cookieHost "pan.baidu.com"]  可以使用跨域cookie请求,可以省略掉cookie助手.

**Comment by syhyz1990** [comment]
> @syhyz1990
> 
> xdown 更新了1.0.0.4版本,
> 新增了两个参数功能.
> https://xdown.org/header/index.htm
> 
> 自定义有三个选项,分别为[--header] [--forbidCookie "1"] [--cookieHost "pan.baidu.com"]
> 
> [--forbidCookie "1"] 为禁用cookie,程序下载会默认载入cookie进行填充,此参数为某种需求,不想提交cookie使用.
> 
> --forbidCookie "1"
> [--cookieHost "pan.baidu.com"] 此参数的意思是使用跨域cookie, 例子就是使用pan.baidu.com的cookie请求. 还可以是
> 
> --cookieHost "http://pan.baidu.com"
> --cookieHost "https://pan.baidu.com"
> 当请求某个域名,并不想使用本地cookie,例子如下:
> 
> "https://d.pcs.baidu.com/file/52f9b60bff29cb2fc300c228629f8d83?fid=1187826186-250528-196948380033096&dstime=1562498630&rt=sh&sign=FDtAERyK-DCb740ccc5511e5e8fedcff06b081203-AaxLelIrc436z9mCGjGx%2Baewgng%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8967488906706405743&dp-callid=0&r=230531620&clienttype=25&vuk=1187826186&sh=1" --out "[SUBPIG][艺人史上最糟糕的一天].mp41" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --forbidCookie "1"
> 当请求某个域名,想使用其他域名cookie,例子如下:
> 
> "https://d.pcs.baidu.com/file/52f9b60bff29cb2fc300c228629f8d83?fid=1187826186-250528-196948380033096&dstime=1562498630&rt=sh&sign=FDtAERyK-DCb740ccc5511e5e8fedcff06b081203-AaxLelIrc436z9mCGjGx%2Baewgng%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8967488906706405743&dp-callid=0&r=230531620&clienttype=25&vuk=1187826186&sh=1" --out "[SUBPIG][艺人史上最糟糕的一天].mp41" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --cookieHost "pan.baidu.com"
> 注意
> [--forbidCookie "1"] [--cookieHost "pan.baidu.com"] 这个两个参数是1.0.0.4版本才具备的,若想使用,需要升级到1.0.0.4版本.
> 
> 免登录链接里面可以新增xdown下载,里面添加一个--forbidCookie "1" ,禁用cookie,不然会默认连带cookie一起请求,导致被限速.
> 
> [--cookieHost "pan.baidu.com"] 可以使用跨域cookie请求,可以省略掉cookie助手.

没太明白 , 具体应该如何操作 , 比如我用的是360浏览器

**Comment by xdown-org** [comment]
比如现在是分享页面获取到的的链接,不限制次数的,目前得到的参数是:
`aria2c "https://d.pcs.baidu.com/file/4b1ad498856a6f593759d637adad485e?fid=1269006717-250528-606360473598595&amp;dstime=1567415659&amp;expires=1567464980&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-Zd0MzMsn2wn9rY%2FNSePCBKQRj9E%3D&amp;r=265833564&amp;sharesign=rh3a0LM+9lyRnFaAsytHCq+bVAYPYA0p4W7kUrpQM/joDjLmH61DOu9EW2wMEKGflX6vmt5wkBumV/DftXmC0cOvTlp7qaLvq+Wwbh1woG6UJmZVJGC3cwKKCVWcs6BJsbacNkyQgtfZXhL4U1YY0aHtWC7HjSlECKykwz9JjyXeJPMjB7ULte9wdAWXz6UsYG6Yd73HR2vWBmNS+lGTECrKEci4JdaSJWApxAUgBCgd9hftwh0T/IpvKDczBdE04qjNjTo7AMeUykGAaFpHuhDFkbyQUH53iIyhgB2Laotlg87ATYTOKQ54+S3ZNn5kSpIywR3G0xF03M+Dq7OIdA==&amp;sh=1" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" `



那么就在尾部添加禁用cookie指令,禁止自动提交cookie,因为百度云会自动验证cookie.

那么就是

`aria2c "https://d.pcs.baidu.com/file/4b1ad498856a6f593759d637adad485e?fid=1269006717-250528-606360473598595&amp;dstime=1567415659&amp;expires=1567464980&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-Zd0MzMsn2wn9rY%2FNSePCBKQRj9E%3D&amp;r=265833564&amp;sharesign=rh3a0LM+9lyRnFaAsytHCq+bVAYPYA0p4W7kUrpQM/joDjLmH61DOu9EW2wMEKGflX6vmt5wkBumV/DftXmC0cOvTlp7qaLvq+Wwbh1woG6UJmZVJGC3cwKKCVWcs6BJsbacNkyQgtfZXhL4U1YY0aHtWC7HjSlECKykwz9JjyXeJPMjB7ULte9wdAWXz6UsYG6Yd73HR2vWBmNS+lGTECrKEci4JdaSJWApxAUgBCgd9hftwh0T/IpvKDczBdE04qjNjTo7AMeUykGAaFpHuhDFkbyQUH53iIyhgB2Laotlg87ATYTOKQ54+S3ZNn5kSpIywR3G0xF03M+Dq7OIdA==&amp;sh=1" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --forbidCookie "1"  `

**Comment by xdown-org** [comment]
另一个参数的用法是跨域使用cookie,得到的url如下:

`http://pcs.baidu.com/rest/2.0/pcs/file?method=download&path=%2Ftemp%2F%E5%96%84%E8%89%AF%E7%9A%84S%E5%AD%902.Good.Model.2.2017.HD1080P.X264.AAC.Korean.CHS.zip&random=0.025667608288630017&app_id=498065`

加上参数之后就是

`http://pcs.baidu.com/rest/2.0/pcs/file?method=download&path=%2Ftemp%2F%E5%96%84%E8%89%AF%E7%9A%84S%E5%AD%902.Good.Model.2.2017.HD1080P.X264.AAC.Korean.CHS.zip&random=0.025667608288630017&app_id=498065 --cookieHost "pan.baidu.com"`

**Comment by xdown-org** [comment]
目前来说,只支持chrome,并不支持360,
如果是chrome的浏览器,会方便很多.
如果是360浏览器,可以继续保持你现在的做法.
crx那边还在审核,审核之后,完全可以点击一下就可以自动下载.

**Comment by JYeung111** [comment]
終於明白 --cookieHost "pan.baidu.com" 這個參數是何意思，
這指令是叫 xdown 程式開啟載有瀏覽器 sqlite database，搜尋以pan.baidu.com為domain 的cookies，免用家自己輸入！ 高招！
有點疑問:
1. 既然chrome可以，火狐應能做到，因火狐一樣是將 cookie 儲存在某個sqlite database 中？
2. 在穩私頁是否能用？

**Comment by xdown-org** [comment]
就百度云来说,目前最有意义的是在无痕模式打开
百度网盘链接：https://pan.baidu.com/s/1bGhyyDj08pgukQTnAmetlw 提取码：q5d9
然后
![image](https://user-images.githubusercontent.com/54701467/64115232-aad55280-cdc1-11e9-9b34-5738bd7bcfd1.png)
![image](https://user-images.githubusercontent.com/54701467/64115257-b45eba80-cdc1-11e9-8af2-9814d44b3bd1.png)
添加一行xdwon专属下载,
因为`--forbidCookie "1" ` 参数 aria2c不兼容.

禁用cookie,防止自动加载cookie,导致限速,异常.
我有看到不少用户反馈,根本原因就是xdwon自动加载了cookie导致了限速.

**Comment by xdown-org** [comment]
@JYeung111 
暂时只兼容了chrome,后续更进.

**Comment by Hervey-Hu** [comment]
> 很奇怪的是，我正常進頁面，脚本不啓動，但是進入主控台后，刷新一下就能正常啓動了。
> 
> 
> 
> 你需要把其他的百度网盘脚本禁用掉 , 否则会冲突

我沒有裝其他的網盤脚本，2.53的時候還是好的，進入2.60以上后就出問題了

**Comment by syhyz1990** [comment]
@xdown-org 我测试了下相同32线程相同链接加了 --forbidCookie "1" , 免登录链接用IDM可以达到2.4MB/s , xdown 只能达到1.1MB/s

`
aria2c "https://d.pcs.baidu.com/file/4b1ad498856a6f593759d637adad485e?fid=1269006717-250528-606360473598595&amp;dstime=1567478686&amp;expires=1567528007&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-6V3wBFNA6BXdQ%2B3Sti%2B9GWLJpDc%3D&amp;r=603811359&amp;sharesign=rh3a0LM+9lyRnFaAsytHCqOmKHLbZ+fSAiafGz5/getuOC+dysBbVu9EW2wMEKGflX6vmt5wkBumV/DftXmC0cOvTlp7qaLvq+Wwbh1woG6cGxv7emRRnOkd1o7oQWujCEGFdQD3MJYhZnuy4lhOsF9mEDbJzrVPScFbPQcXM3qxpSRVw3QxKYS8FDLcbaVCthcR+E4ggDPSn8YnIkQnGoq282x24M4ifcDdG3Pb85vCrjw/y/Zq5dNMDmdUFz/EhbtRzapTL6jfSqjV9t4IGdwFPWVGFBrCw0ZH0+REUuWpbVQnl7IX4MIUdTOSQLHtEsJ5z4+mexk=&amp;sh=1" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --forbidCookie "1"
`

**Comment by f4nff** [comment]
@xdown-org 我测试了下相同32线程相同链接加了 --forbidCookie "1" , 免登录链接用IDM可以达到2.4MB/s , xdown 只能达到1.1MB/s

idm之所以快,是因为idm应该自动载入了你账号的cookie,但是下载多了,就会被限速,
xdown加入` --forbidCookie "1" `的意义在于,下载多少都不会被限速,低峰的时候会满速,

**Comment by xdown-org** [comment]
@syhyz1990 
@xdown-org 我测试了下相同32线程相同链接加了 --forbidCookie "1" , 免登录链接用IDM可以达到2.4MB/s , xdown 只能达到1.1MB/s

idm之所以快,是因为idm应该自动载入了你账号的cookie,但是下载多了,就会被限速,
xdown加入--forbidCookie "1"的意义在于,下载多少都不会被限速,低峰的时候会满速,

**Comment by syhyz1990** [comment]
我是用隐私模式获取的链接 , 应该没有cookie

**Comment by xdown-org** [comment]
```
[2019/9/3 11:21:29:385]
GET /file/a504636d7ed5c70de2ac1231e5243330?fid=117653358-250528-351464971274095&amp;dstime=1567440476&amp;expires=1567700308&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-VnwLujsRlOvbYTaLxBMwZn8XdjI%3D&amp;r=531795212&amp;sharesign=NgArTwvfGMtTGmLFuqK6GdeY5vb6PvC1uaRAObYw/B83PZfkOs412BzxxswmQru+NcAdB9PoP7r8krpCvs71gSP8njdB7dpgd2i7Hd1SBvaEmfqmZOMSF35CzkdlsxTjjX+fUj594nuccGo6V7LaWiEAx/UMkEHuSHl992Xf71fyd3ONz8c4zNyN8ewV6/2Fsrg/wwjCx6SjtPysKDs5OjlDZ5A8/Sps3OxePTpQynQlJZ61mymMeKJJdViqcqHlIcgI3fDcOZL1kcOc/YZ85UelT3KyP+4B5VELcXrYD+EcnCx7Z5J4IMiegRAYog1I&amp;sh=1 HTTP/1.1
Accept: */*,application/metalink4+xml,application/metalink+xml
Host: d.pcs.baidu.com
Cookie: BAIDUID=AD23A9661BCC7D8769C2B290FCDD7E1D:FG=1;
Want-Digest: SHA-512;q=1, SHA-256;q=1, SHA;q=0.1
User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia


[2019/9/3 11:21:29:638]
HTTP/1.1 302 Found
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Tue, 03 Sep 2019 03:21:29 GMT
Flow-Level: 3
Http-X-Isis-Logid: 5693217790092311231
Location: https://nj02cm01.baidupcs.com/file/a504636d7ed5c70de2ac1231e5243330?bkt=en-06f5c65000af0ed6a8e82f2d34ca0f39c80bb7866cdc8e198019eb487622998ad0e20a8de8ec78e4&fid=117653358-250528-351464971274095&time=1567480889&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-HekynradKavzOzQBAiGTYww%2B1JE%3D&to=88&size=13303412430&sta_dx=13303412430&sta_cs=151&sta_ft=mkv&sta_ct=5&sta_mt=5&fm2=MH%2CQingdao%2CAnywhere%2C%2Chenan%2Ccmnet&ctime=1557480025&mtime=1557586362&resv0=cdnback&resv1=0&resv2=&resv3=&vuk=282335&iv=0&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-6a23dad09fe30b3cb480018ca7cffbea5f87b4db8d98cf874246cf932aedceae299bd1b758ada9d3&sl=75432014&expires=1567700308&rt=sh&r=531795212&sh=1&vbdid=50348727&fin=%E5%9F%83%E5%8F%8A%E7%8E%8B%E5%AD%90.%E7%89%B9%E6%95%88%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95.The.Prince.of.Egypt.1998.BD1080P.X264.DTS-HD.MA.5.1.Mandarin%26Taiwanese%26Cantonese%26English.CHS-ENG.Mp4BaFans.mkv&rtype=1&dp-logid=5693217790092311231&dp-callid=0.1&hps=1&tsl=160&csl=80&csign=ZMLyV6T0L9zkkwFfMOo%2F4sxc4LA%3D&so=0&ut=6&uter=-1&serv=1&uc=2966007443&ti=26fa64dbec28822441c31fd071a40d5f956b32b0c8e51b4b305a5e1275657320&by=themis
Remote-Ip: d.pcs.baidu.com
Server: nginx
X-Bs-Pcs-Extra: method=file&file_type=mkv&iv=0&user_operator=cmnet&digest=a504636d7ed5c70de2ac1231e5243330&visitor_ip=113.89.136.71&user_terminal=macygj&v_user_id=0&file_size=13303412430&app_id=250528&user_type=default&fs_id=351464971274095&user_id=129042289&freeispflag=-100&xflag=
X-Bs-Remote-Ip: 10.155.106.38
X-Bs-Request-Id: eXEwMS1vYmplY3QwNi1yMTAtMDEtMDAyLnlxMDEuYmFpZHUuY29tOjEwLjE1NS4xMDYuMzg6MjAxMDo1NjkzMjE3NzkwMDkyMzExMjMxOjIwMTktMDktMDMgMTE6MjE6Mjk=
X-Pcs-Member: 0
X-Poms-Key: 0000c7bbb94ea2cfc8da28b9752c5d5329b5
Yld: 9151982408299088619
Transfer-Encoding: chunked
```


禁用cookie之后进行抓包可以看到,
在X-Bs-Pcs-Extra 字段的user_type=default 会一直为这个.
下载多少都不会被限速.目前限速只会根据user

**Comment by 1608637229** [comment]
> 希望新版中继续支持PanDownload的web及各种第三方下载方式，2.7.1版本好像没有之前的旧版本来得方便

pandownload网页版是不是挂了。我今天获取链接失败

**Comment by 1608637229** [comment]
不知道这个脚本能活多久。最近好像百度又开始发力了，svip都有人被限速了，看起来连svip都有一段时间的下载上限阙值, 且用且珍惜。目前我用这个免登录下载（我是退出了百度账号）idm设置32线程后大概有2M 到3M的速度，默认八线程只有800kB.

**Comment by Porcelana** [comment]
> 大家有什么好的建议和意见都可以留言
希望将v2.5.3版本中的「高速下载(beta)」加回，期待加入pan download＋Aria2GUI的方式

**Comment by xdown-org** [comment]
@Porcelana 
xdown 已经在windows 完全取代了 Aria2GUI

**Comment by JYeung111** [comment]
@xdown-org 
會否有支援 wionxp 版？

**Comment by xdown-org** [comment]
@JYeung111 
不可以,你都用命令行了,何必用ariagui,直接用aria2就可以了,
xdown只有界面操作,没有rpc

xdown 1.0.0.4 已经支持xp,但是跟aria2一样,不支持tls1.2加密,这是windows xp 系统决定的,没有细研究

**Comment by Ragger97** [comment]
之前打在new issue中的问题并没得到解决就被删了。
这边没有截图功能我只能打字描述，希望能被看懂。
我用梅林的aria2下载，所以只能用aria外链下载，
1.大概900MB的视频无法下载？如果就是无法下载可以告知一下我最大下载容量。
2.下载多个文件时点击复制所有链接却只有一条带链接而非多个链接且下载出的内容也只有一项。但我试着复制aria2c的全部链接是该功能可以正常使用。
3.点击“复制全部链接”每条内容都有aria以及双引号的前后缀，进入梅林aria2软件都需要手动加工一下才能识别，很不方便，希望针对“aria外链”可以去掉前后缀。

**Comment by dssle** [comment]
为什么用idm免登陆链接下载只有几百k，开代理最高也就两百k,不开代理32连接数也就三百k，最多有几秒钟的六七百k。我的是校园网。

**Comment by dssle** [comment]
如何解决分享下载的使用直接下载方式idm没有反应，弹不出下载的框？

**Comment by syhyz1990** [comment]
> 之前打在new issue中的问题并没得到解决就被删了。
> 这边没有截图功能我只能打字描述，希望能被看懂。
> 我用梅林的aria2下载，所以只能用aria外链下载，
> 1.大概900MB的视频无法下载？如果就是无法下载可以告知一下我最大下载容量。
> 2.下载多个文件时点击复制所有链接却只有一条带链接而非多个链接且下载出的内容也只有一项。但我试着复制aria2c的全部链接是该功能可以正常使用。
> 3.点击“复制全部链接”每条内容都有aria以及双引号的前后缀，进入梅林aria2软件都需要手动加工一下才能识别，很不方便，希望针对“aria外链”可以去掉前后缀。

既然要去掉 , 干嘛不使用直链

**Comment by 1608637229** [comment]
> > 之前打在new issue中的问题并没得到解决就被删了。
> > 这边没有截图功能我只能打字描述，希望能被看懂。
> > 我用梅林的aria2下载，所以只能用aria外链下载，
> > 1.大概900MB的视频无法下载？如果就是无法下载可以告知一下我最大下载容量。
> > 2.下载多个文件时点击复制所有链接却只有一条带链接而非多个链接且下载出的内容也只有一项。但我试着复制aria2c的全部链接是该功能可以正常使用。
> > 3.点击“复制全部链接”每条内容都有aria以及双引号的前后缀，进入梅林aria2软件都需要手动加工一下才能识别，很不方便，希望针对“aria外链”可以去掉前后缀。
> 
> 既然要去掉 , 干嘛不使用直链

我发现了获取到不登录的地址有好几个。我今天试了有一个速度不行(500kB左右)。后面我重新获取下载地址后速度又满速了（2.5MB)我的网速最大值

**Comment by xdown-org** [comment]
@JYeung111 

xdown 1.0.0.5 已经完美支持winxp,
其他需求正在更进.

**Comment by JYeung111** [comment]
@xdown-org
非常感谢 !
現時甚少程式願意支援 winXP
