### ISSUE TITLE
我的xdown解压后，运行XDown.exe，提示无法正常启动。启动时已经运行了360安全卫士，这和360安全卫士有没有关系？

### ISSUE THREAD

**Issue by theSouthSea** [syhyz1990/baiduyun#229]
![无法正常启动](https://user-images.githubusercontent.com/17595231/63633161-13ac2480-c676-11e9-9bb8-e25e07373353.png)

**Comment by syhyz1990** [comment]
可能缺少环境吧，你去xdown官网上下
