### ISSUE TITLE
大佬，XDOWN卸载后重新安装，下载任务提示异常

### ISSUE THREAD

**Issue by Toumakazasa** [syhyz1990/baiduyun#231]
![image](https://user-images.githubusercontent.com/34472587/63646571-9f41b600-c747-11e9-8f78-53d2cc7d7a30.png)
现在用idm能正常下载。。。。。

**Comment by syhyz1990** [comment]
使用 https://baiduwp.ctfile.com/dir/3994041-35240665-e1ea37/ 这个特定版本
