### ISSUE TITLE
为什么在chrome上用下载助手显示的链接，按“复制全部链接”不能复制呢？

### ISSUE THREAD

**Issue by finnchy** [syhyz1990/baiduyun#232]
-![image](https://user-images.githubusercontent.com/54519075/63661131-f4cf9e80-c7eb-11e9-9f8a-a34e5185ad34.png)

**Comment by syhyz1990** [comment]
双击链接也可以复制

**Comment by finnchy** [comment]
> 双击链接也可以复制

不行的，我试了。好像是chrome不能自动粘贴到剪贴板上的。

**Comment by syhyz1990** [comment]
我试了 , 是可以的

**Comment by finnchy** [comment]
> 我试了 , 是可以的

那么是我的浏览器有问题吧。

**Comment by duliyoumin** [comment]
我也是同样的问题，用的百分浏览器，

**Comment by JYeung111** [comment]
首先要弄清楚在同一頁面中是否有其他腳本也在運作中，如有就大有可是它們其中一個引致！尤是會使用 click handler！

**Comment by finnchy** [comment]
> -![image](https://user-images.githubusercontent.com/54519075/63661131-f4cf9e80-c7eb-11e9-9f8a-a34e5185ad34.png)

已解决，是其它脚本的冲突。

**Comment by cpklas** [comment]
> > -![image](https://user-images.githubusercontent.com/54519075/63661131-f4cf9e80-c7eb-11e9-9f8a-a34e5185ad34.png)
> 
> 已解决，是其它脚本的冲突。

我也遇到了这个问题，请问是什么脚本冲突

**Comment by finnchy** [comment]
> > > -![image](https://user-images.githubusercontent.com/54519075/63661131-f4cf9e80-c7eb-11e9-9f8a-a34e5185ad34.png)
> > 
> > 
> > 已解决，是其它脚本的冲突。
> 
> 我也遇到了这个问题，请问是什么脚本冲突

我用的排除法，保留本百度助手脚本，把其它的关了，然后测试正常。所以把有冲突的删了就好了。
