### ISSUE TITLE
Windows 已从“qdall01.baidupcs.com”接收到一条 HTTP 错误消息: 403 (禁止)

### ISSUE THREAD

**Issue by xunhuanxuan** [syhyz1990/baiduyun#233]
这个问题怎么解决啊，大佬

**Comment by JYeung111** [comment]
只要見到 qdall01.baidupcs.com，就代該用家號己超標下載，已被限速，如繼續下載就會出現SSL error ( https://qdall01.baidupcs.com) 但改用http://qdall01.baidupcs.com 仍可使用但速度更差，如再繼續下載就會被禁下載，只能完全停用該号，等一兩日應會解禁和恢復速度！

**Comment by syhyz1990** [comment]
可以使用免登录链接
