### ISSUE TITLE
mac右键Aria链接使用neatdownloadmanager下载报错

### ISSUE THREAD

**Issue by nanjunyu** [syhyz1990/baiduyun#235]
![image](https://user-images.githubusercontent.com/23097168/63776003-1bd4c000-c913-11e9-9407-f57edd5c7a87.png)
![image](https://user-images.githubusercontent.com/23097168/63776078-3dce4280-c913-11e9-937c-92ae2d96cab7.png)

**Comment by JYeung111** [comment]
一看這 "javascript:void(0)"，就已知道問題的答案！
不是所有選項支援右键，Aria鏈就是其中之一

**Comment by syhyz1990** [comment]
双击链接会复制 ,aria链接不支持右键的复制链接
