### ISSUE TITLE
macos，api直接下载无反应

### ISSUE THREAD

**Issue by Corpama** [syhyz1990/baiduyun#236]
如题所示，使用neatdownload manager，点击无反应

**Comment by goldWave** [comment]
+1, 搞了半天还是没有反应，mac os 10.14.6， chrome：Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by goldWave** [comment]
在其他网站下载均可以唤起neatdownload manager。， 只有在baidu网盘的域名下不能后唤起neatdownload。

**Comment by syhyz1990** [comment]
要安装浏览器插件

**Comment by Corpama** [comment]
> 要安装浏览器插件

已安装相应的chrome插件:NeatDownloadManager Extension，并且之前使用均正常，今天使用发现出现问题

**Comment by Corpama** [comment]
在重裝插件后已可以使用
