### ISSUE TITLE
阿里云盘提示「提示：请先勾选要下载的文件」

### ISSUE THREAD

**Issue by rppig42** [syhyz1990/baiduyun#237]
如标题所示，打了断点看了一下
https://github.com/syhyz1990/baiduyun/blob/fc1560f23afd9e803cf2b914656302a7929a3dc3/panlinker.user.js#L1367
该行执行下来为 
```javascript
document.getElementsByClassName('[class^="node-list-table-view--"] )
``` 
这应该不是一个正确的选择器写法，不清楚原来API的返回是什么。

手动修改代码后运行正常
```
let reactDom = document.querySelector(pan.dom.list);
```

**Comment by NegationSite** [comment]
百度网盘也有类似的弹窗   “提示：获取下载链接失败！请刷新网页后重试！”

**Comment by davidtwchn** [comment]
> 如标题所示，打了断点看了一下
> 
> https://github.com/syhyz1990/baiduyun/blob/fc1560f23afd9e803cf2b914656302a7929a3dc3/panlinker.user.js#L1367
> 
> 
> 该行执行下来为
> ```js
> document.getElementsByClassName('[class^="node-list-table-view--"] )
> ```
> 
> 这应该不是一个正确的选择器写法，不清楚原来API的返回是什么。
> 
> 手动修改代码后运行正常
> 
> ```
> let reactDom = document.querySelector(pan.dom.list);
> ```

已按照楼主提供的方法修改，正常运行了。

**Comment by syhyz1990** [comment]
更新到最新版即可
