### ISSUE TITLE
速度只有400-600k（50m宽带+百度10元+idm）

### ISSUE THREAD

**Issue by ADrifter** [syhyz1990/baiduyun#238]
之前我在greasyfork上下载的时候 是完全可以用的
然后我前天登百度网盘的时候用了一下只有50k的速度
然后就在地址二重新下载了一个v2.6.4（应该是最新版本）
可是网速只有400-600k 而且同一时间只可以下载一个
具体表现就是idm弹出一个窗口
![capture_20190829213221979](https://user-images.githubusercontent.com/54673380/63944703-a567c780-caa4-11e9-849c-61f4eb113c32.jpg)

请问有什么解决办法吗

**Comment by syhyz1990** [comment]
用xdown64线程试下

**Comment by dky815** [comment]
> 用xdown64线程试下

您好，我和这位老哥是一样的问题，用xdown的话添加完任务状态那一栏显示为异常。

**Comment by ADrifter** [comment]
今天开了超级会员 然后就可以用了
不知道是更新了的原因还是超级会员的缘故
我感觉超级会员还是不如idm快
只是这样成本就有点高了

**Comment by JYeung111** [comment]
开超级会员是直向百度買還是經第三者買，是有天與地的差別，因為後者多是和別人共享，

**Comment by ADrifter** [comment]
是直接向百度买的 我觉得度盘的下载速度还是不够稳定
单独下一个文件有时候慢一点只有1-2m 快的时候有5-6m
而idm是很稳定的近10m的速度

只是我不知道是不是开普通会员就能用
还是要开超级会员才能用

**Comment by syhyz1990** [comment]
可以调大线程数
