### ISSUE TITLE
阿里云盘分享页面只能选择idm下载，其他选项选不到。

### ISSUE THREAD

**Issue by mofengcangyue** [syhyz1990/baiduyun#238]
[阿里云盘分享页面只能选择idm下载，其他选项选不到，如动图所示，选择下面会闪退。
![截图_20230601153235](https://github.com/syhyz1990/baiduyun/assets/49826218/d0035cfd-2c6a-4c8b-8f3e-fefeafd650ee)

**Comment by overwatchsss** [comment]
这种情况暂时解决方案是将页面比例缩小到80%就可以选了
