### ISSUE TITLE
【出现异常】提示需要安装百度网盘万能助手

### ISSUE THREAD

**Issue by colemanlee** [syhyz1990/baiduyun#239]
使用时【出现异常】提示需要安装百度网盘万能助手，实际上我已经安装了“百度网盘直链下载助手”了。
![PIC__21](https://user-images.githubusercontent.com/10258421/64057436-5e2a2580-cbcf-11e9-8233-06028e2feb72.jpg)
![PIC__20](https://user-images.githubusercontent.com/10258421/64057437-5ec2bc00-cbcf-11e9-99d6-70e7b3b69fb2.jpg)

**Comment by JYeung111** [comment]
腳本提示要加裝的是 Browser 的外掛程式，而不是另一個腳本！

**Comment by syhyz1990** [comment]
楼上正解  ,  去https://www.baiduyun.wiki上看吧

**Comment by tanhenshi** [comment]
遇到一楼这种问题，在二楼的网站也找不到怎么解决

**Comment by JYeung111** [comment]
@ tanhenshi
 去 https://www.baiduyun.wiki/zh-cn/cookie-plugin  上看吧

**Comment by tanhenshi** [comment]
按照网站说法，重启好几次浏览器，依旧手需要按照百度网盘助手

**Comment by JYeung111** [comment]
@ tanhenshi
你要向作者求教，因為我用吾到百度网盘助手，和 吾用aria2c，太煩。

**Comment by colemanlee** [comment]
> 楼上正解 , 去 https://www.baiduyun.wiki 上看吧

**Comment by colemanlee** [comment]
> 楼上正解 , 去 https://www.baiduyun.wiki 上看吧

**Comment by colemanlee** [comment]
> 楼上正解 , 去 https://www.baiduyun.wiki 上看吧
您这里显示需要安装的**百度Cookies获取助手**，请问在哪下载？我现在没有安装这个助手，无法使用`aric2a下载`这个功能，会出现主贴的问题，已经看过您说的 [](https://www.baiduyun.wiki )网站了。
![noYDEuN72iXd9Bc](https://user-images.githubusercontent.com/10258421/64112554-58dcfe80-cdba-11e9-85e9-b051bb38c4bd.png)

**Comment by syhyz1990** [comment]
@colemanlee https://www.baiduyun.wiki/zh-cn/cookie-plugin.html 这个

**Comment by colemanlee** [comment]
> @colemanlee https://www.baiduyun.wiki/zh-cn/cookie-plugin.html 这个

你好，
问题在你帮助下解决了，抱歉未仔细查看网页内容，网页其他链接确实写了。
反馈一个问题：谷歌应用商店李没有【百度网盘万能助手】这个插件了。
![PIC__27](https://user-images.githubusercontent.com/10258421/64169852-3eba2380-ce81-11e9-8a31-a25871d896eb.jpg)

**Comment by lolpeter** [comment]
已经安装了百度网盘万能助手，却一直提示要安装。浏览器重启过了，什么问题？
![截屏2020-03-03上午10 42 14](https://user-images.githubusercontent.com/12607370/75737872-c5ba5c80-5d3b-11ea-96ea-bfac9d359b7e.png)
![截屏2020-03-03上午10 39 42](https://user-images.githubusercontent.com/12607370/75737966-f9958200-5d3b-11ea-85ec-c5c7ff74aada.png)
