### ISSUE TITLE
新离线下载文件无法被脚本识别

### ISSUE THREAD

**Issue by spencerz393** [syhyz1990/baiduyun#240]
离线下载的最新一个文件无法被脚本识别，选择任意下载选项都会跳出提示[未选中文件，请勿勾选文件夹，否则刷新后重试！]
再次离线下载一个文件后先前文件可以被正常识别正常下载
刷新网页后仍旧不会被识别

**Comment by syhyz1990** [comment]
脚本并不会监听离线下载新增加的文件 , 可以刷新重试
