### ISSUE TITLE
使用梅林下载有困难

### ISSUE THREAD

**Issue by Ragger97** [syhyz1990/baiduyun#245]
我想使用梅林ARIA插件下载云盘中内容至U盘中，外链确实可以使用，速度大概100K也能接受。
但是如果想同时下载多个文件，点击复制所有外链却只有一条链接，而且下载下来只有一个文件，导致如果我想下载很多内容只能一个一个点，很麻烦。
以及比较大的文件无法下载，这点我不知道是否是梅林插件的问题，但也有可能是这个插件的问题，我在那边也会有所反应。
还有一点就是所有连接都会有……aria2" "……我需要一个一个编辑来取出这些才能让梅林插件运转，实在是太费精力了，希望可以在下一次版本更新中有所调整，谢谢！

**Comment by JYeung111** [comment]
@ Ragger97 

只要將此腳本作兩個改動就可以啟用打包多文件和文件夾下載，300M總容量仍然有效。

**Comment by syhyz1990** [comment]
@Ragger97 新版本已经修复了复制的问题   https://openuserjs.org/scripts/syhyz1990/%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B
