### ISSUE TITLE
无法使用批量下载

### ISSUE THREAD

**Issue by Hanzy1996** [syhyz1990/baiduyun#246]
![image](https://user-images.githubusercontent.com/34676963/64123940-440f6380-cdd8-11e9-91c9-3bdf65aec161.png)
mac系统，使用批量下载时点击复制，复制到NeatDowloaderManager下载时会报上面的错
![image](https://user-images.githubusercontent.com/34676963/64123974-62755f00-cdd8-11e9-9a97-a366c092bba2.png)

**Comment by xdown-org** [comment]
批量下载只支持xdown,xdown目前只有windows版本.

**Comment by Hanzy1996** [comment]
![image](https://user-images.githubusercontent.com/34676963/64142043-f9740280-ce3c-11e9-8741-0ef5aabb9019.png)
谢谢大佬，请问有时候选api下载的直接下载没有反应是咋回事？

**Comment by syhyz1990** [comment]
@Hanzy1996 没反应有时候可能被其他插件拦截了, 用显示链接是一样的效果
