### ISSUE TITLE
Mac Chrome上无法调用NeatDownloadManager

### ISSUE THREAD

**Issue by wsw201009** [syhyz1990/baiduyun#247]
系统是Mac Chrome，已安装百度网盘直链下载助手版本2.7.2，NeatDownloadManager，也同时安装对应的Chrome插件。

打开打开需要下载的文件的百度分享页面，点击下载助手内的免登录链接，然后右键所显示的“普通链接”，再选择使用NeatDownloadManager下载，系统返回错误信息：“Error : HTTP/1.1 403 Forbidden”，附上截图供参考。
![Screenshot 2019-09-03 at 4 29 13 AM](https://user-images.githubusercontent.com/38053600/64132617-a3369d80-ce03-11e9-835e-d46c1166860c.png)

**Comment by syhyz1990** [comment]
直接点击普通链接调用 NeatDownloadManager 下载

**Comment by wsw201009** [comment]
非常感谢，问题已解决了一半。再测试后发现情况是这样的，如果所打开的百度网页内只有单一文件，直接点击普通链接调用NeatDownloadManager满速下载；但如果所打开的百度网页内有一个目录，点击目录内有多个文件，点选其中一个文件然后点击普通链接下载系统回复403错误。
