### ISSUE TITLE
xdown 专用讨论贴

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#248]
@syhyz1990 

xdown 更新了1.0.0.4版本,
新增了两个参数功能.
https://xdown.org/header/index.htm

自定义有三个选项,分别为[--header] [--forbidCookie "1"] [--cookieHost "pan.baidu.com"]

`--forbidCookie "1"` 为禁用cookie,程序下载会默认载入cookie进行填充,此参数为某种需求,不想提交cookie使用.

`--forbidCookie "1" `
`--cookieHost "pan.baidu.com"`
 此参数的意思是使用跨域cookie, 例子就是使用pan.baidu.com的cookie请求. 还可以是

`--cookieHost "http://pan.baidu.com"`
`--cookieHost "https://pan.baidu.com"`
当请求某个域名,并不想使用本地cookie,例子如下:

`"https://d.pcs.baidu.com/file/52f9b60bff29cb2fc300c228629f8d83?fid=1187826186-250528-196948380033096&dstime=1562498630&rt=sh&sign=FDtAERyK-DCb740ccc5511e5e8fedcff06b081203-AaxLelIrc436z9mCGjGx%2Baewgng%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8967488906706405743&dp-callid=0&r=230531620&clienttype=25&vuk=1187826186&sh=1" --out "[SUBPIG][艺人史上最糟糕的一天].mp41" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --forbidCookie "1" `
当请求某个域名,想使用其他域名cookie,例子如下:

`"https://d.pcs.baidu.com/file/52f9b60bff29cb2fc300c228629f8d83?fid=1187826186-250528-196948380033096&dstime=1562498630&rt=sh&sign=FDtAERyK-DCb740ccc5511e5e8fedcff06b081203-AaxLelIrc436z9mCGjGx%2Baewgng%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8967488906706405743&dp-callid=0&r=230531620&clienttype=25&vuk=1187826186&sh=1" --out "[SUBPIG][艺人史上最糟糕的一天].mp41" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --cookieHost "pan.baidu.com"`

注意
`--forbidCookie "1"`
`--cookieHost "pan.baidu.com"`
这个两个参数是1.0.0.4版本才具备的,若想使用,需要升级到1.0.0.4版本.

免登录链接里面可以新增xdown下载,里面添加一个`--forbidCookie "1" ` ,禁用cookie,不然会默认连带cookie一起请求,导致被限速.

`--cookieHost "pan.baidu.com"  `可以使用跨域cookie请求,可以省略掉cookie助手.

_Originally posted by @xdown-org in https://github.com/syhyz1990/baiduyun/issues/224#issuecomment-526915232_

**Comment by syhyz1990** [comment]
@xdown-org 加了forbidCookie 反而速度慢了 , 我已经把所有浏览器 cookie 全部清空了

**Comment by xdown-org** [comment]
@syhyz1990 
`--forbidCookie "1" `
新增一个链接xdown链接,加上这个,单任务基本速度都能在1m/s,多任务可以叠加,这个速度基本是可以接受的,凌晨之后下载,可以跑满速.
这个参数最大的作用是屏蔽cookie,因为百度默认会验证cookie,如果cookie字段为空,基本每个连接可以得到100k/s的速度.
加了`--forbidCookie "1" ` 不会因为下载很多被限速,
其他百度限速的规则我暂时没研究,可能对ip也有一个限速规则.随后我在跟踪看下
很多用户下载多之后,速度就只有几K,这个你可以看其他用户反馈,就是这个原因.

**Comment by xdown-org** [comment]
![image](https://user-images.githubusercontent.com/54701467/64145775-cafe2380-ce4c-11e9-99c6-5ab94a9e4101.png)

`http://d.pcs.baidu.com/file/a504636d7ed5c70de2ac1231e5243330?fid=117653358-250528-351464971274095&amp;dstime=1567440476&amp;expires=1567700308&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-VnwLujsRlOvbYTaLxBMwZn8XdjI%3D&amp;r=531795212&amp;sharesign=NgArTwvfGMtTGmLFuqK6GdeY5vb6PvC1uaRAObYw/B83PZfkOs412BzxxswmQru+NcAdB9PoP7r8krpCvs71gSP8njdB7dpgd2i7Hd1SBvaEmfqmZOMSF35CzkdlsxTjjX+fUj594nuccGo6V7LaWiEAx/UMkEHuSHl992Xf71fyd3ONz8c4zNyN8ewV6/2Fsrg/wwjCx6SjtPysKDs5OjlDZ5A8/Sps3OxePTpQynQlJZ61mymMeKJJdViqcqHlIcgI3fDcOZL1kcOc/YZ85UelT3KyP+4B5VELcXrYD+EcnCx7Z5J4IMiegRAYog1I&amp;sh=1 --forbidCookie "1"  --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" `


64个并发,可以到10M/s 你试试

**Comment by syhyz1990** [comment]
你试下
`http://d.pcs.baidu.com/file/4b1ad498856a6f593759d637adad485e?fid=1269006717-250528-606360473598595&amp;dstime=1567490332&amp;expires=1567539653&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-lr11XiHALR%2FV8p10g7KyBYBxu4k%3D&amp;r=574997150&amp;sharesign=rh3a0LM+9lyRnFaAsytHCh1FFbV8MrX8P513Ewr3Qmk9KuYR26s6qu9EW2wMEKGflX6vmt5wkBumV/DftXmC0cOvTlp7qaLvq+Wwbh1woG6UJmZVJGC3cwKKCVWcs6BJsbacNkyQgtfZXhL4U1YY0aHtWC7HjSlECKykwz9JjyXeJPMjB7ULtdVUAeMu8uiwaB2s0wDfSP3Z4bevzMs68CrKEci4JdaSJWApxAUgBCgd9hftwh0T/IpvKDczBdE04qjNjTo7AMeUykGAaFpHuhDFkbyQUH53wbQ5f8SsCBfMVg/CQGR/H/lrQRpTKp5LofSjjK+rcMR03M+Dq7OIdA==&amp;sh=1 --forbidCookie "1" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia"`

和

`http://d.pcs.baidu.com/file/4b1ad498856a6f593759d637adad485e?fid=1269006717-250528-606360473598595&amp;dstime=1567490332&amp;expires=1567539653&amp;rt=sh&amp;chkv=1&amp;chkpc=et&amp;sign=FDtERVYA-DCb740ccc5511e5e8fedcff06b081203-lr11XiHALR%2FV8p10g7KyBYBxu4k%3D&amp;r=574997150&amp;sharesign=rh3a0LM+9lyRnFaAsytHCh1FFbV8MrX8P513Ewr3Qmk9KuYR26s6qu9EW2wMEKGflX6vmt5wkBumV/DftXmC0cOvTlp7qaLvq+Wwbh1woG6UJmZVJGC3cwKKCVWcs6BJsbacNkyQgtfZXhL4U1YY0aHtWC7HjSlECKykwz9JjyXeJPMjB7ULtdVUAeMu8uiwaB2s0wDfSP3Z4bevzMs68CrKEci4JdaSJWApxAUgBCgd9hftwh0T/IpvKDczBdE04qjNjTo7AMeUykGAaFpHuhDFkbyQUH53wbQ5f8SsCBfMVg/CQGR/H/lrQRpTKp5LofSjjK+rcMR03M+Dq7OIdA==&amp;sh=1 --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --forbidCookie "1"`

参数的位置影响下载的速度??

**Comment by xdown-org** [comment]
不会影响,都是同样的解析逻辑.
影响下载速度的关键是解析出来的 
`Location: https://nj02cm01.baidupcs.com/file/a504636d7ed5c70de2ac1231e5243330?bkt=en-06f5c65000af0ed6a8e82f2d34ca0f39c80bb7866cdc8e198019eb487622998ad0e20a8de8ec78e4&fid=117653358-250528-351464971274095&time=1567480889&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-HekynradKavzOzQBAiGTYww%2B1JE%3D&to=88&size=13303412430&sta_dx=13303412430&sta_cs=151&sta_ft=mkv&sta_ct=5&sta_mt=5&fm2=MH%2CQingdao%2CAnywhere%2C%2Chenan%2Ccmnet&ctime=1557480025&mtime=1557586362&resv0=cdnback&resv1=0&resv2=&resv3=&vuk=282335&iv=0&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-6a23dad09fe30b3cb480018ca7cffbea5f87b4db8d98cf874246cf932aedceae299bd1b758ada9d3&sl=75432014&expires=1567700308&rt=sh&r=531795212&sh=1&vbdid=50348727&fin=%E5%9F%83%E5%8F%8A%E7%8E%8B%E5%AD%90.%E7%89%B9%E6%95%88%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95.The.Prince.of.Egypt.1998.BD1080P.X264.DTS-HD.MA.5.1.Mandarin%26Taiwanese%26Cantonese%26English.CHS-ENG.Mp4BaFans.mkv&rtype=1&dp-logid=5693217790092311231&dp-callid=0.1&hps=1&tsl=160&csl=80&csign=ZMLyV6T0L9zkkwFfMOo%2F4sxc4LA%3D&so=0&ut=6&uter=-1&serv=1&uc=2966007443&ti=26fa64dbec28822441c31fd071a40d5f956b32b0c8e51b4b305a5e1275657320&by=themis`
对应的域名的IP

**Comment by syhyz1990** [comment]
同一个文件 , 参数位置放前面确实比后面的快一倍

**Comment by xdown-org** [comment]
我这边没测出区别,

**Comment by 9760711243** [comment]
今天更新之后，XDown只能同时下载两个文件，第三个就没速度，只能等下完一个再开始另一个，之前还是不限数量。还有另外一个问题，百度分享页面默认只能显示100个文件，超过100的需要下拉滚动条才能显示，后显示的这部分文件选择免登录下载就提示“提示：未选中文件，请勿勾选文件夹，否则刷新后重试！”

**Comment by syhyz1990** [comment]
@9760711243 重新安装下    https://github.com/syhyz1990/baiduyun/raw/master/baiduyun.user.js

**Comment by shawnyue** [comment]
win10下为什么会报病毒？

**Comment by xdown-org** [comment]
程序vmp加壳,报毒自己添加例外,

**Comment by dis-xcl** [comment]
xdown并发数是否开的越多越好？试了试开得多确实速度会快一点点。那连接数开的最多对硬盘是否有影响？

**Comment by xdown-org** [comment]
1:增加自动更新功能
2:完美支持windows xp(1.0.0.4不支持tls1.2 1.3)
3:纠正修好代{过}{滤}理ip不即时生效,
4:增加[--uri-defined-host-info] [--uri-defined-concurrent]  前者位固定ip,跳过解析,后者为自定义当前任务的并发数
5:修正http任务下载一半,点删除任务 勾选删除文件无效.
6:增加RR算法,默认开启(大幅度提升资源越下越慢的情况)
7:修正下载百度云中途小概率出现异常(下载链接依然有效的情况下)
8: 修复插件id保存失效
9: 修复删除任务,文件可能没有彻底删除
10: 修复右键打开文件,如果权限不够,无法打开

支持windows xp/7/8/10

https://dl.xdown.org/xdown-1.0.0.5(0911).zip

http://www.mediafire.com/file/46h60uzebbwonwl/xdown-1.0.0.5%25280911%2529.zip/file

@syhyz1990 
作者可以更新一下分流,特别更新了RR算法,
大幅度提升了下载速度的稳定性,
资源越下越慢的问题得到根治,随后会出一个详细的对比视频.

**Comment by xdown-org** [comment]
![image](https://user-images.githubusercontent.com/54701467/64690614-6cc3e700-d4c3-11e9-8c01-b44e2ee09bb4.png)
![image](https://user-images.githubusercontent.com/54701467/64690620-70576e00-d4c3-11e9-8d07-f90be8367369.png)
http://545c.com/dir/3994041-35240665-e1ea37?35333125

@syhyz1990

**Comment by syhyz1990** [comment]
已经更新了

**Comment by lahmuller** [comment]
xdown用了1.0.0.5 下载显示异常

**Comment by xdown-org** [comment]
@lahmuller 下载什么显示异常,
如果连续5次连接失败,或者其他错误代码,会抛出异常,
如果中途url失效,
你可以重新获取url,然后右键更新url,继续下载.

**Comment by lahmuller** [comment]
@xdown-org 下载什么都显示异常
![image](https://user-images.githubusercontent.com/35281095/64709418-cbe82280-d4e8-11e9-9133-14e0135ce5ff.png)

**Comment by xdown-org** [comment]
你这样应该是用的那种带cookie的解析地址,
带了cookie有请求次数限制,没几次,就对账号限速了,

给你2个解决办法,

1:使用免登陆下载那个解析.
2:在复制出来的url后面添加  `  --uri-defined-rr  0` 前面注意加空格
3:设置里面 取消RR算法

**Comment by xdown-org** [comment]
https://www.youtube.com/watch?v=crug9LfAfc0

这里有演示视频,无限制的.

**Comment by xdown-org** [comment]
https://www.youtube.com/watch?v=tK-xPAzaXu4

这是windows 7的演示视频

**Comment by xdown-org** [comment]
@syhyz1990 

[离线安装chrome的扩展crx.zip](https://github.com/syhyz1990/baiduyun/files/3603731/chrome.crx.zip)
上传一下这个,你网上的说明离线不能安装chrome插件,

**Comment by lahmuller** [comment]
> 你这样应该是用的那种带cookie的解析地址,
> 带了cookie有请求次数限制,没几次,就对账号限速了,
> 
> 给你2个解决办法,
> 
> 1:使用免登陆下载那个解析.
> 2:在复制出来的url后面添加 ` --uri-defined-rr 0` 前面注意加空格
> 3:设置里面 取消RR算法

嗯，使用免登录解决了

**Comment by koy1619** [comment]
eg：Xdown我有十个任务，总的下载速度可以达到4M/s，单个任务速度皆不一样，
我暂停了其他任务；只留一个，为什么这一个任务的速度始终不变？不应该是4M/s么？
@xdown-org @syhyz1990

**Comment by xdown-org** [comment]
@koy1619 
根据猜测,速度是百度云服务端进行限速,是根据单任务+ip进行限速的,
一个任务1m/s 是个任务一起可能就是10M/s  
单任何很难突破1m/s

这也只是猜测,

**Comment by xdown-org** [comment]
@syhyz1990 
我这里有一个关系xdown插件,
`https://github.com/xdown-org/xdown`
可不可以你来维护?

xdown配套的crx已经审核通过了:
`https://chrome.google.com/webstore/detail/xdown/eapmjcdkdlenhkbanlgacimfibbbiinc`

基本套路就是

chrome 调用 xdown.crx 然后配合油猴+js
点击之后自动启动xdown下载.

我这边对js了解真的不多.
不知道你有没有兴趣,挂到你主站上,你来维护?

**Comment by syhyz1990** [comment]
> @syhyz1990
> 我这里有一个关系xdown插件,
> `https://github.com/xdown-org/xdown`
> 可不可以你来维护?
> 
> xdown配套的crx已经审核通过了:
> `https://chrome.google.com/webstore/detail/xdown/eapmjcdkdlenhkbanlgacimfibbbiinc`
> 
> 基本套路就是
> 
> chrome 调用 xdown.crx 然后配合油猴+js
> 点击之后自动启动xdown下载.
> 
> 我这边对js了解真的不多.
> 不知道你有没有兴趣,挂到你主站上,你来维护?
> 
> xdown我这边很快发布1.0.0.6版本,主要就是针对错误修正,还有对插件的支持.
> 
> 安装插件+js+xdown, 用户只需要点击一下就可以下载,
> 体验是大大提升.

@xdown-org 可以，等我休息的时候具体研究下

**Comment by xdown-org** [comment]
@syhyz1990 


[XDown-Youtube.user.zip](https://github.com/syhyz1990/baiduyun/files/3662471/XDown-Youtube.user.zip)

你上传到你这边吧,我把介绍改成你的git

**Comment by cywy** [comment]
> https://www.youtube.com/watch?v=crug9LfAfc0
> 
> 这里有演示视频，无限制的。
大佬可不可以参考 yanu破解版IDM 里的代理开关功能做个按钮，这样下载外网文件方便切换到更快速的VPS那边。
https://i.postimg.cc/C1YCy36j/123.png

**Comment by s920170s9201** [comment]
使用最新版的xdown，三個插件都安裝了，點擊測試連結正常，但是點擊右鍵沒有影片中的快捷功能，直接點擊要下載的檔案也沒辦法呼叫出xdown(而是瀏覽器自帶的下載功能)

**Comment by xdown-org** [comment]
@s920170s9201 
目前只是打通了插件调用exe,
把youtube下载搞好了,成为默认的下载工具这块不熟悉还没搞
目前在优化bittorrent,之后才会着手插件完善,

**Comment by jorismq** [comment]
@xdown-org 
用了“百度网盘万能助手”，点“批量链接”不能批量下载了。速度很慢。关RR没用，加--uri-defined-rr 0
也没用

**Comment by pubdreamcc** [comment]
@xdown-org  ,Xdown 现在是被限制速度了吗？，我用的1.0.1.4版本，速度只有 50kb/s ...
