### ISSUE TITLE
chrome 76.0.3809.100 bug

### ISSUE THREAD

**Issue by arienjy** [syhyz1990/baiduyun#249]
已经装好了，但是还是显示没安装
![image](https://user-images.githubusercontent.com/39986424/64187010-5f46a580-cea2-11e9-9945-8d155ae629e1.png)

**Comment by syhyz1990** [comment]
请仔细阅读教程 https://www.baiduyun.wiki/zh-cn/cookie-plugin.html

**Comment by japheryLCJ** [comment]
发现问题所在了，缺少“万能助手”时点击链接会跳转到“直链下载助手”的页面，不注意的话就就以为安装过了，建议更新下链接的跳转页面。
