### ISSUE TITLE
网盘直接下载助手，idm,迅雷

### ISSUE THREAD

**Issue by TAN9999** [syhyz1990/baiduyun#25]
![image](https://user-images.githubusercontent.com/44641079/47787439-de7ec080-dd49-11e8-9d3b-8ddd82752ea5.png)
没有idm的下载链接，获取链接后点击右键也并没有出现迅雷的下载，怎么解，求指教

**Comment by liusxg** [comment]
你下载迅雷插件

**Comment by TAN9999** [comment]
哪个迅雷插件？方便说一下怎么用idm嘛

**Comment by liusxg** [comment]
> 哪个迅雷插件？方便说一下怎么用idm嘛

浏览器安装迅雷下载插件呀，idm没用过
