### ISSUE TITLE
firefox安装网盘万能助手显示扩展已损坏，无论zip crx 还是开发者转xpi均同样结果

### ISSUE THREAD

**Issue by Sutodonez** [syhyz1990/baiduyun#25]
firefox安装网盘万能助手显示扩展已损坏，无论zip crx 还是开发者转xpi均同样结果

**Comment by syhyz1990** [comment]
@Sutodonez 火狐用这个Tampermonkey Beta版 ，不需要万能助手了 https://firefox.tampermonkey.net/firefox-current-beta.xpi
