### ISSUE TITLE
IDM点击按教程点击连接无法下载

### ISSUE THREAD

**Issue by xuanyu66** [syhyz1990/baiduyun#255]
昨天晚上还可以使用，今天就开始报错。
配置和操作完全按照教程
具体错误如下：
idm拦截了根据baidupcs.com网站设置只能请求一次的下载，因此IDM回尝试在浏览器之前请求它。但截获的请求中没有足够的数据来下载此文件
![捕获3](https://user-images.githubusercontent.com/17768378/64472600-741d8480-d193-11e9-8986-e630837a6261.PNG)

**Comment by syhyz1990** [comment]
API 链接无法直接复制 ,需要右键
