### ISSUE TITLE
aria2c下载---->显示链接，出现 aria2c "error" --out 错误

### ISSUE THREAD

**Issue by goocheez** [syhyz1990/baiduyun#256]
## 使用环境

- OS: win10
- 浏览器：firefox 69.0
- 百度网盘直链下载助手	2.7.3 （下载自 github.com）
- 百度网盘万能助手  1.0.4 （下载自 firefox 市场）

## 问题描述
选中网盘文件后，aria2c下载---->显示链接，出现如下信息：
```aria2c "error" --out "test.pdf" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --header "Cookie: BDUSS=loaW1RU3lWZjFOLUFlflh6YlVaV0MzcTBTNDdzdlZCUTJhY05lSU9pZFBlaTVkSVFBQUFBJCQAAAAAAAAAAAEAAAAzQ-MA1qPQwtDHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE~tBl1P7QZdVU"```

其中的 test.pdf 是我计划下载的文件名。如果选择多个文件，则出现多行这样类似的信息。

**Comment by syhyz1990** [comment]
原因是未获取到请求到下载地址 , 重试下 , 看别的文件是否存在此情况

**Comment by goocheez** [comment]
全部文件都是出现上述错误
![图片](https://user-images.githubusercontent.com/36024678/64521824-44a18000-d32b-11e9-9ef6-7c074ad8ccf7.png)


另外，使用 `aria2c 外链下载---显示链接` 功能，提供的地址可以下载，但用 xdown 下载后出现的文件名是一长串乱码，如下：
![图片](https://user-images.githubusercontent.com/36024678/64521907-7adeff80-d32b-11e9-80dd-864315bd0277.png)

**Comment by goocheez** [comment]
已解决。

在另一浏览器（chrome）测试发现，可以正常。因此怀疑 firefox 下控件问题。经删除百度网盘万能助手，重新在 firefox 市场安装，恢复正常。

**Comment by syhyz1990** [comment]
好的，问题关闭
