### ISSUE TITLE
能否增加导出到Aria2 RPC Server的功能

### ISSUE THREAD

**Issue by sakuramisaki** [syhyz1990/baiduyun#257]
我的意思是不用复制aria2链接，配置完RPC地址后，直接导出就可以了，类似于下面的插件的功能。
https://github.com/acgotaku/BaiduExporter
rpc的地址类似于https://token:secret@hostname:port/jsonrpc
https://token:123456@192.168.123.123:6800/jsonrpc

**Comment by syhyz1990** [comment]
这个功能比较小众，暂时不会增加这个功能。
