### ISSUE TITLE
建议在API下载-显示链接中增加“复制全部链接功能”

### ISSUE THREAD

**Issue by ikkyusan123** [syhyz1990/baiduyun#258]
更新日志中提到：v2.7.4 支持IDM批量复制下载功能。不知道这个功能怎么使用，在Firefox中没看到批量复制下载链接的选项。
![0](https://user-images.githubusercontent.com/18085459/64528388-ee3c3d80-d33a-11e9-97b2-b4a29c91c927.png)

**Comment by syhyz1990** [comment]
api不支持复制下载

**Comment by monalisir** [comment]
@syhyz1990 请问在mac下面，如何用Neat Download Manager 批量下载，好像上一版本还可以？

**Comment by ikkyusan123** [comment]
那IDM批量复制下载功能怎么使用呢？ @syhyz1990

**Comment by syhyz1990** [comment]
鼠标左键选择全部链接，会显示idm的小弹窗，点击弹窗会批量添加地址
