### ISSUE TITLE
今天更新的，下载地址解析不出来

### ISSUE THREAD

**Issue by Hugo342523** [syhyz1990/baiduyun#259]
9月2日才下过大文件，满速没毛病；6号再用就只有几十K每秒，我以为是百度升级了，就坐等脚本更新；
今天（9号），脚本升级了，大文件直链直接解析不出来，几M的小文件，能解析出来，但只有几十K每秒

**Comment by goocheez** [comment]
我也曾出现昙花一现的高速下载，后来都只有几十上百k了。不过昨日更新最新版本，我依旧可以正常下载大文件（最大测试过500M左右）。

你试试重装一下相关控件？
