### ISSUE TITLE
火狐RPC下载无反应

### ISSUE THREAD

**Issue by saltfishh** [syhyz1990/baiduyun#26]
你好,使用的时候遇到了一些问题
- 问题描述
  - 使用火狐浏览器RPC下载,点击发送全部后motrix无反应,没有任务
- 系统环境
  - OS :archlinux 5.10.6-arch-1-1 gnome 3.38.2
  - Browser : firefox84.0.2,chrome 87.0.4280.141
  -  mortix : 1.5.15
 RPC配置如下:
![2021-01-15_01-12](https://user-images.githubusercontent.com/44364154/104624656-ca2b0200-56ce-11eb-9ba2-4a707556c1e6.png)

**Comment by syhyz1990** [comment]
看下Mortix 端口号是多少

**Comment by saltfishh** [comment]
下载助手配置的16800,主机http:localhost,路径D: 和/home/xx/tmp都试过了~

**Comment by syhyz1990** [comment]
linux 路径可能不对

**Comment by saltfishh** [comment]
也有尝试/home/xx/download

iPc <notifications@github.com> 于 2021年1月25日周一 13:03写道：
