### ISSUE TITLE
1.3.2已失效，IDM无法下载，会遇到403

### ISSUE THREAD

**Issue by Vampers** [syhyz1990/baiduyun#26]

**Comment by NormanBB** [comment]
我能下载，但是只有三个线程。估计还是账号被限速的问题。
按照作者说的，先分享出来，打开自己的分享链接，在下载助手处提取链接，idm就可以下载了。

**Comment by Vampers** [comment]
我知道怎么操作，一直使用脚本至今，今天更新后发现彻底无法下载了。

BTW，我对百度云脚本的未来走向持悲观态度，感觉现在开发者已经彻底被百度牵着鼻子走了。

**Comment by KenHopkin** [comment]
无法显示下载助手

**Comment by icleris** [comment]
的确不好用了，上周还好好的，现在下载一个文件后就限速了，退出登录其他帐号就不能下载

**Comment by westCastle** [comment]
> 我能下载，但是只有三个线程。估计还是账号被限速的问题。
> 按照作者说的，先分享出来，打开自己的分享链接，在下载助手处提取链接，idm就可以下载了。

我分享出来之后试了好几次才能够下载，并且只有三个线程。。。。。
