### ISSUE TITLE
Windows 平台使用教程 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#264]
https://www.baiduyun.wiki/zh-cn/windows.html#_5-%E6%8D%90%E8%B5%A0%E4%BD%9C%E8%80%85 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by YYQcoma** [comment]
开始速度很快，1-2M，但是后来只有20kb,请问是校园网限流了，还是网盘限速了？

**Comment by 1015127214** [comment]
为什么百度网盘插件2.0不能下载了

**Comment by wuhuihong** [comment]
idm下载显示403 forbidden

**Comment by Ytkcmdn** [comment]
就没有人遇到百度网盘万能助手插件在谷歌浏览器上用不了的情况吗，因为在插件商店里并没有这个插件，就算安装了也无法使用，希望作者可以更改一下这个脚本，不一定要用那个插件吧

**Comment by Iryya** [comment]
IDM not working, xdown working with aria links.

**Comment by 1263892066** [comment]
安装了两次网盘万能助手插件文件夹都被chome吞了，找不到了，不过没有万能助手也能用，提示第一次用暗号

**Comment by 1922097231** [comment]
为什么一直不显示文件名和大小_(:з)∠)_

**Comment by Hafeez-zhf3536** [comment]
为什么没有免登录链接啊

**Comment by LeslieSong** [comment]
怎么不显示直接下载了

**Comment by Hafeez-zhf3536** [comment]
在线解析错误提示：下载失败  不能解析啊

**Comment by git12343423423** [comment]
idm批量全是error

**Comment by cy9102** [comment]
免登录下载链接打开之后页面空白了

**Comment by cy9102** [comment]
> 免登录下载链接打开之后页面空白了

用的是Edge浏览器

**Comment by n0005073** [comment]
idm无法获取文件名和大小

**Comment by rickterry2** [comment]
我是chrome，安装了tampermonkey和百度助手，但是显示链接后没有“复制全部链接”的按钮，手动复制后，用迅雷可以达到400k。下的文件多时没有复制链接的功能还挺郁闷的。。

**Comment by shi900384** [comment]
安装扩展后,并没有出现下载助手这个按钮,我用的是chrome

**Comment by io23312** [comment]
用免登入下载时显示403错误

**Comment by cxryun** [comment]
解析链接无法下载

**Comment by SpikerA** [comment]
2.10没有出现 复制全部链接

**Comment by vsoulstudio** [comment]
xdown下载Aria的解析，小文件可以 大文件显示异常

**Comment by ychao661** [comment]
前几天开始，不管下什么都显示异常了，在多台电脑上试过，都不行

**Comment by chairzeng** [comment]
已经炸了

**Comment by mikcc123** [comment]
没显示下载助手2.9.4，下载2.10版本的扩展浏览器不支持··被禁用了。

**Comment by yeziming233** [comment]
我这边API下载选择多个连接之后，出现的是”请先安装 百度网盘万能助手 右键"IDM下载"“，我把脚本删了重新安装，出现的还是一样的字。有什么解决方法吗？

**Comment by leefgx** [comment]
校园网好像用不了，一用就会被电信天翼封

**Comment by ray777342** [comment]
为什么我这更新2.9.4后，不显示下载助手了？

**Comment by chairzeng** [comment]
最新IDM还是不行，限速了

**Comment by taoleee** [comment]
第一次使用idm可以成功下载，下载xdown后idm没用了

**Comment by GOMrHU** [comment]
请先勾选文件，若已勾选请刷新后重试！（无解）

**Comment by QuietCao** [comment]
懒人版是绿色版吗？可以解压到U盘然后直接放到U盘带走吗?
别问我为啥问这个，我只是不想折腾Chrome绿化而已

**Comment by syhyz1990** [comment]
> 懒人版是绿色版吗？可以解压到U盘然后直接放到U盘带走吗?
> 别问我为啥问这个，我只是不想折腾Chrome绿化而已

当然可以

**Comment by wiixiiidi** [comment]
Xdown下载东西，状态显示异常，什么原因？

**Comment by zlj19931010** [comment]
批量下载：
1、我手动全选，然后使用idm下载，部分error
2、我把隐藏的选中按钮显示出来，只能idm从剪切板下载，全部error
3、我一个一个添加到待下载列表，就可以，但是这样好累！！

**Comment by kcceoi** [comment]
下载到一半突然没速度了怎么办？

**Comment by stone926** [comment]
下载助手为什么现在没有直接下载选项了，显示链接出来的又是403forbidden，我用idm，不用xdown

**Comment by kcceoi** [comment]
你可以更新一下插件试试。

发送自 Windows 10 版邮件应用

发件人: stone926
发送时间: 2019年12月21日 16:47
收件人: syhyz1990/baiduyun
抄送: kcceoi; Comment
主题: Re: [syhyz1990/baiduyun] Windows 平台使用教程 | 百度网盘直链下载助手 (#264)

下载助手为什么现在没有直接下载选项了，显示链接出来的又是403forbidden，我用idm，不用xdown

**Comment by qingsibaixue** [comment]
不能用

**Comment by CPCer** [comment]
`两个工具任选其一即可，如需获取aria链接，需要安装 XDown 和 百度网盘万能助手` 万能助手 是什么，，点开又跳转回 直链下载助手 了

**Comment by ACupofAir** [comment]
# 要是一直不显示文件名和大小呢

**Comment by JDsilent** [comment]
提示说是要更新，或者去设置里改一些东西，我没有去更新，但是设置里也没有能去改的东西呀？

**Comment by ACupofAir** [comment]
那玩意我就没成功过，还是租一个VIP账号吧，三小时几块钱淘宝上很多

发自我的华为手机

**Comment by resticDOG** [comment]
**感谢作者**

**Comment by DandanIS** [comment]
只有分享后下获取链接可以满速了其他的全限速

**Comment by zzhgod1996** [comment]
XDown复制完连接后，显示异常

**Comment by amazedyueyue** [comment]
请问那个idm为啥要输www.baidupcs.com啥的，我输云盘的用户名和1密码也不对啊？？？？

**Comment by lov3lace996** [comment]
作者辛苦啦！

**Comment by StackL0nG** [comment]
IDM无法有效启动多线程，一直失败

**Comment by Mark-1234567** [comment]
IDM现在点击链接后一点反应都没有

**Comment by liufan1993** [comment]
是不是不能用了呀

**Comment by LoveTruth** [comment]
作者，请问4.0.0版的直链下载助手为何找不到可以修改“神秘代码”的地方了呀？

**Comment by Harry991224** [comment]
请问为什么无法显示 全部复制

**Comment by chengmozhi** [comment]
我的IDM弹出了文件名和类型大小也下载不了，点了就提示“请求的文件不存在。备注：HTTP/1.1 404 Not Found”

**Comment by Mark-1234567** [comment]
emm




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chengmozhi"<notifications@github.com&gt;; 
发送时间: 2020年4月11日(星期六) 下午5:31
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
抄送: "吕逸轩"<2824532640@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [syhyz1990/baiduyun] Windows 平台使用教程 | 百度网盘直链下载助手 (#264)





 
我的IDM弹出了文件名和类型大小也下载不了，点了就提示“请求的文件不存在。备注：HTTP/1.1 404 Not Found”
 
&mdash;

**Comment by delusionxb** [comment]
"从剪切板批量添加"下载的结果都是错误, 只能一个个的点击链接才行. IDM必须用你给的么? 我用的是从其他地方下载的, 6.36build7

**Comment by Mark-1234567** [comment]
我用的是ypojie.com上的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "delusionxb"<notifications@github.com&gt;; 
发送时间: 2020年4月13日(星期一) 上午10:50
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
抄送: "吕逸轩"<2824532640@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [syhyz1990/baiduyun] Windows 平台使用教程 | 百度网盘直链下载助手 (#264)





 
"从剪切板批量添加"下载的结果都是错误, 只能一个个的点击链接才行. IDM必须用你给的么? 我用的是从其他地方下载的, 6.36build7
 
&mdash;

**Comment by mkcs123456** [comment]
神秘代码没了？用直接下载完全没速度

**Comment by lanserhu** [comment]
我用的idm的版本是6.37beta8，浏览器捕获也都勾上了，结果点击“默认链接”后idm就没能捕获到下载，用了idm的浏览器集成插件也没用。另我的万能助手跟下载助手都是最新版的。

**Comment by xjt927** [comment]
懒人版的 打不开了
