### ISSUE TITLE
比特彗星捆绑杀毒软件

### ISSUE THREAD

**Issue by Xerzsh** [syhyz1990/baiduyun#265]
![image](https://github.com/syhyz1990/baiduyun/assets/48620641/4e77d869-e23c-423f-96f3-064076dcff8d)

**Comment by ghost** [comment]
用贴吧版 无广无捆绑 我一直在用 和官方没什么区别

**Comment by Xerzsh** [comment]
> 用贴吧版 无广无捆绑 我一直在用 和官方没什么区别

说的就是官方版。官方版会捆绑杀毒软件

**Comment by syhyz1990** [comment]
网盘有绿色纯净版
