### ISSUE TITLE
MacOS 平台使用教程 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#265]
https://www.baiduyun.wiki/zh-cn/mac.html 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by Hilimmer7** [comment]
想请问下出现403 forbidden怎么办？

**Comment by Hilimmer7** [comment]
看到了后面的常见问题了 谢谢

**Comment by ariour** [comment]
网盘分享页面只有保存后下载，自定义保存路径两个选项没有上述按钮。更新到最新版本之前的版本还有的

**Comment by YeungKC** [comment]
最好的下载方法应该是用 https://chrome.google.com/webstore/detail/aria2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjn，直接转到 aria2 上面

**Comment by oshiwei** [comment]
下载时会报错：{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":6259412647687363959}

**Comment by xiangchen2011** [comment]
> @oshiwei
> 下载时会报错：{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":6259412647687363959}

我也出现类似的报错

**Comment by Masstone** [comment]
推荐Motrix下载器

**Comment by xiangchen2011** [comment]
> 推荐Motrix下载器

额，刚把它卸载

**Comment by Masstone** [comment]
> > 推荐Motrix下载器
> 
> 额，刚把它卸载

那你用啥

**Comment by xiangchen2011** [comment]
他推荐的啊，Neat Downloader

Masstone <notifications@github.com> 于2019年10月8日周二 下午4:18写道：

**Comment by Sakuradreancat** [comment]
提示：请先勾选要下载的文件，否则刷新后重试！ 但是我勾选了页重试了，刚刚实验的时候还可以了，然后要下需要的就不行了。

**Comment by OoaLH** [comment]
Mac IDM一直403。。用Windows虚拟机打不开xdown，提示xdown has stopped running。。

**Comment by Zhenye-Na** [comment]
下载 `Aria2GUI` 使用解析出来的链接 (不是 aria 的那个) 可以达到 2MB/s

嘿嘿

**Comment by wangbingqian** [comment]
自己网盘的直接下报403，分享出去下就没问题了……

**Comment by Masstone** [comment]
已经看不到直接下载了

直连和aric在下载上有区别么

NeatDownloadManager安装了浏览器插件之后也是要手动复制粘贴么

**Comment by Masstone** [comment]
这个下载器呢
Persepolis Download Manager
https://persepolisdm.github.io/

**Comment by YGQ8988** [comment]
直连地址访问如下错误：
{
    "error_code": 31326,
    "error_msg": "user is not authorized, hitcode:107",
    "request_id": 6853218931876021289
}

**Comment by superbaobei** [comment]
mac chrome中《百度网盘万能助手》报错：
```javascript
 Unchecked runtime.lastError while running webRequestInternal.eventHandled: Invalid header specification '{"name":"Access-Control-Allow-Origin"}'.
```
上下文：
> html/background.html
堆叠追踪
html/background.html:0 (匿名函数)

**Comment by liuze0109** [comment]
出现403问题

**Comment by Hsiaopan** [comment]
实测macOS上点API下载，然后点到右键链接选择download by NeatDownloadManager，线程选32，速度贼快。其他几个下载选项，不知道怎么配合motrix使用。

**Comment by kinkykitty** [comment]
请问多线程下载工具有支持Safari的吗

**Comment by Skytostop** [comment]
neatdown用哪个链接呢？

**Comment by bwang24** [comment]
NeatDownloadManager选32线程也会被限制在2个线程.

**Comment by xiangchen2011** [comment]
直接下载没反应，API下载403，Aira的话Neat Downloader Manager也没反应。。。。。。。

bbw <notifications@github.com> 于2019年12月18日周三 下午5:48写道：

**Comment by Tao-bug** [comment]
没有加速效果呢

**Comment by JieyuLiang** [comment]
> 自己网盘的直接下报403，分享出去下就没问题了……

我是自己网盘里的同一个文件，用chrome下载就403，Firefox就正常

**Comment by JieyuLiang** [comment]
> 已经看不到直接下载了
> 
> 直连和aric在下载上有区别么
> 
> NeatDownloadManager安装了浏览器插件之后也是要手动复制粘贴么

我一开始也遇到类似的问题，通过教程里的链接把暴力猴里的插件更新到最新版本，点扩展插件里的网盘直链下载助手-启动，再刷新一下网页，直接下载就显示出来了

**Comment by effycoco** [comment]
下载好之后复制链接的选项只出现过一次，后面就没有这个选项了，所有插件都启用了

**Comment by User-Star** [comment]
####百度网盘使用aria2下载时一直是79-85kb/s，是百度网盘对这种方式做了限制吗？
