### ISSUE TITLE
Android 平台使用教程 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#266]
https://www.baiduyun.wiki/zh-cn/android.html 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by 87zrjojo** [comment]
安卓用kiwi浏览器按照教程设置，ADM自定义useragent
netdisk;6.7.1.9;PC;PC-Windows;10.0.17763;WindowsBaiduYunGuanJia下载老失败，只有设置成chrome的才可以下载，不知道为什么

**Comment by syhyz1990** [comment]
> @87zrjojo
> 安卓用kiwi浏览器按照教程设置，ADM自定义useragent
> netdisk;6.7.1.9;PC;PC-Windows;10.0.17763;WindowsBaiduYunGuanJia下载老失败，只有设置成chrome的才可以下载，不知道为什么

自定义代理，ua改成Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14
线程拉到最大试下

**Comment by jnznn96** [comment]
请问都安装好后怎么使用呢

**Comment by cengjingdeshuye** [comment]
关于AMD Pro的设置我找不到你说的路径啊

**Comment by zhl321** [comment]
安卓版可以批量下载吗？好像只能粘贴一个链接下载。而且浏览器不能直接调动ADM Pro吗？

**Comment by wineejam** [comment]
ADM Pro  试了WindowsBaiduYunGuanJia、Chrome、Opera的UserAgent，都是提示客户端错误（访问被拒），求解决方案

**Comment by superbaobei** [comment]
错误提示
> 客户端错误（访问被拒）

**Comment by leyan22** [comment]
貌似失效了，每次都提示客户端错误（访问被拒）

**Comment by Nancy70935** [comment]
最后的路径是不是设置-下载-然后自定义填进去链接啊，填了没有用能不能出个视频

**Comment by sjkhsl** [comment]
修改了adm的标识，还是不行啊！

**Comment by DoveBoy** [comment]
同样问题，显示链接后分享给adm提示客户端访问拒绝，修改adm中的ua也无效
