### ISSUE TITLE
百度网盘万能助手 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#267]
https://www.baiduyun.wiki/zh-cn/cookie-plugin.html 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by endlesslovee** [comment]
halo,关于百度网盘万能助手安装教程有些问题：
方法一：介绍里放的链接打开是404，到商店地址直接搜索名字未能找到该文件
方法二：直接改后缀的方法会导致文件损坏无法解压；通过传统压缩方法再解压，通过开发者模式，76版本的Chrome依旧无法打开，希望能够得到解决。
谢谢！

**Comment by devil9ema** [comment]
重启还是一直提示安装

**Comment by syhyz1990** [comment]
> @devil9ema
> 重启还是一直提示安装
> 

参考下安装视频

**Comment by syhyz1990** [comment]
> @endlesslovee
> halo,关于百度网盘万能助手安装教程有些问题：
> 方法一：介绍里放的链接打开是404，到商店地址直接搜索名字未能找到该文件
> 方法二：直接改后缀的方法会导致文件损坏无法解压；通过传统压缩方法再解压，通过开发者模式，76版本的Chrome依旧无法打开，希望能够得到解决。
> 谢谢！

参考下安装视频  https://www.baiduyun.wiki/zh-cn/xdown.html

**Comment by zslasa** [comment]
谷歌商店挂了

**Comment by syhyz1990** [comment]
感谢反馈 , 暂时下载安装吧!

**Comment by fly2light** [comment]
你好，mac一直提示重新安装，但是已经重启好几次了

**Comment by gjxgjxgjxgjx** [comment]
点复制链接没有反应怎么办

**Comment by syhyz1990** [comment]
用的什么浏览器



---原始邮件---
发件人: "gjxgjxgjxgjx"<notifications@github.com&gt;
发送时间: 2019年9月19日(星期四) 晚上8:57
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"iPc"<syhyz1990@qq.com&gt;;
主题: Re: [syhyz1990/baiduyun] 百度网盘万能助手 | 百度网盘直链下载助手 (#267)



点复制链接没有反应怎么办

**Comment by gjxgjxgjxgjx** [comment]
chrome


 
---原始邮件---
发件人: "iPc"<notifications@github.com&gt;
发送时间: 2019年9月20日(星期五) 晚上9:50
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"gjxgjxgjxgjx"<912939669@qq.com&gt;;
主题: Re: [syhyz1990/baiduyun] 百度网盘万能助手 | 百度网盘直链下载助手 (#267)


用的什么浏览器 
 
 
 
 ---原始邮件--- 
 发件人: "gjxgjxgjxgjx"<notifications@github.com&amp;gt; 
 发送时间: 2019年9月19日(星期四) 晚上8:57 
 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&amp;gt;; 
 抄送: "Author"<author@noreply.github.com&amp;gt;;"iPc"<syhyz1990@qq.com&amp;gt;; 
 主题: Re: [syhyz1990/baiduyun] 百度网盘万能助手 | 百度网盘直链下载助手 (#267) 
 
 
 
 点复制链接没有反应怎么办

**Comment by InfiniteSin** [comment]
百度网盘万能助手那个链接无法下载

**Comment by shuzhihen** [comment]
阻止网站的验证码显示了

**Comment by shuzhihen** [comment]
火狐浏览器的怎么安装，大神指导一下啊
