### ISSUE TITLE
IDM 使用技巧 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#268]
https://www.baiduyun.wiki/zh-cn/idm.html 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by shadowdragon1123** [comment]
我是chorme浏览器，安装了脚本，但是IDM显示403没有权限无法下载。IDM使用的是最新的6.3.5，并且修改了UA。
以前一直用IDM都正常，但就是7月开始不支持了。即便是不限速链接也不行，xdown是可以下载

**Comment by Mao0509** [comment]
IDM:6.35
脚本:2.8.0
按照README中修改了IDM设置，但是批量下载失败，文件类型显示Error

**Comment by urnotaltman** [comment]
用IDM下载大文件，为什么总是半途让提供账号和密码呢？

**Comment by naoh2004** [comment]
修改UA 的那个没了？ 现在点极速 有时候会出验证码 输入完验证码还是不弹极速链接

**Comment by wxb2468235** [comment]
百度网盘直链下载助手 只有保存后下载和自定义保存路径2个选项，而且下载txt自动转化为了pdf

**Comment by abcabc5566** [comment]
文件类型显示Error

**Comment by sheenblue** [comment]
百度网盘直链下载助手  看不到免登录或者极速下载的地方了

**Comment by vul31931u04** [comment]
强迫使用万能助手就算了，还强迫一定要用微信，是不是没考虑到没微信的使用者，海外用户谁跟你用微信，周遭也没人用，第一次办完就显示帐号异常，能不能考虑whatsapp或是line之类的海外通信软体？

**Comment by HolyFlanker** [comment]
> @vul31931u04
> 强迫使用万能助手就算了，还强迫一定要用微信，是不是没考虑到没微信的使用者，海外用户谁跟你用微信，周遭也没人用，第一次办完就显示帐号异常，能不能考虑whatsapp或是line之类的海外通信软体？

那你别用不就完了？逼你用了？又不挣你钱还把你给能的。

**Comment by shadowdragon1123** [comment]
> @vul31931u04
> 强迫使用万能助手就算了，还强迫一定要用微信，是不是没考虑到没微信的使用者，海外用户谁跟你用微信，周遭也没人用，第一次办完就显示帐号异常，能不能考虑whatsapp或是line之类的海外通信软体？

那你别用啊，又没人拿枪指着你

**Comment by 49woS** [comment]
> @vul31931u04
> 强迫使用万能助手就算了，还强迫一定要用微信，是不是没考虑到没微信的使用者，海外用户谁跟你用微信，周遭也没人用，第一次办完就显示帐号异常，能不能考虑whatsapp或是line之类的海外通信软体？

兄弟好好说话，请到google play store下载wechat(微信)。注册账号非常简单，我身边的人都在用，还有我是马来西亚人。

**Comment by vsoulstudio** [comment]
批量下载的话链接直接复制显示文件类型error，但是直接在浏览器里点击链接可以被IMD监控到弹出下载框，链接粘贴到chrome的地址栏回车后也能被IDM识别

**Comment by kidkid** [comment]
不好用啊，403forbidden

**Comment by yushaiyang** [comment]
IDM试用到期后还能继续用吗

**Comment by fauthor** [comment]
idm通过剪贴板批量下载，文件类型错误，下载不了。这种情况应该怎么解决呢

**Comment by chendf24** [comment]
分享一下: IDM批量下载的话, 直接在自己的网盘里多选然后显示直链, 添加到IDM后会显示error. 需要把文件分享以后, 在分享界面多选显示直链后可以正常批量下载.

**Comment by chendf24** [comment]
> @abcabc5566
> 文件类型显示Error

需要把文件分享以后, 在分享界面多选显示直链后可以正常批量下载.

**Comment by xunhuanxuan** [comment]
不管是分享后下载，还是在分享界面下载，都是显示Error

**Comment by zhanggege1100** [comment]
用xdown下载，第一个好好的，第二个就异常了

**Comment by yyli12345** [comment]
XDOWN一个都下载不了，永远显示异常是什么原因？IDM则是动不动没有权限下载此文件？

**Comment by wangmengton** [comment]
用不了了啊

**Comment by vbmnvbn** [comment]
IDM下载显示错误
 Internet Download Manager
IDM拦截了根据baidupcs.com网站设置只能请求一次的下载,因此IDM会
尝试在浏览器之前请求它。但截获的请求中没有足够的数据来下载此文件。
您可能使用一种非常规的方式在共享网站上绕过网页处理向浏览器添加下载。
在这种情况下,您需要从指向下载的公共链接重新开始,并传递所有必要的步
骤,以便截获的请求将包含所有必要的数据。
如果它
不是下载,并且IDM错误拦截了它,请在IDM选项中设置一个特殊键

**Comment by noomevolmsz** [comment]
MacOS, 直链复制到Neat Download Manager 里下载就会弹出HTTP/1.1 403 Forbidden  求解

**Comment by jxy90** [comment]
下载的线程数量变少了，现在最多只能有两个.

**Comment by pythonlover3** [comment]
403

**Comment by lihangzju** [comment]
只有两个线程了。。。好慢

**Comment by jujunchen** [comment]
直接点击下载，没反应，使用链接也无反应
chrome version: 79.0.3945.117
插件版本：3.0.1

**Comment by RC-122** [comment]
它老是说：此版本的idm不支持该类下载，请尝试将idm更新至最新版本。不给我下。

**Comment by InfiniteLJH** [comment]
为何只有两个线程了？如何解决？谢谢啦

**Comment by 15925710363** [comment]
速度不快啊

**Comment by 666emmm** [comment]
> https://www.baiduyun.wiki/zh-cn/idm.html
> 
> 🖖油猴脚本 一个脚本搞定百度网盘下载

idm长时间下载一个文件时，中途停止后重新开始会要求输入管理员账号和密码，请问这是什么

**Comment by suken1017** [comment]
为什么我从百度网盘下载助手选择复制全部链接后不弹出这个软件，插件里面安装了

**Comment by Jacksonlinj** [comment]
为什么下载助手3.0.3没有api链接这个选项，更没法用神秘代码

**Comment by sennyou-kuruneko** [comment]
建议还是8线程下载，32线程可能配置不够反而降速，或者被服务器检测到从而拉黑

**Comment by script93-lu** [comment]
> IDM下载显示错误
> Internet Download Manager
> IDM拦截了根据baidupcs.com网站设置只能请求一次的下载,因此IDM会
> 尝试在浏览器之前请求它。但截获的请求中没有足够的数据来下载此文件。
> 您可能使用一种非常规的方式在共享网站上绕过网页处理向浏览器添加下载。
> 在这种情况下,您需要从指向下载的公共链接重新开始,并传递所有必要的步
> 骤,以便截获的请求将包含所有必要的数据。
> 如果它
> 不是下载,并且IDM错误拦截了它,请在IDM选项中设置一个特殊键

你是不是用的新版Edge？试一试Chrome

**Comment by X-Hello** [comment]
IDM点击下载后无反应怎么办？？？

**Comment by HOMMEEN** [comment]
hi 不管是批量下载还是直接下载 IDM 都提示 **IDM 拦截了根据BAIDUPCS.COM 网站设置只能请求一次的下载,因此 IDM 会尝试在浏览器之前请求他....** 这该怎么办呀

**Comment by CYFchenyifei** [comment]
同上， **IDM 拦截了根据BAIDUPCS.COM 网站设置只能请求一次的下载**，我看论坛上说50M以后就会有这种弹窗。

**Comment by KingdaShi** [comment]
更换神秘代码也没用，IDM下了第一个 后面的文件都下不了了

**Comment by SandmanGit** [comment]
> @vbmnvbn
> IDM下载显示错误
>  Internet Download Manager
> IDM拦截了根据baidupcs.com网站设置只能请求一次的下载,因此IDM会
> 尝试在浏览器之前请求它。但截获的请求中没有足够的数据来下载此文件。
> 您可能使用一种非常规的方式在共享网站上绕过网页处理向浏览器添加下载。
> 在这种情况下,您需要从指向下载的公共链接重新开始,并传递所有必要的步
> 骤,以便截获的请求将包含所有必要的数据。
> 如果它
> 不是下载,并且IDM错误拦截了它,请在IDM选项中设置一个特殊键

同样错误，有解决办法吗

**Comment by hejingjie** [comment]
# 为什么我的字这么大
## 他又变小了
### 变得更小了
