### ISSUE TITLE
https://pan.xunlei.com/ 迅雷云盘选定文件后无法进行下载

### ISSUE THREAD

**Issue by RX1018** [syhyz1990/baiduyun#269]
![image](https://github.com/syhyz1990/baiduyun/assets/53224480/001fb8be-0932-4a53-a3c2-03ed7a5e6e93)
勾选文件后仍然提示需要先勾选需要下载的文件

**Comment by RX1018** [comment]
补充：五个下载方式都无法使用

**Comment by taozhiyu** [comment]
~~话说你可以正常显示这个按钮吗，可能是作者更新了？~~
更新了但是没有完全更新
按照 #268 操作即可（或者等待作者更新）

**Comment by r4p0** [comment]
亲测将2136行
```js
let doms = document.querySelectorAll('.pan-list-item');
```
改为
```js
let doms = document.querySelectorAll('.pan-list li');
```
即可正常运行

问题原因估计是迅雷改了Dom的class命名规则导致原本的无法匹配

**Comment by forthepeak** [comment]
> 亲测将2136行
> 
> ```js
> let doms = document.querySelectorAll('.pan-list-item');
> ```
> 
> 改为
> 
> ```js
> let doms = document.querySelectorAll('.pan-list li');
> ```
> 
> 即可正常运行
> 
> 问题原因估计是迅雷改了Dom的class命名规则导致原本的无法匹配

实测有用，谢谢大佬( •̀ ω •́ )

**Comment by TNTGans665** [comment]
> 亲测将2136行
> 
> ```js
> let doms = document.querySelectorAll('.pan-list-item');
> ```
> 
> 改为
> 
> ```js
> let doms = document.querySelectorAll('.pan-list li');
> ```
> 
> 即可正常运行
> 
> 问题原因估计是迅雷改了Dom的class命名规则导致原本的无法匹配

感谢🙏
