### ISSUE TITLE
mac motrix无法传送

### ISSUE THREAD

**Issue by fredericky123** [syhyz1990/baiduyun#27]
是不是链接无法传送到Motrix上，总是下载失败
普遍吗

**Comment by ElectronZGZY** [comment]
我也一样，每次下载都显示下载发生错误#22，即“HTTP response header was bad or unexpected.”

**Comment by taoletsgo** [comment]
多传几次

**Comment by horizon365** [comment]
> 我也一样，每次下载都显示下载发生错误#22，即“HTTP response header was bad or unexpected.”

Mac 上同样的问题

**Comment by aes-alienrip** [comment]
已經失效好一段時間了

**Comment by fredericky123** [comment]
我之前好像设置出了问题，现在设置好了，能传送
