### ISSUE TITLE
常见问题 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#270]
https://www.baiduyun.wiki/zh-cn/question.html 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by hewittchoi** [comment]
idm 6.32升级到6.35后下载的线程数就只有4了，速度只有几十k，没更新前本来很快的。

**Comment by syhyz1990** [comment]
> @hewittchoi
> idm 6.32升级到6.35后下载的线程数就只有4了，速度只有几十k，没更新前本来很快的。

检查下idm中的线程数

**Comment by Joe-LI-Sir** [comment]
浏览器有IDM扩展但是显示多个连接的时候显示，直接复制链接无效，请安装 IDM 及浏览器扩展后使用

**Comment by Cat-tails** [comment]
你好,现在没法批量下载了么,没有复制全部链接按个按钮了

**Comment by j2979** [comment]
我的这里aria没有了，不能用xdown下载...是不是账号被限速了？

**Comment by j2979** [comment]
分享后下载也还是80k左右...

**Comment by lluweibejone** [comment]
甚至把这个都删了 还是老师提示发现新版本
更新日志：v2.8.3 修复IDM下载失效的问题，需更新【百度网盘万能助手】，下载地址：http://pan.baiduyun.wiki/down

**Comment by wzhju183513** [comment]
我已经更新了2.8.3了，怎么一打开还要更新。我已经安装百度网盘助手的火狐版本的插件了

**Comment by wzhju183513** [comment]
我在油猴桃已经更新了2.8.3版本，火狐浏览器也安装了百度助手下载的插件），一打开浏览器老是让更新。如何（单独）更新百度助手2.20版本。

**Comment by buzhipowwz** [comment]
安装百度网盘万能助手时，谷歌浏览器提示“该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的”，无法使用,有谷歌商店的版本吗？

**Comment by buzhipowwz** [comment]
如果无法使用的话，有什么方法去除更新提示，打开一个知乎网页就会跳出更新提示，这是什么引起的？

**Comment by wzhju183513** [comment]
我是火狐浏览器

&nbsp;
------------------



王招军
设计师助理
陕西凯旋装饰工程有限公司第一分公司


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "buzhipowwz"<notifications@github.com&gt;; 
发送时间: 2019年9月21日(星期六) 晚上10:01
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
抄送: "461034185"<461034185@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)




安装百度网盘万能助手时，谷歌浏览器提示“该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的”，无法使用,有谷歌商店的版本吗？

**Comment by tupis2008** [comment]
我是QQ浏览器，刚更新完2.8.3，结果打开页面还是疯狂跳升级提示，这是什么鬼啊？怎么解决？
另外，百度网盘万能助手在QQ浏览器怎么安装？在下载页面老是提示无法从该网站安装应用。有没有其他链接可以下载那个crx文件？谢谢

**Comment by tupis2008** [comment]
安装完百度网盘万能助手2.0还是疯狂跳更新2.8.3的提示。。。无语了

**Comment by coinca** [comment]
我把脚本都卸载了，每次打开网页依然弹窗提示更新，拦截软件也找不到，流氓木马一样的更新提醒。

**Comment by syhyz1990** [comment]
把懒人专用，全网vip...这个脚本禁用



---原始邮件---
发件人: "lluweibejone"<notifications@github.com&gt;
发送时间: 2019年9月21日(星期六) 晚上7:08
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"iPc"<syhyz1990@qq.com&gt;;
主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)



甚至把这个都删了 还是老师提示发现新版本
 更新日志：v2.8.3 修复IDM下载失效的问题，需更新【百度网盘万能助手】，下载地址：http://pan.baiduyun.wiki/down

**Comment by syhyz1990** [comment]
把懒人专用开头的这个脚本禁用，无法安装的话用ie浏览器下载后，到qq扩展页面打开开发者模式，拖进去安装



---原始邮件---
发件人: "tupis2008"<notifications@github.com&gt;
发送时间: 2019年9月21日(星期六) 晚上10:31
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"iPc"<syhyz1990@qq.com&gt;;
主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)



我是QQ浏览器，刚更新完2.8.3，结果打开页面还是疯狂跳升级提示，这是什么鬼啊？怎么解决？
 另外，百度网盘万能助手在QQ浏览器怎么安装？在下载页面老是提示无法从该网站安装应用。有没有其他链接可以下载那个crx文件？谢谢

**Comment by eweiwen** [comment]
已更新到2.8.3，IDM是6.5.3，星愿浏览器，浏览器IDM模块是6.5.2，用复制全部直链后黏贴到IDM显示error，单个文件下载就显示无权限，求解

**Comment by tupis2008** [comment]
> @syhyz1990
> 把懒人专用开头的这个脚本禁用，无法安装的话用ie浏览器下载后，到qq扩展页面打开开发者模式，拖进去安装
> 
> 
> 
> ---原始邮件---
> 发件人: "tupis2008"<notifications@github.com&gt;
> 发送时间: 2019年9月21日(星期六) 晚上10:31
> 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
> 抄送: "Author"<author@noreply.github.com&gt;;"iPc"<syhyz1990@qq.com&gt;;
> 主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)
> 
> 
> 
> 我是QQ浏览器，刚更新完2.8.3，结果打开页面还是疯狂跳升级提示，这是什么鬼啊？怎么解决？
>  另外，百度网盘万能助手在QQ浏览器怎么安装？在下载页面老是提示无法从该网站安装应用。有没有其他链接可以下载那个crx文件？谢谢
>  
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

谢谢~  昨天用城通网盘客户端下载crx文件安装成功后就关机了，今天开机一切就都正常了。。。 那个懒人专用的脚本还留着没动，但是好像已经OK了。

**Comment by necnotdie** [comment]
大佬，脚本有个bug，就是下载一个文件夹中的文件，如果这个文件夹的文件数超过100个，百度默认是加载前100的，这个脚本初始化的时候只能初始化100个文件到fileList里面，所以如果下载100个之后的文件，就会在fileList中找不到对应文件，就会提示“未选中文件，请勿勾选文件夹，否则刷新后重试！”，实际上文件是勾过的。

**Comment by haveastar** [comment]
為何我有兩個下載助手按鈕...  已經移除掉插件按鈕竟然還在?!= =

**Comment by syhyz1990** [comment]
把其他的盗版脚本删掉




------------------ 原始邮件 ------------------
发件人: "haveastar"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 中午12:35
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "【暗~@_@~】"<syhyz1990@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)




為何我有兩個下載助手按鈕...  已經移除掉插件按鈕竟然還在?!= =

**Comment by haveastar** [comment]
> @syhyz1990
> 把其他的盗版脚本删掉
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: "haveastar"<notifications@github.com>;
> 发送时间: 2019年9月24日(星期二) 中午12:35
> 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
> 抄送: "【暗~@_@~】"<syhyz1990@qq.com>;"Mention"<mention@noreply.github.com>;
> 主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)
> 
> 
> 
> 
> 為何我有兩個下載助手按鈕...  已經移除掉插件按鈕竟然還在?!= =
>  
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


但我確定兩個都是這個腳本XD
新裝了一個火狐也是這樣 出現兩個一樣的按鈕

這是CHROME的
https://imgur.com/mrz0C6K

**Comment by iuyfguyij** [comment]
现在点击显示直链调用idm会弹出一个新标签页{"error_code":   ,"error_msg":"expire time out error","request_id":   }  这种格式且无法下载。调用xdown会被告知下载异常失败

**Comment by why2face** [comment]
无痕模式下也没有免登陆链接的选项啊。。脚本和插件都装了

**Comment by lnuyasha47** [comment]
更新以后打开分享链接只有保存后下载和自定义保存路径两个选项怎么办

**Comment by Thunderltx** [comment]
最近更新没有了免登录这一项了欸，为什么？是脚本改了，还是我设置的问题？

**Comment by BrilliantXie** [comment]
我已经安装教程里的东西，也安装好了，为什么百度云还是没有下载助手呢？

**Comment by BrilliantXie** [comment]
我已经安装教程里的东西，也安装好了，为什么百度云还是没有下载助手呢？

**Comment by 1263892066** [comment]
更新后没有免登录下载了，网速还很慢，是被和谐了么

**Comment by p12313461** [comment]
位啥就算重裝了百度网盘万能助手還重啟了瀏覽器還是提示我要安裝???

**Comment by gaiying** [comment]
为什么更新了万能助手，xdown下载刚开始几秒正常，接着就显示下载异常了。。。

**Comment by gaiying** [comment]
为什么用idm批量下载的时候，有一半以上的文件夹都显示错误，不能正常下载？

**Comment by chenxiaohei66** [comment]
楼主，我更新最新脚本后只有显示api下载和分享下载，而且分享下载没登陆没法下载

**Comment by charliexxxxx** [comment]
卡在「初次使用请输入暗号」，沒有微信該如何獲取暗號?

**Comment by qing2002** [comment]
> @necnotdie
> 大佬，脚本有个bug，就是下载一个文件夹中的文件，如果这个文件夹的文件数超过100个，百度默认是加载前100的，这个脚本初始化的时候只能初始化100个文件到fileList里面，所以如果下载100个之后的文件，就会在fileList中找不到对应文件，就会提示“未选中文件，请勿勾选文件夹，否则刷新后重试！”，实际上文件是勾过的。

我跟你一样遇到同样的问题 不知道如何解决

**Comment by JYeung111** [comment]
@necnotdie
@qing2002 
以我所知，百度可以處文件數的上限是 100 就篁自行收集超過一百都無效用，因這是百度的限制，就像打包不能超過 300MB 一樣。

加果想下過百文件，而總容量又少於300M；
你可一試是將它們保存至一個文件夾内，然後再此文件夾打包式下載！

**Comment by ringfu** [comment]
安装了百度网盘直链下载助手和百度网盘万能助手以后还是不能获取aric链接，怎么解决

**Comment by Hafeez-zhf3536** [comment]
你好，下载助手里面没有免登录链接啊

**Comment by Dominic-Shawn** [comment]
请问一体，使用idm批量下载的时候文件类型是error是什么问题呢

**Comment by digitalhouse** [comment]
Unchecked runtime.lastError: Invalid header specification '{"name":"Access-Control-Allow-Origin"}'.
內容
html/background.html
堆疊追蹤
html/background.html:0 (匿名函式)

**Comment by Fatefulness** [comment]
用IDM显示无权限，用Xdown下载异常

**Comment by thtznet** [comment]
启用了百度网盘万能助手，pan.baidu.com 内容不显示，全部消失了，Firefox浏览器插件

**Comment by maruasuka** [comment]
请问不用微信的人该怎么办

**Comment by K37Gem** [comment]
谷歌扩展程序里显示未封装是不是就用不了

**Comment by 18983228883** [comment]
IDM粘贴链接进去 文件类型 Eroor

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)

**Comment by lvziqiaozilv** [comment]
请问有一些文件云盘 不允许分享，有什么办法吗？

**Comment by poxiaozhiguang** [comment]
> @thtznet
> 启用了百度网盘万能助手，pan.baidu.com 内容不显示，全部消失了，Firefox浏览器插件

好像我也遇到了这个情况，不知道百度是识别了油猴还是这个下载助手，看不见百度网盘内的文件

**Comment by freshwind68** [comment]
在360极速浏览器和360安全浏览器安装了“百度网盘万能助手v2.1.0”这个插件之后，今天（10月13号）打不开百度搜索的网站了，一点击百度搜索后弹出的网页一直在反复刷新，禁用“百度网盘万能助手v2.1.0”这个插件就能正常打开百度的网站，只不过会弹出一个证书风险的警告。不知道百度证书风险、百度网盘万能助手之间有什么冲突，望大神排查一下

**Comment by jgx91** [comment]
我想知道能不能直接用http://aria2c.com这个webui下载，我试了下，总是提示请求头错误

**Comment by JYeung111** [comment]
aria webui 是需要配搭 已啟動RPC 功能的Aria server 才能正常使用！
而 xdown  是Aria server但不支援RPC 功能 的！
用 webui 下載百度鏈是需要提供合適的cookie(有些下載鏈是不需要) 和 useragent！
useragent 是可以在 Aria config file 預設，節省麻煩！
因此這環境下，外鏈和免登離線分析提供的下載鏈是可以直用。

**Comment by rilegoule** [comment]
在线解析错误提示：下载失败,怎么搞

**Comment by rilegoule** [comment]
在线解析错误提示：下载失败,怎么搞

**Comment by JYeung111** [comment]
剛測試完，無發現任何問題，可以用！
請提供該百度分享鏈！

**Comment by rilegoule** [comment]
pan.baidu.com/s/13aXGnDMN5UPA35IvcbSz4w

发件人: JYeung111
发送时间: 2019年10月16日 18:27
收件人: syhyz1990/baiduyun
抄送: rilegoule; Comment
主题: Re: [syhyz1990/baiduyun] 常见问题 | 百度网盘直链下载助手 (#270)

剛測試完，無發現任何問題，可以用！
請提供該百度分享鏈！

**Comment by jgx91** [comment]
成功实现web UI 下载， 复制连接后请求头填入useragent回车后再填入cookie就可以下载了，但是好像同时只能下载一个链接，这又是为什么

**Comment by JYeung111** [comment]
@rilegoule 
在线解析错误提示：下载失败,怎么搞
原因是"在线解析" 在有些缺失，如分享鏈是需輸入提取碼，就會有機會出現這反應。
如遇到這問題，只要將目標轉自己盤再分享(要無提取碼)，再用在线解析，
好似腳本己有這功能，叫 "一键保存"


 rilegoule ycns

**Comment by Xforcen** [comment]
大佬的官网是不是失效了？打不开。而且最新版脚本也失效了，不显示“下载助手”按钮

**Comment by 631464904** [comment]
直链在线解析：进入解析结果界面之后,解析的文件会分页显示。但当我选择第二页的文件夹demo进入时,显示的是文件夹demo分页的第二页内容,而不是首页，如果我文件夹demo分页后结果的第二页没有文件，就会显示暂无数据。其实以上原因也和解析后的结果可以一直往后翻页有关。

**Comment by othpark** [comment]
服务器响应显示您没有权限下载此文件

**Comment by rilegoule** [comment]
> @othpark
> 服务器响应显示您没有权限下载此文件

我也是这样

**Comment by lvziqiaozilv** [comment]
今天提取的链接无法用IDM和XDown下载了

**Comment by Optimus7845878** [comment]
IDM、Xdown、MiniGet全部都凉了，都无法下载

**Comment by JaminZhang** [comment]
The response status is not successful. status=403  
任务状态: 发生错误 (22)  
错误描述: HTTP 返回头无效或无法识别.

凉了？

**Comment by shadowdragon1123** [comment]
> @Optimus7845878
> IDM、Xdown、MiniGet全部都凉了，都无法下载

MiniGet也是下载HTTP链接的？那就是和IDM作用一样咯，链接现在无法下载，换下载软件无济于事啊

**Comment by pleasecall** [comment]
今天我用idm，xdown也下不了百度云链接

**Comment by soloveyoy** [comment]
API下載跟直連下載的
顯示連結，能新增複製全部連結嗎？

**Comment by wbsu2003** [comment]
在线解析完成后的地址，富之岛XDown中下载直接显示“异常”

**Comment by Hugo342523** [comment]
“百度网盘直链下载助手”是不是全线凉了？还有能用的客官吗？

**Comment by YQ-China** [comment]
在线解析百度云文件的下载链接无法用xDown下载

**Comment by wp7031** [comment]
xdown下载显示异常

**Comment by Samsalee** [comment]
xDOWN下载显示异常怎么回事

**Comment by wp7031** [comment]
直链助手版本2.9.2，Xdown版本1.0.0.8，正常操作，但是Xdown上速度0，状态显示异常。
是不是账号被封或者IP被封了

**Comment by wp7031** [comment]
刚才又测试了一下，换一个账号可以下载了，估计是账号被封了
之前有用Xdown下过单文件2G的资源，下到1G左右出现异常，可能是百度检测到三方工具了

**Comment by shadowdragon1123** [comment]
> @wp7031
> 刚才又测试了一下，换一个账号可以下载了，估计是账号被封了
> 之前有用Xdown下过单文件2G的资源，下到1G左右出现异常，可能是百度检测到三方工具了
> 
> 
xdown换一个账号？怎么换？

**Comment by feng0824** [comment]
服务器响应显示您没有权限下载此文件。
备注：
HTTP/1.1 403 Forbidden

**Comment by feng0824** [comment]
xdm和idm都无法下载

**Comment by Martrax** [comment]
安装完之后提示“由贵单位管理”什么情况？

**Comment by Martrax** [comment]
> @Samsalee
> xDOWN下载显示异常怎么回事

也是一样，显示异常，主要的是谷歌浏览器菜单多了个“由贵单位管理”选项

**Comment by kairyfor** [comment]
上周通过“分享后下载”--打开--显示直连，复制链接到IDM中还可以下载，今天不行了，到idm中提示的错误，文件名显示不出来，是一串字符，下载不了，；
如果采用免登录下载会要求输入提取码，而提取码在分享时并没有显示出来，也找不到，

**Comment by iuyfguyij** [comment]
使用xdown下载了一段时间后就会报告“下载异常”，会下降到极慢的速度

**Comment by hibernation404** [comment]
助手启用后浏览百度的搜索页面会无限重定向

**Comment by whh03** [comment]
服务器响应显示您没有权限下载此文件。
备注：
HTTP/1.1 403 Forbidden

**Comment by whh03** [comment]
IDM:
服务器响应显示您没有权限下载此文件。
备注：
HTTP/1.1 403 Forbidden

**Comment by RUILIOIJ** [comment]
嗨，现在的似乎已经没法用IDM批量下载了，多选之后，点击‘直接下载’显示“多个文件请点击显示链接”。

**Comment by sunpeijie0** [comment]
SSL/TLS handshake failure: SSL I/O error

**Comment by hao0606** [comment]
网盘万能助手被chrome强制关闭，且无法打开，求解决办法

**Comment by dreamchaser123** [comment]
用Aria链接总是提示先安装网盘助手怎么回事

**Comment by dreamchaser123** [comment]
用Aria链接总是提示先安装网盘助手怎么回事

**Comment by wiixiiidi** [comment]
怎么现在下载东西异常了

**Comment by BaMYoo** [comment]
更新 网盘万能助手 2.2.1插件后，百度网盘上传按钮无法使用，鼠标移动到上传按钮后不在弹出上传文件菜单，关闭插件后上传按钮恢复正常。

**Comment by iuyfguyij** [comment]
最近用Aria获取链接进行下载会“下载异常”了

**Comment by XiaoChunGYC** [comment]
为什么Kiwi浏览器在油猴里装了脚本就删除不了呢，点删除按钮没反应得

**Comment by XiaoChunGYC** [comment]
Kiwi浏览器在暴力猴里，有的脚本装起，但是没起到作用，为什么呢？

**Comment by Sharkkie** [comment]
求助：Firefox 71.0，OSX 10.14.6，只要启用万能助手插件，百度网盘页面就不显示内容

**Comment by wzcbdxhyddwa** [comment]
你好，版本都是最新的，但是用xdown下载的时候，下载状态时异常，什么也下不了

**Comment by boyoungzheng** [comment]
mac下显示API下载显示了链接，但是单击和复制到neat download manager无效。Aria下载提示请先安装【网盘万能助手】
---
OS: macOS Catalina 10.15.2
Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
Tempermonkey: v4.9
百度网盘直链下载助手: 2.9.8
NeatDownloadManager: 1.1
NeatDonwloadManager Extension: 1.3.0

**Comment by boyoungzheng** [comment]
我的问题解决了
在API链接显示后右键用neat download manager下载。但是只能用2线程下载

**Comment by JDsilent** [comment]
此版本的IDM不支持该类下载，请尝试将IDM更新至最新版本
about:black#blocked

**Comment by Andrew-Hum** [comment]
我用aria RPC方法的时候 我启动了http://localhost:8086 然后我点击完发送到aira的时候会显示发送成功  但是回到http://localhost:8086就直接停止下载了显示http返回头无效或无法识别  这种情况怎么办

**Comment by c1023465811** [comment]
下载文件的时候 除了小到能够直接下载的以外，其他的文件在下载时都会出现连接失败而无法下载的情况

**Comment by juki75** [comment]
用IDM下载，是不是有次数限制？

**Comment by juki75** [comment]
最近用IDM下载时，速度大不如从前了，只有几百k，不知道是什么原因？

**Comment by developerZGJ** [comment]
> 最近用IDM下载时，速度大不如从前了，只有几百k，不知道是什么原因？

我也是，我一直以为是升级Catalina导致的

**Comment by Avalon-Saber** [comment]
你好，我想问一下楼主提供的网盘里的idm的安装包是破解过的还是官方原版的

**Comment by ttxz** [comment]
你好，我将插件装到谷歌浏览器中，一段时间后，就会被删除，然而也没有任何提示，也不知道是杀毒软件的问题还是其他什么问题？

**Comment by fskdj** [comment]
关闭了idm浏览器插件就没法下载文件了，但是常见问题里（使用IDM下载出现下图如何处理？）的处理方法就是如此解决，该怎么办

**Comment by xioi** [comment]
### 把神秘代码没输完，结果现在百度网盘直接不显示了怎么办。。。
