### ISSUE TITLE
无论用什么方式都是:获取下载链接失败 请刷新网页后重试

### ISSUE THREAD

**Issue by ghost** [syhyz1990/baiduyun#272]
![QQ截图20231106115114](https://github.com/syhyz1990/baiduyun/assets/113178566/32765bcf-cccd-43e0-8d9c-f6b0968c38e9)

**Comment by QuLtum** [comment]
我也有这种问题

**Comment by ErlkingHub** [comment]
附议

**Comment by StarCollector1** [comment]
待续
