### ISSUE TITLE
我觉得免登陆链接不需要退出登录

### ISSUE THREAD

**Issue by mofadeyunduo** [syhyz1990/baiduyun#273]
登录链接和免登陆链接的区别仅仅在于 bdstoken 是否为 null，访问时候直接把 bdstoken 设置成 null 就可以，和百度的 cookie 无关（除了 BDCLND，但无论登录和免登陆链接 BDCLND 都是存在的）

**Comment by syhyz1990** [comment]
新版已经去掉了 , 感谢反馈
