### ISSUE TITLE
> @Aho-Sakura

### ISSUE THREAD

**Issue by sc1066** [syhyz1990/baiduyun#276]
> @Aho-Sakura
> 请问有没有回退到2.8.0版本的方法，我要下载文件夹，可是2.8.1无法直接下载文件夹

可以安装这个版本 https://www.baiduyun.wiki/install-alpha.html

_Originally posted by @syhyz1990 in https://github.com/syhyz1990/baiduyun/issues/271#issuecomment-532615530_

谢谢，不过这个还是没有下载助手这个选项，有老版本的吗

**Comment by syhyz1990** [comment]
发下你控制台的代码

**Comment by sc1066** [comment]
### ****发不了图啊，我按f12 也看不懂··

-

**Comment by sc1066** [comment]
Uncaught SyntaxError: Unexpected identifier
    at a (<anonymous>:3:28764)
    at Object.post (<anonymous>:3:28983)
    at t (<anonymous>:3:20313)
    at o (<anonymous>:3:20378)
    at LoadScripts (<anonymous>:3:20779)
    at r (<anonymous>:3:14253)
    at HTMLDocument.<anonymous> (<anonymous>:3:28961)
    at a (<anonymous>:3:28764)
    at Object.post (<anonymous>:3:28983)
    at t.default (<anonymous>:3:19513)
boot.js?t=1568099843086:1 Service worker active
/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-sharelinkpic&list%5B0%5D%5Bw%5D=200&list%5B0%5D%5Bh%5D=200&list%5B1%5D%5Bid%5D=web-sharemultibanner&list%5B1%5D%5Bw%5D=960&list%5B1%5D%5Bh%5D=60&list%5B2%5D%5Bid%5D=web-sharelinkrepeat&list%5B2%5D%5Bw%5D=1&list%5B2%5D%5Bh%5D=1&uk=791392859&channel=chunlei&web=1&app_id=250528&bdstoken=82a994e51841f676005cf56d7aa653dc&logid=MTU2ODgwNTU4MTAxMjAuNzQ2MDg4OTA1MjAzNTEwNQ==&clienttype=0 Failed to load resource: net::ERR_CANCELED_BY_ABP
/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-sharelinkpic&list%5B0%5D%5Bw%5D=200&list%5B0%5D%5Bh%5D=200&list%5B1%5D%5Bid%5D=web-sharemultibanner&list%5B1%5D%5Bw%5D=960&list%5B1%5D%5Bh%5D=60&list%5B2%5D%5Bid%5D=web-sharelinkrepeat&list%5B2%5D%5Bw%5D=1&list%5B2%5D%5Bh%5D=1&uk=791392859&channel=chunlei&web=1&app_id=250528&bdstoken=82a994e51841f676005cf56d7aa653dc&logid=MTU2ODgwNTU4MTA4NDAuNzc5MDU4NDg1NzcwNzQ3Nw==&clienttype=0 Failed to load resource: net::ERR_CANCELED_BY_ABP
/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-text&list%5B0%5D%5Bw%5D=0&list%5B0%5D%5Bh%5D=0&uk=791392859&channel=chunlei&web=1&app_id=250528&bdstoken=82a994e51841f676005cf56d7aa653dc&logid=MTU2ODgwNTU4MTQ2MDAuMTM1ODM1MTc3NDQzNDMyNTQ=&clienttype=0 Failed to load resource: net::ERR_CANCELED_BY_ABP
monitor.jpg Failed to load resource: net::ERR_NAME_NOT_RESOLVED
(unknown) https://pan.baidu.com/s/1jKck4wY#list/path=%2Fsharelink441350688-1035546124944647%2Fwindows7&parentPath=%2Fsharelink441350688-1035546124944647

**Comment by syhyz1990** [comment]
看这个发图 https://github.com/syhyz1990/baiduyun/issues/271#issuecomment-530751909

**Comment by sc1066** [comment]
https://i.loli.net/2019/09/18/Q1Ci7tWeVaJsK9p.jpg
https://i.loli.net/2019/09/18/oOWQV7RYcXDt2sP.jpg

**Comment by syhyz1990** [comment]
![image](https://user-images.githubusercontent.com/5344173/65145082-4534c780-da4b-11e9-90da-58f195f1092b.png)

这俩禁用  , 删除原来的脚本 , 从这里安装 https://www.baiduyun.wiki/install.html

**Comment by sc1066** [comment]
还是不行，我估计只有老版本可用了

**Comment by syhyz1990** [comment]
好吧，关帖了
