### ISSUE TITLE
希望能支持基于 aria2 的开源跨平台下载工具 Motrix 

### ISSUE THREAD

**Issue by lvii** [syhyz1990/baiduyun#277]
[Motrix](https://github.com/agalwood/Motrix) 是一个跨平台的基于 aria2 的下载工具。算是 MacOS 比较好用的 _开源_ 下载工具了，但 Motrix 只有一个基于开源的 **Chrome 浏览器扩展** [BaiduExporter](https://github.com/agalwood/BaiduExporter) 构建（附：[原版 github 仓库地址](https://github.com/acgotaku/BaiduExporter)），添加了 Motrix 相关的配置，下载地址如下：[https://motrix.app/release/BaiduExporter.zip](https://motrix.app/release/BaiduExporter.zip)

![](https://cdn.nlark.com/yuque/0/2018/png/129147/1543747149902-cc28bb15-b26f-4293-92e8-a302031c38db.png?x-oss-process=image/resize,w_719)

仅有 chrome 浏览的扩展，不能像 **百度网盘直链下载助手** 这样跨浏览器的 _**油猴脚本**_

火狐用户就比较悲摧了

希望能增加对 Motrix 工具的支持，这样可以方便多个平台下使用 Motrix 的用户

感谢！

**Comment by gqbre** [comment]
这个要支持 Motrix 强强联手
