### ISSUE TITLE
百度网盘万能助手 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#279]
https://www.baiduyun.wiki/zh-cn/assistant.html#%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by 199654kid** [comment]
每次打开页面这个软件总是弹出让去更新的页面，然后明明更新了，还是弹出来。

**Comment by Designning5** [comment]
b站打开视频会提示更新这个，明明更新了还是弹出更新界面，怎么解决

**Comment by Designning5** [comment]
> 每次打开页面这个软件总是弹出让去更新的页面，然后明明更新了，还是弹出来。

你解决了这个问题吗

**Comment by HZRUI3** [comment]
该扩展程序未列在 Chrome 网上应用店中,并可能是在您不知情的情况下添加的。这个怎么解决？？

**Comment by YYQcoma** [comment]
> @HZRUI3
> 该扩展程序未列在 Chrome 网上应用店中,并可能是在您不知情的情况下添加的。这个怎么解决？？

https://jingyan.baidu.com/article/ceb9fb108bad968cad2ba0f0.html

**Comment by a364680532** [comment]
更新了打开网页还一直提示更新，我TM卸载了还提示。

**Comment by dis-xcl** [comment]
老是提示更新，更新完了还让更新，没完没了的

**Comment by 1015127214** [comment]
为什么这个插件不能下载啊？

**Comment by JJUMPING** [comment]
下载地址怎么都是同一个 crx文件没办法保存到本地啊  直接识别失败了

**Comment by syhyz1990** [comment]
> @JJUMPING
> 下载地址怎么都是同一个 crx文件没办法保存到本地啊  直接识别失败了

使用ie浏览器下载试下 , 360系列浏览器下载后自动安装

**Comment by LeeHAO-arch** [comment]
我安装了百度网盘万能助手，并且加入了拓展，为什么点显示连接的时候还是要我安装，我自己也重启浏览器很多次了

**Comment by Leojc** [comment]
百度网盘万能助手2.0.0 开启时导致YouTube界面异常

**Comment by syhyz1990** [comment]
点击助手图标  [已为此域启用]-> 关闭




------------------ 原始邮件 ------------------
发件人: "Liao junchao"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 晚上6:04
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "【暗~@_@~】"<syhyz1990@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] 百度网盘万能助手 | 百度网盘直链下载助手 (#279)




百度网盘万能助手2.0.0 开启时导致YouTube界面异常

**Comment by Leojc** [comment]
> 
> 点击助手图标 [已为此域启用]-> 关闭
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Liao junchao"<notifications@github.com>; 发送时间: 2019年9月24日(星期二) 晚上6:04 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>; 抄送: "【暗~@_@~】"<syhyz1990@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [syhyz1990/baiduyun] 百度网盘万能助手 | 百度网盘直链下载助手 (#279) 百度网盘万能助手2.0.0 开启时导致YouTube界面异常 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

多谢~解决了！ 我还以为这个插件只对pan.baidu.com域名生效呢。

**Comment by myl86898244** [comment]
谷歌浏览器无法启用 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by Suli-sparks** [comment]
打开b站视频总提示更新 已经都卸载了还是提示   这怎么处理  真的很烦

**Comment by ShuiTunGao** [comment]
万能助手启用了  百度还是弹出来 安装

**Comment by imoutodaisuki** [comment]
根本启用不了,行不行啊

**Comment by syhyz1990** [comment]
把懒人脚本禁用



---原始邮件---
发件人: "Sparks"<notifications@github.com&gt;
发送时间: 2019年9月25日(星期三) 下午2:02
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"iPc"<syhyz1990@qq.com&gt;;
主题: Re: [syhyz1990/baiduyun] 百度网盘万能助手 | 百度网盘直链下载助手 (#279)



打开b站视频总提示更新 已经都卸载了还是提示   这怎么处理  真的很烦

**Comment by aifans** [comment]
1 下载crx
2 改名zip，解压，得到文件夹
3 chrome扩展管理中，打开开发者选项。
4 加载已解压的扩展，选择文件夹
5 ok

**Comment by YanceyChiew** [comment]
之前明明不需要安插件就能复制aria2链接的，现在更新后却必须要了，很难让人相信这是技术上的必要而非经营上的需要。还有那个免登录链接没了，一键保存后下载完全没用，现在只能进自己手动保存后的目录用api直链下载，也就是破除了大小限制，速度是没变的。

**Comment by shadowdragon1123** [comment]
> @YanceyChiew
> 之前明明不需要安插件就能复制aria2链接的，现在更新后却必须要了，很难让人相信这是技术上的必要而非经营上的需要。还有那个免登录链接没了，一键保存后下载完全没用，现在只能进自己手动保存后的目录用api直链下载，也就是破除了大小限制，速度是没变的。

免登录链接没了不是大问题，之前改成不限速链接能用的。问题是昨天开始点显示直链和aria2 IDM和XDOWN都下载失败，不限速链接来回重复要求验证码但是不给链接，现在更新脚本之后的一键保存后下载点了只建立文件夹，不下载

**Comment by shadowdragon1123** [comment]
现在更新2.8.4脚本之后在分享链接页面选择一键保存后下载点了只建立文件夹，不下载，我度盘里一键显示建立5.6个文件夹也没反应

**Comment by assoyuan** [comment]
1.  如何设置只对`xxx://pan.baidu.com/xxx`？

**Comment by shadowdragon1123** [comment]
> @assoyuan
> 1.  如何设置只对`xxx://pan.baidu.com/xxx`生效？这个助手对我所有网站都有影响，会导致我打开或者关闭页签操作响应比较慢
> 答：在扩展程序->百度网盘助手->有权访问的网站->在特定网站上，加上指定域名，就会只在指定域名上生效，其他域名需要点击生效
> 2. 这个助手会使google的搜索框input向止偏移37px

我也是 google搜索框向上移动了

**Comment by joshatt** [comment]
能登录但安装后扩展图标是灰色的, 不能用

**Comment by Bernard-1993** [comment]
> @joshatt
> 安装后扩展图标是灰色的, 不能用

打开拓展程序管理界面（浏览器栏输入chrome://extensions/）看看是不是没启用，如果异常原因是“该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的”，把拓展程序卸载掉，然后使用以下方法安装：
1.首先把需要安装的第三方插件，后缀.crx 改成 .rar；
2.然后解压，得到一个文件夹
3.再拓展程序管理界面点击“加载已解压的扩展程序”，选择步骤2得到的文件夹，成功安装，你会发现拓展程序的开关打开了

**Comment by Bernard-1993** [comment]
> @myl86898244
> 谷歌浏览器无法启用 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。 

把拓展程序卸载掉，然后使用以下方法安装：
1.首先把需要安装的第三方插件，后缀.crx 改成 .rar；
2.然后解压，得到一个文件夹
3.再拓展程序管理界面点击“加载已解压的扩展程序”，选择步骤2得到的文件夹，成功安装，你会发现拓展程序的开关打开了

**Comment by Poocea** [comment]
- 每次浏览器重启都提示“请停用以开发者模式运行的扩展程序”！
- 怎么回事啊？

**Comment by joshatt** [comment]
> > @joshatt
> > 安装后扩展图标是灰色的, 不能用
> 
> 打开拓展程序管理界面（浏览器栏输入chrome://extensions/）看看是不是没启用，如果异常原因是“该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的”，把拓展程序卸载掉，然后使用以下方法安装：
> 1.首先把需要安装的第三方插件，后缀.crx 改成 .rar；
> 2.然后解压，得到一个文件夹
> 3.再拓展程序管理界面点击“加载已解压的扩展程序”，选择步骤2得到的文件夹，成功安装，你会发现拓展程序的开关打开了

谢谢. 试了, 还是一样. 发现扩展管理中, 该扩展图标右下角有个红色小标, 象个相机或微波炉, 悬停显示"未封装的控制程序"

**Comment by brnznf** [comment]
百度网盘万能助手的Chorme商店地址跳转到直链助手的安装地址？

**Comment by 5632515** [comment]
IDM依旧403

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)

**Comment by infoma990** [comment]
win10，系统自带杀毒软件，网盘助手无法下载。下载立即就遭删除。

**Comment by onlysamuel** [comment]
Baidu Cloud Assistant

Size: < 1 MBSize< 1 MBVersion: 2 . 2 . 1Version2.2.1

This extension is not from any known source, and may have been added without your knowledge.

**Comment by hellguard0** [comment]
IDM 有时能下载有时不能，或者下载一半出现问题要求登录账号密码

**Comment by xxjp999** [comment]
装了还是没有aira2的选项啊

**Comment by hellguard0** [comment]
> 装了还是没有aira2的选项啊

我的装了还是有的，就是Aria2发送过去时，它无法下载，一直显示下载失败。你可以尝试删除助手后再装过.我的IDM时灵时不灵。。。

**Comment by Simon-clound** [comment]
FireFOX打开插件后网盘页面就不能显示

**Comment by Xiehejia** [comment]
Firefox启用网盘万能助手2.3的附加组件就无法正常使用 哔哩哔哩 ，会出现已拦截跨源请求：同源策略禁止读取位于 ‘https://cm.bilibili.com/cm/api/receive/content/pc’ 的远程资源。（原因：凭据不支持，如果 CORS 头 ‘Access-Control-Allow-Origin’ 为 ‘*’）。这种信息，同时无法观看任何视频，关闭附加组件的网盘万能助手则恢复正常

**Comment by huxubo** [comment]
请问 2.3.0的下载链接在哪里

**Comment by kalinshakalin** [comment]
该扩展程序未列在 Chrome 网上应用店中,并可能是在您不知情的情况下添加的。这个怎么解决？？

**Comment by kalinshakalin** [comment]
懒人版，登陆后，直接下载还是不能用

**Comment by liugcc** [comment]
我用的是2.3.1 我下载完成了 同时下载了aria    和xdown 下载文件时 也把前缀去了为什么就是下载不成功呢aria（403）xdown（异常）

**Comment by liugcc** [comment]
之前用xdown成功了一个但下载一半就不行了以后连下载都下载不了

**Comment by 97Yates05** [comment]
motrix无法下载，这东西确定能用吗

**Comment by 97Yates05** [comment]
太麻烦了，mac上还不好使，还是买账号吧

**Comment by iuyfguyij** [comment]
请问能否更换一个，或者多提供一个下载助手扩展的下载渠道，现在城通网盘已经不提供免费用户的客户端下载了

**Comment by bb107** [comment]
> @Designning5
> > 每次打开页面这个软件总是弹出让去更新的页面，然后明明更新了，还是弹出来。
> 
> 你解决了这个问题吗

1) download Chrome group policy templates here: http://dl.google.com/dl/edgedl/chrome/policy/policy_templates.zip
2) Copy [zip]\windows\chrome.admx to c:\windows\policydefinitions
3) Copy [zip]\windows\[yourlanguage]\chrome.adml to c:\windows\policydefinitions\[yourlanguage]\chrome.adml (not c:\windows\[yourlanguage])
4) In Chrome, go to Settings -> Extensions
5) Check the Developer Mode checkbox at the top
6) Scroll down the list of disabled extensions and note the ID's of the extensions you want to enable.  LogMeIn, for example, is ID: nmgnihglilniboicepgjclfiageofdfj
7) Click Start -> Run, and type gpedit.msc
8) Expand User Configuration -> Administrative Templates -> Google -> Google Chrome -> Extensions
9) Double-click to open "Configure extension installation whitelist"
10) Select "Enabled", then click "Show..."
11) In the list, enter all the ID's for the extensions you noted in Step 6
12) Click OK and restart Chrome.

**Comment by ajibayi** [comment]
明明我安装好了网盘万能助手但是提示 请先安装 网盘万能助手

**Comment by kruezhev** [comment]
这个城通网盘把我恶心坏了，怎么下载啊

**Comment by burn1ngsun** [comment]
> @iuyfguyij
> 请问能否更换一个，或者多提供一个下载助手扩展的下载渠道，现在城通网盘已经不提供免费用户的客户端下载了

+1

**Comment by SeemWind** [comment]
> @burn1ngsun
> > @iuyfguyij
> > 请问能否更换一个，或者多提供一个下载助手扩展的下载渠道，现在城通网盘已经不提供免费用户的客户端下载了
> 
> +1

+1

**Comment by gundamfenglai** [comment]
360极速我拖进 直接现实无效程序包啊！！！求助啊！！QQ59343160
