### ISSUE TITLE
收不到开源协议

### ISSUE THREAD

**Issue by snake94115** [syhyz1990/baiduyun#279]
收不到开源协议，发微信收不到码

**Comment by pocsan** [comment]
and you

**Comment by yiBF** [comment]
+1

**Comment by Yume-Hatsuyuki** [comment]
查找该方法，修改如下即可

        async initDialog() {
            let result = await Swal.fire({
                title: pan.init[0],
                html: `<div><img style="width: 250px;margin-bottom: 10px;" src="${pan.img}" alt="${pan.img}"><input class="swal2-input" id="init" type="text" placeholder="${pan.init[1]}"></div>`,
                allowOutsideClick: false,
                showCloseButton: true,
                confirmButtonText: '确定 - 验证码为：' + pan.num
            });
            if (result.isDismissed && result.dismiss === 'close') return;
            if (pan.num === $('#init').val() || pan.license === $('#init').val()) {
                base.setValue('setting_init_code', pan.num);
                base.setValue('license', pan.license);
                message.success(pan.init[2]);
                setTimeout(() => {
                    history.go(0);
                }, 1500);
            } else {
                await Swal.fire({
                    title: pan.init[3],
                    text: pan.init[4],
                    confirmButtonText: '重新输入',
                    imageUrl: pan.img,
                });
                await this.initDialog();
            }
        },
    };

**Comment by syhyz1990** [comment]
已修复
