### ISSUE TITLE
为何需要“暗号”？

### ISSUE THREAD

**Issue by ipcjs** [syhyz1990/baiduyun#28]

**Comment by syhyz1990** [comment]
我想要的想做的
你比谁都了
你想说的想给的
我全都知道
未接来电没留言
一定是你孤单的想念
任何人都猜不到
这是我们的暗号
他们猜随便猜不重要
连上彼此的讯号
才有个依靠
有太多人太多事
夹在我们之间咆哮
杂讯太多讯号弱
就连风吹都要干扰
可是你不想
一直走在黑暗地下道
想吹风想自由
想要一起手牵手
去看海绕世界流浪
我害怕你心碎
没人帮你擦眼泪
别管那是非
只要我们感觉对
我害怕你心碎
没人帮你擦眼泪
别离开身边
拥有你我的世界才能完美
他们猜随便猜不重要
连上彼此的讯号
才有个依靠
有太多人太多事
夹在我们之间咆哮
杂讯太多讯号弱
就连风吹都要干扰
可是你不想
一直走在黑暗地下道
想吹风想自由
想要一起手牵手
去看海绕世界流浪
我害怕你心碎
没人帮你擦眼泪
别管那是非
只要我们感觉对
我害怕你心碎
没人帮你擦眼泪
别离开身边
拥有你我的世界才能完美
你说你想逃开松手
爱太累爱得不自由
因为我给不起最简单的承诺
你停止收讯号
我开始搜寻不到
到底有谁知道
是几点钟方向
你才会收到暗号
我害怕你心碎
没人帮你擦眼泪
别管那是非
只要我们感觉对
我害怕你心碎
没人帮你擦眼泪
别离开身边
拥有你我的世界才能完美
我害怕你心碎
没人帮你擦眼泪
别离开身边
拥有你才能完美
我害怕你心碎
没人帮你擦眼泪
别管那是非
只要我们感觉对
我害怕你心碎
没人帮你擦眼泪
别离开身边
拥有你才能完美
我害怕你心碎
没人帮你擦眼泪
别管那是非
只要我们感觉对
