### ISSUE TITLE
Mac Neat Download Manager下载403

### ISSUE THREAD

**Issue by xiebruce** [syhyz1990/baiduyun#281]
Mac无法自动调起Neat Download Manager(chrome浏览器已安装Neat Download Manager插件)，所以我是点`直链下载`→`显示链接`：
![image](https://user-images.githubusercontent.com/13575500/65382783-93ddac80-dd3e-11e9-87f0-cee441090b48.png)

然后到Neat Download Manager中点`New URL`手动下载，但是下载报错：
![image](https://user-images.githubusercontent.com/13575500/65382776-7c9ebf00-dd3e-11e9-9367-ee2841a66e36.png)

Chrome浏览器版本：`Version 77.0.3865.90 (Official Build) (64-bit)`

**Comment by AlexLL55** [comment]
之前遇到过类似的问题，请尝试从NeatDM退出Total_Quit，然后重新启动它，这样它将被自动吊销。

**Comment by xiebruce** [comment]
@AlexLL55 没用呀，我退出了，再启动，下载还是403呀

**Comment by draculapile** [comment]
有一个曲线救国的方法是，点分享后下载，然后打开分享的页面，在那边获取直链，就可以在 NDM 里下载了

**Comment by xiebruce** [comment]
@draculapile 试了一下，这个方法确实有效

**Comment by kinsen** [comment]
@draculapile 分享后直链接，出现timeout，
{
  "error_code": 31360,
  "error_msg": "expire time out error",
  "request_id": 6201377911299869981
}

这个问题你们有出现过吗？

**Comment by Croc-ye** [comment]
我也 403 了，不太行

**Comment by iBotasky** [comment]
同样的问题~，分享链接可以吗？

**Comment by xiebruce** [comment]
@iBotasky 分享的链接是可以的，我试了

**Comment by iBotasky** [comment]
@xiebruce 额，具体的方法是啥啊？我这边只有一个分享，没有分享后下载的按钮啊？

**Comment by xiebruce** [comment]
@iBotasky 哎，我也不知道怎么回事，前两天用分享链接还下载了几部电影，现在试就不行了，不知道哪出的问题

**Comment by draculapile** [comment]
> @iBotasky 哎，我也不知道怎么回事，前两天用分享链接还下载了几部电影，现在试就不行了，不知道哪出的问题

好像分享这种方式挂了。。。分享过后说自己分享的链接请去自己网盘下载。。。

**Comment by iBotasky** [comment]
坑爹啊，我上周都还正常，BD真的是臭不要脸了~

**Comment by xiebruce** [comment]
@draculapile 对对对，我就说嘛，我之前是可以的，现在就不行了

**Comment by xiebruce** [comment]
@iBotasky @draculapile 
我发现这样就可以下了(不需要分享)，勾选要下载的文件，然后点`下载助手`→`API下载`→`直接下载`就行：
![image](https://user-images.githubusercontent.com/13575500/66103800-5eac4680-e5e9-11e9-9023-cb71a880f334.png)

点了下载后，会弹出这个下载界面：
![image](https://user-images.githubusercontent.com/13575500/66103824-6d92f900-e5e9-11e9-9aae-1074cda173fa.png)

**Comment by AlexLL55** [comment]
我通过支持电子邮件问了这个问题，答案是：
macOS: /Users/Your-User/Application Support/com.NeatDownloadManager/
Windows: c:/Your-User/AppData/Roaming/NeatDM/

每个下载都有一个DownloadID（从1开始，可以在下载的LogFile中找到）和一个名为该ID的文件夹。
完成下载后，将删除所有段文件，仅保留LogFile，如果从内部应用程序中删除下载，则将完全删除相应的文件夹。

**Comment by carlliuxx** [comment]
> 我通过支持电子邮件问了这个问题，答案是：
> macOS: /Users/Your-User/Library/Application Support/com.NeatDownloadManager/
> Windows: c:/Users/Your-User/AppData/Roaming/NeatDM/
> 
> 每个下载都有一个DownloadID（从1开始，可以在下载的LogFile中找到）和一个名为该ID的文件夹。
> 完成下载后，将删除所有段文件，仅保留LogFile，如果从内部应用程序中删除下载，则将完全删除相应的文件夹。

thanks～～～

**Comment by percy097189** [comment]
大佬們，是不是又不能用啦？我用NDM試過樓上的各種方法都跳403

**Comment by baggio10czm** [comment]
很奇怪,昨天可以同时下三个,今天就只能下一个了,还经常报403

**Comment by EricJSanchez** [comment]
macos 无法下载

**Comment by syhyz1990** [comment]
点击链接下载 , 不要用右键扩展
