### ISSUE TITLE
极速下载无法使用

### ISSUE THREAD

**Issue by yongqingxie** [syhyz1990/baiduyun#285]
![TIM截图20190924230609](https://user-images.githubusercontent.com/24885976/65525796-ac0e2100-df22-11e9-85db-769005c12a4c.png)

**Comment by RudeTheJack** [comment]
+1

**Comment by JYeung111** [comment]
@syhyz1990

如果我無看錯，极速下载 (即 免登录下载) 已被百度封殺！
因百度送回dlink 是 null！
{"errno":0,"request_id":428329316435384907,"dlink":null}

希望這是暫時性!!!

**Comment by xdown-org** [comment]
临时可以用 https://www.baiduwp.com/ 解析一下,然后改下 user-agent

**Comment by dis-xcl** [comment]
@xdown-org
已用，无效！
应该是昨天开始百度全面封杀，目前所有第三方下载器和脚本全部无法下载，全部失效
