### ISSUE TITLE
如果你不登录百度是不是下载。

### ISSUE THREAD

**Issue by SingingDalong** [syhyz1990/baiduyun#289]
如果你不登录百度是不是下载。

**Comment by superiver0** [comment]
你说的是：如果你不登录百度网盘是不是就不能下载文件了？好像免登陆下载按钮被取消了。我点击“保存后下载”提示“保存目录不存在，是否先创建该目录？”，我点击“自定义保存路径”显示：“路径设置成功！点击确定后立即生效”然后再点击“保存后下载”还是提示“保存目录不存在，是否先创建该目录？”完全没有办法免登录下载。没有免登陆下载那这个插件岂不是废了？

**Comment by LiuCH4NG** [comment]
我今天重装完系统，用到这个插件以后，有些懵，以前的一键下载去哪里了？
研究了半天，发现需要下载应用程序配合使用，但是依旧不好用。
而Pandownload网页版依旧好用，只能忍痛放弃这个脚本了。
我们使用这个脚本只是下载一些不到1G的小文件而已，宽带跑满一分钟，跑不满三分钟，真不在这点时间。我们只是不想打开百度网盘而已，望开发人员了解
