### ISSUE TITLE
Tips1 是不是已经不适用了？

### ISSUE THREAD

**Issue by pscj** [syhyz1990/baiduyun#29]

**Comment by ChikamaYan** [comment]
如果百度云整改导致不登录账号提取不了直链的话，那脚本基本都没什么意义了，多线程载一次第二次就被ban……难道真的要充会员了吗

**Comment by westCastle** [comment]
今天无论尝试什么方式下载，全都只有几kb~几十kb/s，感觉要崩溃

**Comment by Legend94rz** [comment]
不行就先用PanDownload吧
