### ISSUE TITLE
确认该脚本已失效，脚本死循环

### ISSUE THREAD

**Issue by toddliu1** [syhyz1990/baiduyun#290]
点击“保存后下载” 提示“保存目录不存在，是否先创建该目录？” 点击“自定义保存路径”显示：“路径设置成功！点击确定后立即生效”然后再点击“保存后下载”还是提示“保存目录不存在，是否先创建该目录？”，无法下载，死循环。以前的免登陆极速下载消失了

**Comment by koy1619** [comment]
+1
