### ISSUE TITLE
2.8.4脚本api下载限速 有效，极速下载功能取消，增加免密分享功能

### ISSUE THREAD

**Issue by toddliu1** [syhyz1990/baiduyun#293]
已更新2.8.4脚本，保存后下载功能正常，只能使用api下载，立即下载，测试100k以内速度，限速，Aria下载未测试。

**Comment by bai1999** [comment]
今日使用，发现问题，我在未登录百度云的情况下，选中文件点击极速下载后，要求输入验证码，成功输入点击ok，未出现air链接

**Comment by tianxingtao** [comment]
请问显式链接中的“复制全部链接”取消了是吧？请问有什么功能可以替代呢

**Comment by superiver0** [comment]
> 今日使用，发现问题，我在未登录百度云的情况下，选中文件点击极速下载后，要求输入验证码，成功输入点击ok，未出现air链接

2.8.5未发现“极速下载”，只有“保存后下载”，保存后下载和网盘自带的保存有什么区别？最后同样被拉入黑名单限速。

**Comment by xdown-org** [comment]
免登录利用xdown满速下载百度云教程(0927):

https://dl.xdown.org/mp4/xdown-download-baiduyun.mp4
