### ISSUE TITLE
近期使用Edge浏览器识别不出来按钮了

### ISSUE THREAD

**Issue by SoultionLss** [syhyz1990/baiduyun#294]
使用edge浏览器出现错误了，按钮出不来了，不知道是浏览器更新后还是阿里云盘界面改版后出现了错误

**Comment by onlineage** [comment]
chrome 也不显示了

版本 120.0.6099.110（正式版本） （64 位）

**Comment by YURUNXIANG** [comment]
夸克网盘也无法使用😢
edge版本120.0.2210.91 (正式版本)
