### ISSUE TITLE
6.1.4版本必须是百度网盘会员才能用吗，好像一直不显示下载助手按钮

### ISSUE THREAD

**Issue by Hxy1008** [syhyz1990/baiduyun#295]

**Comment by codeLee5** [comment]
+1

**Comment by WoHal** [comment]
cdn挂了。
@require           https://unpkg.com/jquery@3.6.0/dist/jquery.min.js
@require           https://unpkg.com/sweetalert2@10.16.6/dist/sweetalert2.all.min.js
@require           https://unpkg.com/js-md5@0.7.3/build/md5.min.js

将 `https://unpkg.com` 替换为 `https://cdn.jsdelivr.net/npm`

**Comment by yigexiangjiao** [comment]
// @require           https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js
// @require           https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.all.min.js
// @require           https://cdn.jsdelivr.net/npm/js-md5@0.7.3/build/md5.min.js
替换成这样对吗？
貌似还是不行？

**Comment by SoultionLss** [comment]
替换就能用了，就是那天找不到这个替换的网址

**Comment by yigexiangjiao** [comment]
> 替换就能用了，就是那天找不到这个替换的网址

我这样替换的对吗，我这样替换完之后还是不能用

**Comment by yigexiangjiao** [comment]
> 替换就能用了，就是那天找不到这个替换的网址

噢噢，可以了
