### ISSUE TITLE
现在凉了吗 用不了了

### ISSUE THREAD

**Issue by mofadeyunduo** [syhyz1990/baiduyun#296]

**Comment by superiver0** [comment]
取消免登录下载就是凉凉了。分享页面的保存后下载和网盘自带的保存有什么区别？最后同样被拉入黑名单限速。

**Comment by mofadeyunduo** [comment]
关键是分享下载也下不了...

**Comment by xdown-org** [comment]
免登录利用xdown满速下载百度云教程(0927):

https://dl.xdown.org/mp4/xdown-download-baiduyun.mp4

**Comment by frankandtony** [comment]
> 免登录利用xdown满速下载百度云教程(0927):
> 
> https://dl.xdown.org/mp4/xdown-download-baiduyun.mp4
我有个 10G的文件, 显示大于 4G 就不能下, 这怎么解决, 多谢!

**Comment by tskspree** [comment]
> 免登录利用xdown满速下载百度云教程(0927):
> 
> https://dl.xdown.org/mp4/xdown-download-baiduyun.mp4

有下载次数限制

**Comment by superiver0** [comment]
> 免登录利用xdown满速下载百度云教程(0927):
> 
> https://dl.xdown.org/mp4/xdown-download-baiduyun.mp4

实际上就是PANDOWNLOAD网页版。XDOWN和IDM只是一个下载工具，你这个和这个GITHUB上面的插件已经没有关系了。

**Comment by Porcelana** [comment]
目前版本暂无法使用了，用pandownload的民间脚本凑合，也就是之前极速下载，后来改的直接删掉了这个方法，反而没那么好用 https://greasyfork.org/zh-CN/scripts/383059-pandownload%E7%BD%91%E9%A1%B5%E7%89%88-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E4%B8%8D%E9%99%90%E9%80%9F%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD-jaeger

**Comment by Porcelana** [comment]
现在还有一个凑合的房子，彻底退到v2.5.3，高速下载的选项还在

**Comment by tskspree** [comment]
请问如何找到历史脚本文件？

发自我的 iPhone
