### ISSUE TITLE
xdown设置中填写代理地址后不能保存

### ISSUE THREAD

**Issue by litchen-cz** [syhyz1990/baiduyun#298]
xdown设置中填写代理地址 Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14 ，
点确定，弹出“代理地址不能包含特殊符号”，不能保存啊

**Comment by xdown-org** [comment]
![image](https://user-images.githubusercontent.com/54701467/65818536-d3c3f880-e244-11e9-8c0b-eaa7be5475c6.png)
没有问题.

**Comment by xdown-org** [comment]
代理是你自己的代理服务器地址,可以有,也可以没有.
