### ISSUE TITLE
目前脚本已经失去了存在的意义！

### ISSUE THREAD

**Issue by dis-xcl** [syhyz1990/baiduyun#299]
就事论事，就目前的形式，发表一下个人观点，可能也代表了其他一些人的观点。当前由于百度进一步的封锁措施，本页的脚本已经无法免登录下载。诸如pandownload、速盘等第三方下载器也已经无法下载。大家都使用本页的脚本插件，无非就是为了能有多一种方法来分享下载百度云的资源。目前本页的脚本对于分享链接已经无效了，而保存到自己网盘下载，更会加速百度对账号的限速，无异于自投罗网。因此由于百度的封锁措施，目前使得本页的脚本已经没有存在的意义了。希望这只是目前特殊时期的暂时性情况，更希望脚本作者可以看到此贴，站出来发帖和大家说明一下脚本的情况，免得大家每天都在发帖说不能下载的问题。相信作者可以开发出像之前免登录下载极速链接一样的更好脚本插件，造福于受到百度侵害的网民。

**Comment by vyronjo** [comment]
还是看个人吧，我有充SVIP，一样找第三方来用，只为能跑满带宽，说到底还是官方的客户端太烂

**Comment by 1608637229** [comment]
没办法。作者去掉那些接口是因为百度封杀已经失效了。留着也没用啊，我特意降级到老板试了下。极速下载没反应。
