### ISSUE TITLE
现在脚本能用是能用，但是速度被限制在400K/s了

### ISSUE THREAD

**Issue by Legend94rz** [syhyz1990/baiduyun#3]
IDM 6.30，32个下载线程，速度只有400K。
不是网络问题，望修复

**Comment by swl521** [comment]
退出百度账号就OK了

**Comment by ikely** [comment]
同样的问题，没有登录百度账号，隐身模式，IDM下载速度在400kb/s

**Comment by syhyz1990** [comment]
@ikely 是所有资源还是单个资源

**Comment by ikely** [comment]
@syhyz1990 所有的资源，不同时间段，都是一样。而且百度在2个小时左右就会关闭通道，之前下载一个2.4G的资源，因为上限在400kb/s，速度浮动的情况下，经常2个多小时通道关闭了才下载了95%，于是又得重新下载，反复了5，6次终于才下下来。

**Comment by Legend94rz** [comment]
@ikely 你可以用IDM的“刷新下载链接”功能继续下载。不用从头

**Comment by ikely** [comment]
@Legend94rz 我点恢复下载就直接被弹出失效了，必须重下，下次我试试这个功能。谢谢
