### ISSUE TITLE
IDM下载问题

### ISSUE THREAD

**Issue by LovesAsuna** [syhyz1990/baiduyun#30]
API下载点击无反应的问题能否修复一下？我并不想采用Aria或者RPC进行下载

**Comment by syhyz1990** [comment]
> API下载点击无反应的问题能否修复一下？我并不想采用Aria或者RPC进行下载

更新到5.0版本试下 https://www.baiduyun.wiki/install.html

**Comment by LovesAsuna** [comment]
还是不顶用

**Comment by syhyz1990** [comment]
@LovesAsuna https://www.baiduyun.wiki/zh-cn/idm.html#唤起idm下载 看这里

**Comment by LovesAsuna** [comment]
![error](https://user-images.githubusercontent.com/32810896/110578872-9fc26600-81a0-11eb-85b3-f562cc998a07.gif)

**Comment by syhyz1990** [comment]
是否更新到了最新版本呢？如果不是私密文件，可以分享一个08ms的文件给我，我试下

**Comment by syhyz1990** [comment]
我试了下是可以的，检查下IDM浏览器扩展是否安装了

![image](https://user-images.githubusercontent.com/5344173/110729341-7f0a1700-8259-11eb-86fc-d8cce6dbaa53.png)

**Comment by LovesAsuna** [comment]
当然是安装的了，为了排错我还把扩展卸载重装了。
