### ISSUE TITLE
[置顶]2.8.5 讨论专用贴 , 收集下无法下载的问题

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#300]
关于部分用户无法下载的问题已收到 , 现统计下无法下载用户的用户类型

1. 不是vip
2. 普通vip
3. 超级vip

**Comment by tskspree** [comment]
1

**Comment by 1027431541** [comment]
2.普通vip，可下载，速度仅有500kb/s，并且只能下载一个，同时下载会出现另外链接无法下载情况

**Comment by edison99x** [comment]
1

**Comment by iBotasky** [comment]
1

**Comment by koulamo** [comment]
1

**Comment by DuKanghub** [comment]
1，都没有免登录获取链接了，只有一个“保存后下载”

**Comment by Scared-Heart** [comment]
1

**Comment by thginsk** [comment]
可以提交一个bug吗，使用插件后浏览器标识出现错误，打开google、youtube等网站会显示移动端网页。

**Comment by syhyz1990** [comment]
> 可以提交一个bug吗，使用插件后浏览器标识出现错误，打开google、youtube等网站会显示移动端网页。

更新 万能助手到2.0.2 已经修复该问题  https://www.baiduyun.wiki/download.html

**Comment by huanghe2015** [comment]
置顶应该是“Pinned Issue"，有空可以设置下。

**Comment by huanghe2015** [comment]
我觉得可以参考一下 baiduwp.com 解析出来的HTTP直链格式。同样一个文件，看看本地获取直链和网站获取的直链有什么相似之处，相似就按网站解析的URL改写再复制出来，这样可以保证直链的足够稳定。

**Comment by 1iver** [comment]
更新2.8.5,IDM下载连接数只有一个了,天天更新真是迷,就是这结果?

**Comment by hqiwen** [comment]
1

**Comment by monater** [comment]
1，只能选择API下载，并且速度为几十K，其余下载不可用

**Comment by ggxx55** [comment]
1 速度只有50K左右

**Comment by yarude** [comment]
1，只能选择API下载，并且速度为几十K，其余下载不可用

**Comment by koulamo** [comment]
目前只能使用API下載下在速度不會超過50K，最多使用4條線下載多一條就降低下載速度不到20K

**Comment by superiver0** [comment]
已经更新万能助手到v2.0.2，无法用分享链接下载，只能在自己的网盘上下载，用XDOWN1.0.0.5下载，128线程，速度维持在10KB/S。

**Comment by mrsniperz** [comment]
1，开始速度挺快，后来就个位数，最后就直接异常。windows/xdown

**Comment by showapi** [comment]
普通vip，选中文件点击助手任何“显示链接”无反应，chrome控制台有错误信息
感谢！
Access to XMLHttpRequest at 'https://pan.baidu.com/api/download?bdstoken=#####&web=5&app_id=#####&logid=######&channel=chunlei&clienttype=5' from origin 'https://yun.baidu.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:770 Uncaught TypeError: Cannot read property 'errno' of undefined
    at Object.eval (userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:770)
    at Function.each (userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:7)
    at getDirectBatchLink (userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:762)
    at HTMLAnchorElement.batchClick (userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:723)
    at HTMLAnchorElement.dispatch (userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:8)
    at HTMLAnchorElement.r.handle (userscript.html?id=bedbd00a-e1fe-4ce7-854c-d97ef37d2739:8)

**Comment by 1608637229** [comment]
百度真的绝啊。。。好像是关闭了http的下载。基本上所有的第三方的软件都不能用了。。
