### ISSUE TITLE
edge浏览器有按钮显示但是获取的链接是空白

### ISSUE THREAD

**Issue by heyjackem** [syhyz1990/baiduyun#304]
[如题，可以正常显示按钮，但是无法生成链接。
![微信图片_20240118160527](https://github.com/syhyz1990/baiduyun/assets/67465169/3ff93195-c004-4f09-af4c-ac86373c3c97)
试了一下谷歌浏览器是正常的，edge不知道为啥就不行了。

**Comment by a-strong-python** [comment]
我也是edge浏览器，1月15号还能用的，然后今天19号就用不了。希望谷歌没问题，我现在去试一下谷歌的chrome

**Comment by heyjackem** [comment]
> 我也是edge浏览器，1月15号还能用的，然后今天19号就用不了。希望谷歌没问题，我现在去试一下谷歌的chrome我试了chrome是正常的，就是edge不知道为啥这样子。。

**Comment by National777** [comment]
我是老号可以但是这两年注册的新号容量105g的就不行，按钮都在就是没有链接
![屏幕截图 2024-04-20 185053](https://github.com/syhyz1990/baiduyun/assets/114747659/71cfeabb-264a-4dc0-a79b-7eb1b9d06a3c)
