### ISSUE TITLE
升級到2.9.0後要求一定要輸入。沒有微信的人要怎麼獲得暗号？

### ISSUE THREAD

**Issue by SUCM** [syhyz1990/baiduyun#305]
沒有智慧型手機
不知道為什麼微信的申請一直無法通過
之前的版本沒有這個要求啊

**Comment by syhyz1990** [comment]
https://mp.weixin.qq.com/s/rvZP2bOVfMGGtB8OI2ankQ



---原始邮件---
发件人: "SUCM"<notifications@github.com&gt;
发送时间: 2019年10月2日(星期三) 凌晨1:36
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 升級到2.9.0後要求一定要輸入。沒有微信的人要怎麼獲得暗号？ (#305)



沒有智慧型手機
 不知道為什麼微信的申請一直無法通過
 之前的版本沒有這個要求啊
