### ISSUE TITLE
No WeChat; Can't verify Script

### ISSUE THREAD

**Issue by Kaiton121** [syhyz1990/baiduyun#306]
Hello,

thank you for your work. I was able to use your tampermonkey script for a long time and it always worked as intended. I really appreciate your efforts.

But since the newest update it wants me to verify the plug-in with WeChat (https://cdn.baiduyun.wiki/scode.png). However, I don't have WeChat and I cannot create an WeChat account either since its security check requires me to have someone else who uses wechat to verify my account.

Could you please provide a way for people like me to get the password for the script?

**Comment by syhyz1990** [comment]
you can type 94108



---Original---
