### ISSUE TITLE
2.9.0 讨论专用贴 , 收集下无法下载的问题 

### ISSUE THREAD

**Issue by superiver0** [syhyz1990/baiduyun#308]
麻烦版主置顶。
关于部分用户无法下载的问题已收到 , 现统计下无法下载用户的用户类型：1，不是vip；2，普通vip；3，超级vip。
1，软件没有免登录下载选项，只能登录后下载，分享链接也必须登录后下载，我于10月2日使用在chrome的无痕模式下的百度云分享链接下载，添加了参数： --forbidCookie "1"，xdown的线程数调满-128线程。刚开始下载可以满速下载，下载3个大小为1G，1个大小为144mb的文件后下载任务全部显示异常，已经确定被拉入黑名单。软件自此无法使用。。。。。。。19年10月5日，分享页面还是网盘页面用“显示连接”都显示{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":6441243915027658263}，就算登录不同的账号也是这样。

**Comment by 1608637229** [comment]
> 麻烦版主置顶。
> 关于部分用户无法下载的问题已收到 , 现统计下无法下载用户的用户类型：1，不是vip；2，普通vip；3，超级vip。
> 1，软件没有免登录下载选项，只能登录后下载，分享链接也必须登录后下载，我于10月2日使用在chrome的无痕模式下的百度云分享链接下载，添加了参数： --forbidCookie "1"，xdown的线程数调满-128线程。刚开始下载可以满速下载，下载3个大小为1G，1个大小为144mb的文件后下载任务全部显示异常，已经确定被拉入黑名单。软件自此无法使用。

估计实际上没有真正禁止掉cookies。所以账号被限速。百度现在连svip如果一天内下载太多都有可能限速。。

**Comment by dis-xcl** [comment]
百度封锁了免登录下载之后，现在都是需要账号，无论使用什么方法下载都是在百度的掌控之中，一旦下载量多了，马上就会被限速。只有更换账号才行，充值普通会员一样无用了，超级会员都会被限速。下载需求的小的还好，下载需求大的只能多储备一些账号了，目前是没有别的办法了。好怀念以前可以免登录下载的日子。

**Comment by OkazakiYumemi** [comment]
1，下载一些单个文件（直接下载）出现提示：未选中文件，请勿勾选文件夹，否则刷新后重试！但有一些又没有问题。

**Comment by MFamilys** [comment]
> 某种意义上的解决(2019.10.2 UTC+08 23:24 update)：把要下载的文件全部选中使用`分享后下载`，此时在我未开启`百度网盘万能助手`时选择`显示直链`直接复制到剪贴板，再在IDM中`从剪贴板添加批量下载`就成功了。
----------------------------------------------------------------------------------------------------
使用IDM下载之后出现文件类型都是Error的情况，参照**@OkazakiYumemi**的说法尝试之后，可以下载。批量下载60多个视频文件，没出现问题，Thanks。

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)
