### ISSUE TITLE
海外用户无法获取暗号的请点这里

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#309]
https://twitter.com/iPc666

**Comment by SingingDalong** [comment]
Thanks....

**Comment by samlee111** [comment]
good job

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)

**Comment by rufengsuixing** [comment]
自己动手丰衣足食
title: "初次使用请输入暗号"+t.scode,
//滑稽
