### ISSUE TITLE
增加付费版本

### ISSUE THREAD

**Issue by loveqianool** [syhyz1990/baiduyun#311]
付费安装不需要输入暗号即可使用。

**Comment by JYeung111** [comment]
暗号只需输入一次就可以，除你次次用完就清洗 browser local storage

**Comment by syhyz1990** [comment]
谢谢建议，不考虑收费版本，部分用户质疑为何加入暗号这一功能，现在统一回答下：


1. 有人拿脚本卖钱并植入其他代码，这以脚本的免费使用初衷相违背。
2. 有付费的那个钱推荐大家去购买官方百度网盘会员。也能让百度网盘拥有更好的发展。
3. 关于加入公众号获取二维码的功能，纯粹是为了赚一点腾讯的广告费维护脚本正常开发。
另外说下: 暗号只需要输入一次，正确后即可使用。
且用且珍惜！！！



---原始邮件---
发件人: "zhuYe"<notifications@github.com&gt;
发送时间: 2019年10月2日(星期三) 晚上7:54
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 增加付费版本 (#311)



付费安装不需要输入暗号即可使用。

**Comment by superiver0** [comment]
支持开发者，现在不是花钱进QQ群就是按时付费买流量什么的，这么好的开发者已经很少见了。谢谢。还有2.9.0不好使，会被拉入黑名单。

**Comment by JYeung111** [comment]
@syhyz1990 
近日在 greasyfork.org 看多篇惡意批評文，甚為不滿意有廣告，又說要收費！
既然邢邊用户不滿意，又無人走出說公道話，你又何必浪癈心力和時間去維護，然後又要受批，

強烈建議停止此腳本在 greasyfork.org 維護

**Comment by loveqianool** [comment]
收费能更有维护下去的动力，象征性五块钱一个月这样？
我用超级会员用官方客户端下载最高也才 2M+，用脚本配合 aria2 能跑到 10M 左右。

**Comment by bitternolis** [comment]
这个暗号改个1=1就行了，简单的修改……是在客户端验证的并不是服务端。

**Comment by pso2yui** [comment]
@syhyz1990 
建议把开源协议换成AGPL :)

**Comment by syhyz1990** [comment]
> AGPL

感谢建议
