### ISSUE TITLE
阿里云盘新域名 alipan.com 无法下载

### ISSUE THREAD

**Issue by xtremforce** [syhyz1990/baiduyun#312]
如题， 新域名 alipan.com 的资源，「使用 RPC 下载」会失败。
手工切换到旧域名 aliyundrive.com 后能正常下载

**Comment by muse90673** [comment]
谢谢，实测能正常下载

**Comment by bloodkingdom** [comment]
一样用新域名rpc不行,用的是motrix

**Comment by leoatchina** [comment]
6.1.6,  rpc方式同样的问题， 手动换成原来的域名后解决

**Comment by EmptyC1ty** [comment]
2024.3.6手动改变域名的方法用bc下载已经失效，之前该域名是可以用的，但是现在好像修复了

**Comment by feiudfyg** [comment]
2024.3.9对阿里网盘已全部失效
