### ISSUE TITLE
百度网盘API下载没有出现直链

### ISSUE THREAD

**Issue by charron0121** [syhyz1990/baiduyun#313]
![QQ截图20240216173003](https://github.com/syhyz1990/baiduyun/assets/129203139/c2e3ac04-d9aa-4d70-b56b-45068f8abe0e)
油猴beat5.1.6193+直链助手6.1.6

**Comment by yi714** [comment]
出现同样的问题。

**Comment by National777** [comment]
同，老哥解决了吗，我是用RPC也是如此
