### ISSUE TITLE
推送的方法行不通

### ISSUE THREAD

**Issue by Iris-en** [syhyz1990/baiduyun#314]
完全按步骤操作后显示如下：
1 xdown
![Snipaste_2019-10-05_21-08-06](https://user-images.githubusercontent.com/53547007/66255375-3f621480-e7b5-11e9-8324-d4a4ed836bde.png)
2 idm
![Snipaste_2019-10-05_21-08-29](https://user-images.githubusercontent.com/53547007/66255378-44bf5f00-e7b5-11e9-95f9-431c8ce702c9.png)

**Comment by Iris-en** [comment]
推送的方法指免登陆在线解析

**Comment by syhyz1990** [comment]
> 推送的方法指免登陆在线解析

粘贴下链接地址

**Comment by Iris-en** [comment]
> > 推送的方法指免登陆在线解析
> 
> 粘贴下链接地址

已在置顶贴粘贴
