### ISSUE TITLE
[置顶]在线解析讨论贴

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#315]
如链接无法下载 , 留下分享链接和提取码 及地区和宽带运营商

**Comment by Iris-en** [comment]
链接：https://pan.baidu.com/s/1qKlQdLxqmG28HLgRocKw6g 
提取码：8qe0

**Comment by xdown-org** [comment]
`aria2c "https://d.pcs.baidu.com/file/5dc7c9e82f01f2eb15e22590763bba83?fid=3893237467-250528-976214371050727&dstime=1570282126&expires=1570343873&rt=sh&chkv=1&sign=FDtERVA-DCb740ccc5511e5e8fedcff06b081203-fzQd%2BcodWRisSFCvytoOhWSSmtk%3D&r=384900354&sharesign=8TxdhfDdC/oQFfMjr17U04mNJRO9PgwsYb1kmOOmYpk3Ad4+RUt44+9EW2wMEKGfFlP3gCPnLYQ5CsBv9iAUuAAuQPFb4kkLWlsI/vGR5cM=&sh=1" --header "User-Agent: netdisk;"`

获取到的链接,请求异常,

百度云下载

```
https://pan.baidu.com/s/1xIdnUGocZHadlirYAyuT4A 

密码: vxat
```

**Comment by Iris-en** [comment]
> 链接：ht防tps:/和/pan.baidu.co谐m/s/1r2zp1vGJUxB7wK-zOMrhsA 
> 提取码：li63

**Comment by syhyz1990** [comment]
> https://pan.baidu.com/s/1xIdnUGocZHadlirYAyuT4A

http://175.20.29.46/r/d0.baidupcs.com/file/5dc7c9e82f01f2eb15e22590763bba83?bkt=en-26dcfdb4e5ee1a49594376334083a983c5c96755fe0ff27a84b12ac851db2c8665819a6b9713e62d&xcode=d911525d7676d3b2c308a65ece6fb6a0c8abe696ca82b5ff9378fa1cec7369d43259174722087b276842c4fe62064ba40b2977702d3e6764&fid=3893237467-250528-976214371050727&time=1570283683&sign=FDTAXGERQBHSKfa-DCb740ccc5511e5e8fedcff06b081203-cd5sNKvdFr6DGQip%2BKQMa%2BZnXsM%3D&to=d0&size=3161459588&sta_dx=3161459588&sta_cs=1865&sta_ft=mp4&sta_ct=1&sta_mt=1&fm2=MH%2CYangquan%2CAnywhere%2C%2Cbeijing%2Ccnc&ctime=1570175193&mtime=1570175688&resv0=cdnback&resv1=0&resv2=&resv3=&vuk=3422552933&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-a1bc9316b51ee7717d20199ab6f57d8fec2dbda9a77c54017f8c6f76c533727c9e8e605a6446ee67&expires=1570345422&rt=sh&r=206815296&sh=1&vbdid=4050204571&fin=%E9%AB%98%E8%8D%89%E4%B8%9B%E4%B8%AD.In+the+Tall+Grass.2019.%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.WEBrip.AAC.1080p.x264-VINEnc.mp4&rtype=1&dp-logid=6445587075488783931&dp-callid=0.1&tsl=0&csl=0&csign=5iGpkzWcW%2BcBoyJm2JP4njoWR0s%3D&so=1&ut=1&uter=0&serv=1&uc=2723652912&ti=5902310e0d478cb6db8b20f3c40ba79cb57c131ac9806efe&by=themis

**Comment by koulamo** [comment]
连结可以解析出来，输入验证码后有跳出下载的视窗
但是不管用IDM或是xdown下载都出现异常
![2019-10-05 21_50_00-百度网盘直链在线解析](https://user-images.githubusercontent.com/50986704/66255813-d7163180-e7ba-11e9-987d-e9dcb1a179c1.png)
![2019-10-05 21_50_19-添加下载任务](https://user-images.githubusercontent.com/50986704/66255817-daa9b880-e7ba-11e9-80d9-b8ab4a254ad5.png)
![2019-10-05 21_50_42-XDown](https://user-images.githubusercontent.com/50986704/66255819-dd0c1280-e7ba-11e9-8bdd-8868ecc516d3.png)

**Comment by xdown-org** [comment]
@syhyz1990    你解析出来的地址是什么?

**Comment by xueshao** [comment]
同样情况

**Comment by JYeung111** [comment]
解析出来的地址是  ：

啊哦，你所访问的页面不存在了。

**Comment by syhyz1990** [comment]
有可能是你们的ip被百度给限制了 , 换个ip试下 , 或用手机分享个热点测试下

**Comment by syhyz1990** [comment]
> li63

你的链接我试了是可以的

![image](https://user-images.githubusercontent.com/5344173/66257076-4560f100-e7c7-11e9-847a-8d55f384fa61.png)

**Comment by syhyz1990** [comment]
> https://pan.baidu.com/s/1WA4tZuzXDXSskYKlsY8TYw

![image](https://user-images.githubusercontent.com/5344173/66257095-80fbbb00-e7c7-11e9-928c-d9b6c5b5f3ac.png)

**Comment by syhyz1990** [comment]
> > https://pan.baidu.com/s/1xIdnUGocZHadlirYAyuT4A

![image](https://user-images.githubusercontent.com/5344173/66257126-bb655800-e7c7-11e9-8a27-bb86926c634e.png)

**Comment by xdown-org** [comment]
不可以的,

`aria2c "https://d.pcs.baidu.com/file/5dc7c9e82f01f2eb15e22590763bba83?fid=3893237467-250528-976214371050727&dstime=1570282126&expires=1570343873&rt=sh&chkv=1&sign=FDtERVA-DCb740ccc5511e5e8fedcff06b081203-fzQd%2BcodWRisSFCvytoOhWSSmtk%3D&r=384900354&sharesign=8TxdhfDdC/oQFfMjr17U04mNJRO9PgwsYb1kmOOmYpk3Ad4+RUt44+9EW2wMEKGfFlP3gCPnLYQ5CsBv9iAUuAAuQPFb4kkLWlsI/vGR5cM=&sh=1" --header "User-Agent: netdisk;"`


`--header "User-Agent: netdisk;"`

这个header 你确认你没搞错?

**Comment by orocannoneer** [comment]
https://pan.baidu.com/s/1CPZBHSvrPK_GatKTXX26VQ
提取码：無

**Comment by liao6964799** [comment]
https://pan.baidu.com/s/1SoU61bhJIXS94z2ZIs-EdQ  没有提取码  ，我解析出来的普通地址，使用idm后出现如图：
![image](https://user-images.githubusercontent.com/35887374/66258318-7694ed80-e7d6-11e9-851b-e2930f5af907.png)
无法下载啊！ 什么原因

**Comment by JYeung111** [comment]
@syhyz1990 
@xdown-org 

我知道開問題在下載鏈做少了一  step；
就是將百度下載鏈進行一次 "&" ==> "&amp;" 替代程序便一切 OK

https://d.pcs.baidu.com/file/5dc7c9e82f01f2eb15e22590763bba83?fid=3893237467-250528-976214371050727&amp;dstime=1570282126&amp;expires=1570343873&amp;rt=sh&amp;chkv=1&amp;sign=FDtERVA-DCb740ccc5511e5e8fedcff06b081203-fzQd%2BcodWRisSFCvytoOhWSSmtk%3D&amp;r=384900354&amp;sharesign=8TxdhfDdC/oQFfMjr17U04mNJRO9PgwsYb1kmOOmYpk3Ad4+RUt44+9EW2wMEKGfFlP3gCPnLYQ5CsBv9iAUuAAuQPFb4kkLWlsI/vGR5cM=&amp;sh=1

**Comment by superiver0** [comment]
https://pan.baidu.com/s/1ef6FBb8R9gXChNDBxPdAjw提取码：czj9；点击“一件解析”出现文件名称，点击文件名称出现“请输入验证码”，输入验证码点击确定后没有反应，连续点击多次确定后还是没有反应，停一会儿再点击确定后验证码被更换了，再填入验证码后重复上述流程。

**Comment by liao6964799** [comment]
> @syhyz1990
> @xdown-org
> 
> 我知道問題在下載鏈做少了一 step；
> 就是將百度下載鏈進行一次 "&" ==> "&amp;" 替代程序便一切 OK

@syhyz1990   可能真的是上面这个问题哦，我在线解析不行，分享后下载可以，而且获得的地址不一样

**Comment by syhyz1990** [comment]
@xdown-org 试下新版本 ， 已经解决了

**Comment by SUCM** [comment]
直接點連結會得到這類的錯誤
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":6457804109927471618}
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":6457863702699424916}

**Comment by SUCM** [comment]
aria2的連結沒問題

**Comment by Iris-en** [comment]
更新后idm xdown都可用👌

**Comment by Professor-T** [comment]
测试了下，脚本2.9.1，插件2.0.3，100M宽带。IDM批量下载每个任务可以2.8M/S左右（32连接数），Xdowm免登录解析，任务速度峰值可以达到8~9M/S左右（128连接数）。
请问一下，关注公众号不限次数，是只要关注就可以了么？

**Comment by xdown-org** [comment]
@syhyz1990   https://www.baidusu.com/

点击解析没反应了,

百度云下载

```
https://pan.baidu.com/s/1xIdnUGocZHadlirYAyuT4A 

密码: vxat
```

**Comment by xdown-org** [comment]
```
Request URL: https://api.baidusu.com/v1/verify?data=f8e9678c342c8244cf7f8bf57cd8417c4cb753cf014d6912b689da3d9fc69ada7b8e8cb8a0d7c0a903f32ecf2ba98a71ccd30d4a5d62e58f054e2c356c9fa3a9a009916b48010386ab74ca189df5f23e3b17996bd977ab86488e233745dabe1d
Request Method: POST
Status Code: 404 
Remote Address: 103.142.102.40:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by JYeung111** [comment]
估計是在判定是否 SurlWithRoot 出了問題？

同樣是root
https://pan.baidu.com/s/11Q0bXuihrb1s2s8uJ2cJUw
這鏈又無問題

**Comment by syhyz1990** [comment]
> 测试了下，脚本2.9.1，插件2.0.3，100M宽带。IDM批量下载每个任务可以2.8M/S左右（32连接数），Xdowm免登录解析，任务速度峰值可以达到8~9M/S左右（128连接数）。
> 请问一下，关注公众号不限次数，是只要关注就可以了么？

是的呢

**Comment by syhyz1990** [comment]
> jn3c

一个参数写错了，已经可以了

**Comment by xdown-org** [comment]
ok ,可以用了

**Comment by holydragon-gh** [comment]
链接: https://pan.baidu.com/s/1n1RBnjryb75vJ6kAhcBBpw 提取码: eb8v   点击输验证码后提示红字下载失败上海移动宽带

**Comment by zhihuo0120** [comment]
1、直链解析需要关闭广告屏蔽。
当我打开Adblock Plus后，页面时空的
![image](https://user-images.githubusercontent.com/48322854/66269255-04291980-e879-11e9-859e-cefca224b70e.png)


2、直链解析后，直接复制普通链接到IDM，无法下载
只有把链接用浏览器打开后，才会自动弹出IDM下载窗口（或是浏览器自带的下载器）
（小的文件没有问题，1G好像有点问题）

**Comment by xdown-org** [comment]
用xdown使用aria2c链接,
idm下载场景本身对这种特殊请求不友好.

**Comment by siair** [comment]
像之前的旧版直接获取免登录下载地址不是挺好吗？为啥还要再打开一个网页？

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)

**Comment by dis-xcl** [comment]
出现提示：暂时无法解析含提取码的链接，请自己分享后解析

**Comment by SUCM** [comment]
變成是空白網頁了

**Comment by wangxiangyao** [comment]
在线解析 
有时候能打开，有时候打不开  无法访问

**Comment by xdown-org** [comment]
@syhyz1990 

百度插件基本就这样了,
有空来搞 
https://github.com/xdown-org/xdown

目的就是模拟点击,后缀是
`localStorage.getItem('xdown-file-suffix-data');`
截取当前链接的请求信息,发送给xdown进行下载.
目前只搞了youtube,对js不懂,
我这边在优化BT传输协议,
HTTP协议请求基本也就这样了.

idm vs xdown
https://www.youtube.com/watch?v=B7TVzttHnf0

http算法已经可以说优于idm,
但是插件这块实在不熟悉,

**Comment by ijkm1234** [comment]
https://pan.baidu.com/s/1ptUfqp_NQfUmdkjdKLrgTw 提取码: bj71
403 forbidden
西安电信

**Comment by xwlcn** [comment]
又不行了：{"error_code":31326,"error_msg":"user is not authorized, hitcode:107","request_id":6817353002175319642}

**Comment by zbyzzxy** [comment]
在线解析后无法用aria2下载了，403错误

**Comment by syhyz1990** [comment]
已找到问题所在，待稳定后更新

**Comment by zbyzzxy** [comment]
> 已找到问题所在，待稳定后更新

谢谢

**Comment by dis-xcl** [comment]
目前在线解析全部失效，IDM、Xdown均无法下载，期待作者更新！
@syhyz1990 
@xdown-org

**Comment by JYeung111** [comment]
@syhyz1990
已找到问题所在，待稳定后更新

我測試完新的在线解析，它是可似運作，但必須要在登錄後，否則一樣是
{"error_code":31326,"error_msg":"user is not authorized, hitcode:107",...
功能好似以前的分享鏈下載，但吾知會否每次下載同時扣減下載限量指標？

可否指點一下如何令下載鏈這參數 chkpc=et 消失

**Comment by 1608637229** [comment]
> @syhyz1990 說：
> 已找到问题所在，待稳定后更新
> 
> ==================================
> 
> 我測試完新的在线解析，它是可似運作，但必須要在登錄後，否則一樣是
> {"error_code":31326,"error_msg":"user is not authorized, hitcode:107",...
> 功能好似以前的分享鏈下載，但吾知會否每次下載同時扣減下載限量指標？
> 而且這修復只支援大約 50MB或以下的 文件！
> 
> 我剛做到相似功能，不知為何多咗這參數！
> 可否指點一下如何令下載鏈中這參數 chkpc=et 消失？？

我感觉可能是我的锅。我公开在提问中说了可以打包300M下载，结果刚好一周后就和谐只能50M了

**Comment by JYeung111** [comment]
@1608637229 
那50MB 的限到不是說打包下載，而是單文件，而這限制亦是百度早前已定下，它是用來在網頁下載中去觸發需要使用百度管家下載的指標！

打包下載限制在300M以下，公开談論己很久遠，不是甚麼禁忘，再者兩者是有不同目的和運作！

**Comment by s3787684** [comment]
@syhyz1990 輸入了每日授權代碼沒反應

**Comment by shadowdragon1123** [comment]
打包下载现在已经被禁了 没用了

**Comment by superiver0** [comment]
19.10.31.我有三个电脑，我用的是同一条宽带，电脑1和电脑3有百度云直链下载助手，电脑2没有。我用电脑1和电脑2下载的时候都没有问题，我用电脑3下载的时候所有的下载任务都显示异常，这是怎么回事？电脑1是WIN7，电脑2和电脑3是WIN10。

**Comment by superiver0** [comment]
谢谢版主一直能更新，在线解析有的时候可以用有的时候不能用，可以推测版主在和百度作斗争。版主能不能想办法解决文件大小限制，我有很多电影需要下载，但是每次都提示：“暂只支持3G内文件。”

**Comment by god01a** [comment]
海外用户无法关注公众号取得授权代码 有人可以告知一下吗?
或是楼主多一个地方发布

**Comment by qiaoduan1422503940** [comment]
一枚高中生默默地支持版主。。。

**Comment by JYeung111** [comment]
由於 无法关注公众号取得授权代码 ！
誰可以提供一個完整 xdown 下載鏈作為測試之用？

**Comment by lick2016** [comment]
报告状态 2019 11 6    在线可以解析但是解析出来的链接 xdown下载显示异常  
https://pan.baidu.com/share/init?surl=Z8q2qk5pk0rGIazb3Am17A#list/path=%2F
x8m3

**Comment by lick2016** [comment]
还有pandownload 网页版也阵亡
