### ISSUE TITLE
下载失败 地址出来不

### ISSUE THREAD

**Issue by acdc126** [syhyz1990/baiduyun#317]
插件这些都是最新的  一直这样什么链接都不行呀!
![3SAQGVGAC6)RT1~U`EV %Q2](https://user-images.githubusercontent.com/52092007/66269102-16a25380-e877-11e9-91e3-936743728341.png)

**Comment by airoys** [comment]
我也是遇到这个 有些会提示下载失败

**Comment by syhyz1990** [comment]
保存到自己网盘里，自己分享一个链接下

**Comment by airoys** [comment]
没有账号 想着可以免登陆 看来没办法了 感谢开发者

**Comment by RoyalShooter** [comment]
同问，使用脚本分享后下载没有反应，aria直连发生异常，使用百度官方分享功能也被封掉，有方法解决吗？
![image](https://user-images.githubusercontent.com/22939113/66292815-11a2cb80-e89a-11e9-8d9d-e56b6d7f34e8.png)

**Comment by acdc126** [comment]
落都落不到地就被杀了..

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)
