### ISSUE TITLE
阿里云网页版下载按钮下拉栏部分被遮挡，导致无法选择被遮挡的下载方式

### ISSUE THREAD

**Issue by lzy-Jolly** [syhyz1990/baiduyun#318]
![image](https://github.com/syhyz1990/baiduyun/assets/52607257/b602c283-84bb-4b3e-9ac0-227b74a5cf06)
如图，被阿里云官方的广告挡住了一部分（橙色），鼠标下滑调过就自动收回下拉栏了。

**Comment by leoatchina** [comment]
用adblock 或者 ctrl+shift+i 手动去除这个bom 对象

**Comment by EmptyC1ty** [comment]
放大缩小网页或者右键点开菜单之后再把鼠标往下方移动即可
