### ISSUE TITLE
广告屏蔽 | IDM解析下载

### ISSUE THREAD

**Issue by zhihuo0120** [syhyz1990/baiduyun#318]
1、直链解析需要关闭广告屏蔽。
当我打开Adblock Plus后，页面时空的
![image](https://user-images.githubusercontent.com/48322854/66269341-e4debc00-e879-11e9-9561-d483ab569a0e.png)

2、直链解析后，直接复制普通链接到IDM，无法下载
只有把链接用浏览器打开后，才会自动弹出IDM下载窗口（或是浏览器自带的下载器）
（小的文件没有问题，1G好像有点问题）

**Comment by syhyz1990** [comment]
此网站上并未投放广告，不支持ie浏览器
