### ISSUE TITLE
阿里云盘分享页面无法获取链接

### ISSUE THREAD

**Issue by louisZai** [syhyz1990/baiduyun#319]
![屏幕截图 2024-03-06 153601](https://github.com/syhyz1990/baiduyun/assets/122164637/45304d57-049d-419a-a340-6418f36ab89b)
![屏幕截图 2024-03-06 153614](https://github.com/syhyz1990/baiduyun/assets/122164637/8ee8cf53-70ec-4af0-803a-63f884f2eab8)

**Comment by feiudfyg** [comment]
我这里也是

**Comment by MalcKear** [comment]
一样

**Comment by 3320099** [comment]
我这里也是一样

**Comment by feiudfyg** [comment]
大抵是寄了 不知道什么时候会修复
