### ISSUE TITLE
提示暗号正确后仍要求输入暗号

### ISSUE THREAD

**Issue by mokurin000** [syhyz1990/baiduyun#32]
浏览器： firefox nightly 87
OS: archlinux ( linux-zen )
插件 ViolentMonkey
油猴下没问题

**Comment by Parampaa** [comment]
pardon for asking, but what is the password for overseas user? I don't have wechat and the password in Twitter (ipc) is no longer working. Thanks.

**Comment by mokurin000** [comment]
> pardon for asking, but what is the password for overseas user? I don't have wechat and the password in Twitter (ipc) is no longer working. Thanks.

https://kinhdown.kinh.cc/
I don't know whether if I can send you the key
But this tool is avaliable to use
Though it's not a good tool

**Comment by syhyz1990** [comment]
> pardon for asking, but what is the password for overseas user? I don't have wechat and the password in Twitter (ipc) is no longer working. Thanks.

the key is 80149

**Comment by poly000** [comment]
> > pardon for asking, but what is the password for overseas user? I don't have wechat and the password in Twitter (ipc) is no longer working. Thanks.
> 
> the key is 80149

**Comment by mokurin000** [comment]
emmm 这个脚本期望支持暴力猴吗

**Comment by syhyz1990** [comment]
> emmm 这个脚本期望支持暴力猴吗

支持暴力猴
