### ISSUE TITLE
rpc下载发送任务失败，配置正常

### ISSUE THREAD

**Issue by DavidTsou** [syhyz1990/baiduyun#320]
![image](https://github.com/syhyz1990/baiduyun/assets/33798797/f6791553-160b-4167-ae1b-31aaa294f6c9)

**Comment by ysinx** [comment]
我这也是，前几天就不行了，用的Motrix

**Comment by cccccd111** [comment]
保存到网盘就可以下了，跟夸克迅雷一样不方便了

**Comment by DavidTsou** [comment]
> 保存到网盘就可以下了，跟夸克迅雷一样不方便了

是的，昨天复现出来了。保存到网盘里就能下载了
