### ISSUE TITLE
安装脚本后不显示下载助手

### ISSUE THREAD

**Issue by weidongzhou1994** [syhyz1990/baiduyun#320]
以前能正常使用，但是最近几天突然不能正常使用，更新到2.9.1页无法使用，不知道什么原因?

**Comment by weidongzhou1994** [comment]
我换了一个网络，可以用了，但为什么原来的网络既打不开安装的网址，也无法显示下载助手呢？求解答

**Comment by 51data** [comment]
### **野猫VIP帐号小程序，直接获取百度网盘SVIP帐号，无套路，完全免费！推荐给大家！！！**
![image](https://raw.githubusercontent.com/wuxingsanren/wildcat-vip-account/master/images/wxapp_qrcode.png)
