### ISSUE TITLE
百度网盘 获取API下载链接失败

### ISSUE THREAD

**Issue by zpwen6** [syhyz1990/baiduyun#322]
百度网盘 获取API下载链接失败

提示：获取下载链接失败！请刷新网页后重试！
刷新也不行
重新安装脚本也不行

**Comment by 1molPotato** [comment]
+1

![image](https://github.com/syhyz1990/baiduyun/assets/11970884/8c826b8a-6194-48e5-94fb-fea8b7864d3b)

**Comment by wcc4869** [comment]
+1
<img width="372" alt="image" src="https://github.com/syhyz1990/baiduyun/assets/22254090/f5348acb-90eb-4279-8ca8-b6155ed7e324">
