### ISSUE TITLE
google浏览器使用出现假死

### ISSUE THREAD

**Issue by Carpyehon** [syhyz1990/baiduyun#324]
我之前一直以为是浏览器的问题，后来我关闭了插件，发现就正常了，在启用插件后，点击文件分享的时候会卡，然后复制提取码的时候会卡，在下载页面获取连接的时候会卡死

**Comment by syhyz1990** [comment]
提供下插件的版本





---原始邮件---
发件人: "Carpyehon"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 凌晨0:40
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] google浏览器使用出现假死 (#324)



我之前一直以为是浏览器的问题，后来我关闭了插件，发现就正常了，在启用插件后，点击文件分享的时候会卡，然后复制提取码的时候会卡，在下载页面获取连接的时候会卡死

**Comment by Carpyehon** [comment]
> 提供下插件的版本
> […](#)
> ---原始邮件--- 发件人: "Carpyehon"<notifications@github.com&gt; 发送时间: 2019年10月9日(星期三) 凌晨0:40 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [syhyz1990/baiduyun] google浏览器使用出现假死 (#324) 我之前一直以为是浏览器的问题，后来我关闭了插件，发现就正常了，在启用插件后，点击文件分享的时候会卡，然后复制提取码的时候会卡，在下载页面获取连接的时候会卡死 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

插件版本：2.9.1

**Comment by Carpyehon** [comment]
> 提供下插件的版本
> […](#)
> ---原始邮件--- 发件人: "Carpyehon"<notifications@github.com&gt; 发送时间: 2019年10月9日(星期三) 凌晨0:40 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [syhyz1990/baiduyun] google浏览器使用出现假死 (#324) 我之前一直以为是浏览器的问题，后来我关闭了插件，发现就正常了，在启用插件后，点击文件分享的时候会卡，然后复制提取码的时候会卡，在下载页面获取连接的时候会卡死 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

插件版本：2.9.1

**Comment by syhyz1990** [comment]
> > 提供下插件的版本
> > […](#)
> > ---原始邮件--- 发件人: "Carpyehon"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2019年10月9日(星期三) 凌晨0:40 收件人: "syhyz1990/baiduyun"<[baiduyun@noreply.github.com](mailto:baiduyun@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [syhyz1990/baiduyun] google浏览器使用出现假死 (#324) 我之前一直以为是浏览器的问题，后来我关闭了插件，发现就正常了，在启用插件后，点击文件分享的时候会卡，然后复制提取码的时候会卡，在下载页面获取连接的时候会卡死 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 插件版本：2.9.1

我是说百度万能助手的版本
![image](https://user-images.githubusercontent.com/5344173/66622033-bdd90f00-ec18-11e9-9836-9b6ee6695805.png)
