### ISSUE TITLE
已经勾选文件，还是提示未勾选文件。

### ISSUE THREAD

**Issue by fclmr** [syhyz1990/baiduyun#325]
![百度云错误](https://user-images.githubusercontent.com/19144351/66450423-11b5ed80-ea8b-11e9-8017-1a4a3f819bdb.png)

**Comment by EastLord** [comment]
这应该是个bug

**Comment by 1608637229** [comment]
遇到同样的问题

**Comment by jeffery9** [comment]
the same issue

**Comment by zlf179** [comment]
刷新页面就行了

**Comment by ZerOri** [comment]
同样的bug

**Comment by firstrose** [comment]
FF 69.0.3 64bit 同样问题，刷新无效。

**Comment by qq850482461** [comment]
Chrome 69.0.3497.92 64 同样无效

**Comment by sdysyhj** [comment]
同样的问题，只能全选

**Comment by owenphx** [comment]
部分文件无法勾选，刷新无效，但有一个共性都是当天新添加的文件，即使全选所有文件也看不到这些新文件；当天之前的文件全都可以正常勾选，

**Comment by owenphx** [comment]
> 部分文件无法勾选，刷新无效，但有一个共性都是当天新添加的文件，即使全选所有文件也看不到这些新文件；当天之前的文件全都可以正常勾选，

刚找到临时的解决方法，比如A文件是之前存在的，B文件是现在添加进网盘的，现在要下B文件，但是无论如何都是说没勾选，那么重点来了，把B文件重命名和A文件差一个数字，如A文件叫“123”，那B文件改成“124“，直接勾选A文件获得API地址并复制到记事本，然后把链接地址的A文件名改成B文件名，亲测有效。如果是不同扩展名的，自己灵活点改一下？

**Comment by syhyz1990** [comment]
改名,添加等操作后都需要刷新下重新勾选,不用这么麻烦
