### ISSUE TITLE
请求功能获取打包下载的功能

### ISSUE THREAD

**Issue by 1608637229** [syhyz1990/baiduyun#327]
例如https://greasyfork.org/zh-CN/scripts/26638-ex-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98
这个脚本就可以直接单独获取一个文件的打包的下载链接。虽然只能限制300M以内的
文件，但是至少可以不限速和反和谐8秒的用途。申请此插件也加上这个单独获取打包链接的功能。
主要是由于ex这个插件不支持暴力猴。不然我可以两个插件都装了。

**Comment by 1608637229** [comment]
另外2.91对于某些压缩包明明已经勾选了还是提示没有勾选文件？？难度是这个文件被和谐的原因吗？？
但是用上面那个插件依然可以获取到300M以内的打包的下载链接。

**Comment by JYeung111** [comment]
@1608637229 

EX-百度云盘 这个插件是可以在暴力猴正常使用，
現在不能用是加入 babel transform迎合某些人，但暴力猴似是不支援babel的做法，因此想它在暴力猴正常使用，只需删除幾句Babel 封裝代碼就可以，非常簡單！

**Comment by 1608637229** [comment]
> @1608637229
> 
> EX-百度云盘 这个插件是可以在暴力猴正常使用，
> 現在不能用是加入 babel transform迎合某些人，但暴力猴似是不支援babel的做法，因此想它在暴力猴正常使用，只需删除幾句Babel 封裝代碼就可以，非常簡單！
怎么被删除了，什么包含脚本语法错误被删除。

**Comment by JYeung111** [comment]
@1608637229

只需用editor這三段代碼 删除或將其改為備註，然後儲存，刷新後便可用！

[三段代碼.txt](https://github.com/syhyz1990/baiduyun/files/3729448/default.txt)

**Comment by 1608637229** [comment]
> @1608637229
> 
> 只需用editor這三段代碼 删除或將其改為備註，然後儲存，刷新後便可用！
> 
> [三段代碼.txt](https://github.com/syhyz1990/baiduyun/files/3729448/default.txt)

ok了，感谢指导。

**Comment by 1608637229** [comment]
佛了。github真有百度的卧底啊。我不该说出来的，现在好像超过50M都不能下载了。牛皮。
