### ISSUE TITLE
user is not authorized,

### ISSUE THREAD

**Issue by jiasong-cn** [syhyz1990/baiduyun#33]
ode":31326,"error_msg":"user is not authorized, hitcode:107","error_info":"","request_id":72691

**Comment by telepati** [comment]
I am getting the same error. Also when I try to download with IDM it giving a Forbidden 403 error.

**Comment by leoxxx** [comment]
It is caused by the file over 50Mib.
You need share the file, then download it.

**Comment by Sheldonsuckz** [comment]
Same here I seem to be getting a 403 error regardless of the link.
