### ISSUE TITLE
弹二维码，吃相有点难看

### ISSUE THREAD

**Issue by zhoushenglin** [syhyz1990/baiduyun#330]

**Comment by syhyz1990** [comment]
没人逼着你用，有本事自己写去。



---原始邮件---
发件人: "zhoushenglin"<notifications@github.com&gt;
发送时间: 2019年10月16日(星期三) 凌晨0:03
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 弹二维码，吃相有点难看 (#330)

**Comment by JYeung111** [comment]
我百分百認同作者

**Comment by zhoushenglin** [comment]
格局也就这样了，删除再见。
