### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hgdagon** [syhyz1990/baiduyun#337]
I can't download any of the links

Here's what I did:
I installed the script in TamperMonkey
Downloaded Firefox Extension "Baidu Cloud Assistant"
Got the unlock code from WeChat
The button appeared

However I can;t download ANY of the generated links.
I don't speak Chinese, so I don't know what XDown says, but there's an error
IDM says 403, access denied.
I only managed to download with Firefox's own DownThemAll!, but it errors out after a few minutes "Server error"

Did I not do everything? The tutorial on the website seems outdated, at least the screenshots are.

**Comment by Silencxc** [comment]
It just doesn't work now. There's also 403 error for me, and also for many other users (according to other issues).

**Comment by hgdagon** [comment]
OK. Just wait for and update, then?

**Comment by JYeung111** [comment]
Upon my testing result:
Author has been updated, but only support for file size less  than 50MB and also  user must be login .

You can use "API download" for temp solution.

**Comment by hgdagon** [comment]
> 
> You can use "API download" for temp solution.

I don't speak Chinese, so...
API download -> 1 does nothing
API download -> 2 shows a link, but XDown shows some (unknown) error, IDM says 403, DownThemAll! downloads the link @ 20 KB/s, but shows "Server Error" after a while.
API download -> 3 I don't even know what the third button does...

**Comment by JYeung111** [comment]
If you want to "API Download" working, it must be under two condition,

first is the download speed of your account does not limited by baidu.com,   

second  is  your secretCode "神秘代码" must be correctly set, different secretCode
will affect your download speed which is low or high and also got the error response.
This secretCode will periodic change by Baidu. 
ie. Today secretCode A is high speed and after a few days later, it is change to low 
speed , even be error. and after a few months it wll changing back to high.

Tips: secretCode of script ver 2.9.2 has speed about 2~3xxK for 3 threads

**Comment by ssvs09** [comment]
can anyone help me how to get those code? i've scanned the qr and it direct me to wechat app. i've tried installed and create new account but turns out it won't work in my phone. the app itself say that we chat won't work in my phone. (i'm using meizu m1 note).

**Comment by syhyz1990** [comment]
type API -> 神秘代码 -> 778750 , then choose the file you need to download ,do API下载 -> 显示链接 , click right mouse "Save as"
