### ISSUE TITLE
这两天突然不能用了

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [syhyz1990/baiduyun#338]
xdown一直显示异常，换了地址也是，所以应该不是我的IP被限制了。

**Comment by Silencxc** [comment]
大概是都炸了，我在国外也用不了

**Comment by huanghe2015** [comment]
HTTP直链全挂，连VIP都不行了。。。

**Comment by huanghe2015** [comment]
补充：直链单文件大小限制进一步收紧，目前是小于40MB，欢迎大家做试验。

**Comment by AhianRen** [comment]
我用idm单文件直链50M以下可下，50M以上就不行了

**Comment by AndroidJohnsonWang** [comment]
@huanghe2015 我也用VIP试了下，发现超级VIP也没有速度，不知道百度在搞什么

**Comment by thromsbird** [comment]
我试了下50M以下也不行，换账号也一样

**Comment by moli222** [comment]
😅😅

**Comment by sgzman** [comment]
我也是xdown下载异常  哎

**Comment by shadowdragon1123** [comment]
52破解那个亿寻是目前唯一能用的
然而 屏蔽北京和海外
海外党欲哭无泪

**Comment by JYeung111** [comment]
此腳本尚有部份仍可運作，速度平均都有５～６xxK，如本身户口未被限速還可有更高！

**Comment by hccgk** [comment]
下载限速了，保持在100k以下，要不然就报一个错误 什么没有认证

**Comment by hccgk** [comment]
可以用了吗
