### ISSUE TITLE
把下载链接的前缀改为d.pcs.baidu吧

### ISSUE THREAD

**Issue by Bagener** [syhyz1990/baiduyun#34]
c.pcs.baidu开头的IDM根本请求不了链接，改为d.pcs.baidu立马可以下载了，就是速度不快不过也忍了。
![untitled](https://user-images.githubusercontent.com/35773805/48297846-c3037a80-e4ec-11e8-831e-98eecbace9e8.png)

**Comment by aclihub** [comment]
idm选项可以32线速度可以更快
