### ISSUE TITLE
阿里云盘下载无链接

### ISSUE THREAD

**Issue by jafox-12** [syhyz1990/baiduyun#349]
选API下载后没有下载链接：
![image](https://github.com/syhyz1990/baiduyun/assets/74179218/bc0558de-029c-497c-ad28-2414b9236ede)

**Comment by liutianyan** [comment]
使用 RPC 下载，也会提示“发送失败，请检查您的RPC配置信息！”。但同样的配置，能下载百度网盘的

**Comment by ihuangke777** [comment]
一样的情况，应该是阿里云不给玩咯？拿到的内容是：aria2c   --out "xxxxxx" --header "Referer: https://www.aliyundrive.com/"

**Comment by javarike** [comment]
一样+1

**Comment by jiemo9527** [comment]
+1

**Comment by ysinx** [comment]
+1，RPC 下载，提示“发送失败，请检查您的RPC配置信息！

**Comment by ICraZY-EE** [comment]
+1

**Comment by ihuangke777** [comment]
又过来看看，没有更新，明天再来打卡。。。。

**Comment by jiemo9527** [comment]
继续深究下去，得到个encrypt_url??怎么个意思，把链接加密了，不知道加密方式和密码，几乎不可能得到结果。这条路走不通了

**Comment by ihuangke777** [comment]
> 继续深究下去，得到个encrypt_url??怎么个意思，把链接加密了，不知道加密方式和密码，几乎不可能得到结果。这条路走不通了

太难啦，继续来逛逛。。作者大大来救救我们。。

**Comment by jiemo9527** [comment]
已解决

**Comment by liutianyan** [comment]
> 已解决；需要自己备个服务器做中转

能分享一下吗

**Comment by misaka10843** [comment]
> > 已解决；需要自己备个服务器做中转
> 
> 能分享一下吗

自己使用alist搭建一下就可以了直链了，缺点就是有点麻烦
