### ISSUE TITLE
aria链接获取问题

### ISSUE THREAD

**Issue by vsoulstudio** [syhyz1990/baiduyun#349]
获取的Aria和直链里大文件的直接没法用，几MB的小文件正常，从官网的直接解析页面有的可以有的不行
chrome

**Comment by shadowdragon1123** [comment]
小于50M本来就可以直接浏览器下载不会调用百度云客户端

**Comment by vsoulstudio** [comment]
> 小于50M本来就可以直接浏览器下载不会调用百度云客户端

头一次知道获取直链/aria和调不调用客户端有关系

**Comment by shadowdragon1123** [comment]
难道没关系？

**Comment by vsoulstudio** [comment]
> 难道没关系？

你问我我问谁，我又不是写程序的只是来反馈bug的，毕竟这提直链和Aria链接又没要求必装度盘客户端，度盘也没说他用的是aria协议，我咋知道会和需不需要度盘客户端有关
