### ISSUE TITLE
脚本突然失效

### ISSUE THREAD

**Issue by wmhy** [syhyz1990/baiduyun#35]
使用idm下载时能够成功连接，但随后就显示：服务器响应没有权限下载该文件。直接下载和api下载方式均是如此。

**Comment by bbq191** [comment]
百度该规则了，加了cookie信息也不行了。

**Comment by qybgh** [comment]
我刚刚还用了，没问题啊。

**Comment by shewayjutest** [comment]
單純複製連結些上FDM會有問題
要用FDM配chrome的擴充功能，右鍵功能表下載
但會有連結數跟速度限制
