### ISSUE TITLE
What is '授权'?

### ISSUE THREAD

**Issue by SingingDalong** [syhyz1990/baiduyun#350]
What is '授权'?
What does '因资源有限，仅支持关注用户下载！' mean?

**Comment by zhmw84** [comment]
"授权" means to authorize. "因资源有限，仅支持关注用户下载!" translates to, "Due to limited resources, we only provide support downloading for our followers." What the developers ask you to do is to follow their wechat public account, text "授权" where asked to to get the downloading code for the day.

**Comment by syhyz1990** [comment]
you can type 963256

**Comment by SingingDalong** [comment]
> 963256
Thank you.

**Comment by JYeung111** [comment]
@syhyz1990 

我因用吾到掃碼，無法直接獲得 免登录 "授权代码"；
可否助我或給我此碼？
