### ISSUE TITLE
禁止分享的文件，怎么破？

### ISSUE THREAD

**Issue by Penny1a** [syhyz1990/baiduyun#351]
有些文件被禁止分享，有什么办法吗？

**Comment by rzdtjb** [comment]
新建一个文件夹，把文件拖进来，分享文件夹。

**Comment by Penny1a** [comment]
> 新建一个文件夹，把文件拖进来，分享文件夹。

不行

**Comment by bakaest** [comment]
> > 新建一个文件夹，把文件拖进来，分享文件夹。
> 
> 不行

是不是文件名有屏蔽词，试过随便改个文件名吗

**Comment by Penny1a** [comment]
> > > 新建一个文件夹，把文件拖进来，分享文件夹。
> > 
> > 
> > 不行
> 
> 是不是文件名有屏蔽词，试过随便改个文件名吗

试过，大小显示 0B 点不开文件夹。

**Comment by JYeung111** [comment]
有個程式聲稱可突被封禁，本人未試用過！
記得以前有人曾說過 "百度封禁"是針對文件的MD5去做的！
因此改名，換位是破不了的
