### ISSUE TITLE
已经不可以用了。

### ISSUE THREAD

**Issue by pp605** [syhyz1990/baiduyun#355]
![image](https://user-images.githubusercontent.com/16586824/68390711-d64d3280-01a0-11ea-8395-d343967e4721.png)
Xdown也已经不行了。看样子真的要交钱买会员了~！

**Comment by kenneth104** [comment]
恩，我是丢到aria2里面，不行

**Comment by gsons** [comment]
究竟还能用吗?各位大佬

**Comment by Leojc** [comment]
我还可以，刚刚还在用（xdown）

**Comment by MarikoKujo** [comment]
今日配IDM不可用，各种403
