### ISSUE TITLE
在线解析挂了吗？

### ISSUE THREAD

**Issue by weidongzhou1994** [syhyz1990/baiduyun#356]
如题

**Comment by dis-xcl** [comment]
挂掉了，在线解析的网址直接跳到网盘助手的首页。连之前在线解析的讨论贴也给删了。应该是百度太厉害了，作者已经选择放弃了！

**Comment by Leojc** [comment]
我这是好的，使用xdown下载，我刚刚还在用呢

**Comment by gsons** [comment]
我第一次用 这个然鹅////。。。

**Comment by duliyoumin** [comment]
已经成为历史了，

**Comment by liuxyon** [comment]
下载了10个文件后就不能用了.怎么回事? 免登录怎么不行?

**Comment by JYeung111** [comment]
免登录已恢復 

我因用吾到掃碼，無法直接獲得 免登录 "授权代码"；
誰可助我或給我此碼？

**Comment by 1608637229** [comment]
> 免登录已恢復
> 
> 我因用吾到掃碼，無法直接獲得 免登录 "授权代码"；
> 誰可助我或給我此碼？

没必要了。这软件已经不能免登录了。我关注了公众号作者现在是建议你开超级会员配合
这个插件使用。实际上你开了超级会员用官方客户端也能有不错的速度。

**Comment by JYeung111** [comment]
@1608637229 
我是看看它回覆的下載鏈，並想做一些测試，可否幫幫忙忙？

**Comment by 1608637229** [comment]
> @1608637229
> 我是看看它回覆的下載鏈，並想做一些测試，可否幫幫忙忙？

哦。好像可以下载但是现在只支持Xdown了。不支持idm了。我刚试了下。
授权码：385236。后面可能会改变。台湾或者香港不能注册微信吗？？

**Comment by JYeung111** [comment]
先感謝你的幫忙，因為個人理由(視力)，暫時停用智能手機！

**Comment by JYeung111** [comment]
@1608637229 
初步測試做完，作者今次己做了一些更新，真的做到免登录下載，它回覆的下載鏈是終極鏈，是可直接下載，不理用家是否已登彔，而且下載所扣下載量是作者，它是可以使用任何 "downloader which support for customer user-Agent" 去下載。

![未命名](https://user-images.githubusercontent.com/41117798/68771355-db0f5c00-0662-11ea-8ff9-f12c39962a99.PNG)


正因是用作者的下載量去運作，它是會很快便因用完下載量而被限速。
以上是初步估計，如有錯請見諒！

再一次感謝你的幫忙！

**Comment by 1608637229** [comment]
> @1608637229
> 初步測試做完，作者今次己做了一些更新，真的做到免登录下載，它回覆的下載鏈是終極鏈，是可直接下載，不理用家是否已登彔，而且下載所扣下載量是作者，它是可以使用任何 "downloader which support for customer user-Agent" 去下載。
> 
> ![未命名](https://user-images.githubusercontent.com/41117798/68771355-db0f5c00-0662-11ea-8ff9-f12c39962a99.PNG)
> 
> 正因是用作者的下載量去運作，它是會很快便因用完下載量而被限速。
> 以上是初步估計，如有錯請見諒！
> 
> 再一次感謝你的幫忙！

那估计需要更多的svip才行。百度现在为了防止租号对svip也采取了流量限制。流量达到上限一样会限速账号。

**Comment by gsons** [comment]
万恶的百度😩  谁能赐他一死 😡
