### ISSUE TITLE
剛漏調部份 重新說明 請求作者 火狐插件网盘万能助手更新到2.20版本 剛要去裝  火狐插件還是停留 2.1版本 所以 請求作者 火狐插件网盘万能助手更新到2.20版本

### ISSUE THREAD

**Issue by ok3672108** [syhyz1990/baiduyun#359]
剛漏調部份 重新說明 請求作者 火狐插件网盘万能助手更新到2.20版本 剛要去裝  火狐插件還是停留 2.1版本 所以 請求作者 火狐插件网盘万能助手更新到2.20版本
https://addons.mozilla.org/zh-CN/firefox/addon/baidu-cloud-assistant/versions/

**Comment by abcfy2** [comment]
顶这个，我也想反馈这个，firefox插件未更新
