### ISSUE TITLE
API下载功能已经失效(20210303开始)

### ISSUE THREAD

**Issue by newdive** [syhyz1990/baiduyun#36]
API下载使用的是: https://pan.baidu.com/api/sharedownload 
这个接口需要页面中 `yunData` 的 `sign` 参数
而今天( 也就是 20210303)下午share页面返回的数据中已经不再附加 `sign` 参数  
导致插件无法获取正确参数传给这个接口， 进而无法正常的获取文件下载链接
目前能获取文件下载链接的只有个人云盘的页面( 对应的API: https://pan.baidu.com/api/list )
悉知

**Comment by newdive** [comment]
期待解决方法

**Comment by syhyz1990** [comment]
> 期待解决方法

更新到最新版本试下，最好附上一个演示图

**Comment by newdive** [comment]
你好 更新到版本 `5.0` ， 也是有这个问题
    在share页面 点击 `API下载` `Aria下载` `RPC下载` 中的任何一个
    都会提示  `"登录网盘后才能使用此功能哦！"`

具体分析如下
1、页面返回的yunData只有  `{skinName:'white', neglect:1}`  ， 没法拿到 `bdstoken`  
     导致点击API下载的时候提示 `"登录网盘后才能使用此功能哦！"`
     而 `bdstoken` 数据是有的，只是设置在` locals ` 里,   参考我截取的share页面的返回（ `***`隐藏了私有数据 ）

``` 
<script type="text/javascript">
    function() {
        window.yunData={skinName:'white', neglect:1};
        locals.set('servertime', 1615248274054);
        locals.mset({"csrf":"***","uk":"***","username":"***","loginstate":1,"vip_level":*,"skinName":"white","bdstoken":"***","photo":"***","is_vip":1,"is_svip":1,"is_evip":0,"now":"***","XDUSS":"***","curr_activity_code":0,"show_vip_ad":0,"share_photo":"***","share_uk":"***","shareid":***,"hit_ogc":false,"expiredType":467923,"public":0,"ctime":***,"description":"","followFlag":0,"access_list_flag":true,"owner_vip_level":6,"owner_vip_type":2,"linkusername":"***","share_page_type":"multi","title_img":["***"],"file_list":[***],"errortype":-1,"errno":0,"self":0});
        require("disk-share:widget/system/util/contextExtend.js");
    }(); 
</script>
```

2、页面返回的数据中没有 `sign` 参数
      通过调试方法跳过 `bdstoken`的校验，进入请求 `https://pan.baidu.com/api/sharedownload`
     但由于接口的 `sign` 参数 为 `undefined`，导致请求失败，
    返回  `{"errno":2,"request_id":408920120914645841}`

**Comment by syhyz1990** [comment]
API要求登录后才能请求

**Comment by ZERO-5413** [comment]
在分享页面即使是登陆了也会提示"登录网盘后才能使用此功能哦！"

**Comment by newdive** [comment]
> API要求登录后才能请求

实际上是登录过的了  这个功能在3月3号之前是可以正常使用的(之前一直使用正常的)
只是3月3号之后百度云分享页面返回数据修改 （修改后的数据格式参考我之前分析的第一点）
导致无法获取`bdstoken` 从而误提示需要登陆

**Comment by History-exe** [comment]
同样有这个问题。我是ubuntu系统，网盘万能助手这个插件是靠转换，在firefox上安装的。之前一直正常。

**Comment by syhyz1990** [comment]
> > API要求登录后才能请求
> 
> 实际上是登录过的了 这个功能在3月3号之前是可以正常使用的(之前一直使用正常的)
> 只是3月3号之后百度云分享页面返回数据修改 （修改后的数据格式参考我之前分析的第一点）
> 导致无法获取`bdstoken` 从而误提示需要登陆

你打印下 yunData.MYBDSTOKEN 这个值是不是空

**Comment by Dealtz** [comment]
是的, 同样的问题.
即使登录后, 脚本仍然提示"登录网盘后才能使用此功能哦！"

**Comment by Dealtz** [comment]
> > > API要求登录后才能请求
> > 
> > 
> > 实际上是登录过的了 这个功能在3月3号之前是可以正常使用的(之前一直使用正常的)
> > 只是3月3号之后百度云分享页面返回数据修改 （修改后的数据格式参考我之前分析的第一点）
> > 导致无法获取`bdstoken` 从而误提示需要登陆
> 
> 你打印下 yunData.MYBDSTOKEN 这个值是不是空

为空
```
>yunData
{
    "skinName": "white",
    "neglect": 1
}
```

**Comment by newdive** [comment]
> > > API要求登录后才能请求
> > 
> > 
> > 实际上是登录过的了 这个功能在3月3号之前是可以正常使用的(之前一直使用正常的)
> > 只是3月3号之后百度云分享页面返回数据修改 （修改后的数据格式参考我之前分析的第一点）
> > 导致无法获取`bdstoken` 从而误提示需要登陆
> 
> 你打印下 yunData.MYBDSTOKEN 这个值是不是空

现在的返回数据结构已经变化，具体数据内容请详细参考我之前分析 的第一点中的代码

**Comment by syhyz1990** [comment]
更新到5.0.2试下

**Comment by newdive** [comment]
> 更新到5.0.2试下

另外的报错
![微信图片_20210312080312](https://user-images.githubusercontent.com/10500515/110871621-b33d1080-8309-11eb-8d4a-ff52ef78ddd3.png)

还有你这种修复方式解决不了问题  请参考我之前分析的第2条

**Comment by syhyz1990** [comment]
我这里没有问题

**Comment by newdive** [comment]
> 我这里没有问题

你自己试过share页面没？
这个例子给你看下   
百度飞桨产业应用案例精选：https://pan.baidu.com/s/1X2c711WhaTKyoqIkHxQ39g  密码: sq9s

**Comment by History-exe** [comment]
> 我这里没有问题

系统：ubuntu20.04.2
浏览器：Firefox 86.0
网盘万能助手版本：firefox插件转换的2.3.2
网盘直链下载助手版本：5.0.2

1. 在任意分享的界面点击下载助手按钮后，弹出的窗口一直在加载，无任何后续动作。
![2021-03-12 21-04-44 的屏幕截图](https://user-images.githubusercontent.com/33642965/110943816-9db20000-8376-11eb-825e-8659ef5718de.png)



2. 更新到5.0.2之后，配置界面错位。4K屏幕
![2021-03-12 20-59-06 的屏幕截图](https://user-images.githubusercontent.com/33642965/110943176-dd2c1c80-8375-11eb-8d89-a6fb7859098b.png)

**Comment by zensea** [comment]
> 一直转圈圈问题的原因

![微信图片_20210313130013](https://user-images.githubusercontent.com/6258888/111019732-114a2080-83fc-11eb-8ba1-cd80dd2efae4.png)

**Comment by newdive** [comment]
周末找了个时间看下  目前百度云修改下载文件时候 `sign`  和 `timestamp` 这两个参数的获取方式
这两个参数需要通过 `https://pan.baidu.com/share/tplconfig` 这个接口获取  
获取之后的参数会存储在 `window.locals` 中

目前想下有两种方法，作者可以参考下， 希望能有所帮助

1、先通过 `window.locals.get('sign')` 判断是否已经获了签名之类的参数
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;如果有可以直接从这里取出所需的所有参数  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;其它 的参数也可以用这种方法获取

2、如果还未获取 签名的相关参数  则可以通过 `https://pan.baidu.com/share/tplconfig` 这个api获取参数  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;下边是这个api的请求和返回的样例

```   
  GET https://pan.baidu.com/share/tplconfig?
        surl=可以通过解析share页面链接获取
        &fields=sign,timestamp  这里是要获取的参数名，多个则用逗号隔开
        &channel=chunlei
        &web=1
        &app_id=250528
        &bdstoken=bdstoken的值 （这个也可以通过 window.locals.get  获取）
        &logid=base64( Cookie中的 BAIDUID 属性 )
        &clienttype=0
  返回 
  {
     'errno': 0,
     'request_id': 527468549412033369,
     'data': {
        'timestamp': ***,
        'sign': '***'
     },
     'show_msg': 'success'
  }
```

**Comment by syhyz1990** [comment]
测试了一下，可行，稍后更新
