### ISSUE TITLE
百度账号被限制，未知错误[9013]

### ISSUE THREAD

**Issue by chinesepy** [syhyz1990/baiduyun#360]
如题，百度网盘权限被限制，下载别人分享的**文件夹**提示“未知错误[9013]，也无法转存别人的文件夹
跟百度客服扯了半个小时的皮之后告诉我是使用了“非官方客户端”导致的，好说歹说给解封了。
想确认下是否与此脚本有关，如果有类似的情况的朋友请留言。
![863b2e12a16decaf5612b6f03967c42](https://github.com/syhyz1990/baiduyun/assets/14289912/8994b8ec-e6d2-4a47-933b-0e34f475338b)

**Comment by sdy623** [comment]
改密码就恢复了
