### ISSUE TITLE
XDown 现在下载速度是被限制了吗？我用的是1.0.1.4版本，下载只有50kb/s ..求助！

### ISSUE THREAD

**Issue by pubdreamcc** [syhyz1990/baiduyun#361]
![1574128373(1)](https://user-images.githubusercontent.com/46315263/69109584-2be3e200-0ab3-11ea-84de-605a68f6b742.jpg)

**Comment by syhyz1990** [comment]
只有超级会员能帮你，骚年保重身体呀！91.rar

**Comment by pubdreamcc** [comment]
> 1.rar
....好吧，有更好的办法没

**Comment by abcfy2** [comment]
脱离百度保平安
