### ISSUE TITLE
mac  下不行了,一直403，不知道为啥？

### ISSUE THREAD

**Issue by Jason8Zhang** [syhyz1990/baiduyun#362]
INFO   2019-11-21 14:10:49 ( 1574316649 )   Opening LogFile...
INFO   2019-11-21 14:10:49 ( 1574316649 )   DownloadEngine State Changed : Unkown -> Starting...
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   DownloadEngine is Starting...
INFO   2019-11-21 14:10:49 ( 1574316649 )   Trying to Start Download for -> http://qdall01.baidupcs.com/file/719486d272a10dcf9edf76d5492c6b8f?bkt=en-cf7b18a7c51d9078ec91cb9916b2b5a0e3d28d3e75542b5f7b5d3e5abf6d0520ab41cf403f4e068b&fid=1628753341-265486-686639240197423&time=1574316648&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-Fwtb2ZrH%2F7eTBY2N%2F1hUQx5%2BO9k%3D&to=34&size=819548071&sta_dx=819548071&sta_cs=17&sta_ft=vep&sta_ct=5&sta_mt=1&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshanghai%2Cct&ctime=1569228924&mtime=1574135353&resv0=cdnback&resv1=0&resv2=rlim&resv3=5&resv4=819548071&vuk=1628753341&iv=-2&htype=&randtype=em&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-917f9c68fb4a9a3ff026b4890da1388d9d85fed95ef1c7e2dc3a70b140304f7990147a660738a17c&sl=81068110&expires=8h&rt=pr&r=845993137&mlogid=7528177942698527310&vbdid=2295882191&fin=1%E3%80%81Runtime%E5%BA%95%E5%B1%82%E5%8E%9F%E7%90%86%E5%88%86%E6%9E%90.vep&rtype=1&dp-logid=7528177942698527310&dp-callid=0.1.1&tsl=10&csl=10&csign=2GQLbUBx0USqUrRyY%2Fxdhaah7To%3D&so=1&ut=8&uter=0&serv=0&uc=3200815480&ti=26fa64dbec288224e2f799d7b907c74ace7d2b0a9db4e8b3305a5e1275657320&reqlabel=265486_d_5a80ab3c7afe7211ddcff0772fbe4911&by=themis
INFO   2019-11-21 14:10:49 ( 1574316649 )   DownloadID = 294 , Protocol = HTTP
INFO   2019-11-21 14:10:49 ( 1574316649 )   New Socket(s) Created. MaxAllowedConnection = 8 And ActiveSockets = 1
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   Socket ( 1 )  Connecting to  140.249.34.22:80 ...
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   SegmentManager Created a New Segment and now has 1 Segments.
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   Socket ( 1 ) HttpStatus =  HTTP_STATE_VOID  RoundNumberServer = 0 and RoundNumberProxy = 0
INFO   2019-11-21 14:10:49 ( 1574316649 )   Sending Http-GET  for Socket ( 1 )  Range = 0-
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_VOID  ->  HTTP_STATE_GET_SENT 
INFO   2019-11-21 14:10:49 ( 1574316649 )   GET Sent : 
<< GET /file/719486d272a10dcf9edf76d5492c6b8f?bkt=en-cf7b18a7c51d9078ec91cb9916b2b5a0e3d28d3e75542b5f7b5d3e5abf6d0520ab41cf403f4e068b&fid=1628753341-265486-686639240197423&time=1574316648&sign=FDTAXGERLQBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-Fwtb2ZrH%2F7eTBY2N%2F1hUQx5%2BO9k%3D&to=34&size=819548071&sta_dx=819548071&sta_cs=17&sta_ft=vep&sta_ct=5&sta_mt=1&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshanghai%2Cct&ctime=1569228924&mtime=1574135353&resv0=cdnback&resv1=0&resv2=rlim&resv3=5&resv4=819548071&vuk=1628753341&iv=-2&htype=&randtype=em&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-917f9c68fb4a9a3ff026b4890da1388d9d85fed95ef1c7e2dc3a70b140304f7990147a660738a17c&sl=81068110&expires=8h&rt=pr&r=845993137&mlogid=7528177942698527310&vbdid=2295882191&fin=1%E3%80%81Runtime%E5%BA%95%E5%B1%82%E5%8E%9F%E7%90%86%E5%88%86%E6%9E%90.vep&rtype=1&dp-logid=7528177942698527310&dp-callid=0.1.1&tsl=10&csl=10&csign=2GQLbUBx0USqUrRyY%2Fxdhaah7To%3D&so=1&ut=8&uter=0&serv=0&uc=3200815480&ti=26fa64dbec288224e2f799d7b907c74ace7d2b0a9db4e8b3305a5e1275657320&reqlabel=265486_d_5a80ab3c7afe7211ddcff0772fbe4911&by=themis HTTP/1.1
Host: qdall01.baidupcs.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Accept: */*
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Accept-Charset: *
Origin: https://pan.baidu.com
Referer: https://pan.baidu.com/disk/home?#/all?vmode=list&path=%2F%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99%2FiOS%E8%BF%9B%E9%98%B6%E5%88%B0%E9%A1%B9%E7%9B%AE%E5%AE%9E%E6%88%98%EF%BC%88%E9%80%BB%E8%BE%91%EF%BC%89%2F1%E3%80%81%E8%A7%86%E9%A2%91
Range: bytes=0-

>>
INFO   2019-11-21 14:10:49 ( 1574316649 )   All Response Headers For Socket ( 1 ) :
INFO   2019-11-21 14:10:49 ( 1574316649 )   
<<HTTP/1.1 403 Forbidden
Date: Thu, 21 Nov 2019 06:10:49 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
x-bs-client-ip: MTE2LjIyOC44OC4xOA==
x-bs-request-id: cWRiaC15dW4tYXJpZXMtcjEzNC05Ny0xNTMucWRiaC5iYWlkdS5jb206MTAuMTM0Ljk3LjE1MzoyMDEwOjc1MjgxNzc5NDI2OTg1MjczMTA6MjAxOS0xMS0yMSAxNDoxMDo0OQ==
Access-Control-Allow-Methods: HEAD, GET, OPTIONS, PUT, POST, DELETE
Access-Control-Allow-Headers: Range, Origin, Content-Type, Accept, Content-Length
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Accept-Ranges, Content-Range, Content-Length, ETag, x-bs-request-id
Access-Control-Allow-Origin: https://pan.baidu.com
Content-Length: 94
Remote-Ip: flowserver.pcs.bae.baidu.com
Server: POMS/CloudUI 1.0>>

DEBUG  2019-11-21 14:10:49 ( 1574316649 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_GET_SENT  ->  HTTP_STATE_PARSING_HTTP_HEADER 
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   Status Code For Socket (1 ) = 403
ERROR  2019-11-21 14:10:49 ( 1574316649 )   Handling Error - Socket ( 1 ) - SocketState =  HTTP_STATE_PARSING_HTTP_HEADER  ErrorText = HTTP/1.1 403 Forbidden
ERROR  2019-11-21 14:10:49 ( 1574316649 )   HTTP/1.1 403 Forbidden
INFO   2019-11-21 14:10:49 ( 1574316649 )   DownloadEngine State Changed : Starting... ( 4 ) -> Error
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   Socket ( 1 ) All Headers have been Parsed. Now HttpStatus =  HTTP_STATE_PARSING_HTTP_HEADER  And StatusCode = 403
ERROR  2019-11-21 14:10:49 ( 1574316649 )   Error Occurred. HTTP/1.1 403 Forbidden
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   DownloadEngine Is Terminating. EngineState = Error.
DEBUG  2019-11-21 14:10:49 ( 1574316649 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_PARSING_HTTP_HEADER  ->  HTTP_STATE_VOID 
INFO   2019-11-21 14:10:49 ( 1574316649 )   Closing LogFile.

![image](https://user-images.githubusercontent.com/10389173/69312176-30ea9200-0c69-11ea-9c59-956d2289b444.png)
![image](https://user-images.githubusercontent.com/10389173/69312189-3942cd00-0c69-11ea-8132-3a368c1df47b.png)

**Comment by syhyz1990** [comment]
下载太多,百度把你加入了黑名单
