### ISSUE TITLE
提示：获取下载链接失败！请刷新网页后重试！ 

### ISSUE THREAD

**Issue by maritimus0** [syhyz1990/baiduyun#363]
这是什么情况啊，我试了百度和迅雷，迅雷正常，是百度又作妖了吗

**Comment by xclimbing** [comment]
百度无法直接下载，跟楼主问题相同。但先转存到自己网盘再下载是可以的。

**Comment by maritimus0** [comment]
所以以后都必须先保存到自己网盘了吗






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月11日 16:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [syhyz1990/baiduyun] 提示：获取下载链接失败！请刷新网页后重试！ (Issue #363) |

百度无法直接下载，跟楼主问题相同。但先转存到自己网盘再下载是可以的。

**Comment by syhyz1990** [comment]
已修复，升级到6.2.5
