### ISSUE TITLE
macOS + Firefox 根本用不了

### ISSUE THREAD

**Issue by zoujiaqing** [syhyz1990/baiduyun#363]
什么狗屁东西，一会儿跳转到这一会儿跳转到那，装了这个还要装那个，还要执行脚本，最后还 TM 不能用。白 TM 发了两个小红包了。还要关注你妈 B 的服务号结果还用不了。

**Comment by zoujiaqing** [comment]
mlgb..

**Comment by TipzTeam** [comment]
This is your browser's problem, not this script's fault, as I can use it on my Hackintosh with macOS Catalina and Firefox.
