### ISSUE TITLE
访问www.baidu.com被修改了UA

### ISSUE THREAD

**Issue by abcfy2** [syhyz1990/baiduyun#364]
发现一个小BUG，同时安装了https everywhere会造成www.baidu.com无限跳转。

究其原因，是因为访问www.baidu.com的时候，UA被修改为LogStatics，导致百度强行将访问链接跳转为http，然后又被https everywhere跳转回https，无限循环，希望作者予以修复，应该仅仅下载百度云资源的时候再修改UA，而不是百度所有的网站都被修改UA

**Comment by syhyz1990** [comment]
感觉反馈 , 2.2.1 已修复此问题
