### ISSUE TITLE
Chrome 12月3日无法使用

### ISSUE THREAD

**Issue by Jim-Luo** [syhyz1990/baiduyun#368]
直接下载没反应，打开链接加载不出来

**Comment by madaopt** [comment]
Same issue here

**Comment by menshiyun** [comment]
Mark

**Comment by whynotjinx** [comment]
同样的问题
另：同时打开网盘会半卡死，不知道是不是也是插件的问题

**Comment by rilyuuj** [comment]
同样，点击直接下载无效

**Comment by jerryz1982** [comment]
访问https://qdall01.baidupcs.com/这个域名的请求连接被拒掉了。https可以响应，但是带着下载路径就被拒掉。
