### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by MrADus** [syhyz1990/baiduyun#369]
![image](https://github.com/syhyz1990/baiduyun/assets/96512594/ac2da9ed-4232-4cd9-ac2e-7eaa7ca84b2c)
无法下载

**Comment by toisard** [comment]
问问客服是不是被封号了

**Comment by CloudyEagle** [comment]
> 问问客服是不是被封号了

我两个SVIP账号在手机上能是能正常下载，用这个插件死活下载不了，奇怪的嘞。
我虽然是有SVIP，但不想下载电脑客户端占用硬盘空间，所需要调用软件的硬盘空间和系统资源占用比电脑客户端低很多。

**Comment by MrADus** [comment]
问百度客服？

Cloudy Eagle ***@***.***> 于2024年7月2日周二 11:00写道：

**Comment by CloudyEagle** [comment]
The Author of this Script has fixed in latest version. Please Update Quickly!!!

**Comment by MrADus** [comment]
Okay！

Cloudy Eagle ***@***.***> 于2024年7月17日周三 10:35写道：

**Comment by syhyz1990** [comment]
已修复，升级到6.2.5
