### ISSUE TITLE
12.05 限速只有几十KB，之前是15Mb/S

### ISSUE THREAD

**Issue by qiurigao** [syhyz1990/baiduyun#369]
换ip也没用

**Comment by SinDogle** [comment]
我这里大概500KB左右

**Comment by pleasecall** [comment]
我现在下载每个文件也只有10到20kb左右，如果下载多个项目的话，容易下载异常

**Comment by owenphx** [comment]
同样问题，从12月6号开始就是这样，之前无论下多少都是满速，用手机破解版狗度反而能拉到满速一半？

**Comment by sk1418** [comment]
我发现是不一样的文件, 速度不同.不知道什么规律, 但是"助手"还是可用状态.
基本都可以跑满带宽(家里100mbps), 有一些就是1Mbps以下

**Comment by syhyz1990** [comment]
更新至2.9.9
