### ISSUE TITLE
AriaNG 不能使用 aria2c 链接吗？

### ISSUE THREAD

**Issue by roro4ever** [syhyz1990/baiduyun#370]
环境：路由器R7000，使用梅林改版固件 380.70_0-X7.9.1，软件中心使用 aria2 插件 2.4 版本。

问题：aira2c 链接不能用于 AriaNG （可用于 xdown)。

**Comment by roro4ever** [comment]
https://github.com/koolshare/merlin-aria2, 这是 aria 插件的 repo

**Comment by whynotjinx** [comment]
删除前缀只保留引号里的应该是可以。。都是我最近都根本下不了。。。

**Comment by sk1418** [comment]
> 删除前缀只保留引号里的应该是可以。。都是我最近都根本下不了。。。

不可以的, 见 #371

**Comment by syhyz1990** [comment]
2.9.9 版本已经支持发送链接到aria , 需要配置rpc地址, 参见 https://www.baiduyun.wiki/zh-cn/rpc.html
