### ISSUE TITLE
在百度网盘用API下载失败问题

### ISSUE THREAD

**Issue by isyinxian** [syhyz1990/baiduyun#370]
不知道算不算一个bug，就是用在网页端的用下载助手里面的API下载，一直弹出：
**提示：获取下载链接失败！请刷新网页后重试**
不过，按照提示操作之后并没有下载，然后我点击了百度网盘自带的下载按钮之后，唤醒了IDM，显示是否下载（这个时候又可以直接下载）
反馈一下，遇到了，或许有用

**Comment by raging-flames** [comment]
并没有用，下载的是一个叫panlinker.user.js的文件

**Comment by isyinxian** [comment]
> 并没有用，下载的是一个叫panlinker.user.js的文件
> 
> 并没有用，下载的是一个叫panlinker.user.js的文件

可是，我这边是亲测有用

**Comment by syhyz1990** [comment]
已修复，升级到6.2.5
