### ISSUE TITLE
作者看下, 能不能在前端就提供这个功能(aria2c, jsonrpc) 已提供本地脚本链接

### ISSUE THREAD

**Issue by sk1418** [syhyz1990/baiduyun#371]
- WP助手可以导出(并copy)wp文件的aria2c下载命令, 这已经挺方便了. 但是每条命令都会新启动一个-aria2c进程, 无法利用当前的aria2c daemon.
- 特别是如果自己有aria2 server, 每次都要ssh进去, 再逐条执行命令
- 如果aria2c 跑在docker里, 就更麻烦, 还有进入docker环境(我的aria2c 在RaspberryPi的docker里)
- 即使通过ssh粘贴并启动aria2c命令, 也无法通过前端(比如ariaNG, webui等)监控下载情况和控制, 因为- 是不同的aria2c进程.

 因为导出的aria2c命令有cookie等, 无法通过UI只下载http(s)://.. 部分. 我不知是不是有更容易的办法, 就写了这个脚本(python)来实现. 我觉得如果前端可以实现就更好了:

https://github.com/sk1418/link2jsonrpc

**Comment by syhyz1990** [comment]
没太明白什么意思

**Comment by sk1418** [comment]
@syhyz1990 就是说, 你本地如果已经有aria2c daemon, 然后通过wp助手到处的aria2c下载命令, 每一条都会起一个aria2c进程, 而不用你本地的aria2c daemon, 同样, 你和那个daemon相关的web 前端也无法看到那些新的下载进程.
当然如果有远程的aria2c服务也是一样的道理.

**Comment by abcfy2** [comment]
js没权限访问本地文件。所以大多数aria2插件的做法都是得自己启动一个aria2c rpc，然后在插件配置rpc访问方式，通过发起网络请求调用

**Comment by sk1418** [comment]
@abcfy2 恩, 如果是本地local的aria2c进程可能不太容易, 因为没有网络路由. 
可如果有远程运行的aria2c daemon, 可以提供一个小界面, 用户可以输入rpc的url, token, 然后就发送到远程的aria2c daemon.

**Comment by syhyz1990** [comment]
这个已解决, 可以发送到任何rpc地址

**Comment by sk1418** [comment]
:+1:
