### ISSUE TITLE
百度网盘万能助手2.2导致贴吧无法打开精品贴，文库无法加载文件

### ISSUE THREAD

**Issue by Fyred** [syhyz1990/baiduyun#372]
![批注 2019-12-13 005136 PNG](https://user-images.githubusercontent.com/9011413/70732083-c5b14e80-1d42-11ea-9e4a-d77b81d7eb78.jpg)
更新了百度网盘万能助手2.2后，导致上图红圈处无法打开
百度文库无法加载文档内容

环境：360极速浏览器11.0.2251

**Comment by syhyz1990** [comment]
可以暂时禁用 , 需要的时候打开
