### ISSUE TITLE
The downloads are very slow 2.9.8

### ISSUE THREAD

**Issue by Superhackman** [syhyz1990/baiduyun#373]
The downloads are very slow with the latest version 2.9.8
![image](https://user-images.githubusercontent.com/27593140/70796447-48043780-1d70-11ea-8267-9fa8612f5255.png)

**Comment by Superhackman** [comment]
![image](https://user-images.githubusercontent.com/27593140/70797924-98c95f80-1d73-11ea-9c76-c548fc97d387.png)

**Comment by Iris-en** [comment]
same

**Comment by JerryCheng1** [comment]
Baidu is going to fail.
![QQ截图20191220150321](https://user-images.githubusercontent.com/12195659/71236452-fd6b5800-2339-11ea-8370-757f106c805d.jpg)

**Comment by syhyz1990** [comment]
update to 2.9.9
