### ISSUE TITLE
无意发现将百度网盘文件保存到自己网盘里，可以调用API下载

### ISSUE THREAD

**Issue by xmple067** [syhyz1990/baiduyun#374]
![微信截图_20240622160256](https://github.com/syhyz1990/baiduyun/assets/28042965/e655e82b-9153-48a3-bde2-4f6d736247f1)

**Comment by xmple067** [comment]
![Uploading 微信截图_20240622160256.png…]()

**Comment by qjliu258** [comment]
为什么我连显示那个下载助手都不显示了

**Comment by King-ZF** [comment]
> 为什么我连显示那个下载助手都不显示了

我也一样，不显示

**Comment by syhyz1990** [comment]
已修复，升级到6.2.5
