### ISSUE TITLE
百度网盘无法弹出链接

### ISSUE THREAD

**Issue by XoYaPeng** [syhyz1990/baiduyun#378]
![image](https://github.com/syhyz1990/baiduyun/assets/130196652/05541df2-e7e7-45e9-b000-e9da709e3437)
我在谷歌浏览器浏览器下载，但是无法弹出链接，但是在edge浏览器却是可以的，这是因为什么原因。两个浏览器的插件以及脚本配置都是一样的

**Comment by Dragon1573** [comment]
![image](https://github.com/syhyz1990/baiduyun/assets/49941141/5a63f271-4a85-4b5a-9765-6c8eb12531be)

我这里是直接转半天弹不出链接来

**Comment by CloudyEagle** [comment]
我是用Aria+XDown下载的，在Microsoft Edge上也是，Google Chrome没有尝试。
![Snipaste_2024-07-05_09-09-17](https://github.com/syhyz1990/baiduyun/assets/58777085/2bc8ef8b-7880-4368-9203-5d0aab8622a1)
之前以为是公司网的问题，后来回到家的宽带网络也是这样；
我还把拓展从浏览器卸载再重装脚本重装都还是没有用，有怀疑过账号问题，不过我两个SVIP账号在手机上都是能正常下载的，不知道啥情况。

**Comment by XoYaPeng** [comment]
@CloudyEagle 看来跟脚本有关系了，等待大佬修复。

**Comment by CloudyEagle** [comment]
The Author of this Script has fixed in latest version. Please Update Quickly!!!
