### ISSUE TITLE
最近一打开pan.baidu.com 卡死

### ISSUE THREAD

**Issue by linpan** [syhyz1990/baiduyun#381]
浏览器mac chrome
插件:最新版网盘下载助理;
一直显示加载:  https://pan.baidu.com/, 导致我这个chrome 都卡死了

如果关闭你的插件: 正常了.

**Comment by syhyz1990** [comment]
把网盘万能助手 禁用下
![image](https://user-images.githubusercontent.com/5344173/71567491-816fcd80-2afa-11ea-9a9a-c616f6f81b1e.png)
