### ISSUE TITLE
Mac 下无法使用

### ISSUE THREAD

**Issue by yasencoder** [syhyz1990/baiduyun#382]
Mac 下 NDM 403，aria 失败

**Comment by syhyz1990** [comment]
@yasencoder 参考https://www.baiduyun.wiki/zh-cn/rpc.html

**Comment by syhyz1990** [comment]
使用mortix

**Comment by yasencoder** [comment]
@syhyz1990  
1、使用插件 搭配mortix   下载百度云资源
2、点击发送到Aria，显示发送成功
3、打开 mortix 显示如下错误提示

Office.2019.Mac.16.30.mac-torrents.io.zip 下载发生错误 [#18](https://aria2.github.io/manual/en/html/aria2c.html#exit-status)
