### ISSUE TITLE
2.9.9 無法正常下載 右按下載會顯示 about:blank#blocked

### ISSUE THREAD

**Issue by tkp206093** [syhyz1990/baiduyun#383]
RT

**Comment by syhyz1990** [comment]
贴下图片

**Comment by tkp206093** [comment]
在自己的網盤下載中會這樣
在別人的分享連接不會

![image](https://user-images.githubusercontent.com/29872453/71611888-8c4c6000-2bd7-11ea-9d8e-ac217ed0a2fb.png)

**Comment by tkp206093** [comment]
使用迅雷演示
因為使用idm右按下載不會彈出任何視窗

使用瀏覽器右按新分頁都會有同樣效果

2.9.8版本完全沒有問題

**Comment by chad-it** [comment]
同上

**Comment by chad-it** [comment]
mac下新建任务链接为javascript:;

**Comment by tkp206093** [comment]
以及無法在自己的網盤中正常下載 想下載都需要分享

**Comment by tkp206093** [comment]
3.0.0 已修復問題
