### ISSUE TITLE
百度网盘不能正常的显示出下载助手

### ISSUE THREAD

**Issue by 001harmless** [syhyz1990/baiduyun#384]
换了两个浏览器都是这样，没有办法正常的显示出下载助手，有两次不知道为啥重装了一次之后能显示出来，然后再刷新又没了

**Comment by shikexuan666** [comment]
一样，百度网盘的分享链接界面，显示不出来“下载助手”的按钮选项了，但是进入度盘首页，可以正常显示“下载助手”

**Comment by Atul-8** [comment]
+1

**Comment by Clearlove2015** [comment]
![企业微信截图_20240717163914](https://github.com/user-attachments/assets/298e10d8-2b86-4fcd-97d5-da89e6f343ba)

// @require           https://unpkg.com/jquery@3.6.0/dist/jquery.min.js
// @require           https://unpkg.com/sweetalert2@10.16.6/dist/sweetalert2.all.min.js
// @require           https://unpkg.com/js-md5@0.7.3/build/md5.min.js
