### ISSUE TITLE
最新套件+範本無法顯示任何檔案

### ISSUE THREAD

**Issue by SUCM** [syhyz1990/baiduyun#385]
在全新安裝的火狐上安裝完最新套件+範本什麼設定都沒變更下
一旦開啟网盘万能助手檔案完全顯示不出來
![圖片](https://user-images.githubusercontent.com/7042609/71638794-ba4ba600-2ca4-11ea-82be-41f3b09d5470.png)
關掉网盘万能助手檔案就全都顯示出來了
![圖片](https://user-images.githubusercontent.com/7042609/71638795-c46da480-2ca4-11ea-8b8c-f33cea7a7617.png)

**Comment by syhyz1990** [comment]
只要不退出百度网盘就可以先禁用插件，获取的cookie一直存在本地的



---原始邮件---
发件人: "SUCM"<notifications@github.com&gt;
发送时间: 2020年1月1日(周三) 下午2:45
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 最新套件+範本無法顯示任何檔案 (#385)



在全新安裝的火狐上安裝完最新套件+範本什麼設定都沒變更下
 一旦開啟网盘万能助手檔案完全顯示不出來
 
 關掉网盘万能助手檔案就全都顯示出來了

**Comment by SUCM** [comment]
不太清楚那實際上應該如何使用呢？
禁用插件的話助手無法傳連結到aria2
可是啟用插件的話檔案全都不顯示而無法點選檔案。如你所看到的連下載助手選項都不會出現

**Comment by syhyz1990** [comment]
火狐的话 , 下个版本进行修复
