### ISSUE TITLE
无法连接到RPC服务，请检查RPC配置

### ISSUE THREAD

**Issue by SUCM** [syhyz1990/baiduyun#386]
助手RPC設定跟aria-ng還有webui-aria2一樣但是卻得到「无法连接到RPC服务，请检查RPC配置」的錯誤訊息。這部份希望範本能給更詳細的錯誤資訊方便debug
![圖片](https://user-images.githubusercontent.com/7042609/71639120-4bbe1680-2cab-11ea-823b-3ecbec13fa59.png)

但是aria-ng和webui-aria2在同一個火狐上跑卻都可以正常連上
![圖片](https://user-images.githubusercontent.com/7042609/71639136-ac4d5380-2cab-11ea-8051-31660122d4b5.png)
![圖片](https://user-images.githubusercontent.com/7042609/71639146-efa7c200-2cab-11ea-9752-63fd8bdbd621.png)

**Comment by syhyz1990** [comment]
临时解决方案是 使用懒人版 , 下个版本修复对火狐的支持

**Comment by SUCM** [comment]
一般Chrome只要一啟動就會開始對系統動手腳（自動添加砍不完的系統等級的更新排程和背景監控小程式、未經使用者同意傳輸資料到某伺服器、連結使用者沒在瀏覽的未知伺服器等等）
不知道這個懶人版本是否會有這類的問題

**Comment by SUCM** [comment]
更新後可以連上Aria2但是下載時永遠都是這個錯誤。Aria2設定裡面split=1所以應該是其他的問題
[HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403
