### ISSUE TITLE
2.x ~ 3.0下载都很慢，是否一定需要超级会员

### ISSUE THREAD

**Issue by SaferSky** [syhyz1990/baiduyun#387]
升级到3.0后问题依旧，30k左右，尝试过直链+IDM下载，aria+xdown，RPC+Motrix，尝试过改神秘代码，全都没效果。

付xdown设置，但应该是默认的没动过
![360截图20200101023434104](https://user-images.githubusercontent.com/6609835/71640489-e3861b00-2c3f-11ea-85e7-17d6092b7f3e.jpg)

**Comment by syhyz1990** [comment]
那是你的账号，被百度加黑名单了



---原始邮件---
发件人: "SaferSky"<notifications@github.com&gt;
发送时间: 2020年1月1日(周三) 晚上6:40
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 2.x ~ 3.0下载都很慢，是否一定需要超级会员 (#387)



升级到3.0后问题依旧，30k左右，尝试过直链+IDM下载，aria+xdown，RPC+Motrix，尝试过改神秘代码，全都没效果。
 
付xdown设置，但应该是默认的没动过

**Comment by SaferSky** [comment]
> 那是你的账号，被百度加黑名单了

这种情况换个号有效果吗，还是说需要其他办法？

**Comment by syhyz1990** [comment]
换账号只能保证速度在1m左右 , 超级会员不受限制 , 可无限下载

**Comment by lihangzju** [comment]
> 换账号只能保证速度在1m左右 , 超级会员不受限制 , 可无限下载

老哥，我本来是普通会员的，以前都能无限制慢速下载，最近被限制到2个线程了，看了你这话，我去升级了超级会员，结果还是2个线程啊。。。。。。。

**Comment by syhyz1990** [comment]
你升级到3.0.0 了么 , 不要用3.0以下的脚本 , 那个会限速  ,把神秘代码改成250528

**Comment by 405722907** [comment]
> 你升级到3.0.0 了么 , 不要用3.0以下的脚本 , 那个会限速 ,把神秘代码改成250528

请问最新版本的神秘代码在哪里修改啊?我怎么找不到
