### ISSUE TITLE
百度盘无法获取链接

### ISSUE THREAD

**Issue by vvv-347** [syhyz1990/baiduyun#388]
环境:
* Edge: Version 126.0.2592.102 (Official build) (64-bit)
* panlinker.user.js: Version 6.2.3

上下文描述:
1. 勾选文件后, 点击"下载助手", 任意下载方式, 均无法返回链接

截图:
![Snipaste_2024-07-20_16-48-55](https://github.com/user-attachments/assets/0872da07-1351-4322-907b-39b237a1bcc3)

**Comment by fgr178707** [comment]
我也是这个问题

**Comment by syhyz1990** [comment]
已修复，升级到6.2.5
