### ISSUE TITLE
无法在 Greasemonkey 里正常使用

### ISSUE THREAD

**Issue by xflcx1991** [syhyz1990/baiduyun#388]
Ubuntu 16.04，firefox。按照教程安装 Tampermonkey后确实可以用了。不过我原有的 Greasemonkey 安装本脚本缺没有「下载助手」按钮出现。这个以后是否考虑支持？

**Comment by syhyz1990** [comment]
Greasemonkey 的部分api和 Tampermonkey 无法保持一致 , 目前暂不考虑兼容
