### ISSUE TITLE
user is not authorized, hitcode:119

### ISSUE THREAD

**Issue by cwl168** [syhyz1990/baiduyun#391]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":45330156803164485}

**Comment by fighterhit** [comment]
+1 所有链接都是
`{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":60331634965093261}`

**Comment by ddgg** [comment]
mine is slightly different
{"error_code":4,"error_msg":"No permission to do this operation","request_id":nnnnnn...}

**Comment by syhyz1990** [comment]
非超级会员修改神秘代码为778750 , 超级会员改成250528

**Comment by TurnOffNOD** [comment]
> 
> 
> 非超级会员修改神秘代码为778750 , 超级会员改成250528

不管事了，我是超级会员，神秘代码250528输入进去之后还是403，hitcode:119.

**Comment by paladin4fan** [comment]
> 非超级会员修改神秘代码为778750 , 超级会员改成250528

不顶用了 非会员的那一串代码 链接会被重置 超级会员的代码 会提示user is not authorized, hitcode:119

**Comment by BoredBean** [comment]
> 非超级会员修改神秘代码为778750 , 超级会员改成250528

改成778750之后成功了一次，然后就又都失败了，而且这一次的速度和使用云盘客户端的速度没有差别

**Comment by myeveryheart** [comment]
@BoredBean 我和你的情况一模一样！
