### ISSUE TITLE
请勾选要下载的文件，若已勾选请重新勾选

### ISSUE THREAD

**Issue by jeffery9** [syhyz1990/baiduyun#392]
![image](https://user-images.githubusercontent.com/1404460/71778789-3a4b7600-2fed-11ea-8b73-977490ddb3b8.png)

**Comment by jeffery9** [comment]
mac osx 10.15.2   chrome 79

**Comment by Wilson-G** [comment]
我也遇到过,解决办法是把这个文件重命名一下 活着改一下文件位置 神奇的就过了
