### ISSUE TITLE
需要反复点击按钮才能发送到远程AriaRPC

### ISSUE THREAD

**Issue by shenghan97** [syhyz1990/baiduyun#393]
我在chrome中经常按“点击发送到Aria”按钮之后没有任何反应，远程服务的Aria也么有接收到任务，我必须反复点击若干次才能最终显示发送成功的弹窗，并且成功添加的远程服务器。BaiduExporter不存在这个问题

希望能够有改进！谢谢

**Comment by syhyz1990** [comment]
远程rpc服务的话根据服务器时间来的提示

**Comment by shenghan97** [comment]
> 远程rpc服务的话根据服务器时间来的提示

是因为两端时间不同步造成的吗？  问题是我点了之后不光没有成功的提示，远程rpc也没有收到任务

**Comment by syhyz1990** [comment]
主要是异步请求, 可能超时了
