### ISSUE TITLE
mac点击直接下载没有反应，且使用下载链接下载时，出现403错误

### ISSUE THREAD

**Issue by lybja** [syhyz1990/baiduyun#397]
mac点击直接下载没有反应，且使用下载链接下载时，出现403错误

**Comment by googooog** [comment]
同样的问题，我是超级会员，刚才还能下，现在一直显示403.
使用普通用户的神秘码可以下，但是只有两个线程，很慢

**Comment by syhyz1990** [comment]
可以试下分享后的下载链接

**Comment by zJoyceLee** [comment]
> 同样的问题，我是超级会员，刚才还能下，现在一直显示403.
> 使用普通用户的神秘码可以下，但是只有两个线程，很慢

请问普通用户神秘码是什么

**Comment by lybja** [comment]
分享之后的下载链接还是不行，不管是保存到自己网盘之后，还是保存完再分享出来的直接下载都是不好使的

**Comment by googooog** [comment]
确实不行，都是显示403

**Comment by as168795** [comment]
同 那种情况都是 403

**Comment by as168795** [comment]
噢 更新3.0.1分享可下 但是只有几百k的速度
