### ISSUE TITLE
下载速度好慢额

### ISSUE THREAD

**Issue by dingxiaolong** [syhyz1990/baiduyun#4]
mac使用motrix下载速度还是几十k,真的好慢额有啥解决办法么,直接下载按钮点击没反应

**Comment by yoooooolx** [comment]
几十K就是百度账号被ban了，据说大概一周后会恢复，期间换个号就正常了（如果不是网络问题的话）

**Comment by JancerWu** [comment]
一周后也没恢复。。。换了个账号又被ban了
