### ISSUE TITLE
3.03版aria2链接cookie错误

### ISSUE THREAD

**Issue by chen-assert** [syhyz1990/baiduyun#403]
我更换账号之后aria2链接怎么都下载不了,XDown显示403错误,仔细看了会发现是插件获取到的cookie不是我新的cookie,反而和我以前下载时用的cookie一样,手动替换aria2中cookie部分后可正常下载
重启过浏览器后问题依旧

**Comment by syhyz1990** [comment]
重新安装下万能助手



---原始邮件---
发件人: "chen-assert"<notifications@github.com&gt;
发送时间: 2020年1月29日(周三) 下午3:18
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 3.03版aria2链接cookie错误 (#403)



我更换账号之后aria2链接怎么都下载不了,XDown显示403错误,仔细看了会发现是插件获取到的cookie不是我新的cookie,反而和我以前下载时用的cookie一样,手动替换aria2中cookie部分后可正常下载
 重启过浏览器后问题依旧
