### ISSUE TITLE
导出到rpc的motrix应用，报#18错误aria2 could not create directory

### ISSUE THREAD

**Issue by chenweiyj** [syhyz1990/baiduyun#410]
macos 10.13 
motrix 1.4.1

导出到rpc的motrix应用，报#18错误aria2 could not create directory

**Comment by syhyz1990** [comment]
自己修改一下下载路径



---原始邮件---
发件人: "Chen Wei"<notifications@github.com&gt;
发送时间: 2020年2月6日(周四) 晚上10:18
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 导出到rpc的motrix应用，报#18错误aria2 could not create directory (#410)



macos 10.13
 motrix 1.4.1
 
导出到rpc的motrix应用，报#18错误aria2 could not create directory

**Comment by chenweiyj** [comment]
> 自己修改一下下载路径
> […](#)
> ---原始邮件--- 发件人: "Chen Wei"<notifications@github.com&gt; 发送时间: 2020年2月6日(周四) 晚上10:18 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [syhyz1990/baiduyun] 导出到rpc的motrix应用，报#18错误aria2 could not create directory (#410) macos 10.13 motrix 1.4.1 导出到rpc的motrix应用，报#18错误aria2 could not create directory — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

修改了也没用，换成/Users/xxx/Desktop 也是报同样的错误

**Comment by syhyz1990** [comment]
@chenweiyj 可能是你的权限不够
