### ISSUE TITLE
【显示链接】成功出现批量链接，却没有”复制全部链接“的按钮

### ISSUE THREAD

**Issue by liaodapo** [syhyz1990/baiduyun#411]
扩展均使用当前教程中提供版本。使用IDM方式下载，无论是集成的”懒人版“，还是手动安装到edge的方式，均未出现”复制全部链接“的按钮。但每个链接都可点击单独下载。

**Comment by syhyz1990** [comment]
此功能暂时失效，当前版本已去掉



---原始邮件---
发件人: "liaodapo"<notifications@github.com&gt;
发送时间: 2020年2月7日(周五) 下午3:52
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 【显示链接】成功出现批量链接，却没有”复制全部链接“的按钮 (#411)



扩展均使用当前教程中提供版本。使用IDM方式下载，无论是集成的”懒人版“，还是手动安装到edge的方式，均未出现”复制全部链接“的按钮。但每个链接都可点击单独下载。

**Comment by liaodapo** [comment]
感谢回复，请问有什么替代的办法吗，我尝试复制到excel分拣出超链接，但是都不能下载

**Comment by liaodapo** [comment]
> ·约
> [...](#)
> ---原始邮件--- 发件人: "liaodapo"<notifications@github.com&gt; 发送时间: 2020年2月7日(周五) 下午3:52 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [syhyz1990/baiduyun] 【显示链接】成功出现批量链接，却没有”复制全部链接“的按钮 (#411) 扩展均使用当前教程中提供版本。使用IDM方式下载，无论是集成的”懒人版“，还是手动安装到edge的方式，均未出现”复制全部链接“的按钮。但每个链接都可点击单独下载。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 此功能暂时失效，当前版本已去掉
> […](#)
> ---原始邮件--- 发件人: "liaodapo"<notifications@github.com&gt; 发送时间: 2020年2月7日(周五) 下午3:52 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [syhyz1990/baiduyun] 【显示链接】成功出现批量链接，却没有”复制全部链接“的按钮 (#411) 扩展均使用当前教程中提供版本。使用IDM方式下载，无论是集成的”懒人版“，还是手动安装到edge的方式，均未出现”复制全部链接“的按钮。但每个链接都可点击单独下载。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复，请问有什么替代的办法吗，我尝试复制到excel分拣出超链接，但是都不能下载

**Comment by syhyz1990** [comment]
@liaodapo 可以用这个方法

![1.gif](https://i.loli.net/2020/02/20/5thrvPi8CMsyfBN.gif)

**Comment by liaodapo** [comment]
@syhyz1990 感谢提点，这个方法试过了，之前也用过类似的方法，文件进入IDM后就会error。目前找到的相关说法是[百度在下载的时候检查了客户端](https://www.52pojie.cn/thread-964780-1-1.html)，但因方法过于盲繁，暂未采用
