### ISSUE TITLE
无法调用idm

### ISSUE THREAD

**Issue by Nyyyb** [syhyz1990/baiduyun#412]
1. 点击连接后或者点击直接下载后不会调用idm只会直接调用chrome自带的下载器 

2. API下载-显示连接 会显示所有链接但没有复制链接按钮 手动复制链接进入idm下载只会下载html文件

- IDM版本: 6.36build5
- 百度网盘直链下载助手版本: 3.0.3
- 百度万能助手版本: v2.2.1
- Chrome版本: 80.0.3987.87（正式版本） （64 位）

**Comment by Nyyyb** [comment]
> 1. 点击连接后或者点击直接下载后不会调用idm只会直接调用chrome自带的下载器
> * 其他网页点击下载可以正常调用idm比如说qq
> 2. API下载-显示连接 会显示所有链接但没有复制链接按钮 手动复制链接进入idm下载只会下载html文件

> * IDM版本: 6.36build5
> * 百度网盘直链下载助手版本: 3.0.3
> * 百度万能助手版本: v2.2.1
> * Chrome版本: 80.0.3987.87（正式版本） （64 位）

**Comment by syhyz1990** [comment]
安装idm插件了吗

**Comment by Nyyyb** [comment]
> 安装idm插件了吗

安装的呀 官网上说的不就是油猴的一个脚本和chrome扩展吗  idm插件也正常安装了呢
