### ISSUE TITLE
一直提示要先安装[网盘万能助手]，重启也用效！

### ISSUE THREAD

**Issue by mrmign** [syhyz1990/baiduyun#413]
![image](https://user-images.githubusercontent.com/1880532/74460941-b7a9b680-4ec8-11ea-9502-c1b7eba06f2f.png)
如上图所示，Chrome已经重启多次，一直是这样子提示，不知道哪里不对劲，麻烦看一下。谢谢

**Comment by syhyz1990** [comment]
直接点下载链接调用IDM下载就行了
