### ISSUE TITLE
找不到RPC导出设置的按钮

### ISSUE THREAD

**Issue by Yanstory** [syhyz1990/baiduyun#414]
如题，点击导出到RPC，只能看见导出到RPC的按钮，但是找不到RPC设置按钮

**Comment by syhyz1990** [comment]
![image](https://user-images.githubusercontent.com/5344173/74910950-97ad5200-53f6-11ea-87d1-73c2bf36b7f0.png)

**Comment by zenozhang26** [comment]
在很多情况下这个二级菜单是不显示的，mac+Chrome

**Comment by Yanstory** [comment]
> 在很多情况下这个二级菜单是不显示的，mac+Chrome
> 我认为是个判定bug

了解了
