### ISSUE TITLE
版本4.0，填写了普通用户的神秘代码，但依然显示为超级用户的，并没有修改成功

### ISSUE THREAD

**Issue by goeway** [syhyz1990/baiduyun#418]
如题。。。填写了XXXXX，重新打开神秘代码输入框时，依然显示为YYYYY

**Comment by syhyz1990** [comment]
不需要改了，都用250528就行。其他的暂时无效



---原始邮件---
发件人: "goeway"<notifications@github.com&gt;
发送时间: 2020年2月24日(周一) 凌晨0:56
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 版本4.0，填写了普通用户的神秘代码，但依然显示为超级用户的，并没有修改成功 (#418)



如题。。。填写了XXXXX，重新打开神秘代码输入框时，依然显示为YYYYY

**Comment by goeway** [comment]
收到，只是不知是不是因为我在一天内下载了3G多的东西还是这个月累积下载了超额的大小了，用IDM下载失败，用Xdown下载时显示为异常，用百度云盘下载则为4-7K每秒，我这是被限流量了吧？

**Comment by DavidpYau** [comment]
> 收到，只是不知是不是因为我在一天内下载了3G多的东西还是这个月累积下载了超额的大小了，用IDM下载失败，用Xdown下载时显示为异常，用百度云盘下载则为4-7K每秒，我这是被限流量了吧？

百度近来我觉得疯了，应该限制的厉害了，找了个V下了一个文件，然后第二个文件速度就<50k了，我自己的号也早就下不动了

**Comment by ws511341206** [comment]
为啥我没有api选项呢

**Comment by syhyz1990** [comment]
> 为啥我没有api选项呢

我的网盘里有

**Comment by gearfox** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":1475295416652148898}

**Comment by CYFchenyifei** [comment]
楼上我也是，如果使用IDM之后会出现 **IDM 拦截了根据BAIDUPCS.COM 网站设置只能请求一次的下载**
