### ISSUE TITLE
未识别到idm

### ISSUE THREAD

**Issue by Mint328** [syhyz1990/baiduyun#42]
已安装idm，并且可以通过idm成功下载，但是脚本页面提示未识别到idm。此问题大概率出现，我下载了90个左右的图片，只有大概8次左右显示通过idm下载，其他全部识别失败。

**Comment by Mint328** [comment]
edge浏览器，油猴4.61.6120，脚本5.1.0

**Comment by syhyz1990** [comment]
检查IDM扩展是否安装

**Comment by Mint328** [comment]
> 检查IDM扩展是否安装
扩展是安装了的

**Comment by syhyz1990** [comment]
图片后缀添加到IDM下载列表

**Comment by Mint328** [comment]
> 图片后缀添加到IDM下载列表

添加了的。。
都是png图片，有部分能下载，有部分不能。。。。

**Comment by Mint328** [comment]
> 图片后缀添加到IDM下载列表

刚才找了几个试了下又都是正常的。。
以后如果再出问题的话，我再看看。。
