### ISSUE TITLE
最新4.0版本下载老实报403: User not authorized 错误

### ISSUE THREAD

**Issue by wsw201009** [syhyz1990/baiduyun#421]
您好，安装了新的4.0版本后，无论是直接下载，或者是保存到网盘后导出API连接后下载，系统都是显示403：User not authorized 错误。没升级到这个版本前是完全没有问题的。也试过改用另外一个百度账号，但都是显示同样的403错误，请问有解决方法吗？或者是，可以给我连接安装上一个版本吗？谢谢

**Comment by Sheldonsuckz** [comment]
Hi running into the same problem. Receive a 403 error when downloading on the new 4.0.0 update.

**Comment by rwat1** [comment]
'I also have 403 error.

**Comment by yanxublack** [comment]
同样不能正常使用

**Comment by 510846** [comment]
情况一样。。。恢复到上一版本，神秘代码改不了 @@

**Comment by myeveryheart** [comment]
恢复到上个版本问题依旧

**Comment by CNaatest** [comment]
==**最新版所有连接直接报错，http 1.1 403 forbidden。是只有我这样么？**==

**Comment by PRO-2684** [comment]
一开始可以下载，过了不久后正在下载的速度变慢，并且新下载的提示403
