### ISSUE TITLE
【新4.0版本问题】下载速度突然变慢了

### ISSUE THREAD

**Issue by GareArc** [syhyz1990/baiduyun#422]
更新4.0之前刚好下载了一个文件，速度是8M/s，更新了以后就恒定200KB/s怎么也提不上去。。IDM下载界面里面一直在刷disconnected。难道是我的号突然进黑名单了吗QAQ

**Comment by StackL0nG** [comment]
我也是，IDM的多线程启动不了

**Comment by blueqblood** [comment]
同问题，4.0变成龟速了，还不如度自己下的速度高

**Comment by CoderShmily** [comment]
一样呀，升级完速度几十K了，怎么安装旧版呀

**Comment by GareArc** [comment]
旧版也不行了。。

**Comment by yanyingwang** [comment]
哈哈哈哈

**Comment by CYFchenyifei** [comment]
没错只有两个线程，超级慢
