### ISSUE TITLE
没有用油猴用的插件版本，好像会拦截百度文库，一直转，不显示

### ISSUE THREAD

**Issue by redleafnew** [syhyz1990/baiduyun#423]
没有用油猴用的插件版本，好像会拦截百度文库，一直转，不显示。版本2.2.1

**Comment by syhyz1990** [comment]
火狐暂时会有这个问题 , 可以先关闭 

![image](https://user-images.githubusercontent.com/5344173/75506799-19fecd00-5a1a-11ea-870f-44fa081f8473.png)

**Comment by redleafnew** [comment]
谢谢。
