### ISSUE TITLE
aria rpc下载一次只能下一个？

### ISSUE THREAD

**Issue by liwei1997** [syhyz1990/baiduyun#429]
我rpc发送一个到aria rpc 在发送一个就不能下载了 只能等一个下载完再发送一个是这样吗？
还是我aria设置的有问题？

**Comment by syhyz1990** [comment]
你可以一直发送但非超级会员一次只能下载一个



---原始邮件---
发件人: "李伟"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 上午6:07
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] aria rpc下载一次只能下一个？ (#429)



我rpc发送一个到aria rpc 在发送一个就不能下载了 只能等一个下载完再发送一个是这样吗？
 还是我aria设置的有问题？
