### ISSUE TITLE
4.0版本，API下载->直接下载 console 400 Bad Requst

### ISSUE THREAD

**Issue by Adam0407** [syhyz1990/baiduyun#430]
出现以上错误，无法下载，选择显示链接也是同样问题，无法解析到正确的下载地址

**Comment by Adam0407** [comment]
刚刚仔细看了下报错的下载链接，显示app_id = undefined，不知道是不是app_id获取异常所导致的结果

**Comment by druginmind** [comment]
同400错误，25日之后就不能使用了

**Comment by syhyz1990** [comment]
点击 API下载 -> 恢复默认 试下
