### ISSUE TITLE
API下载点击后出现错误

### ISSUE THREAD

**Issue by jie991230** [syhyz1990/baiduyun#431]
API下载点击后出现错误 
{"error_code":31023,"error_msg":"param error","request_id":1458514140645515339}

**Comment by syhyz1990** [comment]
@jie991230 是否为超级会员 , 神秘代码写的多少?

**Comment by gearfox** [comment]
我也是这个错误，神秘代码250528，重新获取新的提示错误

**Comment by syhyz1990** [comment]
改成778750试下

**Comment by syhyz1990** [comment]
改成778750试下

**Comment by skilyxx** [comment]
`778750`亲测有效
