### ISSUE TITLE
怎麼一直重複出現要我輸入暗號

### ISSUE THREAD

**Issue by NeiL978** [syhyz1990/baiduyun#433]
你好
我安裝了4.0.0版的助手
我連結到了百度網盤後，它顯示要我輸入暗號
我也去微信取的暗號且輸入了
他也顯示暗號正確，正在初始化中的視窗。
然後他就開始重新整理了頁面 卻又要我再輸入一次暗號？
一直重複循環這樣的動作。

**Comment by NeiL978** [comment]
請問該怎麼解決？？

**Comment by syhyz1990** [comment]
是不是安装了多个助手 , 把其他的禁用掉

**Comment by NeiL978** [comment]
只有裝一個 但是我是裝在adguard中 不知道是不是這個問題
