### ISSUE TITLE
5.1.0 无法使用

### ISSUE THREAD

**Issue by maxhuangping** [syhyz1990/baiduyun#44]
![image](https://user-images.githubusercontent.com/34203062/111862292-60113080-898f-11eb-8401-649a42244c33.png)

更新完 ，暗号也搞过了，还是要求重启浏览器，我电脑都重启了！

**Comment by wsxceerf** [comment]
同，下了懒人版还是一样的情况……

**Comment by syhyz1990** [comment]
建议使用 Tampermonkey
