### ISSUE TITLE
errorCode=22 The response status is not successful. status=400 复制aria链接到terminal里下载失败

### ISSUE THREAD

**Issue by huyaxiong** [syhyz1990/baiduyun#441]
![image](https://user-images.githubusercontent.com/6245250/77165319-feed1d80-6aec-11ea-92af-e1ff2d0ae1e7.png)

![image](https://user-images.githubusercontent.com/6245250/77165277-f0066b00-6aec-11ea-847c-c04b6463704e.png)

**Comment by syhyz1990** [comment]
@huyaxiong 恢复一下默认代码

![image](https://user-images.githubusercontent.com/5344173/77608195-80aed200-6f57-11ea-92cd-3db1571c2278.png)
