### ISSUE TITLE
关于两个作者做的字体和夜间模式的脚本

### ISSUE THREAD

**Issue by gittohabo** [syhyz1990/baiduyun#442]
我点击下载后，直接触发了浏览器的下载，而不是像在greasyfork里面的安装页面。下载完了后，Chrome直接提示无法安装脚本。
于是尝试直接去油猴的后台导入脚本，也不行。
有人也是这个情况吗？

**Comment by syhyz1990** [comment]
要先安装tampermonkey



---原始邮件---
发件人: "gittohabo"<notifications@github.com&gt;
发送时间: 2020年3月23日(周一) 中午1:32
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 关于两个作者做的字体和夜间模式的脚本 (#442)




 
我点击下载后，直接触发了浏览器的下载，而不是像在greasyfork里面的安装页面。下载完了后，Chrome直接提示无法安装脚本。
 于是尝试直接去油猴的后台导入脚本，也不行。
 有人也是这个情况吗？

**Comment by gittohabo** [comment]
油猴肯定安装了的，在greasyfork装其他脚本的时候，油猴会正常弹出安装页面。但点作者的安装，就会变成调用浏览器的下载功能。

**Comment by syhyz1990** [comment]
我试了下是不会的 , 你可以新建一个脚本 , 把代码复制进去
