### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xzw2935** [syhyz1990/baiduyun#443]
idm弹出无权限，xdown显示异常，aria提示HTTP返回头无效....有的文件可以下载但是也很慢

**Comment by allen43** [comment]
> idm弹出无权限，xdown显示异常，aria提示HTTP返回头无效....有的文件可以下载但是也很慢

应该崩了，不如私信我网盘24小时，租用价格2.5元。微信comm2312

**Comment by HustreLiny** [comment]
> > idm弹出无权限，xdown显示异常，aria提示HTTP返回头无效....有的文件可以下载但是也很慢
> 
> 应该崩了，不如私信我网盘24小时，租用价格2.5元。微信comm2312

HH,某平台上的正经会员才七八块一个月，您这确实来钱快
