### ISSUE TITLE
宽带提速脚本

### ISSUE THREAD

**Issue by EricMzky** [syhyz1990/baiduyun#447]
宽带提速，点击一键提速后，显示 没有登录账号，并且无法登陆账号。无法提速。

**Comment by syhyz1990** [comment]
等待修复 , 可以先去APP上提速

**Comment by EricMzky** [comment]
> 等待修复 , 可以先去APP上提速
小翼管家上面最近不可以提速了。始终获取不到宽带账号。之前一直都可以。
