### ISSUE TITLE
Mac端直接下载无效

### ISSUE THREAD

**Issue by smelloftime** [syhyz1990/baiduyun#448]
软硬件环境：MAC 10.14.6 (18G95)，Chrome 80.0.3987.149，脚本 4.0.0，
网络环境：四川省成都市 电信
bug：点击“API下载”，页面无跳转，浏览器控制台获取到错误信息：
Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by syhyz1990** [comment]
使用 Mortix & rpc下载 试下

**Comment by Wizard23333** [comment]
几周前的某一天好像可以的，现在好像只能下小文件，mp4格式的无论大小一律不能下
