### ISSUE TITLE
希望免登陸回歸。

### ISSUE THREAD

**Issue by superiver0** [syhyz1990/baiduyun#449]
登錄賬號後賬號被黑，拉入黑名單限速無法下載：IDM無法下載文件，下載下來的不是網盤內的壓縮包而是無格式文件，下載開始後直接403；XDOWN建立鏈接後下載顯示-異常；ARIA2導入下載文件後下載文件直接失敗。腳本的所有方式在登錄賬號的情況下都無法下載，強烈希望免登陸回歸。希望版主能夠關注一下。@syhyz1990

**Comment by syhyz1990** [comment]
目前百度的API不支持了
