### ISSUE TITLE
如何下載不被拉入黑名單限速10kb/s？

### ISSUE THREAD

**Issue by superiver0** [syhyz1990/baiduyun#456]
版主說目前百度的API不支持免登陸下載所以無法免登錄，那麼最今天又更新了版本到4.1.0，問一下何時的版本能夠下載而不被拉入黑名單限速10kb/s？否則下載一個就拉入黑名單了，腳本就是廢的呀。不行，無論是直接點擊油猴，https://wx3.sinaimg.cn/mw690/006LEJLmly1gdjmj8dr9aj307607w3yn.jpg
還是在油猴裡面點開設置：https://wx3.sinaimg.cn/mw690/006LEJLmly1gdjmnkwky7j30bo06w3yt.jpg
https://wx1.sinaimg.cn/mw690/006LEJLmly1gdjmqekimyj31gm0nign8.jpg
https://wx2.sinaimg.cn/mw690/006LEJLmly1gdjmqhc2gdj31gu0i5t9r.jpg
全都沒有找到設置和腳本配置。對於我們這些無法像你給的示意圖那樣操作的用戶版主可不可以直接幫我們配置好了呀？謝謝啦。否則完全用不了呀。
好了，現在油猴腳本已經出現設置了，第二個問題解決了，就差第一個問題了，也就是黑名單限速的問題。

**Comment by GareArc** [comment]
其实我想说如果知道什么版本可以不被拉黑名单的话脚本早就更新了吧，现在百度云恶心的连超级会员都会加黑名单，估计只能等了。。

**Comment by superiver0** [comment]
試了一下，4個備用鏈接導入到RPC下載後全部只有兩線程，速度都為40KB/S左右。

**Comment by Kuroneko0420** [comment]
目前来说，这个脚本不能用了吧，idm是403，xdown是异常
