### ISSUE TITLE
修改了User-Agent后可以用Aria2下载了，但是速度依旧很慢

### ISSUE THREAD

**Issue by ocdman** [syhyz1990/baiduyun#460]
将原来的aria2下载链接中的--header "User-Agent: XXX"，改为--header "User-Agent: LogStatistic"后，不会报403错误了。

但是电信平均下载速度只有70KB，移动平均下载速度40KB。

**Comment by LeiDoubi** [comment]
@ocdman 按照你的方法后尝试了一下，确实没有了403问题。我这边默认设定的是64线程，第一次对某资源下载时6个有效，我嫌太慢就终止了下载。在接下来的几次尝试时每次就只有1个线程有效了，这还是在我有会员的情况下，很明显百度那边做了限制。不过我很好奇大佬是怎么知道修改User-Agent 能够解决不能下载的问题的

**Comment by ocdman** [comment]
@LeiDoubi 很简单，你把aria2的下载链接放浏览器里执行，后台抓包就能看到了

**Comment by LeiDoubi** [comment]
@ocdman 我在浏览器的network 里能 看到访问的资源被redirect 了 并且 由于新网址域的改变导致cookies 没有被一同附在新的请求的 header 里面，所以就403 了。还请大佬详细指导一下小菜鸡怎么知道修改User-Agent 有效的，不胜感激

**Comment by ocdman** [comment]
@LeiDoubi 大佬不敢当，我也是自己试出来的。因为我发现浏览器下打开下载链接是可以直接下载的。所以就去看Network下的Request Headers里参数，发现User-Agent变成了LogStatistic。
