### ISSUE TITLE
兄弟，城通网盘下载不了你的这个插件，必须先买城通的会员

### ISSUE THREAD

**Issue by sanigo** [syhyz1990/baiduyun#461]
能否放在github的release里？

**Comment by syhyz1990** [comment]
直接点击普通下载就可以了



---原始邮件---
发件人: "sanigo"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 上午10:45
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 兄弟，城通网盘下载不了你的这个插件，必须先买城通的会员 (#461)




 
能否放在github的release里？

**Comment by plus-zhang** [comment]
> 直接点击普通下载就可以了
> […](#)
> ---原始邮件--- 发件人: "sanigo"<notifications@github.com&gt; 发送时间: 2020年4月7日(周二) 上午10:45 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [syhyz1990/baiduyun] 兄弟，城通网盘下载不了你的这个插件，必须先买城通的会员 (#461) 能否放在github的release里？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

普通下载也需要会员了, 试了IE, Edge,Chrome都会有会员提示

**Comment by sanigo** [comment]
普通下载也不让下啦，很无语。。。

**Comment by yangge8522424** [comment]
无法下载城通网盘里的网盘万能助手，普通下载也不行。提示升级VIP会员

**Comment by shenmeiqian** [comment]
老哥 下载不了了，推荐你用蓝奏云保存文件，不限速，还干净

**Comment by syhyz1990** [comment]
稍后换个网盘
