### ISSUE TITLE
诚通网盘

### ISSUE THREAD

**Issue by 438763751** [syhyz1990/baiduyun#462]
大佬  用诚通网盘下载不了呀，说文件保存时间已过期，能换个网盘吗

**Comment by syhyz1990** [comment]
没看到有备用的吗？



---原始邮件---
发件人: "438763751"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 中午1:31
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 诚通网盘 (#462)




 
大佬  用诚通网盘下载不了呀，说文件保存时间已过期，能换个网盘吗

**Comment by 438763751** [comment]
额  着实尴尬  我看到过  但从来没点过
