### ISSUE TITLE
提取码自动共享了？

### ISSUE THREAD

**Issue by blueqblood** [syhyz1990/baiduyun#464]
下了个文件竟然没用提取码

**Comment by syhyz1990** [comment]
只调用接口获取，放心不会上传提取码的，



---原始邮件---
发件人: "bqb"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 晚上6:56
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/baiduyun] 提取码自动共享了？ (#464)




 
下了个文件竟然没用提取码
