### ISSUE TITLE
api域名突然502.（baiduyun.wiki）均无法访问

### ISSUE THREAD

**Issue by ckx000** [syhyz1990/baiduyun#468]
www和api的baiduyun.wiki的地址均无法解析访问了，
打开du盘页面 脚本也不显示下载按钮了。。
就在几个小时前我还是正常的。。然后现在就突然打不开了。。是服务器挂了还是？？
联想到今天出新闻说那个下载软件pandown的作者被抓事件，，，
作者你还好吗？

**Comment by lyscop** [comment]
R.I.P

**Comment by shezik** [comment]
救救孩子……

**Comment by shezik** [comment]
希望作者只是去避避风头了，别真是同一个人做的……

**Comment by InitialYsky** [comment]
同，我在pd挂了之后找到这个的，我挂上随便下了个网盘软件测速来着，下完没多久这就挂了，我头一次离新闻这么近……

**Comment by ckx000** [comment]
我晚上9点的时候还正常用了下
11点的时候刷新了 突然发现按钮没了，f12看一下 api域名挂掉了。我就觉得不对劲，，
刚才紧急扒代码分析了下，强行注释掉请求服务器api的地方，能凑合获得直接连接了。
然而只能让浏览器直接慢速下载，想要给idm调用下载 还需要作者api返回的userAgent参数和ids参数，，到这里我就没辙了。唉。。难道真的要RIP了吗。。

**Comment by hentaiwhite** [comment]
一直用这个，希望作者平安无事。

**Comment by hyf6661669** [comment]
好人一生平安，希望作者好运

**Comment by EricMzky** [comment]
啊啊啊啊啊 最后的希望啊。
