### ISSUE TITLE
貌似现在不能用了？

### ISSUE THREAD

**Issue by JasonkayZK** [syhyz1990/baiduyun#472]
RT…

**Comment by yinbun** [comment]
估计百度加多了点东西，让文件也套了一个文件夹，导致下载文件时也显示是文件夹

**Comment by JasonkayZK** [comment]
> 
> 
> 估计百度加多了点东西，让文件也套了一个文件夹，导致下载文件时也显示是文件夹

啊…这……，那现在怎么解决呢大佬= =

**Comment by syhyz1990** [comment]
> > 估计百度加多了点东西，让文件也套了一个文件夹，导致下载文件时也显示是文件夹
> 
> 啊…这……，那现在怎么解决呢大佬= =

更新后解决

**Comment by JasonkayZK** [comment]
> 
> 
> > > 估计百度加多了点东西，让文件也套了一个文件夹，导致下载文件时也显示是文件夹
> > 
> > 
> > 啊…这……，那现在怎么解决呢大佬= =
> 
> 更新后解决

好的，感谢!♥
