### ISSUE TITLE
失效了吗？

### ISSUE THREAD

**Issue by Echardwang** [syhyz1990/baiduyun#49]
下载按钮不见了

**Comment by xsm1997** [comment]
`https://api.baiduyun.wiki/upgrade?ver=5.1.3&a=YouXiaoHou`返回404

**Comment by Echardwang** [comment]
> `https://api.baiduyun.wiki/upgrade?ver=5.1.3&a=YouXiaoHou`返回404

我可以正常更新但是不知道为什么百度网盘里面没有下载助手的下载按钮了，他们官网里面也没有这个助手的链接了

**Comment by machdive** [comment]
> > `https://api.baiduyun.wiki/upgrade?ver=5.1.3&a=YouXiaoHou`返回404
> 
> 我可以正常更新但是不知道为什么百度网盘里面没有下载助手的下载按钮了，他们官网里面也没有这个助手的链接了

复议

**Comment by ShionjiART** [comment]
确实不见了

**Comment by o1232000** [comment]
不见了+1

**Comment by xiaolu3550** [comment]
+1

**Comment by heyun666** [comment]
+1

**Comment by keniji** [comment]
+1, 只能等一个不知道还会不会有的修复..

**Comment by sunnyjackyang** [comment]
复议

**Comment by sunnyjackyang** [comment]
<img width="1414" alt="1" src="https://user-images.githubusercontent.com/34548222/114963550-96af6d80-9e9f-11eb-8580-e61ddf1209f5.png">

这是官网关于这个脚本唯一存在的地方

**Comment by ZhaoqiangCn** [comment]
+1

**Comment by debugbb** [comment]
按钮不见了+1

**Comment by ShionjiART** [comment]
昨天开始就不见了

**Comment by main2018** [comment]
+1

**Comment by stu640978** [comment]
+1

**Comment by keniji** [comment]
> <img alt="1" width="1414" src="https://user-images.githubusercontent.com/34548222/114963550-96af6d80-9e9f-11eb-8580-e61ddf1209f5.png">
> 
> 这是官网关于这个脚本唯一存在的地方

这样看来怕不是又被毒娘搞趴下了..

**Comment by gouheng** [comment]
垃圾百度网盘

**Comment by iDTer** [comment]
+1

**Comment by ZaoRiTian** [comment]
前天还用来下了Mindustry的，今天不显示了。。。。。。

**Comment by RustDesert** [comment]
+1，最近按钮一直都消失的，而且好像还从油小猴官网上消失了

**Comment by duanpj001** [comment]
不知道是不是被百度盯上了,有能力的同学可以自己修改一下脚本,测试过还能用

**Comment by main2018** [comment]
@duanpjGit 求指教

**Comment by duanpj001** [comment]
> @duanpjGit 求指教

交流一下https://t.me/joinchat/4u9ZibJiSzAwODNl

**Comment by main2018** [comment]
@duanpjGit 
😅
![image](https://user-images.githubusercontent.com/28427901/115192479-72f95b00-a11d-11eb-8882-c9ca1dd7e641.png)

**Comment by szehoi-wu** [comment]
> > @duanpjGit 求指教
> 
> 交流一下https://t.me/joinchat/4u9ZibJiSzAwODNl

可以了，感谢老哥。
