### ISSUE TITLE
不能用IDM下载大于1G的文件或文件夹

### ISSUE THREAD

**Issue by wuchangmin** [syhyz1990/baiduyun#49]
我的IDM设置了最大连接数32，其他默认。已按提示登录。无论是自己分享还是别人分享的都下载不了。一直以来这个脚本给了我很大便利，希望不要需要特别复杂的步骤才能下载，再次感谢开发者的辛苦。

**Comment by syhyz1990** [comment]
@wuchangmin 这是百度服务器的限制，我也没办法

**Comment by aloneZERO** [comment]
我这边可以下，尝试了一个1.2G的文件（分享的）。只不过IDM下载连接只能达到4个。。。

**Comment by wuchangmin** [comment]
没用，降低下载连接数到4个或1个都没有反应，直接用浏览器下载也没有反应，只能下载小于1G的文件。
