### ISSUE TITLE
Mac 使用Folx下载有问题？

### ISSUE THREAD

**Issue by Destinyxl** [syhyz1990/baiduyun#5]

**Comment by Destiny7777** [comment]
下载一会就没动静了，已经很久了

**Comment by clock-z** [comment]
显示连接：显示获取的链接，可以使用右键迅雷或IDM下载，复制无用，需要传递cookie
复制连接地址后粘贴到folx里，显示如下：
![Xnip2019-04-07_01-36-58](https://user-images.githubusercontent.com/37953042/55673099-b9ccdd00-58d5-11e9-9a34-8b76cbacc80b.jpg)
这是无法搭配使用folx下载百度云盘内容么？

**Comment by syhyz1990** [comment]
复制链接不带cookie ,获取不到真实地址的
