### ISSUE TITLE
不显示下载助手按钮，版本5.13

### ISSUE THREAD

**Issue by lxn-net** [syhyz1990/baiduyun#51]
不显示下载助手按钮，版本5.13

**Comment by AlieinApril** [comment]
+1

**Comment by OcenYu** [comment]
+1

**Comment by qingyuchan** [comment]
+1

**Comment by xiaolizi-oss** [comment]
+1

**Comment by CloudyEagle** [comment]
是啊，我也是用到5.1.3后用不了，没动静。
是不是被百度函告后跑路了呀？！
目前是用Greasy Fork上找到的{软件小妹妹}的，
稍微看了下代码，感觉思路都是差不的。
也许为了可用借鉴了一点，
但这边一点动静都没有有点担心原作者是不是被百度请去喝茶了哈！？

**Comment by syhyz1990** [comment]
不存在的，开发者的APPID到期而已
