### ISSUE TITLE
无法安装 网盘万能助手

### ISSUE THREAD

**Issue by fredericky123** [syhyz1990/baiduyun#54]
https://www.youxiaohou.com/zh-cn/assistant.html
这里的网盘万能助手，在线安装会弹出一个assistant.crx的文件，拖到chrome浏览器后虽然能安装，但是被无法开启启用
Chrome 90.0.4430.93
请问如何解决？
![image](https://user-images.githubusercontent.com/13982749/117447380-0204d080-af70-11eb-98c0-83d03e867912.png)

**Comment by fhfshkkmk** [comment]
> https://www.youxiaohou.com/zh-cn/assistant.html
> 这里的网盘万能助手，在线安装会弹出一个assistant.crx的文件，拖到chrome浏览器后虽然能安装，但无法开启
> Chrome 90.0.4430.93 请问
> 如何解决？
> ![图像](https://user-images.githubusercontent.com/13982749/117447380-0204d080-af70-11eb-98c0-83d03e867912.png)

无法开启是因为插件未认证导致的。开启开发者模式后，再把.crx改成.rar。注意：此时将文件解压到一个文件夹内。解压后的文件妥善保管，切勿删除或移动。再将整个文件夹拖进chrome://extensions/。在此之后就不能删除或移动该文件夹，否则会导致插件失效

**Comment by syhyz1990** [comment]
启用开发者模式 -> 后缀改成zip，拖动安装
