### ISSUE TITLE
网盘上已经看不到下载链接的图标了

### ISSUE THREAD

**Issue by althougha** [syhyz1990/baiduyun#56]

**Comment by Xiaotouming** [comment]
百度网盘出了新版界面，旧版的图标也不见了，不知是不是更新后没有适配

**Comment by jbxiaoyu** [comment]
不是,是因为浏览器没刷出来导致的.你可以多刷新几遍,总会有一遍出来的.或者你可以在代码中定位到 `$toolWrap.prepend($button);` ,在后面添加:

         let createButton = setInterval(function() {
                pageType === 'home' ? $toolWrap = $(pan.btn.home) : $toolWrap = $(pan.btn.share);
                if ($toolWrap.length > 0) {
                    util.clog('已找到按钮栏，添加下载助手按钮！');
                    $toolWrap.prepend($button);
                    clearInterval(createButton);
                } else {
                    util.clog('未找到按钮栏！');
                };
            }, 100);

**Comment by win98se** [comment]
@jbxiaoyu `$toolWrap.prepend($button);`有两处，添加的代码是放在`addButton()`，还是放在`addInitButton()`，还是两者都放？

**Comment by althougha** [comment]
推倒旧版页面就可以看到了，已经解决了。
