### ISSUE TITLE
idm显示获取的不是文件而是网页

### ISSUE THREAD

**Issue by YueCoding** [syhyz1990/baiduyun#57]
下载大文件下到一半时就无法继续下载，继续下载或获取链接继续下载idm就显示获取的不是文件而是网页。

**Comment by apt42541** [comment]
it grab slow link http://yqall04.baidupcs.com

**Comment by qndydyhm** [comment]
Try "refresh download address" in idm and use this script get a new link, and then you can continue downloading.

**Comment by qndydyhm** [comment]
![image](https://user-images.githubusercontent.com/40054460/50475342-59d5b900-09ff-11e9-9b5b-d9b8663ef55e.png)
HERE

**Comment by qndydyhm** [comment]
![image](https://user-images.githubusercontent.com/40054460/50475369-7540c400-09ff-11e9-8e46-2cf34175a595.png)
HERE

**Comment by apt42541** [comment]
i say it grab slow link mean it capable downlode but slowly
