### ISSUE TITLE
RPC 发送失败

### ISSUE THREAD

**Issue by ShixiangWang** [syhyz1990/baiduyun#57]
Motrix 是固定的RPC端口，我想不到问题出在哪里。

![image](https://user-images.githubusercontent.com/25057508/119446787-94271a00-bd61-11eb-9f83-62e9034475de.png)

![image](https://user-images.githubusercontent.com/25057508/119446728-7c4f9600-bd61-11eb-9467-dea4f625d977.png)

**Comment by higari9** [comment]
问题同上。。。求问怎么解决

**Comment by higari9** [comment]
> Motrix 是固定的RPC端口，我想不到问题出在哪里。
> 
> ![image](https://user-images.githubusercontent.com/25057508/119446787-94271a00-bd61-11eb-9f83-62e9034475de.png)
> 
> ![image](https://user-images.githubusercontent.com/25057508/119446728-7c4f9600-bd61-11eb-9467-dea4f625d977.png)
同样的问题，求问怎么解决。。。
