### ISSUE TITLE
it slow to download

### ISSUE THREAD

**Issue by bloodsucker3011** [syhyz1990/baiduyun#58]
on the 24/12 i able to download bulk file 25 gb without  problem (5 file in 5 mb/sec)
but after on the 25/12 that i can't download second file when first file is still running, and it very slow 9~60 kb/sec

**Comment by qndydyhm** [comment]
Maybe you should check your baidu account and make sure that it hasn't been banned/limited.
I could only download 1 file at the same time with maximum speed around 300KB/S when I use a banned account.
