### ISSUE TITLE
有没有让403的文件能正常下载的办法？

### ISSUE THREAD

**Issue by yoooooolx** [syhyz1990/baiduyun#6]
显示的链接点了没反应，强制调用IDM下点也没反应，新窗口打开提示没有权限，右键IDM下载报403，获取同一文件的aria2链接直接用aria2c下载也报403。请问有没有什么办法能让这个文件可以下载呢？

**Comment by iRubbish** [comment]
不知道你的这个问题解决了么？我的也是这个问题
