### ISSUE TITLE
下载出现http/1.1 403、http/1.1500 error

### ISSUE THREAD

**Issue by starrynight4seasons** [syhyz1990/baiduyun#60]
6/11开始，下载出现http/1.1 403跟http/1.1500 error，无论是IDM、NDM、Xdown都无法下载
想请教解决办法

**Comment by wxd19891212** [comment]
我也有相同的问题 mac,
但是小文件是可以用的，大文件（100M以上）就会报错

**Comment by syhyz1990** [comment]
非会员百度做了限制，可以尝试使用超级会员帐号试试

**Comment by wxd19891212** [comment]
![image](https://user-images.githubusercontent.com/9044268/132805861-93f9eb1f-db4e-4d2d-96c2-2873f1354e25.png)
我开超级会员了，直链下载 调用NDM 还是403 的错误

**Comment by wxd19891212** [comment]
![image](https://user-images.githubusercontent.com/9044268/132806140-a6580a25-4c3f-4b04-833f-2a84a121b134.png)
我开超级会员了，但是API下载还是 403 的错误
日志
![image](https://user-images.githubusercontent.com/9044268/132806365-110fdd35-78d3-4a93-9dbe-05ff6d10b1c9.png)

**Comment by syhyz1990** [comment]
@wxd19891212 Mac直接用curl方式复制到终端里下载吧 https://www.baiduyun.wiki/zh-cn/curl.html
