### ISSUE TITLE
opera无法唤起idm

### ISSUE THREAD

**Issue by zlhdd108** [syhyz1990/baiduyun#61]
opera版本号：
版本：77.0.4054.172
浏览器识别
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 OPR/77.0.4054.172

在百度网盘点击下载的时候，会提示无法唤起idm；换到微软新版的edge是正常的；idm里面已经关联了opera浏览器，也设置了相应的文件扩展
![image](https://user-images.githubusercontent.com/16465666/124857528-09337380-dfdf-11eb-82dd-9f1632b4a8bc.png)
![image](https://user-images.githubusercontent.com/16465666/124857535-0cc6fa80-dfdf-11eb-9447-8753aef01453.png)
![image](https://user-images.githubusercontent.com/16465666/124857632-3bdd6c00-dfdf-11eb-9d08-0011a1daf1e5.png)

**Comment by syhyz1990** [comment]
检查下IDM自带的crx扩展装了吗？不行试下这个 https://addons.opera.com/zh-cn/extensions/details/download-with-internet-download-manager-idm/

**Comment by zlhdd108** [comment]
> 检查下IDM自带的crx扩展装了吗？不行试下这个 https://addons.opera.com/zh-cn/extensions/details/download-with-internet-download-manager-idm/

我没表述清楚；下载别的东西的时候，比如直接下载的时候，opera可以正常调起IDM；但是度盘这个通过油小猴就无法调起
