### ISSUE TITLE
无法使用迅雷下载

### ISSUE THREAD

**Issue by lamia0725** [syhyz1990/baiduyun#61]
mac，chrome，选择直接下载的话速度比百度云限速还慢，要么就无响应；右键迅雷之后，迅雷又提示未知错误，无法下载！为什么啊

**Comment by Geno1024** [comment]
（跑题）关注你啦，以后就拜托你从你提的 Issue 里带我逛 GitHub 上各种好用的 baiduyun 插件啦~
