### ISSUE TITLE
API下载给了错的下载地址

### ISSUE THREAD

**Issue by 72888hshu** [syhyz1990/baiduyun#63]
助手给的不是mp4链接
![github baiduyun 1](https://user-images.githubusercontent.com/48046222/125979699-5fda8f3c-def7-43e7-88dd-130e891cd9c2.png)

完整的链接
![github baiduyun 2](https://user-images.githubusercontent.com/48046222/125979756-94e4ae99-29f0-458a-92b4-64b0ad38322a.png)

因为没唤醒IDM，所以我自己右键点IDM
![github baiduyun 3](https://user-images.githubusercontent.com/48046222/125979896-8db650fa-b4b8-4c3a-a406-361c07513444.png)

**Comment by syhyz1990** [comment]
不能自己点右键获取

**Comment by 72888hshu** [comment]
刚发现就算我在IDM配置了，他还是不会唤起IDM

脚本唤起IDM失败：
![图片](https://user-images.githubusercontent.com/48046222/131323616-7f0d4ce7-48d5-4412-b771-e31d876967c6.png)

IDM文件后缀配置（MP4已Highlight起来）：
![图片](https://user-images.githubusercontent.com/48046222/131323700-3c10e6c6-56fc-4f4e-8cf5-a6bb5af09f29.png)


（这是用最新的脚本再尝试了）
