### ISSUE TITLE
无法获取aria下载链接

### ISSUE THREAD

**Issue by Solacex** [syhyz1990/baiduyun#66]
下载助手已经正常安装，
![image](https://user-images.githubusercontent.com/12868455/130762881-1a47e4b6-3607-4452-8432-5fedb91d157b.png)
但是aria的下载链接始终无法正常获取
已经重启了浏览器
![image](https://user-images.githubusercontent.com/12868455/130762979-01589428-386f-4969-9a71-72b21a528471.png)

**Comment by syhyz1990** [comment]
不行的话用懒人版试下 https://www.lanzoui.com/b00tj19nc
