### ISSUE TITLE
mac网盘客户端闪退

### ISSUE THREAD

**Issue by tf2jaguar** [syhyz1990/baiduyun#67]
// ==UserScript==
// @name              网盘直链下载助手
// @namespace         https://github.com/syhyz1990/baiduyun
// @version           5.3.0
// @author            YouXiaoHou
// @icon              https://www.baiduyun.wiki/48x48.png
// @icon64            https://www.baiduyun.wiki/64x64.png

macOS Big Sur  11.5.1

**Comment by syhyz1990** [comment]
什么问题？

**Comment by tf2jaguar** [comment]
安装完成使用了一段时间，关闭后重新打开网盘闪退，重新下载最新版网盘后，无法使用插件

macOS Big Sur 11.5.1
网盘 版本3.8.2 (2)
网盘直链下载助手  5.3.0

**Comment by syhyz1990** [comment]
这是浏览器脚本，和客户端有啥关系？

**Comment by tf2jaguar** [comment]
他会在客户端渲染一个，快速下载的按钮。这个不是插件做的吗？我再看看流程

**Comment by syhyz1990** [comment]
不是的，你搞错了
