### ISSUE TITLE
下载连接无效

### ISSUE THREAD

**Issue by BITPZY** [syhyz1990/baiduyun#69]
插件得到的连接下载没反应

**Comment by SaguruHakuba** [comment]
我看了一下下载链接，我的显示user is not authorized，这是怎么回事啊？

**Comment by chtzs** [comment]
新方法似乎不行了

**Comment by wy16W2pIilK1xgqN** [comment]
我也这样。·

**Comment by Atticuswx** [comment]
大的文件使用idm下载，还是还是无法下载，提示无法下载此文件

**Comment by SaguruHakuba** [comment]
> 大的文件使用idm下载，还是还是无法下载，提示无法下载此文件

没错，+1

**Comment by tsq456** [comment]
> 服务器响应显示您没有权限下载此文件。
> 
> 备注：
> HTTP:/1.1 403 Forbidden

无法使用

**Comment by Atticuswx** [comment]
> > 服务器响应显示您没有权限下载此文件。
> > 备注：
> > HTTP:/1.1 403 Forbidden
> 
> 无法使用

因为文件太大了

**Comment by caochikai** [comment]
100M一样不行
