### ISSUE TITLE
多个大文件打包下载后会发生""错误:未找到中央目录""

### ISSUE THREAD

**Issue by UlyC** [syhyz1990/baiduyun#7]
下载webug时的自解压文件,多个一起打包下载,下载来的压缩包会无法解压.并报错:
""错误:未找到中央目录"". 下载多次均是如此

**Comment by Samarth1478** [comment]
https://pan.baidu.com/s/1YuzDv-RzzMQdr287S9BAzw
is this link is true

**Comment by syhyz1990** [comment]
@UlyC 大文件解压请用7-zip
