### ISSUE TITLE
Can't get membership without WeChat

### ISSUE THREAD

**Issue by Sonico98** [syhyz1990/baiduyun#71]
WeChat account is required. May someone help with verification?

**Comment by syhyz1990** [comment]
please type 80149

**Comment by Sonico98** [comment]
It says it doesn't exist https://i.ibb.co/q7Vjypq/Ag-ADCaox-Gw-Vl-UEQ.jpg
Thanks for the help and your service!

**Comment by syhyz1990** [comment]
@Sonico98 This WeChat does not belong to me, you may have encountered a fake script
