### ISSUE TITLE
应该是被和谐了吧？5小时前都可以使用的。

### ISSUE THREAD

**Issue by VirgoZhou** [syhyz1990/baiduyun#76]
![image](https://user-images.githubusercontent.com/47199537/53028970-e8683300-34a2-11e9-8cc5-79be9eee09e2.png)
之后报错：
![image](https://user-images.githubusercontent.com/47199537/53029039-09c91f00-34a3-11e9-97dd-02d265af94a5.png)

应该是被和谐了吧？5小时前都可以使用的。

**Comment by syhyz1990** [comment]
更新到2.0.1
