### ISSUE TITLE
v2.0.1更新后反复出现user is not authorized 问题

### ISSUE THREAD

**Issue by SaguruHakuba** [syhyz1990/baiduyun#78]
hit code从109到122...一开始是以为百度云盘挂了，结果过来一看是作者更新了。。。

**Comment by SaguruHakuba** [comment]
无论是多小的文件下载总会这样。另外，下载压缩包文件时也会提示user is not authorized。。

**Comment by SaguruHakuba** [comment]
Confirmed:新版本并没有解决在自己云盘api下载时返回403的问题。

**Comment by SaguruHakuba** [comment]
抱歉，我发现作者貌似并没有更新油猴上的脚本，手动更新之后发现如下两个问题：
1.在下载分享文件时，经常能出现user is not authorized的问题
2.在下载自己网盘api的压缩包时，会返回403 forbidden。

**Comment by syhyz1990** [comment]
@SaguruHakuba 提供下下载链接

**Comment by SaguruHakuba** [comment]
> @SaguruHakuba 提供下下载链接

对了，“该方法不支持目录下载！”是什么情况？

**Comment by SaguruHakuba** [comment]
> @SaguruHakuba 提供下下载链接

前两个问题好像都能解决了，就差最后一个“该方法不支持目录下载！”。这个是什么情况呀？

**Comment by syhyz1990** [comment]
现在不能下载目录了,被封了

**Comment by SaguruHakuba** [comment]
> 现在不能下载目录了,被封了

这么惨。。那注明一下，我们close了吧。

**Comment by xnsama** [comment]
我这里也是无权限下载  https://d.pcs.baidu.com/file/eab6c654afad52baad58ae5d6eccc92d?fid=3731891526-250528-387795578985793&dstime=1557822237&rt=sh&sign=FDtAERVY-DCb740ccc5511e5e8fedcff06b081203-Q8%2BDUhQ0mYmE5lJNLOj1THyz0OQ%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=3100493234824905865&dp-callid=0&shareid=1712191691&r=321545558
