### ISSUE TITLE
RPC不支持WebSocket吗还是我填的不对？

### ISSUE THREAD

**Issue by xiaozixun** [syhyz1990/baiduyun#79]
如图
![Screenshot 2021-12-25 at 16-58-19 阿里云盘分享](https://user-images.githubusercontent.com/22409452/147381582-7aa0f8dd-e2af-469b-801f-5a91fe604719.png)

**Comment by syhyz1990** [comment]
@xiaozixun 是的，只支持http/https

**Comment by xiaozixun** [comment]
> @xiaozixun 是的，只支持http/https

不知道能支持下吗？我用的aria2的浏览器扩展，websocket能通知成功与否，http就没办法。

**Comment by syhyz1990** [comment]
哪个扩展必须是ws的？链接发我看下

**Comment by xiaozixun** [comment]
> 哪个扩展必须是ws的？链接发我看下

它不是必须的，只是使用http协议时下载完成后不会有提示
https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration/
