### ISSUE TITLE
标题栏目

### ISSUE THREAD

**Issue by xzS9257** [syhyz1990/baiduyun#80]
很感谢分享，发现一个问题，不知道是不是个例，就是进入某个文件夹后，点击返回上一级或者全部文件按钮没有反应。关闭脚本后就可以用了。

小白，不是专业的，如果问题太白痴还望见谅……
![QQ截图20190315020442](https://user-images.githubusercontent.com/32573086/54380747-33065500-46c7-11e9-824c-4420bac61eae.png)

**Comment by syhyz1990** [comment]
感谢反馈，是什么浏览器呢

**Comment by syhyz1990** [comment]
更新脚本至2.1.1
