### ISSUE TITLE
提示：获取下载链接失败！请刷新网页后重试！

### ISSUE THREAD

**Issue by DeanShiDirect** [syhyz1990/baiduyun#80]
今天用下载助手，下载一个rar包，
提示：获取下载链接失败！请刷新网页后重试！

**Comment by syhyz1990** [comment]
按照提示操作即可。

**Comment by MisakaMikoto9982** [comment]
同问，感觉是浏览器不支持，目前是RunningCheese Firefox 96.2，介绍和下载页： https://www.runningcheese.com/firefox 。以前用edge dev原版是没问题的，换了之后反复刷新也没用

**Comment by syhyz1990** [comment]
工具箱不支持firefox，以edge/chrome为主

**Comment by MisakaMikoto9982** [comment]
> 工具箱不支持firefox，以edge/chrome为主

抱歉猴哥，我无意打扰您，只是看到脚本说明后有些疑惑，因为在您的说明里是支持Firefox的，如果不支持或存在兼容性问题还是标注一下为好，毕竟这个领域的 是非 很多，还是严谨一些，免得给人把柄，最后祝您新春愉快、身体安康
![image](https://user-images.githubusercontent.com/98512118/152484368-4db73072-76f9-4d51-80a4-2c9e616baa78.png)
https://www.baiduyun.wiki/zh-cn/

**Comment by syhyz1990** [comment]
@MisakaMikoto9982

工具箱不支持 Firefox，是指这个 https://www.crxsoso.com/addon/detail/youxiaohoubox

其他的油猴脚本支持 Firefox 的，Firefox 我试过没问题的。

**Comment by nahiken** [comment]
一直刷新但还是获取下载链接失败！

**Comment by nahiken** [comment]
> 一直刷新但还是获取下载链接失败！
并且无论什么文件都是，好几天了
