### ISSUE TITLE
显示连接用IDM抓取失败

### ISSUE THREAD

**Issue by liyingcake** [syhyz1990/baiduyun#82]
谷歌浏览器无法直接抓取，加了谷歌应用商店的IDM抓取也不行，复制连接给IDM也不行

**Comment by liyingcake** [comment]
问题我已自我解决，是IDM的问题，没有在谷歌上完美安装好插件。 IDM帮助连接：
[http://www.internetdownloadmanager.com/register/new_faq/chrome_extension2.html](url)
因为IDM在谷歌商店默认隐藏的，顺着提示安装或者到谷歌商店安装到正确的IDM插件即可：
[https://chrome.google.com/webstore/detail/idm-integration-module/ngpampappnmepgilojfohadhhmbhlaek/related](url)

**Comment by liyingcake** [comment]
emmm虽然原则上这属于IDM的问题，但是估计也是大部分小白也搞不懂，应该加入常见问题合集

**Comment by syhyz1990** [comment]
感谢反馈

**Comment by LevineWoo** [comment]
> 问题我已自我解决，是IDM的问题，没有在谷歌上完美安装好插件。 IDM帮助连接：
> [http://www.internetdownloadmanager.com/register/new_faq/chrome_extension2.html](url)
> 因为IDM在谷歌商店默认隐藏的，顺着提示安装或者到谷歌商店安装到正确的IDM插件即可：
> [https://chrome.google.com/webstore/detail/idm-integration-module/ngpampappnmepgilojfohadhhmbhlaek/related](url)

感谢，提示403报错的用这个方法解决了。
