### ISSUE TITLE
无法下载 epub 文件

### ISSUE THREAD

**Issue by wenLiangcan** [syhyz1990/baiduyun#83]
https://pan.baidu.com/s/1_I0i3LYeJ-ClKpL7i_eMUA
x8yw

里面的 pdf 可以下载，可是 epub 的链接下载不了

**Comment by syhyz1990** [comment]
@wenLiangcan 我试了下是可以的呀，如果用的IDM，记得添加后缀 EPUB

**Comment by wenLiangcan** [comment]
现在又可以了，前段时间发现好几个分享链接都是这样的情况，好奇怪
