### ISSUE TITLE
api无法下载，报错error_code: 31360 error_msg: "expire time out error" request_id: 522099981928045250

### ISSUE THREAD

**Issue by tujixiang** [syhyz1990/baiduyun#84]
点击链接直接下载
Request URL: blob:chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/d4751002-8adc-4e51-8aac-b12966db237d

报错
error_code: 31360
error_msg: "expire time out error"
request_id: 522099981928045250

**Comment by MugeTong** [comment]
I am so happy to encounter this problem when I tried to analyze the direct link for Baidu. Maybe I could provide help if you could provide more information.

Here I encountered this when I tried to download large file use d_link. It seems OK when the file is smaller than 50 MB?

我很高兴在尝试分析百度直接链接时遇到了这个问题。 如果您能提供更多信息，也许我能提供帮助。

在这里，我在尝试使用直链下载大文件时遇到了这个问题。 当文件小于 50 MB 时似乎没有遇到过问题。
