### ISSUE TITLE
请求增加夸克网盘的支持

### ISSUE THREAD

**Issue by SyngnathZ** [syhyz1990/baiduyun#85]
现在夸克网盘用的越来越多了，希望能增加对夸克网盘的直链获取支持！谢谢！

**Comment by syhyz1990** [comment]
夸克网盘目前没有看到有开放的API，观察一段时间

**Comment by SyngnathZ** [comment]
原来其他网盘的实现是利用api的？我以为是对网页链接进行抓取实现的
