### ISSUE TITLE
chrome没法安装crx

### ISSUE THREAD

**Issue by DaveGeneral** [syhyz1990/baiduyun#86]
把crx更改后缀名zip解压后倒是可以加载，但是插件显示有错，感觉是版本不对应。
edge版本的可以正常使用。
另外这个idm是只能免费用30天吗

**Comment by liuzhenyulive** [comment]
同样遇到了插件无法安装的问题

**Comment by syhyz1990** [comment]
可以去  https://chrome.google.com/webstore/detail/idm-integration-module/ngpampappnmepgilojfohadhhmbhlaek/related 下载
