### ISSUE TITLE
问题咨询：麻烦请问开发者使用这个是否有封号风险？

### ISSUE THREAD

**Issue by yxzlwz** [syhyz1990/baiduyun#86]
本人使用这个插件很久了，自己也开了会员，目前使用正常。但是听说使用网盘破解可能有封号风险，请问插件是否有相关的风险或规避策略？

因为网盘里面还是有一些重要文件的，如果确有此事的话以后可能就要用小号了。

感谢开发者百忙中解答！

**Comment by syhyz1990** [comment]
自己使用没有风险，API来自开放平台。https://pan.baidu.com/union/doc/pkuo3snyp

**Comment by recolic** [comment]
`网盘里面还是有一些重要文件`这本身就是一个问题... 总有一天会出现各种理由不让你取回
