### ISSUE TITLE
不支持反向代理地址

### ISSUE THREAD

**Issue by qianbinbin** [syhyz1990/baiduyun#87]
通过反向代理如 `https://token:123456@domain/aria2rpc` 访问，其他应用测试正常，使用此脚本提示发送失败

抓包发现url变为了 `https://domain/aria2rpc:/jsonrpc`，应该是路径有问题

**Comment by syhyz1990** [comment]
截一个配置图我看看

**Comment by qianbinbin** [comment]
没必要，就是路径不对

通过反向代理对外隐藏端口，用一个自定义的路径比如 `https://domain/aria2rpc` 访问，6800可以直接禁掉了

`https://domain/aria2rpc:/jsonrpc` 这个路径，明明不关 `jsonrpc` 啥事，这里出现了，可见是把路径写死了

**Comment by syhyz1990** [comment]
明白了，没端口的话你端口号填80就行了，5.6.2版支持自定义rpc路径了，前往更新即可

**Comment by qianbinbin** [comment]
可以了，不过我这里是https，用的443端口

个人建议可以参考yaaw的做法，直接用一条完整的url `https://token:123456@domain/aria2rpc` 就行，不用分开设置
