### ISSUE TITLE
Xunlei pan 显示登录的提示框

### ISSUE THREAD

**Issue by bookyo** [syhyz1990/baiduyun#88]
```
if (localStorage.key(i).startsWith('captcha_') && localStorage.key(i).indexOf('captcha_device_id') == -1)
```
1727行改成以上就能解决，因为你这里获取captcha_开头的localStorage，xunlei盘里边的captcha_开头的是有两个，一个captcha_device_id，一个captcha_乱码，所以你得先排除captcha_device_id的key！之后获取链接就正常了！

**Comment by syhyz1990** [comment]
感谢反馈，我抽空看下

**Comment by syhyz1990** [comment]
新版已经解决
