### ISSUE TITLE
更新后，网盘页面和文件分享页面的按钮都没有了

### ISSUE THREAD

**Issue by SaguruHakuba** [syhyz1990/baiduyun#89]
我服了，之前有的下载按钮都没了，reload重启都没用。。。

**Comment by SaguruHakuba** [comment]
![image](https://user-images.githubusercontent.com/22808988/54795342-34cd9c80-4c22-11e9-80a4-ca14299bbae2.png)

**Comment by SaguruHakuba** [comment]
![image](https://user-images.githubusercontent.com/22808988/54795472-bf160080-4c22-11e9-92bb-1f46ff080d13.png)
真的佛了，作者不更新油猴版本，我不知道这里哪个branch能用的。。。

**Comment by SaguruHakuba** [comment]
不过最近网络ping有点高，会不会是因为ping的关系？

**Comment by SaguruHakuba** [comment]
看来不是ping的问题
![image](https://user-images.githubusercontent.com/22808988/54795891-49129900-4c24-11e9-922e-900386ef60a7.png)

**Comment by syhyz1990** [comment]
按照教程操作

**Comment by SaguruHakuba** [comment]
> 按照教程操作

还是没有出现 下载助手的按钮？？？

**Comment by SaguruHakuba** [comment]
![image](https://user-images.githubusercontent.com/22808988/54798167-b70f8e00-4c2d-11e9-956a-31d51dbe8ff1.png)
作者不要老动不动就未经核实 close issue呀。
