### ISSUE TITLE
关于rpc推送

### ISSUE THREAD

**Issue by db-sin** [syhyz1990/baiduyun#90]
尊敬的开发者你好，
感谢您开发了如此完美的脚本让我们的生活变得更加美好
现在我遇到了一个问题
在使用rpc推送下载链接到我的远程aria2（linux下搭建）时，脚本提示失败，我只有配置地址为localhost时（window下搭建）才能推送成功，地址为局域网其他地址都不成功，（我在windows下的谷歌浏览器执行的）
请问这个问题可能出现在哪里呢，
希望您能在百忙之中抽空看下我的问题，感谢了

**Comment by syhyz1990** [comment]
检查下局域网端口是否开放，协议是否填写正确

**Comment by 1-1-2** [comment]
> 检查下局域网端口是否开放，协议是否填写正确

作者您好，请问可以考虑增加多套配置的保存、下载页面切换（选择）的功能吗。

比方说我在本地有 Motrix，又在家里的服务器上搭建了 Aria2，两个地方的地址和配置是不一样的。

**Comment by JiangShanCode** [comment]
作者，您好。我也遇到了这个问题。当我填写liunx服务器的ip时请求会被拒绝。当在Windows下用motrix,填写127.0.0.1也会失败，而填localhost却可以。端口应该没问题，可以用命令行下载。我的脚本版本是5.6.6

**Comment by o-liverkk** [comment]
确实有这个问题，等开发者更新吧

**Comment by o-liverkk** [comment]
> > 检查下局域网端口是否开放，协议是否填写正确
> 
> 作者您好，请问可以考虑增加多套配置的保存、下载页面切换（选择）的功能吗。
> 
> 比方说我在本地有 Motrix，又在家里的服务器上搭建了 Aria2，两个地方的地址和配置是不一样的。

名字不同的脚本可以共存，装两个脚本名字不同就可以了。

**Comment by o-liverkk** [comment]
> 确实有这个问题，等开发者更新吧

是油猴的问题，更新到最新版本就解决了。
