### ISSUE TITLE
不显示下载助手

### ISSUE THREAD

**Issue by Kunkgg** [syhyz1990/baiduyun#91]
安装脚本后，到百度云盘，油猴脚本现实脚本在运行，但我的页面中没有出现｀下载助手｀按钮

**Comment by syhyz1990** [comment]
重启浏览器试下

**Comment by Will-Liu88** [comment]
> 重启浏览器试下

我的也是重启也没有 下载助手

**Comment by Kunkgg** [comment]
> 重启浏览器试下

重启没有用的

**Comment by syhyz1990** [comment]
安装教程及常见问题解答 : https://github.com/syhyz1990/baiduyun/blob/master/help.md

**Comment by 17602588136** [comment]
我的网盘也不显示下载助手，网页里显示但用不了
