### ISSUE TITLE
一点样式捉虫

### ISSUE THREAD

**Issue by CloudyEagle** [syhyz1990/baiduyun#93]
![Snipaste_2022-03-06_04-58-16](https://user-images.githubusercontent.com/58777085/156916554-ce0b3a02-80f1-43c1-9e74-1550c38dd21e.png)
![Snipaste_2022-03-06_17-17-17](https://user-images.githubusercontent.com/58777085/156916866-3dd56940-2a8e-45b8-b999-1340615ecd16.png)
功能是没有问题，不过是百度网盘的新版界面存在样式问题，手动进入旧版样式就没有问题了。

**Comment by CloudyEagle** [comment]
![Snipaste_2022-03-06_18-01-06](https://user-images.githubusercontent.com/58777085/156918436-f1e4597b-d3b9-4065-9638-7edc3c93cd50.png)
我稍微会一点HTML5，发现应该百度的一个class命名改了
我当时复制粘贴后就复原了，我先临时到TamperMonkey里改一下把
还有我图片里的文字标注的反了

**Comment by syhyz1990** [comment]
改版了，下个版本修复

**Comment by syhyz1990** [comment]
@CloudyEagle 新版本已修复
