### ISSUE TITLE
chrome 奔溃啦

### ISSUE THREAD

**Issue by vioulo** [syhyz1990/baiduyun#93]
:joy_cat: 
chrome 版本 72.0.3626.121（正式版本） （32 位）
在百度盘页面使用时候，浏览器异常退出

**Comment by syhyz1990** [comment]
可以换用其他浏览器试试

**Comment by vioulo** [comment]
> 可以换用其他浏览器试试

我只是很在乎浏览器崩溃的原因，很神奇

**Comment by syhyz1990** [comment]
有可能是其他插件导致的 , 问题关闭了
