### ISSUE TITLE
支持 FireMonkey

### ISSUE THREAD

**Issue by linsui** [syhyz1990/baiduyun#94]
请问可以支持 [FireMonkey](https://addons.mozilla.org/zh-CN/firefox/addon/firemonkey/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) 插件吗？是否 FireMonkey 缺少什么特性导致无法在 FireMonkey 中工作？谢谢！

**Comment by syhyz1990** [comment]
这个我试了下，一运行脚本就卡死，不知是和原因。应该 FireMonkey 的功能还不完善

**Comment by linsui** [comment]
是的，会一直卡住。我也在那边询问了，但 FireMonkey 的开发者也不清楚问题是什么。https://github.com/erosman/support/issues/429#issuecomment-1059957519

**Comment by Iey4iej3** [comment]
> 是的，会一直卡住。我也在那边询问了，但 FireMonkey 的开发者也不清楚问题是什么。[erosman/support#429 (comment)](https://github.com/erosman/support/issues/429#issuecomment-1059957519)

这里面（至少）有两个问题。一个是 jquery 的加载，这个容易通过加上一行 `//@require` 解决。加上后看调试信息，显示 `__vue__` 未定义。我已经做了一些努力，但无法解决这个问题：https://github.com/erosman/support/issues/429#issuecomment-1244093804

`vue` 在这个脚本里面只用了这么一次，有没有代替代码不用 `vue`？如果可以的话，在异常处理里面再加上一种获得选择列表的方案？

**Comment by syhyz1990** [comment]
脚本里并未使用vue，而是百度网盘用的是Vue，文件的一些参数绑定在data数据里，需要获取对应dom的__vue__属性。

**Comment by Iey4iej3** [comment]
我发现一个方案可以在 FireMonkey 中工作（我无法理解原因）：将
``` javascript
        getSelectedList() {
            try {
                return require('system-core:context/context.js').instanceForSystem.list.getSelected();
            } catch (e) {
                return document.querySelector('.wp-s-core-pan').__vue__.selectedList;
            }
        },
```
改成
``` javascript
        getSelectedList() {
            try {
                return require('system-core:context/context.js').instanceForSystem.list.getSelected();
            } catch (e) {
                return unsafeWindow.document.querySelector('.wp-s-core-pan').__vue__.selectedList;
            }
        },
```
然后把迭代器
``` javascript
        _getFidList() {
            let fidlist = [];
            selectList.forEach(v => {
                if (+v.isdir === 1) return;
                fidlist.push(v.fs_id);
            });
            return '[' + fidlist + ']';
        },
```
改成循环
``` javascript
        _getFidList() {
            let fidlist = [];
            for (let i=0; i<selectList.length; ++i) {
              if (selectList[i].isdir === 1)
                return;
              fidlist.push(selectList[i].fs_id);
            }
            return '[' + fidlist + ']';
        },
```
这样可以成功进行“API下载”。进度条没有正常显示，但等待一段时间后文件会被正常下载。

**Comment by Iey4iej3** [comment]
这里有个解释，说为什么会产生权限问题：https://github.com/erosman/support/issues/429#issuecomment-1245427689

**Comment by Iey4iej3** [comment]
`forEach` 改成这样，在 FireMonkey 里面可以运行：

``` javascript
        _getFidList() {
            let fidlist = [];
            selectList.forEach(exportFunction(v => {
                if (+v.wrappedJSObject.isdir === 1) return;
                fidlist.push(v.wrappedJSObject.fs_id);
            }, unsafeWindow));
            return '[' + fidlist + ']';
        },
```

**Comment by Iey4iej3** [comment]
进度条问题大概是 FireMonkey 没有实现。我已经报告 https://github.com/erosman/support/issues/506
