### ISSUE TITLE
无法使用aria2c rpc服务器

### ISSUE THREAD

**Issue by tvp100** [syhyz1990/baiduyun#95]
系统: Ubuntu 20.04.4 LTS Linux 5.4.0-102-generic
aira2版本: 1.35.0
![图1](https://user-images.githubusercontent.com/44150076/157999029-9b4b0a94-46ec-4ad6-b117-ff504f2c4c44.png)
![图2](https://user-images.githubusercontent.com/44150076/157999059-83fa4682-b400-4be3-8fd0-0ee4aeb02eac.png)
助手配置是这样的，无效
但是我可以通过我aira2 webui 访问我的aira2 服务

**Comment by tvp100** [comment]
linux shell 和 linux 终端都不行，不懂这两个的区别
我的 aria2 weigui 是跑在 nginx 里的
aria2c 是跑在 screen 里的

**Comment by paladin4fan** [comment]
+1
Linux Mint aria2和motrix都用了 其他webui都可以正常连上 只有这个脚本发送失败
临时解决办法：打开脚本 
把头部userscript的
// @connect           localhost
localhost改成你的服务器地址

**Comment by tvp100** [comment]
> +1 Linux Mint aria2和motrix都用了 其他webui都可以正常连上 只有这个脚本发送失败 临时解决办法：打开脚本 把头部userscript的 // @connect localhost localhost改成你的服务器地址

感谢，这个方法可以正常使用rpc了。
