### ISSUE TITLE
mac idm没有相关下载呀

### ISSUE THREAD

**Issue by JakeRed** [syhyz1990/baiduyun#95]
如题：http://internetdownloadmanager.com/download.html 这个没有mac版本呀

**Comment by Suntgr** [comment]
+1

**Comment by HelplessMan** [comment]
可以支持下fdm 或者folx 么。。 idm 没有看到mac的。。

**Comment by syhyz1990** [comment]
fdm 可以 , folx有浏览器插件的话就可以
