### ISSUE TITLE
rpc推送bug

### ISSUE THREAD

**Issue by bytxk** [syhyz1990/baiduyun#99]
Chrome 版本 99.0.4844.51（正式版本） (arm64)
Tampermonkey BETA 4.16.6156
网盘直链下载助手5.6.8
切换了一个新的RPC地址后，不能正确切换到新的下载路径（aria2.conf配置），导致无法下载
报错如图，AriangUI上显示下载路径为空。<img width="634" alt="截屏2022-03-17 20 28 25" src="https://user-images.githubusercontent.com/62052872/158812700-6e8635de-56a6-478a-b5fe-265a1ba2ba21.png">

在脚本配置助手手动配置保存路径后可正常下载，AriangUI正确显示下载路径。<img width="648" alt="截屏2022-03-17 20 33 14" src="https://user-images.githubusercontent.com/62052872/158812768-751ef3f1-a618-4c4c-96b1-d3cb4691af57.png">

**Comment by murazi** [comment]
同样的问题，还一直是我的问题，一直在整NAS，发现下载普通连接就OK

**Comment by syhyz1990** [comment]
检查 路径是否填写正确，默认为/jsonrpc
